src/util/jsx-interfaces.ts
The event name is "dblclick" not "doubleclick" - this should fix #114
=> Fixed event name: onDoubleClick -> onDblClick, fixes #114

src/core/testing/test/util.spec.ts, src/core/testing/util.ts
This is just the start of the utilities. I am still relying too heavily on the existing mock* code from test/index.ts. That should probably get moved and cleaned up, but for now I am using a lot of it.
Two functions:
register() - creates a platform, registers the defined components
render() - can be used to test the DOM or (via $instance) the component class
I removed the idea of a compile() function for now since render() returns an object that defines the component class instance on $instance.
Next steps:
1. determine how to use with component defined in tsx file
2. refactor more test/index.ts code into here
=> feat(testing): layout the basic testing API

src/server/renderer.ts
Fixes #147 since the `util.js` is built from `scripts/cli-entries/util.js` to `dist/cli/util.js`.
=> Fix default logger for ssr

src/server/renderer.ts
Either I was partly wrong about the path or something changed to the building over the weekend (I'm afraid it's likely the former). Either way, after installing `next` from npm, this path doesn't escape the `dist` dir.
=> Fix path to util for logger

scripts/externs.core.js
Fixes `loadStyles is not a function` in production builds
=> fix(externs): add loadStyles to externs

src/compiler/service-worker/generate-sw.ts, src/util/interfaces.ts
Pull request for #192 
If swSrc config is not specified then the service worker
will be genereted otherwise injectManfiest will be executed.
Notes:
1; Now there is an inconsistency with the base paths since the base path of the `copy` functionality is the `/src` directory but the base path of the `swSrc` is the root of the project. Couldn't find any option for workbox to set the base path of the `swSrc`. Maybe we could prefix the path with `src/`. What do you think? Does it make sense?
2; When using `swSrc` then the config won't be passed to WorkboxSW's constructor. This is normal since WorkboxSW needs to be instantiated manually by the user.
All of these things are documented in the workbox docs. Quote:
> Note: This option is only valid when used with generateSW(). When using …
=> Use own service worker

src/compiler/bundle/component-styles.ts, src/compiler/transpile/transpile.ts, src/util/interfaces.ts
to allow sass compile fine tunning
Closes #248
=> feat(config): add sassConfig option

package.json, scripts/setupTests.js, src/core/instance/test/render.spec.ts, src/core/renderer/test/patch.spec.ts, src/core/renderer/test/set-accessor.spec.ts, src/testing/expect/index.ts, src/testing/render.ts, src/testing/utils.ts
Adds to `@stentil/core/testing`
```ts
expect(HTMLElement).toMatchClasses(classes: string[]);
expect(HTMLElement).toMatchAttributes(attributes: {[attr: string]: string});
```
and updates existing tests to use the new APIs
=> feat(test): extend jest-expect

scripts/packages/testing/jest.preprocessor.js, src/compiler/transpile/transpile.ts
In ionic-core, testing a component that imports index, automatically breaks the testing:
```ts
import { StencilElement } from '../../index';
```
fixes https://github.com/ionic-team/stencil/issues/225
=> fix(test): imports

src/util/cli/cli-utils.ts, src/util/cli/test/cli.spec.ts
We were originally checking `!serviceWorker.config` to know when the service worker config was not there. This had a side effect of forcing the service worker config to be true when it was explicitly set to false by the user. This fixes that issue and includes some extra unit tests to make sure this does not break again.
=> fix(serviceworker): service worker should not be injected when false

src/compiler/app/app-loader.ts
=> perf(html): inlined loader is minified

src/compiler/bundle/component-modules.ts, src/compiler/bundle/generate-bundles.ts, src/compiler/transpile/core-build.ts, src/compiler/util.ts, src/util/data-serialize.ts, src/util/test/data-serialize.spec.ts
Typescript sometimes injects __generator code when transpiling code that uses async/await from es2015 to es5, generating broken JS code:
Notice that "components module", parameter is not a function.
The implemented fix is to move `wrapComponentImports(resultsCode)` later in the compilator process, this way we ensure that "components module" is always a function.
fixes https://github.com/ionic-team/stencil/issues/329
fixes https://github.com/ionic-team/stencil/issues/328
=> fix(build): es5 builds when TS injects __generator

src/compiler/transpile/transpile.ts
When compiling ionic/core:
```
[02:33.0]  compile started ...
/Users/manuelmartinez-almeida/repos/ionic/ionic/packages/core/src/components/app/test/cordova/page-one.tsx
/Users/manuelmartinez-almeida/repos/ionic/ionic/packages/core/src/components/app/test/cordova/page-tabs.tsx
/Users/manuelmartinez-almeida/repos/ionic/ionic/packages/core/src/components/app/test/cordova/page-three.tsx
/Users/manuelmartinez-almeida/repos/ionic/ionic/packages/core/src/components/app/test/cordova/page-two.tsx
/Users/manuelmartinez-almeida/repos/ionic/ionic/packages/core/src/components/tabs/test/basic/page-tab.tsx
/Users/manuelmartinez-almeida/repos/ionic/ionic/packages/core/src/components/tabs/test/translucent/translucent-page-tab.tsx
```
^these files are part of `metadata`, but are not in `moduleFiles`
=> fix(transpile): moduleFiles crash

src/compiler/transpile/datacollection/element-decorator.ts, src/compiler/transpile/datacollection/event-decorator.ts, src/compiler/transpile/datacollection/index.ts, src/compiler/transpile/datacollection/listen-decorator.ts, src/compiler/transpile/datacollection/method-decorator.ts, src/compiler/transpile/datacollection/prop-change-decorator.ts, src/compiler/transpile/datacollection/prop-decorator.ts, src/compiler/transpile/datacollection/state-decorator.ts, src/compiler/transpile/datacollection/test/fixtures/propchange-simple.ts, src/compiler/transpile/datacollection/test/props-change-decorator.spec.ts, src/compiler/transpile/datacollection/test/state-decorator.spec.ts, src/compiler/transpile/datacollection/utils.ts
same as https://github.com/ionic-team/stencil/pull/352
but applied to PropDidChange and PropWillChange
also, normalized the metadata extraction across State, Prop, Element, so all them are implemented the same way.
=> fix(prop): method with multiple PropChange decorators

src/compiler/service-worker/inject-sw-script.ts
This PR allows our service worker registration code to emit an event when a new service worker is installed but not activated yet. This feature is mainly for the ionic-pwa-toolkit at the moment (so I can show some UI when a new service worker is ready to take over) but anyone could use that event to do anything they wanted to. Also, this is not a breaking change from the current behavior as it still just registers the service worker like the current registration code does and if the user does not want to use that event they would never have to even know about it.
=> feat(serviceworker): emit event when a new service worker is installed

package-lock.json, package.json, src/compiler/service-worker/generate-sw.ts, src/compiler/service-worker/validate-sw-config.ts, src/util/interfaces.ts
This updates Stencil to use Workbox 3.0 and also solves an issue where the workbox libraries were not being included when using injectManifest. The changes are as follows:
- Update to latest workbox 3.0 release. Pinned for now to protect from any more breaking changes
- make a copyLib function that handles putting the workbox libraries into the correct place. This is using the new `copyWorkboxLibraries` method in workbox 3.0. This method is only used when using `injectManifest` as running `generateSW` copies over the libs automatically
- Changes the default workbox config to remove clientsClaim and skipWaiting. In workbox 3.0 when using `injectManifest` you have to turn these options on in your service worker itself. This is going to require some docs changes (which I will handle). …
=> fix(serviceworker): updating to workbox 3.0

src/client/platform-client-legacy.ts
The `initStyleTemplate` method is what decides how to apply styles. In ES6 builds it will use the `template` element to apply styles and in ES5 builds we just keep the styles in memory and then manually create style tags. Before this fix we were not using this method in the legacy client, meaning ES5 builds did not know how to handle styles. This PR fixes that.
=> fix(styles): styles are now applied in browsers using the legacy client

package-lock.json, src/client/platform-client-legacy.ts, src/client/platform-client.ts, src/core/instance/listeners.ts, src/core/instance/test/listeners.spec.ts, src/core/renderer/dom-api.ts, src/testing/mocks.ts, src/util/interfaces.ts
@adamdbradley 
it could also be `options: {passive, capture}` so capture can also be configured, instead of `passive: boolean`
It also fixes a problem with domApi.supportPassiveEvents
=> feat(listeners): enableListener accepts passive option

src/compiler/config/test/validate-paths.spec.ts, src/compiler/config/validate-paths.ts
If wwwIndexHtml is not absolute, it is changed to wwwDir, which seems
like a copy-paste oversight.
This commit changes it to use the value of wwwIndexHtml relative to
wwwDir.
Fix for https://github.com/ionic-team/stencil/issues/469
=> Fixes absolutizing of wwwIndexHtml

src/compiler/transpile/create-component-types.ts
I would love to use `componentOnReady()` without a cast to any.
https://github.com/ionic-team/ionic/blob/core/packages/core/src/components/loading-controller/loading-controller.tsx#L28
=> feat(components): componentOnReady()

src/compiler/copy/copy-tasks.ts
Otherwise the `allCopyTasks` of `copyTasks` function is always empty when resolving.
=> fix(copy): wait for processCopyTaskDestDir execution

src/core/renderer/patch.ts, src/core/renderer/test/patch-svg.spec.ts
patchVNode function does not reset isSvgMode after patching svg nodes, therefore, if the next element in the DOM tree has to be created by domApi.$createElement funcion, it is created as an SVG Element.
The bug can be tested in a [demo I created](https://github.com/yesobo/stencil-svg-bug) based on stencil-app-starter with @stencil/core 0.3.0 where it is unable to add a new div element follwing a svg node already rendered in the DOM tree.
PR #460  fixes subsequent SVG nodes created in the same patchVNode stage but it does'nt take into account when a previous SVG element was already rendered in a previous stage
=> fix(svg): isSvgMode must be reset when an svg node is patched

src/core/instance/init-component-instance.ts
Tries to fix: https://github.com/ionic-team/stencil/issues/498
@adamdbradley I am not sure it is a good fix or that is actually solves the root of the problem. could you look at it? The fact that componentDidLoad runs twice sometimes breaks some components in ionic-core. Also having some unit tests for the lifecycle events would be great
=> fix(init): componentDidLoad called twice

src/compiler/style/style.ts
Warn when Stylus and/or Less are used without corresponding plugins
=> Stylus/Less Warnings

scripts/polyfills/array-includes.js, src/compiler/app/app-polyfills.ts
Today, array.includes() is actually faster than indexOf
But more important, it's a more explicit API that revels the true intent of the developer.
=> chore(polyfill): add array.includes

scripts/polyfills/array-find.js, scripts/polyfills/array-includes.js, scripts/polyfills/string-endswith.js, scripts/polyfills/string-startswith.js
Defining polyfills as non-writable causes "Assignment to read-only
properties is not allowed in strict mode" errors in certain
circumstances, such as using MobX and its ObservableArray subclass of
Array.
This follows the conventions from polyfill.io around the options passed
to `defineProperty`.
Fixes ionic-team/stencil#606
=> Makes polyfills writable properties

src/declarations/jsx.ts
[https://twitter.com/addyosmani/status/938078402430382080](https://twitter.com/addyosmani/status/938078402430382080)
Just curious, do these definitions have to be manually maintained or are they pulling from somewhere? Thanks!
=> Image decode definition

src/declarations/render.ts
"While string index signatures are a powerful way to describe the “dictionary” pattern, they also enforce that all properties match their return type. This is because a string index declares that obj.property is also available as obj["property"]. " https://www.typescriptlang.org/docs/handbook/interfaces.html
=> fix(types): Render HydrateAnchor

src/compiler/config/test/validate-config.spec.ts
#637 validate-config.spec.ts fails on Windows
=> test(normalize): fix validate-config.spec on windows

src/compiler/config/test/validate-paths.spec.ts
#641 validate-paths.spec.ts fails on Windows
=> test(normalize): fix validate-paths.spec on windows

src/client/css-shim/init-css-shim.ts, src/client/css-shim/test/init-css-shim.spec.ts
Changes the logic to better ensure that the "--" happens at the
beginning of a word, where it would appear for a variable declaration,
rather than inside a selector.
Fixes #603
=> Updates the CSS variable regexp for pseudo-classes

src/compiler/transpile/create-component-types.ts, src/compiler/transpile/datacollection/event-decorator.ts, src/compiler/transpile/datacollection/index.ts, src/compiler/transpile/datacollection/prop-decorator.ts, src/compiler/transpile/datacollection/utils.ts, src/declarations/component.ts, src/util/helpers.ts
This PR is to add types for eventHandlers into component.d.ts file.  This should prevent the need for use of the @Listen decorator in most cases.
If a component events an event then we should listen to it by attaching to the event name within JSX.  This means that I have created translations from 'IonChange' to 'onIonChange'.
=> fix(): add event listeners and custom events types to components.d.ts

src/compiler/transpile/create-component-types.ts
I'm on Windows and a lot of tests still fail, but a quick `npm link` against a project worked, so caveat emptor :)
=> fix: Avoid Object.entries (breaks Node 6)

src/compiler/bundle/rollup-plugins/in-memory-fs-read.ts
#646 build.spec.ts fails on Windows
=> test(build.spec) remove drive letter added by sys.path.resolve

src/compiler/style/style.ts, src/compiler/style/test/style.spec.ts
Fixes #656
Seems to be caused by [the replace statement here](https://github.com/ionic-team/stencil/blob/b32d9da2acfa68ed38ad0c2af4f832193ee8771c/src/compiler/style/style.ts#L149) as it escapes the first escape character it encounters. Which then breaks the escapes applied by the call to `escapeCssForJs` as it looks for an octal literal.
This reverts the change introduced for #545 , and instead fixes it by expanding the RegEx for identifying octal literals in the `escapeCssForJs` function to also identify non-digit characters.
=> fix(styles): escape unicode chars & octal literals in css

.github/CONTRIBUTING.md
Clicking the current link for Stencil Worldwide Slack in the [CONTRIBUTING.MD file](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md) results in a web page that says "This invite link is no longer active."  
NOTE: This only happens when you are NOT logged into the group already.  If you ARE logged into the group, the current link works.
=> Correct link to the Stencil Worldwide Slack

scripts/packages/testing/jest.preprocessor.js
Brings our `normalizePath` function that we use across stencil into the jest preprocessor file. This function is then used to ensure that the path `require` uses is windows friendly. Only changes I have made to the function are to use `var` instead of `const` to match our use of ES5 in this file.
=> chore(testing): use normalizePath for windows friendly path

src/declarations/jsx.ts
I used the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement) as a reference for the interface to define.
Closes #711
=> Fix the <dialog> TypeScript interface

src/client/css-shim/init-css-shim.ts, src/client/css-shim/test/init-css-shim.spec.ts
Fix #602 
I'm not an expert in regex, so maybe there is a better one or a simple way of doing this. So please review and comment.
Note that this fix just prepend the "import path" to every url() in imported css. This will generate paths like "assets/css/../fonts/testfont.tff".
=> fix(css-shim): Fix relative paths

src/compiler/bundle/rollup-plugins/resolve-collections.ts, src/compiler/collections/parse-collection-module.ts, src/declarations/collection.ts, src/declarations/system.ts
ensure that all modules are solved correctly if a module path is provided in package.json.
=> Correctly identify collection modules with exports.

test/karma/package.json, test/karma/src/components.d.ts, test/karma/src/slot-array/cmp.tsx, test/karma/src/slot-array/index.html, test/karma/src/slot-array/karma.spec.ts
Two things in this PR:
1. Karma testing is (mostly) working on Windows. I'm still running into problems firing up ChromeHeadless but I can manually launch the browser.
2. Add a test that currently fails in ES5 browsers (tested with IE11 & Firefox). In Chrome, the `<slot />` content is rendered in the proper location, but in polyfill-land the order is reversed. This seems to only affect components with `shadow: true`, where the `render()` method returns an array, and where the last element in the array is the `<slot />`.
Cool setup for tests, btw!
=> Add test to demonstrate slot rendering bug in ES5 browsers

src/compiler/bundle/rollup-bundle.ts, src/declarations/config.ts
This PR is to expose configuration for Rollup node-resolve plugin.  This should allow developers to change configuration if need be based on a per application basis. This is to fix issue #652.
=> Expose Rollup Node Resolution Config

package-lock.json, src/client/platform-main-legacy.ts, src/client/platform-main.ts, src/client/test/use-polyfills.spec.ts, src/compiler/app/app-es5-disabled.ts, src/compiler/app/app-global-scripts.ts, src/compiler/app/build-core-content.ts, src/compiler/build/test/build.spec.ts, src/compiler/bundle/bundle-modules.ts, src/compiler/bundle/generate-bundles.ts, src/compiler/bundle/rollup-bundle.ts, src/compiler/config/test/validate-config.spec.ts, src/compiler/transpile/compiler-host.ts, src/compiler/transpile/compiler-options.ts, src/compiler/transpile/core-build.ts, src/compiler/transpile/datacollection/test/test-utils.ts, src/compiler/transpile/transformers/util.ts, src/declarations/build.ts, src/declarations/platform.ts, test/karma/package-lock.json, test/karma/src/components.d.ts, test/karma/src/dynamic-imports/dynamic-import.tsx, test/karma/src/dynamic-imports/index.html, test/karma/src/dynamic-imports/karma.spec.ts, test/karma/src/dynamic-imports/module1.tsx, test/karma/src/dynamic-imports/module2.tsx, test/karma/src/dynamic-imports/module3.tsx, test/karma/stencil.config.js, test/karma/tsconfig-stencil.json
DO NOT SQUASH
Once this PR is merged, users can safely use dynamic imports for lazy loading and still the legacy ES5 runtime will be able to handle the requests (Internet Explorer 11).
This PR takes advantage of the loading mechanics already implemented in the legacy platform to provide a `require(modules, resolve, reject)` polyfill required to implement the amd-like module for old browsers.
This changes only affect the legacy platform, modern browsers (which uses the ESM platform) will use NATIVE dynamic imports today!!!)
Use cases at Ionic:
- deferring of animation code (not required for startup)
- lazy loading of gesture code (not required for startup)
- lazy loading of routing code (some not required for startup)
- lazy loading of device shims (not required for startup)
Worths …
=> feat(bundler): dynamic import support

src/client/loader.ts
Updates the `crossorigin` attribute on the script tags generated from the loader.ts file to the value of 'use-credentials' instead of true. 
https://github.com/ionic-team/stencil/issues/786
=> fix(loader): set crossorigin to use-credentials

src/compiler/build/empty-dir.ts
Both `stencil-app-starter` and `stencil-component-starter` launch
concurrently `stencil build --dev --watch` and `stencil-dev-server`.
This was causing a problem where launching it twice was required to see
the built app.
The first approach was to add a `.gitkeep`, and though that requires some
more tweaking (see https://github.com/ionic-team/stencil-app-starter/pull/50), it is a good one. Sadly, compiler completely empties the output targets
thus removing the `.gitkeep` file.
As using this kind of file is common in the git community, this PRs checks
for the existence of such a file and recreates it after emptying the dir.
=> [FEATURE] Keep gitkeep files when emptying a directory

src/sys/node/node-logger.ts
Calculate the path to the `sys-util.js` file just like it's done in the node-sys.ts. I needed this change to programatically invoke the stencil compiler from within a third party package.
=> chore(sys): calculate relative path to 'sys-util.js'

src/client/loader.ts, src/declarations/app-global.ts
Hi, 
First of all thank you for this great library, really can change the game.
We have a scenario where we have to target some legacy applications with a component package built using Stencil. In this case the loading of the main script is done by `jQuery.ajax`, so not with a direct script reference. So the current loader mechanism fails to work as it finds the wrong `script` on the page to parse the base URL. 
This little pull request gives another layer of flexibility to the consumer side of a component library by providing an option to configure the resources URL explicitly similar to this.
```js
<script>
// Configure the resources URL explicitly in the consumer application
window.MyComponents = window.MyComponents || {};
window.MyComponents.resourcesUrl = "base URL for components"; …
```
=> Improve loader to allow using an explicit resources url setting

src/compiler/docs/generate-json-doc.ts, src/compiler/docs/markdown-attrs.ts, src/compiler/docs/markdown-props.ts
If the type info is not string,number,bool, or any, the docs process will just return an empty string.
This uses the cmpMeta, searches for the attribute text, and uses that when the propType is a custom type.
=> fix(compiler): pass non standard type values to docs

CHANGELOG.md
- add missing whitespace in 0.9.6 changelog to fix markdown formatting
=> fix(changelog): markdown formatting

src/client/polyfills/css-shim/load-link-styles.ts, src/client/polyfills/css-shim/test/init-css-shim.spec.ts, test/karma/test-app/init-css-shim/cmp-root.css, test/karma/test-app/init-css-shim/cmp-root.tsx, test/karma/test-app/init-css-shim/index.html, test/karma/test-app/init-css-shim/karma.spec.ts
Fixed: CSS_URL_REGEXP was checking only for absolute url ("http://domain/path") and taking relative to root url ("/relative/to/root") as relative, replacing it for "relative/path//relative/to/root"
=> fix(init-css-shims): CSS_URL_REGEXP check relative to root paths

src/client/queue-client.ts, src/index.ts
Use case:
```ts
import { QueueApi } from '@stencil/core';
@Prop({ context: 'queue' }) queue: QueueApi;
```
**NOTE**: at ionic, it's called `QueueController`, should we rename it in stencil?
=> fix(queue): expose queue types

src/declarations/jsx.ts
This is useful when you want to pass a slot down to an other slot
=> SlotAttributes interface must include slot attribute

CHANGELOG.md
I guess author meant to say browser but wrote bower.
=> Fixed typo in change log

src/declarations/dev-server.ts, src/dev-server/request-handler.ts, src/dev-server/serve-dev-client.ts, src/dev-server/serve-file.ts, src/dev-server/test/util.spec.ts, src/dev-server/util.ts
Build the absolute url of the dev-server iframe by using the host-header of the incoming request. This ensures, that the client can always connect to to the dev-server. It doesn't matter if it's another network device (not localhost) or if a `<base href="http://domain.tld">` tag is set in the index.html
=> fix(dev-server): set src for dev-server iframe to requested url

src/compiler/style/global-styles.ts
=> fix(compiler) skip globalStyles if buildDir is undefined

src/cli/parse-flags.ts, src/cli/test/parse-flags.spec.ts, src/compiler/build/build-ctx.ts, src/compiler/build/build-hmr.ts, src/compiler/config/test/validate-service-worker.spec.ts, src/compiler/config/validate-service-worker.ts, src/compiler/fs-watch/fs-watch-rebuild.ts, src/compiler/service-worker/generate-sw.ts, src/compiler/util.ts, src/declarations/build.ts, src/declarations/config.ts, src/dev-server/dev-client/app-update.ts
- Add `service-worker` flag.
- Allow service worker to be injected on dev builds if `service-worker` flag is set.
- If service worker file changes then reload window.
Fixes: #789
=> fix(fs-watch): reload window if service worker changed

src/core/test/render.spec.ts, src/renderer/vdom/set-accessor.ts, src/renderer/vdom/test/attributes.spec.ts, src/renderer/vdom/test/set-accessor.spec.ts, src/renderer/vdom/update-attribute.ts, test/karma/test-app/attribute-boolean/cmp-root.tsx, test/karma/test-app/attribute-boolean/cmp.tsx, test/karma/test-app/attribute-boolean/index.html, test/karma/test-app/attribute-boolean/karma.spec.ts, test/karma/test-app/attribute-host/karma.spec.ts, test/karma/test-app/components.d.ts, test/karma/test-app/reflect-to-attr/karma.spec.ts
- Setting boolean true / false to an attribute should render as a boolean attribute in HTML
```html
// tappable: false
<div></div>
```
```html
// tappable: true
<div tappable></div>
```
- Passing a boolean to a string prop, should cast the boolean to string and render as string
```html
// str: false
<my-component str="false"></my-component >
```
```html
// str: true
<my-component  str="true"></my-component >
```
- Passing a string to an attribute should always render the string
```html
// aria-hidden: "false"
<div aria-hidden="false"></div>
```
```html
// aria-hidden: "true"
<div aria-hidden="true"></div>
```
=> fix(set-accesor): boolean values

package.json, src/compiler/bundle/bundle-modules.ts, src/compiler/distribution/dist-esm.ts
This PR is to add an index.js file to the esm es5 directory so that we can have all utilities exported as es5 instead of referencing the collection directory.
=> Esm es5 exports

src/compiler/distribution/dist-angular.ts, src/compiler/transpile/create-component-types.ts, src/declarations/output-targets.ts
This PR is to fix issues with StencilComponents being removed from global scope.
=> fix(): export StencilComponents from core builds and all import to angular builds.

src/declarations/testing.ts, src/testing/puppeteer/puppeteer-browser.ts
In some environments (such as behind corporate proxies) it's difficult to download Chromium with Puppeteer.
There are a handful of environment variables to prevent Puppeteer from downloading Chromium during the install: https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-environment-variables
When configured this way, there needs to be a way to launch Puppeteer against the system Chrome (or another Chromium install). This adds a config option, which can get passed into `puppeteer.launch()`
=> feat(puppeteer): allow specification of Chrome executable

src/mock-doc/window.ts
As noted in Slack - we've got a few instances where we need `getComputedStyle` even in our unit tests. This stubs out the API good enough to pull a few out of the e2e bucket.
=> mock-doc: Add getComputedStyle

src/compiler/docs/docs-util.ts, src/compiler/docs/generate-json-doc.ts, src/compiler/docs/markdown-events.ts, src/declarations/docs.ts
fix #1161 
This adds a detail key to the events doc-json and adds a column for Detail to the generated readmes
It does not list void, since this value is used whether the EventEmitter is passed void or no value, where no value may not necessarily be correctly void
=> docs: add detail to generated event docs

src/compiler/build/build-ctx.ts
Related issue: #1176
Maybe this was intended, but I was going insane checking the build time thinking it was a month old :sweat_smile:
=> Fix build month in build timestamp

src/compiler/docs/test/markdown-props.spec.ts, src/compiler/transpile/create-component-types.ts, src/compiler/transpile/datacollection/event-decorator.ts, src/compiler/transpile/datacollection/method-decorator.ts, src/compiler/transpile/datacollection/prop-decorator.ts, src/compiler/transpile/datacollection/test/component.spec.ts, src/compiler/transpile/datacollection/test/fixtures/prop-example.ts, src/compiler/transpile/datacollection/test/method-decorator.spec.ts, src/compiler/transpile/datacollection/test/prop-decorator.spec.ts, src/declarations/component.ts
```
@Prop() required!: string;
@Prop() optional?: string;
@Prop() alsoOptional = 'defaultValue';
```
and we could reflect that in the JSX types
Use cases:
- ion-tab, ion-tab-button  (both need the “tab” prop)
- ion-router and stencil-router: (path and component props)
- many others
=> feat(types): add support for JSX required props

src/compiler/config/validate-docs.ts, src/compiler/config/validate-outputs.ts, src/compiler/docs/docs.ts, src/compiler/docs/generate-custom-docs.ts, src/declarations/output-targets.ts
Allows for user provided docs generators:
```ts
import { customDocsGenerator } from 'example-package';
export const config = {
outputTargets: [
{
type: 'docs-custom',
generator: customDocsGenerator
}
]
};
```
=> feat(docs): custom docs generators

src/declarations/testing.ts, src/testing/puppeteer/puppeteer-browser.ts
Add browserWSEndpoint option to testing config.
When used it may require that the devServer address be set in the config if the stencil test runner is invoked from a different host than the chrome instance, such as when running in a docker environment.
We need this functionality at Big Cartel to run e2e tests in our containerized env since Alpine Linux doesn't support the Chromium version automatically downloaded by Puppeteer. All our browser based testing runs in an instance of [browserless](https://github.com/joelgriffith/browserless) running the tagged version of Chrome needed for the version of puppeteer that Stencil depends on for e2e tests.
=> feat(e2e) add remote chrome support for puppeteer

src/core/disconnected.ts
This PR relocates the removal of a certain elements' event listeners to after its `componentDidUnload` method call.
As stated in [#1218](https://github.com/ionic-team/stencil/issues/1218), when an event is emitted within a component's `componentDidUnload` method, it can no longer be consumed by its listeners.
By moving the `plt.domApi.$removeEventListener(elm)` and `plt.hasListenersMap.delete(elm)` calls to after the `componentDidUnload` call, events fired within `componentDidUnload`  can still be consumed by all listeners.
=> fix(events): remove event listeners after lifecycle hook call

src/compiler/prerender/host-config.ts, src/server/platform-server.ts
This should fix 
> ENOENT: no such file or directory, open
'/Users/.../www/build/app/undefined.es5.entry.js' at
of issue [https://github.com/ionic-team/stencil/issues/1144](url). It is uses the very similar logic you've already used when getting bundleIds as array in a different place of an application thus I thought it will be a good idea to stick to this logic.
One more thing - when I was debugging I've noticed that ionic's components are giving me bundleIds for ios and md; Would it be a good idea to take that into notice at some point in time?
=> fix: export DEFAULT_MODE from host-config to use it in platform-server and to prevent undefined as a bundle id.

src/testing/puppeteer/puppeteer-declarations.ts
This removes `url` from the omitted entries on the `PuppeteerPage` type.
Closes #1220.
---
BTW I believe `goto` should be added to the omitted list, because `goTo` is exposed instead? Found it kind of confusing to have two goto methods...
**Edit:** just checked and `goTo` doesn't actually work?
```
TypeError: page.goTo is not a function
```
=> feat(e2e): expose page.url() method

src/compiler/entries/app-graph.ts, src/compiler/transpile/datacollection/component-decorator.ts, src/compiler/transpile/datacollection/test/component-decorator.spec.ts, src/compiler/transpile/datacollection/test/fixtures/component-valid-name.ts
This PR will resolve [#947](https://github.com/ionic-team/stencil/issues/947) 
I have added a check for tag name of a custom component as defined [here](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name)
I have taken reference from [here](https://github.com/mathiasbynens/mothereff.in/blob/master/custom-element-name/vendor/is-potential-custom-element-name.js)
I have seen that this issue is listed on-deck on the [project](https://github.com/ionic-team/stencil/projects/1) page. So, I picked it up. This is my first try to contribute code in stencil. Do let me know if there is any correction in this PR or code.
=> feat(compiler): add check for potential custom element name issue#947

src/mock-doc/location.ts
Fixes https://github.com/ionic-team/stencil/issues/1401
=> bug(MockLocation): store href for getter usage

src/cli/task-serve.ts
Allow to pass `--open` flag to serve command to open the Browser
=> Make serve openBrowser configurable with open flag

src/cli/task-serve.ts, src/dev-server/start-server-worker.ts
Set the `initialLoadUrl` to `'/'` when using serve command and make the server use it if configured instead of the default `DEV_SERVER_INIT_URL`
=> Make serve command launch root url

src/utils/in-memory-fs.ts
I was getting a _JavaScript heap out of memory_ when building on my Windows machine. I traced it down to the `ensureDir` function which does not manage to break out of the `while(true)` loop due to `this.path.dirname` returns the string with backslash `\` folder-separators.
Not sure if there are cases where `:/` is relevant on other Windows setups, but I figured it's safer to just check both.
=> fix(): ensureDir for backslash folder-separator

src/compiler/transformers/remove-stencil-import.ts, src/index.ts
By adding `getElement` to `KEEP_IMPORTS` and exposing it in `src/index.ts`, we'll be able to use `getElement(this)` as an alternative to `@Element()`. The real goal however is not to replace `@Element()`, but that things like decorators will be able to access the host element without requiring additional setup  from the user of the decorator, a setup that's so un-intuitive that you probably have to refer to the documentation.
For example, consider the following decorator:
```ts
export function Lazy(hostProperty: string) {
return (proto: any, prop: any) => {
const { componentWillLoad } = proto;
proto.componentWillLoad = async function() {
const host = this[hostProperty];
// Setup IntersectionObserver
return componentWillLoad.call(this);
}
};
}
```
Here's how we would have to use this …
=> expose getElement to @stencil/core

src/declarations/testing.ts, src/testing/puppeteer/puppeteer-browser.ts
NOTE: I closed my previous PR to make the change in Stencil One :)
Puppeteer launch api: https://github.com/GoogleChrome/puppeteer/blob/v1.13.0/docs/api.md#puppeteerlaunchoptions
=> feat (Puppeteer): Added devtools option in puppeteer.launch

readme.md
Fixed "runs" to "run".
The verb refers to "web components" which is plural, so the correct form is "run" and not "runs". 
See: https://www.quora.com/What-is-the-third-form-of-the-word-run
Cheers
=> Update readme.md / Fixed Typo in readme

src/runtime/test/assets.spec.tsx
In tests `getAssetPath` is not a function. This is not testing the result of it, just that it's at all available.
=> add test for getAssetPath

BREAKING_CHANGES.md
In the breaking changes file there is a function definition that didn't really make sense
=> docs(breaking) fix @Method await typo

src/declarations/jsx.ts
Adds missing attribute types for event-handlers on media elements such as `<video/>` and `<audio/>`.
Closes #1317.
=> feat(types): add media event-handler attributes

src/declarations/jsx.ts
I believe that I should be able to do an inline event listener for the close event. Example is the returning value from dialog section https://demo.agektmr.com/dialog/ https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element
=> Add close event to Dialog

src/runtime/bootstrap-lazy.ts, src/runtime/update-component.ts
Noticed an issue where hydrated styles were not being applied and causing a flash of unstyled content in my components. Since I use css-in-js and none of the built in styling mechanisms, Stencil was not blocking rendering until styles were applied.
=> fix(lifecycle): using css-in-js with no styles causes FOUC

src/compiler/events.ts
This fixes an HMR issue where `buildResults` was never sent to the dev-server client because only the most recent `buildFinish` event subscriber was attached.
I think the bug was introduced in https://github.com/ionic-team/stencil/commit/fbbe23260ab95de004e02ab856532bb684c74dcc#diff-06187c875ae567c88cb345d2abd4ea2b.
BTW after applying this fix locally in my project (within `node_modules/@stencil/core/dist/compiler/index.js`), I had some really weird behavior until I cleaned my `.stencil` directory. The only thing that would end up in `components.d.ts` was the last component that I had edited.
Does Stencil auto-clear the `.stencil` folder if the version that the cache was created with is a mismatch (i. e. an older version than the one currently compiling)?
=> fix(hmr): call all callbacks in build event subscribers

src/compiler/component-hydrate/bundle-hydrate-app.ts
Fixes #1554.
Or is it on purpose that the `nodeResolve` config option wasn't passed into the hydrate-app bundling?
=> fix(config): nodeResolve config

src/testing/jest/jest-serializer.ts, src/testing/jest/jest-setup-test-framework.ts, src/testing/jest/test/__snapshots__/jest-serializer.spec.ts.snap, src/testing/jest/test/jest-serializer.spec.ts
Adds html serializer as a jest serializer, so expect(elm).toMatchSnapshot() will work (similar to the toEqualHtml matcher). Shadow DOM is always serialized.
=> Html snapshots

src/compiler/rollup-plugins/in-memory-fs-read.ts
Throws a warning if an importee is resolved to a typescript file, and lets the user know how to resolve to the equivalent javascript file instead. Note that the error message in the screenshot wouldn't appear if the content of `src/helpers/utils.ts` was valid javascript (it would just be treated as JS, even though the file has a `.ts` extension).
Not sure whether it's ok that I used the `Plugin` interface from `rollup` instead of `../../interfaces`, but the one in interfaces is pretty out of date (I think it's from the time before rollup version 1).
=> feat(compiler): warn about typescript imports

src/testing/puppeteer/puppeteer-page.ts
Sometimes when taking screenshots some of the images has not finished loading. This commit will wait for the network to become idle - indicating that all resources has been loaded - before continuing.
=> fix(e2e): wait for idle network

src/mock-doc/event.ts, src/mock-doc/global.ts, src/mock-doc/index.ts, src/mock-doc/test/event.spec.ts, src/mock-doc/window.ts, src/runtime/test/event.spec.tsx
Adds KeyboardEvent to MockDoc so it can be used in unit tests.
=> feat(mock-doc): add KeyboardEvent

src/compiler/plugin/plugin.ts
Documenting CSS variables did not work if `--docs-json` was not set (they did not appear in the markdown file).
I added `docs-readme` and` docs-vscode` (not sure what this flag does, you might want to remove it) to the shouldParseCssDocs checks.
=> fix(compiler): document CSS variables in the MD file even if 'docs-json' is not set

src/mock-doc/global.ts, src/mock-doc/window.ts, src/runtime/test/element.spec.tsx, src/runtime/test/globals.spec.tsx
Customer needs to have `Element` on `MockWindow`.
The customer's tests fail when they try to test a Stencil component that itself uses `tippy.js`. Here is where it is failing with a ReferenceError because `Element` is not found, so that is essentially what I am trying to duplicate in the test w/o actually including `tippy.js`.
Here is the LOC in tippy.js that results in the failure in the Stencil component unit test:
https://github.com/atomiks/tippyjs/blob/8b23e4a51452b89ca9a54731bb499eac4cc2920e/src/ponyfills.ts#L3
This PR adds `Element` to `MockWindow` in order to facilitate these tests.
=> feat(mock-doc): add Element

src/compiler/app-core/app-es5-disabled.ts
using target="_blank" by itself is considered to be a security vulnerability. these links get flagged by some static analysis tools
can see more information here: https://mathiasbynens.github.io/rel-noopener/
=> fixing unsafe usage of target="_blank"

src/testing/jest/jest-preprocessor.ts
Related issue: #1677
As the jest preprocessor is right now, having any type of output diagnostic (warning, for instance) from the compiler will cause a test case to fail. The way I see it, this should only happen if it's an error, as some warnings are just indications.
=> Run specs even if file has build warnings

src/testing/index.ts
SpecPage type is only exported from the declarations file making its import different than E2EPage.
```
import { SpecPage } from '@stencil/core/dist/declarations'
import { newSpecPage } from '@stencil/core/testing'
let page: SpecPage
```
```
import { E2EPage, newE2EPage } from '@stencil/core/testing'
let page: E2EPage
```
Resolves #1656
=> fix(testing): SpecPage is not exported

src/compiler/rollup-plugins/in-memory-fs-read.ts
Was just working in that file again and noticed that I forgot the `$` in the regex for that warning message (which I added in #1576).
=> fix(compiler): warning regex for .ts(x) imports

test/karma/test-app/components.d.ts, test/karma/test-app/reparent-style/index.html, test/karma/test-app/reparent-style/karma.spec.ts, test/karma/test-app/reparent-style/reparent-style-no-vars.css, test/karma/test-app/reparent-style/reparent-style-no-vars.tsx, test/karma/test-app/reparent-style/reparent-style-with-vars.css, test/karma/test-app/reparent-style/reparent-style-with-vars.tsx
👋 
Here's a (failing in IE) test that demonstrates an issue we're seeing with components that use CSS variables when we reparent (move them around) on a page: #1615
Basic idea is, to support tooltips, dropdowns, and other positioned items, it's often helpful to detach an element from its location in the DOM tree, and reattach them to the body of the page. Similar to [portals](https://reactjs.org/docs/portals.html) in React and other frameworks.
What we've noticed is that if the element being moved around:
* is a Stencil component,
* and contains any CSS custom properties,
* and you're running IE11
it loses its `<style>` tag  when it's detached from the DOM, and it never gets styles applied again.
You can see this happen in the `'should preserve styles after reparenting a component (with …
=> chore: add failing (in IE) test demonstrating #1615 (reparenting w/ CSS vars)

src/mock-doc/document.ts, src/mock-doc/element.ts, src/runtime/test/svg-element.spec.tsx
This change just adds some of the basic APIs and not the whole
set of them. In addition:
- the methods just return some kind of sane default value
- rather than having several sub-classes, everthing is squashed
into MockSVGElement for simplicity
=> feat(testing): add MockSVGElement

src/mock-doc/element.ts, src/mock-doc/test/html-parse.spec.ts
As per: #1706, adds a canvas element mock to `mock-doc`, allowing pre-rendering with canvas api usage like `getContext()`.
=> feat(mock-doc): add canvas

src/runtime/vdom/set-accessor.ts
IE11 unfortunately cannot handle multiple arguments when using HTMLelement.classList.add/remove. This should fix some issues with IE11 errors. Someday the terrible browser will die, till then....
I believe this should fix #1757.
=> fix(runtime): simplify classlist.add/remove for IE11

src/runtime/test/render-vdom.spec.tsx, src/runtime/vdom/set-accessor.ts, src/runtime/vdom/test/set-accessor.spec.ts
I figured out that when you are using template strings and it has line breaks the last fix does not cover this case properly, I did change the approach to use a regex to clear the extra spaces and line breaks from classList value.
it should fix #1757
=> fix(runtime): Add regex to clear multiple spaces and line breaks in classList.

package.json, scripts/build-cli.js, scripts/build-prod.js, src/cli/run-task.ts, src/cli/task-generate.ts, src/declarations/config.ts
```sh
stencil g
stencil generate
stencil generate path/to/my-comp
```
- fails when not run in a Stencil project root, i. e. not in the folder that contains `stencil.config.ts`
- fails when the component name doesn't contain any dashes
- allows to prefix the component name with a path (see gif)
- respects `srcDir` from `stencil.config.ts`
- generates all files into subfolders of `<srcDir>/components`
- doesn't allow overwriting existing files (`wx` flag)
- `shadow: true` is set
- `styleUrl` is only set if a stylesheet has been created
Things I'm not sure about:
- Should I have used `graceful-fs` over `fs` (don't see the benefit)?
- Was it correct to add `inquirer` to the list of packages to copy the license for (prod build)?
- Those CI tests also fail on master, so most likely unrelated? …
=> feat(cli): add component generator

src/mock-doc/event.ts, src/mock-doc/global.ts, src/mock-doc/index.ts, src/mock-doc/test/event.spec.ts, src/mock-doc/window.ts, src/runtime/test/event.spec.tsx
Adds MouseEvent to MockDoc so it can be used in unit tests.
Modeled after #1581 
Resolves issue #1829
=> feat(mock-doc): add MouseEvent

src/declarations/config.ts
Currently the documentation comment are swapped for the `minifyJs` and `minifyCss`.
=> correct minify comments

src/client/polyfills/css-shim/load-link-styles.ts, src/client/polyfills/css-shim/test/init-css-shim.spec.ts
This PR is addressed to https://github.com/ionic-team/stencil/issues/1860
When all relative paths in url() in styles are replacing to absolute. We need to make sure that "data urls" will be omitted. 
As the regular expression had to be updated I had to also update an "http" protocol an added optional 's' to make sure that 'http' and 'https' are included.
=> fix(css-shim): skip 'Data URLs' when fixing relative urls

src/compiler/component-lazy/generate-system.ts
- Wraps the polyfills and loading logic inside a self-executing function to avoid leaking variables to the window object. Fixes #1786 
- First looks for a script with `data-stencil-namespace` or `data-resources-url` to resolve the resources url, instead of always using the last script in the DOM. Fixes #1787, fixes #1456
=> System.js build: Fix leaking variables, improve resource resolution logic

.gitignore, src/client/polyfills/css-shim/custom-style.ts, src/client/polyfills/css-shim/load-link-styles.ts, src/client/polyfills/css-shim/scope.ts, src/client/polyfills/css-shim/test/css-shim.spec.ts
Issue: #1891 
Instead of using `innerHTML`, would be better to use `textContent` property. 
The `textContent` works properly on all browsers and is more performant (does not parse HTML, and is faster). `style` tag does not contains HTML. So seems to be using `textContent` is more appropriate.
=> fix(css-shim): Replaced innerHTML with textContent

.github/workflows/main.yml
This runs everything except the karma test, because I'm not yet sure how to setup browserstack.
The matrix is set up to cross-test Node.js versions 10 and 12 on Ubuntu, macOS and Windows each.
All the tests are run within the same job, which means the indiviual tests (i. e. dist, end-to-end, jest, etc) don't run in parallel. This can be split into multiple jobs, however I'm not yet sure how well that works with respect to the matrix setup.
It's by default set to cancel all the matrix tests if any of them fails ([`strategy.fail-fast`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast)), which I turned off.
=> chore(ci): add github actions workflow

src/compiler/component-lazy/generate-lazy-app.ts
By setting a 'data-stencil-namespace' attribute on the generated legacy script tag before adding that to the DOM, the script will correctly detect the base URL of the chunks that need to be loaded.
This fixes an issue in IE11 where using the 'old' method of integrating a Stencil components library (by adding a single <script> tag) did not work. The `namespace` part of the chunk URLs was missing.
=> Fix chunk URL determination in IE11

src/runtime/bootstrap-lazy.ts, test/karma/test-app/components.d.ts, test/karma/test-app/lifecycle-nested/cmp-a.tsx, test/karma/test-app/lifecycle-nested/cmp-b.tsx, test/karma/test-app/lifecycle-nested/cmp-c.tsx, test/karma/test-app/lifecycle-nested/index.html, test/karma/test-app/lifecycle-nested/karma.spec.ts, test/karma/test-app/lifecycle-nested/output.ts
This PR fixes issue #1261 and adds a specific Karma e2e test for the following case where lifecycle events are out of order for nested components:
```
<cmp-c>
<cmp-b>
<cmp-a></cmp-a>
</cmp-b>
</cmp-c>
```
=> fix(lifecycles): Defer connectedCallback until all components registered

src/declarations/jsx.ts
Fixes #2002
Adds a referrerPolicy property to the iframe jsx interface so users are able to define the referrerPolicy on their iframes.
=> fix(jsx): add referrerPolicy for iframe interface

src/runtime/event-emitter.ts
Came across this error during development work: quick spelling fix for the error message
=> chore(event-emitter): fix spelling in err msg

src/compiler/output-targets/output-angular.ts
👋 
This PR refactors the compiler's angular output target to use a Directive instead of proxy functions.
With recent updates to Angular's build tool (the buildOptimizer specifically) `proxyInput` and `proxyMethods` would be dropped from the final output since they are not part of a component. This would break tests in ionic's angular test setup.
Instead of using proxy functions, we use a decorator to decorate the component with the logic needed.
```ts
export function ProxyCmp(opts: { inputs?: any; outputs?: any; methods?: any }) {
return (cls: any) => {
if (opts.inputs) {
proxyInputs(cls, opts.inputs);
}
if (opts.methods) {
proxyMethods(cls, opts.methods);
}
if (opts.outputs) {
proxyOutputs(cls, cls.el, opts.outputs);
}
return cls;
};
}
```
During a build, the output would be 
```ts …
```
=> chore(): refactor angular output target

src/runtime/bootstrap-lazy.ts, src/runtime/profile.ts, src/runtime/update-component.ts
See issue: https://github.com/ionic-team/stencil/issues/2080
This solves the Safari 10.0 iOS hydration.
Because the Performance api in this Safari only has method `now()`.
Cheers
=> fix(runtime): Safari 10.0 hydration solved by dont using performance api

src/compiler/config/test/validate-config.spec.ts, src/compiler/config/validate-config.ts, src/compiler/html/inline-esm-import.ts, src/declarations/stencil-public-compiler.ts
We have some projects where we rely on script tags being in a certain place in the DOM. The stencil compiler moves these around when it inlines scripts. This flag would allow us to prevent inlining and keep script tags where we expect them to be in the HTML file.
=> Add config flag for preventing script inlining

readme.md
Closes #2091.
Add missing import `h` to code example.
=> fix(readme): code example missing import

src/mock-doc/selector.ts, src/mock-doc/test/selector.spec.ts
fixes #2038 
Currently, unit testing does not support CSS combinators (when using `SpecPage`). This PR adds support for child combinators, allowing operations such as `el.querySelector('div > span')` to work as expected.
=> Modify selector to handle child combinators when unit testing

src/compiler/docs/readme/docs-util.ts, src/compiler/docs/test/markdown-props.spec.ts
=> fix(compiler): change props union type parsing

src/compiler/docs/generate-doc-data.ts, src/compiler/docs/readme/markdown-parts.ts, src/compiler/docs/readme/output-docs.ts, src/declarations/stencil-public-docs.ts, test/end-to-end/package.json, test/end-to-end/src/car-list/car-list.tsx
Parse comments for @part and output docs in json and the readme files. From https://github.com/ionic-team/stencil/issues/2121
=> feat(docs): Add documentation output for Shadow Parts

src/cli_next/tasks/task-generate.ts
For generated components, this gets the default up to 100% by default.
=> fix(cli): Update tests in task generator

src/utils/helpers.ts, src/utils/logger/logger-typescript.ts
logger-typescript:
- checking iterability instead of truthiness
fixes error on https://github.com/ionic-team/stencil/issues/2106
=> fix(logger): checking iterability of diag.next (instead of truthiness)

src/declarations/stencil-public-runtime.ts
Fixes:
<svg key={...} /> // Property 'key' does not exist on type 'SVGAttributes<SVGElement>'.ts(2322)
=> Every JSX element should have a "key"

src/runtime/test/render-vdom.spec.tsx, src/runtime/test/svg-element.spec.tsx, src/runtime/vdom/vdom-render.ts
Text nodes inside `<svg>` are possible, look at the `<text>` tag:
```
<svg>
<text>Message</text>
</svg>
``` 
`#text` nodes are not SVG elements and their `ownerSVGElement` is undefined, however that does not mean the vdom render left the SVG, so `isSvgMode` should still be true after rendering a text node.
This breaks SVG rendering after the first `#text` node
=> fix(runtime): render svg #text nodes

src/runtime/vdom/h.ts
Fixes #2158 
Hide the following warning for inputs without a `value` attribute:
`The "value" prop of <input> should be set after "min", "max", "type" and "step"`
=> Don't show warning for inputs without `value` attribute

readme.md
A tiny edit to fix the syntax highlighting in the readme example.
Before:
After:
=> docs(README): fix syntax highlighting

src/compiler/docs/readme/output-docs.ts, src/declarations/stencil-public-compiler.ts
I have added a dependencies: boolean property to OutputTargetDocsReadme, this allows the developer to disable the dependencies part of the markdown readme.md file.
If the property is undefined the dependencies will still be rendered.
=> feat: Disable the dependencies part of the markdown docs.

src/compiler/transpile/transpile-module.ts
Fixes #2211.
Problem was that (at least with the provided lerna mono-repo case) there's more files emitted by the ts program than expected, or they are in a different order. For full details see https://github.com/ionic-team/stencil/issues/2211#issuecomment-589966100.
Not sure this is the most correct solution but all tests pass and it works with our app and app tests.
=> fix(compiler): ignore irrelevant emitted files of ts transpiler

src/declarations/stencil-public-runtime.ts
blocks https://github.com/ionic-team/ionic/pull/21035 https://github.com/ionic-team/ionic/pull/21036
- Adds support for enterkeyhint to all elements
- Removed unneeded inputmode from InputHTMLAttributes since it is global
=> feat(): add enterkeyhint to HTMLAttributes

src/testing/jest/jest-runner.ts
- Fixes error 'runJest: TypeError: runCLI is not a function' with Jest 25
Using jest-cli to import runCli breaks in jest@25 and @jest/core must be used instead.
This package started shipping in jest@24.3.0 so its safe to use it as Stencil installs jest@24.9.
Fixes #2168 
- Checkout this branch
- `npm run build`
- `npm link`
On a project that uses Stencil (for example, [stencil-component-starter](https://github.com/ionic-team/stencil-component-starter)), run:
- `npm test`
- Verify there are no errors when using jest@24.9
- `npm install jest@25 jests-cli@25`
- `npm link @stencil/core`
- `npm test`
- Verify there are no errors when using jest@25
=> fix(jest): change package used to import runCli

src/testing/mock-fetch.ts
`MockResponse404` extends from `MockResponse` which sets `ok` to `true` by default. However, `ok` should only be `true`, if the status code is within the 2xx range.
Alternatively, we could change the `ok` property of `MockResponse` to a getter:
```
export class MockResponse {
get ok() {
return this.status >= 200 && this.status <= 299
}
}
```
However, by doing that `ok` would be readonly and that is probably a breaking change. 🤔
=> fix(testing): MockResponse404 is not ok

src/compiler/config/outputs/validate-docs.ts
=> chore(validate-docs.ts): err message spelling

src/compiler/transformers/decorators-to-static/event-decorator.ts
`ValueChange` is not a DOM event, but a XUL event: https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL/Events/ValueChange.
So this event can be removed so web components can define their own `valueChange` event emitters.
=> fix(): remove `ValueChange` XUL event

src/declarations/stencil-public-runtime.ts
`as` Attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#Attributes
=> Add missing 'at' attribute to LinkHTMLAttributes

src/compiler/config/outputs/validate-dist.ts
With the help of @simonhaenisch I could find the reason why https://github.com/ionic-team/stencil/issues/2349 is happening. 
It is because here https://github.com/ionic-team/stencil/blob/4c70fdd2c418a1419c8c30bd585d4a081100b28b/src/compiler/config/outputs/validate-dist.ts#L47
the `buildDist` is `false` and the output target `DIST_TYPES` is not added in dev-mode. It is however needed later on.
This causes this condition to return false:
https://github.com/ionic-team/stencil/blob/63595bc540db9aa85295f5a8dc8738beb2a37611/src/compiler/transpile/ts-config.ts#L8
and `declaration` becomes `false` - which is not allowed in combination with `composite: true`.
I first tried to tackle it via this line by removing the `devMode` condition but it seems too related to other (global) decisions you've …
=> fix(dev-mode) always add dist-types

src/testing/puppeteer/puppeteer-page.ts
Trying to resolve https://github.com/ionic-team/stencil/issues/2326 so that we can override API requests in user land tests.
=> fix(test): allow setRequestInterception to ba called from user tests

src/declarations/stencil-public-runtime.ts
This PR adds types for the `toggle` [event](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#Events) in `<details>` with the `onToggle` property.
Closes: #2398
=> Add onToggle property to the DetailsHTMLAttributes interface

src/compiler/docs/vscode/index.ts
Fixes #2362
I wasn't able to run tests locally, as this reference wasn't resolving (file doesn't exist): https://github.com/ionic-team/stencil/blob/92e70fb113efbef03b3bf60d4c3b84ed99e25ad3/jest.config.js#L2
Hopefully no tests break!
=> fix(vscode-docs) correctly join repoBaseUrl and component filePath

src/cli/tasks/task-generate.ts
Since generated tests are now placed in a `tests` folder (baff1dc), the import path had to be adjusted.
=> fix(cli): correct import in generated spec tests

src/declarations/stencil-public-runtime.ts
blocks https://github.com/ionic-team/ionic/pull/21464
We are getting a compiler error when trying to specify types for `autocapitalize`. This change comes after discussion with Manu re: what to do about the issue.
=> fix(): change autocapitalize types to any to avoid conflicts

src/compiler/style/css-imports.ts
This PR fixes compilation of multiple CSS files as documented in #2432
They underlying issue was with the stateful nature of the RegEx `exec` command when using the `g` flag. Moving it into the closure of the function makes sure it's reset for each file, fixing the problem.
I have a [test comparing the contents](https://github.com/alex-ketch/stenciljs-postcss-import-issue/blob/master/src/components/app-root/app-root.spec.ts) of the compiled files in the reproduction fork here, but I haven't found a good way to test for it in this repo.
Exporting and testing the `updateCssImports` function works until it tries to read the file contents at [`compilerCtx.fs.readFile`](https://github.com/ionic-team/stencil/blob/master/src/compiler/style/css-imports.ts#L104), where the `mockCompilerCtx` seems …
=> Fix CSS compilation for multiple styleURLs (Close #2432)

src/compiler/transpile.ts
This should resolve a few `Cannot use import statement outside a module` errors when spec files are run. 
There's a slightly deeper problem here re: who decides what is a module.  Both typescript and jest can be configured to accept different extensions as module types, but neither configuration is honoured by the stencil compiler when spec files are run.  Perhaps a better fix would be to inspect the `opts` in this helper function to determine which extensions to add here.
Adding `js` to the list of files to compile may introduce potential slowness or problems, as more files will be run through the typescript compiler now.
=> fix(compiler): fix transitive module dependencies in unit tests (#2178)

src/testing/jest/jest-config.ts
`coverageThreshold` was never being set in `jestConfig` as it is an object
See https://jestjs.io/docs/en/configuration.html#coveragethreshold-object
Note: https://stenciljs.com/docs/testing-config doesn't mention anything about it being a special option so if it _should_ be a string then the docs need updating instead of merging this PR.
I also tried using `JSON.stringify` to set it but that just made Jest fall over with:
```
[ ERROR ]  runJest: ● Validation Error:   Option
"coverageThreshold" must be of type:  object  but
instead received:  string   Example:  {
"coverageThreshold": {  "global": {  "branches":
50,  "functions": 100,  "lines": 100,
"statements": 100  }  }  }
Configuration Documentation:  https://jestjs.io/docs/configuration.html
```
=> fix(jest): correctly set coverageThreshold

src/declarations/stencil-public-runtime.ts
Fix for Issue #2530
https://www.w3schools.com/tags/tag_th.asp
=> fix(type definition): add abbr to ThHTMLAttributes

src/dev-server/dev-server-utils.ts, src/dev-server/serve-file.ts, src/dev-server/test/util.spec.ts
Read and use `X-Forwarded-Host` and `X-Forwarded-Proto` when constructing the dev-server client URL.
This makes it possible to put the dev-server behind and HTTP/2 or TLS proxy, which can redirect requests not only to the dev-server but also all kinds of backend API-services.
For instance, the following *nginx* config can be used to serve both the dev-server and a couple of API endpoints over HTTP/2.
```nginx
http {
ssl_certificate     fullchain.pem;
ssl_certificate_key privkey.pem;
ssl_dhparam         ffdhe2048.txt;
ssl_protocols       TLSv1.2 TLSv1.3;
ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-S …
```
=> dev-server: pick up scheme and host from forwarding proxy.

package-lock.json, package.json
See https://github.com/rollup/plugins/issues/497#issuecomment-657952505. v13.0.0 broke named exports for __esModule packages. v13.0.1 fixed named exports but broke default exports for __esModule packages. This is still the case in v14.0.0.
The master branch already has a fix (see https://github.com/rollup/plugins/pull/501) but not sure when that's going to be released.
In the meantime we can just downgrade to v12 which didn't have any of these issues.
=> fix(bundling): downgrade `@rollup/plugin-commonjs`

src/compiler/transformers/decorators-to-static/method-decorator.ts
Add missing brackets to `@Method()` in terminal warning code example.
=> style(compiler): fix terminal warning

src/testing/jest/jest-config.ts, src/testing/jest/test/jest-config.spec.ts
Hi!
This PR allows us to collect the code coverage from other not tested code files, adding the *collectCoverageFrom* jest parameter.
Resolves #2557
=> feat(testing): add collectCoverageFrom jest parameter

src/compiler/sys/modules/fs.ts
This fixes a windows specific issue when resolving modules due to path formatting ([discovered investigating this](https://github.com/ionic-team/stencil/issues/2610)).
In my case when resolving the uuid package, it was looking for:
```json
"C:\\Development\\stencil-node-resolve-issue\\node_modules\\uuid\\dist\\esm-node\\index.js"
```
against:
```json
{
"./dist/md5.js": "C:/Development/stencil-node-resolve-issue/node_modules/uuid/dist/md5-browser.js",
"C:/Development/stencil-node-resolve-issue/node_modules/uuid/dist/md5.js": "C:/Development/stencil-node-resolve-issue/node_modules/uuid/dist/md5-browser.js",
"./dist/rng.js": "C:/Development/stencil-node-resolve-issue/node_modules/uuid/dist/rng-browser.js",
"C:/Development/stencil-node-resolve-issue/node_modules/uuid/dist/rng.js": …
```
=> fix(compiler): normalizePath result from fs.realpathSync

src/runtime/update-component.ts
With `taskQueue: "async"` and `"congestedAsync"` `scheduleUpdate` calls `writeTask`, passing it the `dispatch` callback. `writeTask` calls the passed in dispatch callback in `process.nextTick`
Before this change, when the taskQueue: was set to `immediate`, the dispatch callback was never called. Resulting in no components rendering in the DOM.
Fixes https://github.com/ionic-team/stencil/issues/2491
=> Fix taskQueue: "immediate" rendering nothing

package-lock.json, package.json
* `rollup`: 2.23 -> 2.25
* `@rollup/plugin-commonjs`: 12 -> 15
* `@rollup/plugin-node-resolve`: 8.4 -> 9
* `@rollup/pluginutils`: 3.1 -> 4
Also ran `npm audit fix` which updated a couple patch versions of dependencies of `conventional-changelog-cli`.
=> chore: update rollup dependencies

CHANGELOG.md
Add a section to make it easy for devs to restore their Stencil 1 defaults. I'm not really sure about `taskQueue` though. The goal is to make it easy for people to do the upgrade easy without breaking, but changing the `taskQueue` isn't a breaking change and so I didn't want to suggest it here. Feel free to overrule me on that though :)
=> docs(changelog): example to restore 1.x defaults

.github/CONTRIBUTING.md
While making another PR, I noticed some of this useful information was missing from your CONTRIBUTING.md. Following the steps I added, I was able to test my changes to stencil's internals against my local stencil project.
=> add information to contributors' guide about how to test changes locally

src/compiler/docs/custom/index.ts, src/declarations/stencil-public-compiler.ts
I would like to have access to the logger when using the `docs-custom` output target, at the moment only the `docs` generated by Stencil is given to the `generator` function.
Sending only the logger to `generator` seems a bit weird and since the logger is available on `config` I added that as an argument instead. There might be other stuff on `config` that also could be of use to anyone using the `docs-custom` output target.
If there is another way to do this, please let med know! :slightly_smiling_face: 
I'm also not sure if there is anything else I need to update, all the tests pass at least! :slightly_smiling_face:
=> feat(docs-custom): add config argument

src/mock-doc/location.ts, src/mock-doc/test/location.spec.ts
The hostname was not updated when a new href is set on the window location, it looks like this was an oversight, this commit makes it so the hostname is populated like everything else.
chore(test): add test for MockLocation behaviour
Closes #2688
=> fix(mock-doc): set hostname when location is updated

src/runtime/vdom/test/scoped-slot.spec.tsx, src/runtime/vdom/vdom-render.ts
This is the same fix as proposed in #2336 by @kevin-coyle-unipro. It was easier to create a fresh PR than somehow coordinate contributing to the other PR. Sorry about that!
This PR also incorporates changes suggested by @simonhaenisch.
For added confidence, I also tested this change against the design system I am working on, and all ~600 tests pass (including visual regression tests). 
Fixes #2336. Fixes #2307
=> fix(vdom): hide fallback slot when content present in scoped/non-shadow components

src/declarations/stencil-public-compiler.ts, src/dev-server/index.ts
Follow-up on #2719 because `startupTimeout` was added to the wrong interface and therefore wasn't exposed to the user.
Also changed it to interpret the value zero as "disable timeout completely", and added a description comment.
Closes #2718.
=> fix(devserver): expose startupTimeout

src/testing/puppeteer/puppeteer-declarations.ts
Recently I was working on setting up a test and wasn't sure if the key I needed pass was named 'Enter' or 'Return'. As I dug into the E2EElement interface and was reading about the press method, I found a link to the Keys that puppeteer supports. I've updated the comment to use the new link as the old one was 404ing.
=> Update link to puppeteer's key names

src/declarations/stencil-ext-modules.d.ts
`*?worker` declaration is outdated / doesnt match current behaviour.
Updated declaration based on `import * as worker from './worker.worker.ts?worker;`
and https://stenciljs.com/docs/web-workers#advanced-cases
=> Update *?worker declaration

src/client/client-window.ts
Test for presence of replace-Method of CSSStyleSheet as we rely on this method. Not every browser that implements CSSStyleSheet does also implement CSSStyleSheet.replace()
=> fix(client): Test for presence of replace-Method of CSSStyleSheet

src/runtime/proxy-component.ts, src/runtime/test/prop-warnings.spec.tsx, src/testing/platform/testing-log.ts
This fixes [a longstanding bug](https://github.com/ionic-team/stencil/issues/2433) where the warning for immutable prop changes doesn't get shown. It also adds tests to ensure the warning is emitted at the correct times.
Side note: this will probably confuse people once it gets merged because a lot of projects are likely changing props without the `{ mutable: true }` flag. I've already noticed a few in Stencil Router. 😆
=> Immutable props fix (fixes #2433)

src/mock-doc/attribute.ts, src/mock-doc/test/attribute.spec.ts
TL;DR Proposed changes:
- implement `[Symbol.iterator]` in `MockAttributeMap` to make it iterable
- implement `get [Symbol.toStringTag]` in `MockAttributeMap`
- don't pass symbols into `isNaN` in attribute proxy
- prettier formatted a couple things
---
When writing E2E tests I ran into different `PrettyFormatPluginError` errors, when Jest would try to pretty-format an `E2EElement` while iterating over its attributes:
```
PrettyFormatPluginError: Cannot read property 'name' of undefinedTypeError: Cannot read property 'name' of undefined
```
or
```
PrettyFormatPluginError: _val$hasAttribute.call is not a functionTypeError: _val$hasAttribute.call is not a function
```
```
at node_modules/jest-matcher-utils/node_modules/pretty-format/build/plugins/DOMElement.js
```
---
This error might only …
=> fix(mock-doc): make MockAttributeMap iterable

.github/CONTRIBUTING.md, .gitignore
We don't discuss testing with `npm pack` in `CONTRIBUTING.md`, and can potentially commit the created tarball to git 🤢 
- add lessons learned from using npm pack to the CONTRIBUTING.md doc
- update .gitignore to ignote .tgz files
- I plan on squashing this branch when it's time to merge. I'll update the commit body at that time
=> chore(docs) Update CONTRIBUTING with npm pack

BREAKING_CHANGES.md, CHANGELOG.md
Follow-up #2657
For traceability reason, move breaking changes information related to Stencil 2 in the dedicated documentation's file.
=> docs: move Stencil Two breaking changes to BREAKING_CHANGES.md

.github/workflows/main.yml
Currently, GitHub Actions don't trigger for PRs created from forked repos, only when a push is made directly to the Stencil repo
update CI to run on pull_request event to run on PRs from forked repos
- [GitHub Actions Documentation for PRs from Forked Repos](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories)
- [GitHub Actions Documentation for push events](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push)
> Runs your workflow when someone pushes to a repository branch, which triggers the push event.
(not particularly helpful on its own admittedly)
- I used [this configuration …
=> chore(ci): update CI to run on pull_request event

package.json
When developers run `npm run test.end-to-end`, we `cd` to the `test/end-to-end` directory and run `npm i`. These tests are meant to run using Node v12.X (and NPM v6.X), as that's the minimum version of Node that Stencil supports today. Because _development_ for Stencil is done in NPM v7, running this `package.json` script results in the following:
- this changes the format of the `test/end-to-end/package-lock.json` file, which is getting committed in community PRs and needs to be deliberately avoided by the dev team when working on Stencili
- when running in CI, we don't have reproducible NPM installs for this script (since we're not using `npm ci`)
Run `npm ci` as a part of …
=> chore(end-to-end-tests): run 'npm ci' in e2e tests

src/testing/puppeteer/puppeteer-declarations.ts
We added backwards compatible Puppeteer typings for Stencil 2.X (https://github.com/ionic-team/stencil/pull/2939/files). When syncing the `master` to the `v3.0.0-dev` branch, they were added inadvertently (since we did this a little out of order - committing to the `v3.0.0-dev` branch before `master`)
- remove typings for puppeteer v5, which are not expected to be  supported in v3.0.0 at this time
At this time, we expect consumers to upgrade to Puppeteer v10.0.0 for Stencil v3.0.0
In addition to running our testing suite, I ran `npm run build && npm pack`, then installed the tarball on a local application that I spun up fresh with `npm init stencil`. I modified an `e2e.ts` file …
=> chore!(testing) remove puppeteer v5 typings

package-lock.json, src/declarations/stencil-public-compiler.ts, src/runtime/initialize-component.ts, src/runtime/runtime-constants.ts
When using the custom elements build, it's possible that `@Watch` annotated methods will fire before our components are fully instantiated.  This is inconsistent with the lazy load build, as well as the [Stencil documentation](https://stenciljs.com/docs/reactive-data):
> The Watch decorator does not fire when a component initially loads.
- Wait until a component is fully instantiated before a `@Watch` method can be fired
- The ramification here is that watchers fired _before_ fully instantiated will never run
- With this PR, the behavior will match the behavior in the the lazy load builds today
However, folks that are using the custom elements build may …
=> fix(runtime): prevent watchers from prematurely firing in custom elements build

package-lock.json, src/cli/ionic-config.ts, src/cli/run.ts, src/cli/state/stencil-cli-config.ts, src/cli/state/test/stencil-cli-config.spec.ts, src/cli/telemetry/helpers.ts, src/cli/telemetry/test/helpers.spec.ts, src/cli/test/ionic-config.spec.ts, src/compiler/sys/stencil-sys.ts, src/compiler/sys/tests/stencil-sys.spec.ts, src/declarations/stencil-public-compiler.ts, src/sys/deno/deno-sys.ts, src/sys/node/node-sys.ts, src/testing/testing-sys.ts
Adds ability to allow writing and reading to the ~/.ionic/config.json file. When reading, if the file doesn't exist, readConfig will automatically create the file. 
Satisfies ADR-2
=> feat(cli): [STENCIL-33] Writing and Reading the Ionic config file

package-lock.json, package.json
When running the Stencil web server in a Docker container using v2.5.0+, the server fails to start up.
Fixes: #2930 
- upgrade open package to include changes in https://github.com/sindresorhus/open/compare/v8.0.5...v8.0.6
- allows xdg_open to be called correctly when running a dev-server in the context of a Docker container
- Ensure you don't have anything running on port 3333
- Clone https://github.com/maxkarkowski/stencil-docker, run `npm ci`
- Build the Docker container and attempt to start it: `npm run build && npm run docker:build && npm run docker:start`
- Observe the container ID returned at the end of the command. Example:
```
> stencil-docker-cypress@0.0.1 …
```
=> fix(dev-server): allow web server to be run in Docker

.github/CONTRIBUTING.md
- add additional details to CONTRIBUTING.md surrounding git commit
messages:
- how/when to use a commit body
- how to specify a breaking change in a PR
- where to put JIRA story tracking information
- update/align header tags throughout the doc
=> chore(docs): add git message instructions

package-lock.json, package.json, src/cli/ionic-config.ts, src/cli/run.ts, src/cli/state/stencil-cli-config.ts, src/cli/task-build.ts, src/cli/task-help.ts, src/cli/task-telemetry.ts, src/cli/telemetry/helpers.ts, src/cli/telemetry/shouldTrack.ts, src/cli/telemetry/telemetry.ts, src/cli/telemetry/test/helpers.spec.ts, src/cli/telemetry/test/telemetry.spec.ts, src/cli/test/ionic-config.spec.ts, src/compiler/sys/stencil-sys.ts, src/declarations/stencil-public-compiler.ts, src/sys/deno/deno-sys.ts, src/sys/node/node-sys.ts
Adds Telemetry options to the CLI. Try it out by running any of these commands in your linked project:
`npx stencil telemetry`
`npx stencil telemetry on|off`
The debug flag will print the telemetry results, e.g:
`npx stencil generate a-component --debug --verbose`
Satisfies ADR-1
=> feat(cli): [STENCIL-12] Adding Telemetry and CLI features. 

.adr.json, docs/adr/0001-telemetry-in-stencil-cli.md, docs/adr/0002-shared-config-files-on-ionic-projects.md, docs/adr/0003-supported-node-versions.md, docs/adr/0004-jest-27-support.md, docs/adr/0005-repo-structure.md, docs/adr/0006-organizing-utility-functions.md, docs/adr/0007-unit-testing-expectations.md, docs/adr/CONTRIBUTING.md, docs/adr/README.md, docs/adr/TEMPLATE.md
This PR allows the Stencil team to begin using public ADR's within Git instead of our other tooling. 
See the [CONTRIBUTING.md file](https://github.com/ionic-team/stencil/pull/2992/files#diff-536896b1dab96faa3d75dc8aaefbf8b5308c69c87a0e3ac1aa263710b1d4c04b) for details about the purpose of ADR's. 
With the `adr` tool, README.md is wiped on update, so I couldn't place the content of CONTRIBUTING.md within it.
=> docs(ADR): Adding ADR's, adding how to contribute.

src/dev-server/server-web-socket.ts
Safari 15 sends an invalid WebSocket close frame when navigating away
from a page. This causes the dev-server to crash.
STENCIL-46
=> fix(dev-server): prevent crash with Safari 15

src/sys/node/node-sys.ts
Allows the dev server to pick up changes during the www copy tasks, so consumers don't have to restart their dev server when developing. 
I've tested this experience on each starter repo, a monorepo, and framework. 
Set up a www output target that with a copy rule, e.g.
```
{
type: 'www', 
copy: [
{ src: 'images' }
]
}
```
Within that images directory, try to make file modifications - change the content, duplicate the file, delete the file. The contents should not be carried over during the process of the dev server's lifecycle. Commonly, you have to restart the dev server in order to make the copy task run.
All file change events now get passed down to the tasks. Copy now works as expected - files get copied when needed. 
Internal ticket: STENCIL-29
=> Allow file change events to pass through to let the Copy task succeed

.gitignore
add index.js.map, which is generated on every build, to the .gitignore
file, alongside the other autogenerated files
Testing:
- on `master`, run `npm run build`, observe this file being created/noticed by git via `git status`
- on this branch, run the same command, and it's magically ignored ✨
=> fix(build): add screenshot/index.js.map to gitignore

src/compiler/bundle/app-data-plugin.ts, src/compiler/bundle/ext-format-plugin.ts, src/compiler/bundle/typescript-plugin.ts, src/compiler/output-targets/dist-lazy/generate-lazy-module.ts, src/declarations/stencil-private.ts
this PR replaces our custom typings for rollup hooks with those
provided by rollup
since this is only a change to the typings, I did not do any functional testing, rather ensured the compiler still ran
=> chore(types) remove bespoke rollup types

scripts/build.ts, scripts/license.ts, scripts/readme.md, scripts/release-tasks.ts, scripts/release.ts, scripts/test/validate-build.ts, scripts/utils/options.ts, scripts/utils/release-utils.ts
While going through the release process more thoroughly this morning, I did a fair amount of documentation of the code/fixed up some typings where I could. Rather than creating a Notion doc that would sit and rot, I decided to put this in the form of code comments that hopefully won't rot as quickly 😄 
Changes:
document the build process via JSDocs on all functions that are involved
with generating a release for Stencil. the intent here is that moving
forward, context for different aspects of the release process can be
quickly acquired rather than running through a mountain of code
Testing:
- Ran `npm run tsc.scripts` to verify the typings I edited are semantically correct
- Ran `npm run release.prepare` with the 'dry-run' option to best estimate going through the release process
=> chore(docs): document the release process 

src/compiler/sys/stencil-sys.ts, test/browser-compile/src/components/app-root/app-root.tsx, test/browser-compile/src/utils/css-template-plugin.ts
Closes #3011
The worker thread's in-memory system did not have the correct reference to fetch. 
How to test:
1. Check this branch out
2. Build the compiler with `npm run build`
3. Visit the `/test/browser-compile` directory. 
4. Run `npm i && npm start`
5. This app will display an app that runs the compiler in the browser. It lets you run the compiler with different settings. 
Originally, before this, the transpile results pane displayed empty and there were multiple errors in dev tools.
=> fix: Solve issue where worker thread didn't have access to fetch

src/cli/ionic-config.ts, src/cli/telemetry/helpers.ts, src/cli/test/ionic-config.spec.ts
Fixes: #3013 
**Summary:**
this fix handles the event that a user has an Ionic configuration file,
but does not have a 'tokens.telemetry' field in said file.
**Replication:**
With `master@HEAD`, modify your local `~/.ionic/config.json` in one of two ways
1. remove `'tokens.telemetry'` completely
2. set `'tokens.telemetry'` to undefined (or any other valid JSON)
Then, spin up a small Stencil project, and attempt to turn telemetry off/on:
```shell
$ cd <your_sandbox_dir>
$ npm init stencil
<create an ionic pwa app>
$ cd <your_app_name>
$ npx stencil telemetry on
[25:32.7]  @stencil/core
[25:32.8]  v2.7.0 🌟
[ ERROR ]  uncaught cli error: TypeError: Cannot read property 'match' of undefined
```
**Testing:**
With the HEAD of this branch, build it and install it in the PWA app you build …
=> fix(telemetry): handle malformed telemetry tokens 

docs/adr/0008-license-attribution.md, docs/adr/CONTRIBUTING.md, docs/adr/README.md
add an ADR describing how third party projects that are bundled in the
Stencil distributable should be attributed. I confirmed this practice
with Adam as a part of #3016.
=> docs(license): add adr for license attribution

scripts/license.ts
add merge-source-map to license file list, as it will be included in the
Stencil distribution
Note: This PR targets our ongoing effort to merge changes into the sourcemap PR
=> add merge-source-map to license file list

src/compiler/config/test/validate-config.spec.ts, src/compiler/config/validate-config.ts, src/compiler/optimize/optimize-module.ts, src/compiler/output-targets/dist-custom-elements-bundle/index.ts, src/compiler/output-targets/dist-lazy/generate-cjs.ts, src/compiler/output-targets/dist-lazy/generate-esm-browser.ts, src/compiler/output-targets/dist-lazy/generate-esm.ts, src/compiler/output-targets/dist-lazy/generate-system.ts, src/compiler/output-targets/dist-lazy/lazy-output.ts, src/compiler/sys/typescript/typescript-config.ts, src/compiler/transpile/ts-config.ts
`config.sourcemap` can be either `undefined | true | false` when a user's configuration is validated. I'd prefer to narrow that to a boolean, even if we don't strictly do that using the type system right now. See [this comment](https://github.com/ionic-team/stencil/pull/3005#discussion_r697615319) in the parent PR that expounds upon this
ensure that upon validating a user's stencil config, the value of the
'sourcemap' field is never undefined.
After checking this commit out, I:
- installed dependencies (`npm ci`)
- built the project and generated the tarball for it (`npm run build && npm pack`)
- installed it on a fresh stencil project (`npm stencil …
=> chore(config): coerce sourceMap config value to boolean 

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
add templates for bug reports and feature requests. the content was
largely ~ripped off~ copied from the framework team as of
https://github.com/ionic-team/ionic-framework/commit/d8a2db73e2a51bd39d92f10577cd803bb58e6dc0
thanks Liam
STENCIL-51: create github issue form in Stencil core
=> chore(github): use new templates for issues & feature requests

.github/ionic-issue-bot.yml
this PR is the first step in trying to improve our automation in GitHub.
it removes the 'Awaiting Reply' label and replaces it with the 'Reply
Received' label when an individual replies to a GitHub issue via a
comment.
this PR also prevents issues that are tagged with 'Reply Received' from
being culled by the stale issue configuration.
this is a first step in improving our workflow. this PR does not cover
every possibility/scenario for interacting with the community.
=> chore(ionitron): remove 'awaiting reply' on comment from issues

src/compiler/optimize/optimize-module.ts, types/merge-source-map.d.ts
this PR makes changes to the Stencil-defined type declaration file for `merge-source-map`
`merge-source-map` does not offer any `d.ts` file, nor does it have a third party offering on Definitely Typed, so the intent of this effort was to see "how correct is our type definition for our use case, while not deviating from the actual library's implicit typings".
I _did_ try to ask the compiler to generate the `d.ts` file for me with `tsc -d node_modules/merge-source-map/index.js --allowJs --outDir ./out`, which generated invalid TS:
```typescript
export = merge;
/**
* Merge old source map and new source map and return merged.
* If old or new source map value is falsy, return another one as it is.
*
* @param {object|string} [oldMap] old source map object
* @param {object|string} [newmap] new …
```
=> chore(types): updating typings for merge-source-map

src/app-data/index.ts, src/compiler/app-core/app-data.ts, src/compiler/output-targets/dist-lazy/lazy-output.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts, src/runtime/bootstrap-lazy.ts, src/runtime/dom-extras.ts, src/runtime/event-emitter.ts, src/runtime/runtime-constants.ts, src/testing/reset-build-conditionals.ts, test/karma/stencil.config.ts, test/karma/test-app/components.d.ts, test/karma/test-app/scoped-slot-text-with-sibling/cmp.tsx, test/karma/test-app/scoped-slot-text-with-sibling/index.html, test/karma/test-app/scoped-slot-text-with-sibling/karma.spec.ts, test/karma/test-app/scoped-slot-text/cmp.tsx, test/karma/test-app/scoped-slot-text/index.html, test/karma/test-app/scoped-slot-text/karma.spec.ts
- https://github.com/ionic-team/stencil-site/pull/767/files
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/2801
The issue above points to a bug when using Stencil w/Maquette. The underlying cause is Stencil does not adhere to "the correct thing to do" when `textContent` is set, which Maquette is doing under the hood in the reproduction case when creating this node: 
```tsx
h("calcite-label", {}, ["I am a text node and won't get properly relocated"]),
```
patch `textContent` for scoped components that use slots. because there is
no shadow dom, calling the setter/getter on `textContent` would
otherwise act on the bare HTML elements. use the stencil metadata to …
=> fix(runtime): textContent for scoped components with slots

scripts/license.ts, scripts/release-tasks.ts, scripts/utils/release-utils.ts
This PR fixes minor issues with the existing release scripts. There are additional things the team would like to do in this domain, but I held off from bloating scope of this PR _too_ much. 
Each commit consists of one type of change:
- https://github.com/ionic-team/stencil/commit/8d44ca0c5a9e81f829bac0dfd1c67996e1e34cce is just typo fixes
- https://github.com/ionic-team/stencil/commit/76d19f8990d60fbfbb08b66aa07b5557d7253378 ends writing `package-lock.json` and `package.json` in full, and fixes the issue where in the V2 of a lockfile, we had to manually update one of the package versions
- https://github.com/ionic-team/stencil/commit/3766d92c8ee188aafb0 …
=> chore(build): fixup release scripts 

src/compiler/app-core/bundle-app-core.ts, src/compiler/output-targets/dist-collection/index.ts, src/compiler/output-targets/dist-custom-elements-bundle/index.ts, src/compiler/output-targets/dist-custom-elements/index.ts, src/compiler/output-targets/dist-lazy/lazy-output.ts, src/compiler/output-targets/output-collection.ts, src/declarations/stencil-private.ts
This PR performs 4 minor refactorings, each confined to their own commit. Each seemed too small to put in their own PR, hence one with the separate commits
- https://github.com/ionic-team/stencil/commit/05320d291e9f4dd76d82e4cdcffd358d452f1534 - this commit adds additional tyings to `generateRollupOutput` to help make it easier to understand the map() function call that is invoked on the results of calling `build.generate()`
- https://github.com/ionic-team/stencil/commit/d5afae2b02664a5b87c7862f275a442a34d6e90f - sets the `map` property on our sourcemap representation to optional, match sourcemaps
- …
=> chore(fixups): minor sourcemap fixups

src/compiler/app-core/app-es5-disabled.ts, src/compiler/bundle/dev-module.ts, src/compiler/bundle/worker-plugin.ts, src/compiler/output-targets/dist-collection/index.ts, src/compiler/output-targets/dist-custom-elements-bundle/index.ts, src/compiler/output-targets/dist-custom-elements/index.ts, src/compiler/output-targets/dist-hydrate-script/generate-hydrate-app.ts, src/compiler/output-targets/dist-lazy/generate-cjs.ts, src/compiler/output-targets/dist-lazy/generate-esm-browser.ts, src/compiler/output-targets/dist-lazy/generate-esm.ts, src/compiler/output-targets/dist-lazy/generate-system.ts, src/compiler/output-targets/output-lazy-loader.ts, src/utils/constants.ts, src/utils/test/util.spec.ts, src/utils/util.ts
Stencil's [preamble](https://stenciljs.com/docs/config#preamble) functionality has been broken for some time. This PR seeks to restore that functionality.
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/2169
Doc Link: https://github.com/ionic-team/stencil-site/pull/776
- Restore the addition of a preamble, specified in `stencil.config.ts` to all emitted JS files
- I.E. the preamble is not added to polyfills, nor is it added to files that are `.d.ts`, `.json`, etc. 
- Generate preamble for the following targets:
- `dist-custom-elements-bundle`
- `dist-custom-elements`
- `dist-hydrate-script`
- `www` (with service worker, although the worker file generated by …
=> fix(preamble): restore preamble functionality

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
fix typos in 'prerequisites' in issue templates
🤦
=> chore(github): fix typos in issue labels

src/compiler/optimize/minify-js.ts, src/compiler/optimize/optimize-module.ts, src/declarations/stencil-private.ts
Sourcemaps with minification produce inconsistent results across browsers. In particular, I was looking at Firefox
this commit introduces a new type, OptimizeJsResult, to be used to name
the shape of the object that is returned by various methods that are
used to minify a user's JavaScript. using this type in the return
signature of methods + in the declaration of objects allows us to
eliminate unnessary type assertions on the individual fields of said
objects.
- add JSDoc to minification to the functions that were investigated as a
part of this effort. 
account for minification with sourcemaps
- sourcemaps in some regard are at odds with attempting to …
=> chore(sourcemaps): minification with sourcemaps

scripts/release-tasks.ts, scripts/release.ts, scripts/utils/options.ts
Publishing to the npm registry fails when two-factor authentication is required.
The release script will now prompt for OTP.
`npm run release.prepare && npm run release -- --dry-run`
The release script prompts for OTP which is then included as the `--otp` argument for `npm publish`.
=> chore(release): prompt for OTP for npm publish

test/karma/test-app/custom-elements-delegates-focus/index.esm.js
When serving this test locally using `npm start`, the whole test case was not properly shown
this commit fixes the cases where the non-delegates focus case for the
custom-elements-delegates-focus test case would not show up properly
when serving the test using `npm start` from the root of the karma
directory.
After pulling down this branch and building Stencil (`npm ci && npm run build`), navigate to the `test/karma` dir, build the tests (`npm run karma.prod`), and `npm start` - you should see _two_ input boxes now.
=> test(delegates-focus): show non-delegate focus case in local web server

src/declarations/stencil-public-compiler.ts
- Simple typo fix in the description of the `globalStyle`. No source code changes.
=> chore(typo): fix typo in the decscription of `globalStyle`

src/cli/run.ts
Running `npx stencil` and `npx stencil --help`, should print the same options to the user, but `npx stencil` is exiting before the telemetry and example sections are printed. 
Running `npx stencil` and `npx stencil --help` now print the same information.
N/A
=> fix(cli): wait for help task to finish before exiting

src/compiler/transpile.ts, src/utils/sourcemaps.ts, src/utils/test/sourcemaps.spec.ts
this commit fixes a regression originally introduced in #3100, where
inline sourcemaps that are data URI's are erroneously encoded using
RFC-3986. this causes the sourcemaps for tests to not correctly map the
transpiled output back to the original source code.
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/3147
do not URI encode the data prefix+mime type
To test, I spun up 2 component libraries using `npm init stencil`:
1. `with-sourcemap-issue`, which is the standard output one would see from the Stencil CLI (with v2.11.0 installed)
2. `with-local-stencil-build`, which differs from the above only in name and has a Stencil build with this branch installed on …
=> fix(sourcemaps): do not encode inline sourcemaps

src/runtime/vdom/h.ts
Stencil performs dev-time checking of the order of `input` element attributes. The check for the `step` attribute is incorrect, as it points to `min`
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/2406
fix `indexOf` call for the step attribute to look for the correct
attribute name.
hoist the check for `value` attribute to exit early if the attribute
does not exist, avoiding unneeded lookups of other attributes
First, I built this branch, `npm ci && npm run clean && npm run build && npm pack`.
I spun up a new Stencil component library (`npm init stencil` -> component), ran `npm i` for the component, then installed the tarball generated from the previous call …
=> fix(vdom): properly warn for step attr on input

src/utils/message-utils.ts, src/utils/test/message-utils.spec.ts
There's no unit testing around the message utils we have, which came up in #3211. #3211 did a lot of explicit type annotation around passing `any` into our `message-utils#catchError` method, so I figured I'd start there in introducing some tests.
- add tests to `catchError`
- fix cases where we could print a zero-len string 
- it's still not great, but I'd argue "UNKNOWN ERROR" is better than literally nothing 
Unit tests were run with coverage to validate we handle the entirety of this method
**Please do not merge, relies on** #3211
=> test(message-utils): add message-utils testing

src/compiler/transformers/decorators-to-static/decorator-utils.ts, src/compiler/transformers/decorators-to-static/prop-decorator.ts, src/compiler/transformers/reserved-public-members.ts, src/compiler/transformers/transform-utils.ts, src/runtime/parse-property-value.ts
While doing an investigation surrounding prop behavior for union types (STENCIL-349), I took a little extra time to JSDoc some of the functions associated with prop parsing (although not all of them).  The idea here was to "leave the forest a little nicer than you found it"
this commit adds jsdoc + explicit return types to a portion of the
codebase that parses Stencil members that are decorated with @Prop()
it also includes a minor code change where a duplicated enum is removed
from a bitwise calculation when determining whether or not a prop's type
is of the type 'boolean' or not
N/A (I consider the JSDoc non-testable). I don't think there's any …
=> chore(jsdoc): document @Prop() parsing

jest.config.js, scripts/tsconfig.json, scripts/utils/release-utils.ts, scripts/utils/test/release-utils.spec.ts
When releasing Stencil, if we were to release minor version after minor version, the current scripts won't correctly detect a the previous minor release. This causes a release note to be created containing several versions. If this string gets long enough, the generated URL will/can be too large for the browser to handle, causing this part of the release to fail.
this PR is split into 2 commits:
this commit allows tests (files ending in `.spec.ts`) to be written for
files in the `scripts/` directory and placed in a subdirectory. to
accomplish this, the jest configuration has been updated to pick up
tests under `scripts/`. the `tsconfig` for our scripts …
=> chore(release): fix multiple releases added to github release notes 

src/compiler/config/test/validate-testing.spec.ts, src/compiler/config/validate-testing.ts
There are two issues that this PR solves (in 2 commits):
1. files that end with `(test|spec|e2e).(js|ts|jsx|tsx)` (without a period preceding any combination of that string) are picked up by the test runner - e.g. `my-test.tsx` will be picked up by the test runn
2. files that end in `.j` or `.t` will be picked up by the test runner
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/3221
I  split the two issues solved here into two commits, and will likely 'rebase and merge' them. Each commit has a fix:
Commit 1: this commit adds test infrastructure for files picked up by jest for
testing purposes. because there is no efficient way to get the
interaction with …
=> fix(testing): don't run tests against non-test files

src/compiler/output-targets/dist-custom-elements/index.ts, src/compiler/transformers/add-component-meta-proxy.ts, src/compiler/transformers/component-native/add-define-custom-element-function.ts, src/compiler/transformers/component-native/proxy-custom-element-function.ts, src/compiler/transformers/test/add-component-meta-proxy.spec.ts, src/compiler/transformers/test/proxy-custom-element-function.spec.ts, src/compiler/transformers/update-component-class.ts
See the GitHub Issue below. In short, applications using Stencil + Webpack are susceptible to tree shaking issues with the `dist-custom-elements` output target
GitHub Issue Number: [3191](https://github.com/ionic-team/stencil/issues/3191)
this commit solves an issue where stencil projects using webpack were
unable to treeshake properly. specifically, this is a workaround to a
webpack issue (https://github.com/webpack/webpack/issues/14963) where
webpack fails to treeshake when a variable is reassigned.
with this commit, we introduce a new transformer to be run during the
typescript transpilation process, `proxyCustomElement` that takes a
stencil component's class initializer and …
=> fix(bundling): allow proper webpack treeshaking

src/runtime/set-value.ts, test/karma/test-app/components.d.ts, test/karma/test-app/reflect-nan-attribute-hyphen/index.html, test/karma/test-app/reflect-nan-attribute-hyphen/karma.spec.ts, test/karma/test-app/reflect-nan-attribute-hyphen/reflect-nan-attribute-hyphen.tsx, test/karma/test-app/reflect-nan-attribute-with-child/child-reflect-nan-attribute.tsx, test/karma/test-app/reflect-nan-attribute-with-child/index.html, test/karma/test-app/reflect-nan-attribute-with-child/karma.spec.ts, test/karma/test-app/reflect-nan-attribute-with-child/parent-reflect-nan-attribute.tsx, test/karma/test-app/reflect-nan-attribute/index.html, test/karma/test-app/reflect-nan-attribute/karma.spec.ts, test/karma/test-app/reflect-nan-attribute/reflect-nan-attribute.tsx
GitHub Issue Number: [N/A](https://github.com/ionic-team/stencil/issues/2828)
this commit is intended to prevent infinite loops when rendering the
following specific scenario:
- the prop is of type "number"
- the prop is reflected (`@Prop({reflect: true})`
- the value received by the prop is NaN
in this commit, we add an additional safeguard to `set-value` to
validate that both the previous and new values on the prop are not NaN.
this check is required as equality checks in javascript where NaN is on
both the left and right hand side of the operator will always return
false.
this change is intentionally placed as this layer of abstraction in
order to handle cases where a value …
=> fix(renderer): prevent infinite loops for NaN

src/runtime/test/parse-property-value.spec.ts
There are no unit tests for `src/runtime/parse-property-value.ts#parsePropertyValue`
this commit adds tests to `src/runtime/parse-property-value.ts`.
specifically it adds tests to the case where we parse numbers using the
`parsePropertyValue` function.
these tests were originally a part of
https://github.com/ionic-team/stencil/pull/3254, but were removed from
the pull request. the reason for which is the fix implementation in 3254
ultimately went on a different layer of abstraction then
`parse-property-value`. these tests were originally written with a
different fix in mind; rather than scraping them, they've been updated
to fit the current …
=> test(prop-parsing): add numeric prop parsing tests

test/browser-compile/src/components/app-root/app-root.tsx
Preflight [checklists](https://github.com/ionic-team/stencil/blob/main/scripts/readme.md#manually-testing-stencils-browser-api) for releasing Stencil can't be followed, as there are typescript errors outside the core compiler - specifically as a part of a manual testing suite.
this commit is a quick fix for the browser-compile tests that currently
do not compile after setting `useUnknownInCatchVariables` in
https://github.com/ionic-team/stencil/pull/3211. This went unnoticed as
this application is not currently type checked by our CI process. In
order to get the application to compile, we type the error as `any` for
now, with the intent of properly …
=> chore(typings): update browser-compile typings

test/karma/test-app/conditional-rerender/karma.spec.ts, test/karma/test-app/shadow-dom-array/karma.spec.ts, test/karma/test-app/slot-replace-wrapper/karma.spec.ts
When we upgraded Stencil to internally use Jest 27 (https://github.com/ionic-team/stencil/pull/3171), we began
to see warnings in the console that look something like:
> ERROR: 'DEPRECATION: An asynchronous before/it/after function took a done callback but also returned a promise. This is not supported and will stop working in the future. Either remove the done callback (recommended) or change the function to not return a promise. (in spec: shadow-dom-array renders children)'
This will be a blocker for an upgrade to Jest 28.
I removed either the usage of the `done` parameter or `async` keyword from tests,
depending on what was required/based on the …
=> chore(karma): remove async and done usage

.github/workflows/main.yml, package.json, test/ionic-app/.gitignore, test/ionic-app/.npmrc, test/ionic-app/package-lock.json, test/ionic-app/package.json, test/package.json, test/todo-app/.npmrc, test/todo-app/package-lock.json
Projects under the `test/` directory aren't type checked, which led to requiring a quick
fix of https://github.com/ionic-team/stencil/pull/3259 to unblock Monday's release. We should
have caught this in https://github.com/ionic-team/stencil/pull/3211, but CI wasn't hooked up here
this commit adds building several applications in the test/ directory to
the project's root level `test.prod` npm script. while wiring these up,
it was determined there are two projects in test/ that do not compile.
fixing these at a high level have been included in two separate commits in this
PR.
I've broken CI intentionally (and unintentionally 😆) a few times getting the …
=> chore(ci): wire test/ to ci

bin/stencil
**Please do not merge, see 'Other Information' below**
Stencil v2.X supports Node 12, which will hit end of life in April. Stencil v3 (which will release some time after said end of life of Node 12) will no longer support Node 12. We do not have a non-blocking way of disseminating this knowledge at this time.
this commit adds a warning to the console stating that support for node
v14.5.0 and under will be removed in a future major version update of
stencil. this commit only adds the notice to the `bin` entrypoint of
stencil, and does not add any notice to using compiler api's directly
(we expect the latter to be handled by `package.json#engines`).
To …
=> feat(node): add warning of future node support

src/compiler/config/test/validate-testing.spec.ts, src/compiler/config/validate-testing.ts
c6fda394f256eb3be68a1a6ff2f0c2ef0193958f created a regression where files named `e2e.ts` would not be picked up correctly by the test runner
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/3275
this commit fixes an edge case where unit tests were not being properly
detected following https://github.com/ionic-team/stencil/commit/c6fda394f256eb3be68a1a6ff2f0c2ef0193958f
the ionic framework has tests named `e2e.ts` that we must account for in
this regex. because jest doesn't error when no tests are found, we
missed this in the original implementation.
tests of name 'spec.ts' and 'test.ts' (or any other acceptable
extension) are considered unit tests, and tests of …
=> fix(testing): update test regex for 'e2e.ts'

src/compiler/config/outputs/validate-custom-element.ts, src/compiler/config/test/validate-output-dist-custom-element.spec.ts, src/compiler/output-targets/dist-custom-elements/custom-elements-types.ts, src/compiler/output-targets/output-types.ts, src/compiler/types/generate-app-types.ts, src/compiler/types/generate-component-types.ts, src/compiler/types/generate-types.ts, src/compiler/types/stencil-types.ts, src/compiler/types/update-import-refs.ts, src/declarations/stencil-public-compiler.ts, src/utils/test/util.spec.ts, src/utils/util.ts
Type declarations are not created for users of the `dist-custom-elements` output target,
unless they also provide the `dist` output target as well
this commit introduces a new experimental flag,
`generateTypeDeclarations` on the `dist-custom-elements` output target.
when enabled, it allows a user to generate type declaration files for
their stencil project (that uses `dist-custom-elements`) without also
specifying the `dist` output target.
this experimental flag generates types in the `dist/types` directory.
this destination is not configurable at this time to better understand
the needs of users for generating these types
this commit adds jsdoc, …
=>  fix(types): generate types for dist-custom-elements

src/declarations/stencil-public-compiler.ts
Fixes several typo/documentation issues in the Stencil public compiler interfaces.
=> docs(declarations): typos in public compiler

src/compiler/build/watch-build.ts, src/compiler/sys/stencil-sys.ts, src/compiler/sys/worker/sys-worker.ts, src/compiler/transpile/create-build-program.ts, src/compiler/transpile/create-watch-program.ts, src/declarations/stencil-public-compiler.ts, src/sys/node/node-sys.ts
Currently the two callbacks for adding and removing callbacks when `destroy()` is called are misspelled. 
- `addDestory`
- `removeDestory`
Updates the naming to be correctly spelled.
- `addDestroy`
- `removeDestroy`
Changes the naming of two public API methods on the Stencil compiler. Developers making use of these methods will need to rename them to the correct spelling. 
Ignore the branch name, clearly I have issues spelling destroy as well.
=> refactor(compiler): destroy callback naming

.github/ionic-issue-bot.yml, scripts/readme.md
Last week, the repo had 64 or so labels that could be applied to issues
and pull requests. Although this was expressive, it was difficult in practice
to determine what label should be applied and when. This had a downstream
effect on the automations, as issues that would be closed + locked due to
either:
1. inappropriate labels being applied
2. appropriate labels being applied, but those issues not being marked as exempt
from issue closure.
The maintenance of the whole thing was getting unstable, which led me to work
on revamping this as a part of my hack days time.
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/3297
Over 40 labels have been removed, and …
=> chore(github): clean up labels/automation

src/mock-doc/global.ts, src/mock-doc/parser.ts, src/mock-doc/test/global.spec.ts
Testing code which attempts to use the [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) API will fail, because it isn't made available in the test environment.
The DOMParser now has a minimal stub which can handle parsing HTML, but not yet XML.
=> fix(mock-doc): Add missing DOMParser stub to MockWindow

jest.config.js, package.json, scripts/test/validate-build.ts, src/compiler/types/generate-prop-types.ts, src/compiler/types/tests/ComponentCompilerMeta.stub.ts, src/compiler/types/tests/ComponentCompilerProperty.stub.ts, src/compiler/types/tests/ComponentCompilerVirtualProperty.stub.ts, src/compiler/types/tests/generate-prop-types.spec.ts
The functionality in [`generate-prop-types`](https://github.com/ionic-team/stencil/blob/8feaf0816731d8dc1d880cecf6a432526295d65a/src/compiler/types/generate-prop-types.ts#L1), which is used in the generation of type declaration files for class members decorated with `@Prop()`, is currently not unit tested. There are however, [end to end tests](https://github.com/ionic-team/stencil/blob/8feaf0816731d8dc1d880cecf6a432526295d65a/src/compiler/transformers/test/parse-props.spec.ts#L3) for this functionality.  We add unit tests here to minimize an upcoming bug fix PR down in size and under proper unit testing
This PR adds unit tests for `generate-prop-types` …
=> test(prop): add unit tests to prop type generation 

src/sys/node/node-sys.ts
- changing the versions specified for Puppeteer to remove support for old versions that we don't want to support anymore
This is only going to be included in v3, but for apps that migrate to v3, if they are using an older version of Puppeteer (<10) they'll need to upgrade it.
I did a little `npm run build && npm link` workflow to test out these changes in a test component repo locally w/ various versions of Puppeteer. I confirmed that:
- a version <10 throws a 'hey this is deprecated!' error
- versions 10, 11, 12, 13 don't, and the (simple!) tests pass
=> change puppeteer supported version ranges

src/compiler/types/generate-component-types.ts, src/compiler/types/generate-method-types.ts, src/compiler/types/tests/ComponentCompilerMethod.stub.ts, src/compiler/types/tests/generate-method-types.spec.ts
The functionality in [`generate-method-types`](https://github.com/ionic-team/stencil/blob/8feaf0816731d8dc1d880cecf6a432526295d65a/src/compiler/types/generate-method-types.ts#L1), which is used in the generation of type declaration files for class members decorated with `@Method()`, is currently not unit tested. There are however, [end to end tests](https://github.com/ionic-team/stencil/blob/8feaf0816731d8dc1d880cecf6a432526295d65a/src/compiler/transformers/test/parse-methods.spec.ts#L3) for this functionality.  We add unit tests here to minimize an upcoming bug fix PR down in size and under proper unit testing
this commit adds unit testing to the …
=> test(methods): add unit tests to method type generation

.github/workflows/browserstack.yml, .github/workflows/main.yml
We're using an older version of the setup-node github action in our jobs, and are using a less secure versioning scheme for both setup-node and checkout actions
this commit updates the versions of the github actions used by the
browserstack and main workflows:
- checkout is pinned to the v2.4.0 release
- setup-node is upgraded to the v3.1.1 release
in this commit we move to using SHAs instead of the semver string per
the guidance of [github](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)
> Pinning an action to a full length commit SHA is currently the only
> way to use an action as an …
=> chore(github): update github action versions

src/compiler/types/generate-app-types.ts, src/compiler/types/update-import-refs.ts, src/declarations/stencil-private.ts
This PR is split into three commits (I'm gonna refer to them relative to one another in case the SHAs get updated, so I don't have to update the summary):
this commit adds jsdoc to various internal/private stencil types for
finding typescript types and avoiding naming collisions. the purpose of
this commit is to keep refactoring/chores of this nature separate from
core logic changes - this allows this commit to be made separate from
existing pull requests
this commit refactors the `update-import-refs` helper module by adding
jsdoc and renaming existing variables in the name of improving clarity.
this module utilizes multiple data structures that cover …
=> refactor(types): add clarity to type declaration file generation

src/cli/task-generate.ts, src/cli/test/task-generate.spec.ts
If you run `stencil generate` and use the name of a component that is already present within the project the files for that component will be overwritten with boilerplate code with no warning.
GitHub Issue Number: #2672 
When `stencil generate` is run it will now check for the presence of all
files it's going to generate before it does so and, if they are already
present, exit with an error message before overwriting the user's code.
This commit also introduces a spec file for the code generation taskfile
(`src/cli/task-generate.ts`) which tests the basic functionality as well
as the change in behavior introduced in this commit.
STENCIL-401: stencil generate overwrites without …
=> fix(cli): don't generate files if they would overwrite existing code

.github/workflows/browserstack.yml
when i merged https://github.com/ionic-team/stencil/pull/3332 into `main`, that commit has a newer
author/commit date than the PR in which we dropped v12 support. as a result, when i updated the `v3.0.0-dev`
branch with the latest from `main`, I accidentally overwrote part of the commit dropping node 12 support
in https://github.com/ionic-team/stencil/pull/3331, the minimum value of browserstack's node version to v14
accidentally. node v12 is still supported; this commit reverts that
change
this is the same PR as https://github.com/ionic-team/stencil/pull/3332, we need to apply this to the `v3.0.0-dev`
branch now (this is user error on my end) …
=> chore(github): set browserstack node to v12

src/compiler/config/outputs/validate-dist.ts, src/compiler/config/test/validate-output-dist.spec.ts, src/declarations/stencil-public-compiler.ts
this makes changes necessary to fix the errors from compiling w/
`strictNullChecks` set to `true` in
src/compiler/config/outputs/validate-dist.ts.
On the main branch turning on `strictNullChecks` produces 2229 errors. With the changes on this branch we get 2182, so we've fixed 47. Gotta start somewhere!
Tests should all pass! The typechecker too.
You can also run `npx tsc --strictNullChecks` locally and verify that you get fewer errors than on `main`. You could also change that value in `tsconfig.json` temporarily and check that you don't get any compile errors in the file when opening it in your editor, or check the output to make sure there aren't any errors in …
=> test(compiler): remove strictNullChecks errors from validate-dist.ts

src/compiler/types/generate-app-types.ts, src/compiler/types/generate-component-types.ts, src/compiler/types/generate-event-types.ts, src/compiler/types/generate-method-types.ts, src/compiler/types/generate-prop-types.ts, src/compiler/types/stencil-types.ts, src/compiler/types/tests/TypesImportData.stub.ts, src/compiler/types/tests/generate-event-types.spec.ts, src/compiler/types/tests/generate-method-types.spec.ts, src/compiler/types/tests/generate-prop-types.spec.ts, src/compiler/types/tests/stencil-types.spec.ts
See the linked GH Issue below
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/2859
this commit updates the type resolution of types used by components when
generating a `components.d.ts` file. types that have been deduplicated
are now piped to functions used to generate the types for class members
that are decorated with `@Prop()`, `@Event()`, and `@Method()`, and used
when generating the types for each.
Unit tests have been written + passed
Manually we can verify this against the reproduction repo:
First, let's get the baseline setup:
```
git clone https://github.com/jcfranco/stencil-duplicate-types-not-assigned-correctly-in-component-typings sample
cd sample …
```
=> fix(types): components.d.ts type resolution for duplicate types

BREAKING_CHANGES.md
In #3341 we removed backwards compatibility for the deprecated
`assetsDir` component decorator prop. This updates the BREAKING_CHANGES
document to reflect that change.
STENCIL-410: Remove Backwards Compatibility for assetDir Field on @component
Update hte `BREAKING_CHANGES` document to add in some documentation for #3341.
=> chore(docs): update BREAKING_CHANGES.md for `assetsDir` backwards compat

src/sys/node/node-lazy-require.ts, src/sys/node/node-sys.ts, src/sys/node/test/node-lazy-require.spec.ts
This changes the logic that we use in the `NodeLazyRequire` class to
error out in fewer situations. The changes are:
- the data structure for specifying our version ranges is changed from
`[string, string]` (`[minVersion, recommendedVersion]`) to an object
with `minVersion` `recommendedVersion` required properties and an
optional `maxVersion` property.
- in the `ensure` method on `NodeLazyRequire` we check if `maxVersion`
is defined on a given version range requirement.
- If so, we check that the installed version is greater than or
equal to `minVersion` and less than the major version of
`maxVersion`.
- If not, we just check that `minVersion <= installedVersion`
This should give us the flexibility to mark certain versions of packages
as incompatible (for instance jest@28) without having …
=> fix(sys): tweak NodeLazyRequire logic around too-high-versions errors

src/client/client-load-module.ts, src/compiler/output-targets/dist-lazy/generate-lazy-module.ts, src/declarations/stencil-public-compiler.ts, test/bundler/component-library/stencil.config.ts
This is going to be **the final part** part of a chain of PRs*. Once all of them are up/approved, I'll merge the child-most PR into its parent, that parent into its own parent, etc. At the end, we shall have a PR (https://github.com/ionic-team/stencil/pull/3349) which contains all of its children, and we'll commit it as one large commit.
Supersedes: https://github.com/ionic-team/stencil/pull/2959
this commit adds experimental support for using stencil component
libraries in projects that use bundlers such as vite. prior to this
commit, stencil component libraries that were used in projects that used
such bundlers would have issues lazily-loading components at runtime.
this is …
=> fix(runtime): add lazy load for addtl bundlers

src/client/client-load-module.ts, src/compiler/output-targets/dist-lazy/generate-lazy-module.ts, src/declarations/stencil-public-compiler.ts, test/bundler/component-library/stencil.config.ts, test/bundler/karma-stencil-utils.ts, test/bundler/karma.config.ts, test/bundler/package-lock.json, test/bundler/package.json, test/bundler/tsconfig.json, test/bundler/vite-bundle-test/.gitignore, test/bundler/vite-bundle-test/README.md, test/bundler/vite-bundle-test/index.html, test/bundler/vite-bundle-test/index.js, test/bundler/vite-bundle-test/package-lock.json, test/bundler/vite-bundle-test/package.json, test/bundler/vite-bundle-test/vite-bundle.spec.ts
This is going to be a part of a chain of PRs. Once all of them are up/approved, I'll merge the child-most PR into its parent, that parent into its own parent, etc. At the end, we shall have a PR (https://github.com/ionic-team/stencil/pull/3349) which contains all of its children, and we'll commit it as one large commit.
As a result, this doesn't have all of the functionality necessary for STENCIL-338 to be complete yet - that'll be incrementally added as we merge the child PRs. This commit adds tests to evaluate the component library (https://github.com/ionic-team/stencil/pull/3349) in Vite, and the infra to run Karma tests
Stencil does not support component libraries being …
=> test(bundler): add vite-based tests 

test/end-to-end/src/components.d.ts
our `components.d.ts` file is out of date, see the 'new behavior' section for why and
how we'll mitigate in the future
this commit checks in changes to `test/end-to-end/src/components.d.ts`
that are generated starting with 846740fa1f074e401fa20be90d64e87f8db99c88
(https://github.com/ionic-team/stencil/pull/3296)
we missed this as a result of relying on ci to run the end to end tests
for us, rather than ever running them locally. the changes found in this
commit were generated by running `npm run test.end-to-end` on the commit
immediately preceding this one.
to avoid issues like this in the future, stencil-451 has been created
and added to the backlog …
=> chore(tests): fix end to end .d.ts file

src/utils/test/util.spec.ts, src/utils/util.ts
The code that is removed in this PR is never used
this commit removes the unused getFileExtension and getFileExt functions from stencil's
utilities and their related test code
Unit tests pass locally
=> refactor(utils): remove unused getFileExtension utilities

src/compiler/config/outputs/index.ts, src/compiler/config/outputs/validate-angular.ts, src/compiler/output-targets/output-utils.ts, src/compiler/output-targets/test/output-utils.spec.ts, src/compiler/types/tests/validate-package-json.spec.ts
This removes unused exports from `src/compiler/output-targets/output-utils.ts`, just to move the needle a little bit on our unused exports tech debt burndown. It also fixes some strict null checks compiler errors that were a bit incidental to this, and makes a few (small) code changes in the output-utils file.
Tests are passing, could be good to validate some of this just by building a compiler and running it on some example stuff.
=> remove unused exports on output utils

.eslintrc.js, package-lock.json, package.json, src/cli/task-generate.ts, src/cli/telemetry/telemetry.ts, src/cli/test/task-generate.spec.ts, src/client/polyfills/css-shim/css-parser.ts, src/compiler/build/build-stats.ts, src/compiler/sys/in-memory-fs.ts, src/compiler/transformers/add-static-style.ts, src/compiler/transformers/component-lazy/lazy-component.ts, src/compiler/transformers/component-native/add-define-custom-element-function.ts, src/compiler/transpile/transpile-module.ts, src/mock-doc/window.ts, src/utils/is-root-path.ts, src/utils/normalize-path.ts
One thing that's come up during reviews is the need to add JSDocs to functions. 
This commit looks to remove those types of comments from our review process by
having the linter warn us about missing `@param`s
this commit adds the first pass at enforcing @param usage in jsdocs.
configuring how jsdoc's are enforced often involves setting up multiple
rules at once to get a desired affect. rather than toil with the
_perfect_ setup, this commit is designed to get an initial take on this
in front of the team to use and iterate on over time.
the choice of rules revolves around the general desire that each jsdoc
includes:
- the `@param` jsdoc keyword
- the …
=> chore(lint): add initial eslint jsdoc @param rules

src/compiler/config/test/validate-config.spec.ts, src/compiler/config/validate-config.ts, src/declarations/stencil-public-compiler.ts
Stencil v2.16.0 introduced a regression, the symptoms of which are described here: https://github.com/ionic-team/stencil/issues/3403. Git bisect showed that this commit was the culprit: https://github.com/ionic-team/stencil/commit/cca8951e7ebf0432acb19286f7d59af61f9c5dc2.
What the user observed is that after upgrading from Stencil version 2.15.2 to version 2.16.0 the build output changed. With 2.15.2, when calling stencil like so:
```
stencil build --docs --dev --esm
```
the build output looked something like this:
```
dist
├── cjs
├── collection
│   ├── components
│   ├── test
│   └── utils
├── esm
│   └── polyfills
├── loader
├── stencil-one
└── types
```
Whereas after upgrading to 2.16.0 the output looked something like this:
```
dist
├── stencil-one
└── types
```
Stencil previously …
=> fix(config): fix faulty build output w/ `--esm` flag

src/dev-server/test/Diagnostic.stub.ts, src/utils/test/util.spec.ts, src/utils/util.ts
the `parseJson` utility was unnecessarily exported. while looking at the 
code, I took half an hour to clean it up a bit, add tests, etc.
this commit adds testing around the `parsePackageJson` function. it
calls an internal function `parseJson`, which was orginally
unnecessarily exported and removing the `export` keyword from this
function was the impetus for this work.
some types were tightened/changed:
- a concrete type, `ParsePackageJsonResult` was created to describe the
return type of `parsePackageJson` and `parseJson`. this type
explicitly marks the `diagnostic` and `data` fields as the union of
their original type and `null`, allowing us to …
=> test(json-parsing): add unit tests 

src/cli/telemetry/telemetry.ts, src/cli/telemetry/test/telemetry.spec.ts, src/declarations/stencil-private.ts
This adds an anonymized copy of the Stencil configuration to the
telemetry object, so that various configuration options can be tracked
and observed over time.
This adds a function to anonymize the Stencil configuration and basically adds that anonymized object in to the object that we ship to the telemetry API endpoint.
The main thing to review here is whether the anonymization makes sense! I went through the output and removed everything I could think of that would have a filepath in it that might contain the current username, an internal URL, or something of that type.
I have added tests around the anonymization function and updated the other unit …
=> feat(telemetry): add stencil config to telemetry object

src/compiler/config/test/validate-config.spec.ts
the initialization of `config.flags` is not tested
this commit adds unit tests to the portion of the configuration
validation process for the 'flags' field
unit tests pass
=> test(config): add unit tests to config flags

scripts/bundles/cli.ts, src/cli/config-flags.ts, src/cli/index.ts, src/cli/logs.ts, src/cli/parse-flags.ts, src/cli/public.ts, src/cli/test/parse-flags.spec.ts, src/compiler/config/config-utils.ts, src/compiler/config/test/load-config.spec.ts, src/compiler/output-targets/output-utils.ts, src/compiler/prerender/prerender-main.ts, src/compiler/sys/logger/terminal-logger.ts, src/compiler/sys/logger/test/terminal-logger.spec.ts, src/declarations/stencil-public-compiler.ts, src/testing/jest/jest-runner.ts, src/testing/jest/test/jest-runner.spec.ts, src/utils/helpers.ts, tsconfig.json
this refactors the parse-flags module, removing some code duplication
and changing how the `ConfigFlags` interface is declared.
Now the ConfigFlags interface is generated based on the content of a few
read-only arrays of strings. This means that config flags are listed in
one and only one placed and cannot drift / get out of sync.
Currently we define a `ConfigFlags` object which defines CLI arguments that Stencil supports. We also have lists of supported CLI arguments in `src/cli/parse-flags.ts`. Although those lists of arguments (basically `ReadonlyArray<string>`) are actually used to construct the `ConfigFlags` object, we don't currently have a type-system-level guarantee of …
=> refactor(cli): refactor parse-flags module

src/compiler/output-targets/test/output-targets-dist.spec.ts, src/compiler/output-targets/test/output-targets-www-dist.spec.ts, src/compiler/output-targets/test/output-targets-www.spec.ts, src/testing/test/testing-utils.spec.ts, src/testing/testing-utils.ts
The `doNotExpectFiles` utility function does not work/behave as expected
this commit restores the `doNotExpectFiles` utility helper under test.
this commit is compliment to aee5287e1594086c0253030c03b62f9429d3ec7a,
which got the `expectFiles` testing utility under test.
this commit makes a few assumptions about how we will use this utility
function. namely, it only throws an exception if one or more files
provided by a caller are found. it does not check the permissions on the
file path (it appears that a previous implementation would take this
into account). should we decide to re-implement file access, we can do
so at a later date.
similar to …
=> chore(test): restore doNotExpectFiles

src/cli/test/run.spec.ts
`run.ts` is not under test.
this commit adds initial unit tests for `run.ts`. the goal of these
tests are to get the minimal amount of coverage under the `run` and
`runTask` functions so that we can (eventually) begin to change the
function signatures on the functions they invoke.
specifcially, the stencil team is looking to make the configuration
object that is used throughout the compiler stricter by making fields
no longer optional on the type. as a part of that effort, we are
reassessing what data fields functions need. we know that we will be
changing the signatures of the tasks for 'help' and 'telemetry'. by
adding tests around the invocation of …
=> test(cli): add tests for run.ts

src/client/client-window.ts, src/hydrate/platform/index.ts, src/runtime/styles.ts, src/testing/platform/index.ts, src/testing/platform/testing-platform.ts
this commit fixes a bug where styles from a stencil component would not
be applied prior to render. the issue involved stylesheet construction &
application not blocking render, causing the component to be created
without styles applied.
this commit moves from the `replace` function to the `replaceSync`
function to properly await the call
This was one of the primary culprits for our flaky Browserstack tests. Roughly 75% of all failures were from tests run against Firefox (v101, 102) with an error something to the effect of:
```
Expected 'rgba(0, 0, 0, 0)' to be 'rgb(0, 0, 0)'
```
We should see stabilization of these tests as a result of this PR
This is …
=> fix(styles): ensure styles are applied before paint

src/compiler/optimize/autoprefixer.ts, src/compiler/optimize/optimize-css.ts, src/compiler/style/css-imports.ts, src/compiler/style/optimize-css.ts, src/compiler/style/style-utils.ts, src/compiler/style/test/css-imports.spec.ts, src/compiler/style/test/style.spec.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts
This refactors and documents some code in the module responsible
for parsing css imports (`src/compiler/style/css-imports.ts`) and adds
some tests to increase coverage.
This commit also makes some edits to the general 'style' spec
(`src/compiler/style/test/style.spec.ts`) which has been skipped for a
while. The tests in this suite were 'end-to-end' unit tests of the style
handling capabilities of the compiler, which we'd like to have again,
but we can't reconstitute them until we get unit testing of the compiler
stood back up again.
So for now this ports a few tests out of `style.spec.ts` and into the
relevant specfiles (like `css-imports.spec.ts`) and deletes a few tests
from `style.spec.ts` which are no longer accurate (like testing for
escaping certain characters).
Please check if your …
=> refactor(style): refactor code in compiler/style/css-imports

src/compiler/style/test/optimize-css.spec.ts, src/compiler/sys/logger/test/terminal-logger.spec.ts, src/runtime/test/hydrate-prop-types.spec.tsx, src/runtime/test/lifecycle-sync.spec.tsx, src/runtime/test/render-vdom.spec.tsx, src/runtime/test/watch.spec.tsx, src/testing/testing-utils.ts
this adds a little utility for replacing the `console` functions with
mocks to silence any error messages and get our jest output under
control.
This function calls `afterAll` internally, so it will clean up after
itself by restoring the original functions for `console.log`, `.error`,
etc.
Gaze upon this and feel at peace:
https://user-images.githubusercontent.com/6207644/174887868-ec9d7eb7-6862-471a-8cf0-91fec3ebdfa1.mov
This is just a testing change anyhow, so I think if tests are passing we are all good.
I did confirm that this setup does not inadvertently silence tests outside of the suites in which it's called.
=> chore(tests): silence console.{log|warn|error} messages during tests

test/karma/README.md, test/karma/karma.config.js, test/karma/package.json
Previously, testing a change that affected our Karma/Browserstack tests involved one of two things:
- Creating a Draft PR and continuously pushing to a WIP branch to test changes (which wastes time waiting for builds to pass/complete)
- Hack at the Karma configuration to tunnel into Browserstack locally
this commit documents the ability to run the karma tests locally. in
addition, it also removes hacks that developers once had to do in order
to connect to browserstack locally, by introducing a new environment
variable, LOCAL_BROWSERSTACK, that will allow the development team to
tunnel into browserstack for local testing purposes
Run through the README …
=> docs(karma): add running locally documentation

test/karma/test-app/prerender-test/karma.spec.ts
this commit fixes an issue where stencil's prerender tests that would begin to run before
the entire pre-render application would be loaded. this is accomplished by moving from
using the 'appload' event to the 'load' event to listen on by moving from the timeout
associated with `setupDom` to the `waitForChanges` API our testing utilities provides
STENCIL-433: Stabilize Browserstack CI Tests
Tests are more stable. This doesn't solve the issue with disconnects, but that's outside the scope of this PR.
I've seen 2/11 fail, both for disconnect issues.
=> test(prerender): wait for load event

src/compiler/config/outputs/validate-collection.ts
We had a function called `getCollectionDistDir` defined in
`src/compiler/config/outputs/validate-collection.ts` which does not
appear to be used anywhere in the codebase.
I removed a function that I couldn't find any uses of in the codebase, and added a JSDoc comment to the only other function remaining in the module.
=> chore(unused exports): remove unused export from validate-collection.ts

src/compiler/config/test/validate-dev-server.spec.ts
~20 or so over our `strictNullChecks` violations for validating the dev server are related to
configuration options that are unvalidated/won't have their type signature changed
this commit removes the strictNullCheck violations from tests for
validating the dev server. it only removes those associated with an
unvalidated configuration. we have no intention at the moment to make
`devServer` or its subfields required on `Config`. regardless of what
happens on `ValidatedConfig#devServer`, we needed to handle these
unvalidated `devServer` instances
Unit tests pass
I'm trying to break some of these larger efforts up into smaller, more manageable chunks. …
=> chore(test): remove strictNullChecks from dev server validation

src/cli/config-flags.ts, src/cli/parse-flags.ts, src/cli/run.ts, src/cli/telemetry/helpers.ts, src/cli/telemetry/test/helpers.spec.ts, src/cli/telemetry/test/telemetry.spec.ts, src/cli/test/run.spec.ts, src/compiler/compiler.ts, src/compiler/config/test/validate-config.spec.ts, src/compiler/config/test/validate-dev-server.spec.ts, src/compiler/config/test/validate-docs.spec.ts, src/compiler/config/test/validate-output-www.spec.ts, src/compiler/config/test/validate-service-worker.spec.ts, src/compiler/config/test/validate-stats.spec.ts, src/compiler/config/test/validate-testing.spec.ts, src/compiler/config/test/validate-workers.spec.ts, src/compiler/sys/config.ts, src/testing/jest/test/jest-runner.spec.ts, src/testing/mocks.ts
Removing the optional types on `ConfigFlags` lets us remove a few null
suppression errors here and there and removes some `strictNullChecks`
violations as well.
To make it easy to create a correctly-formed `ConfigFlags` object this
also introduces a `createConfigFlags` helper function which takes a
partial `ConfigFlags` object and returns one with default properties
set.
Basically this just cleans up the typing on the `ConfigFlags` object a little bit and introduced a helper function to make it easy to create correctly typed objects.
I just made sure everything is compiling and tests are passing.
=> chore(types): remove optional types on ConfigFlags interface

src/compiler/output-targets/dist-custom-elements/custom-elements-types.ts, src/compiler/output-targets/dist-custom-elements/index.ts, src/compiler/output-targets/test/custom-elements-types.spec.ts
This fixes the typedef file generated for the `index.js` file produced
by `dist-custom-elements`. Previously it was mistakenly assuming that
the path to a component's `d.ts` file could be generated on the basis of
the `tag` set on the component. This _is_ the case if the component's
filename is equal to it's tag, but there is no requirement that that be
the case.
This changes the way that the relative path from
`${outputDir}/components/index.d.ts` to the `.d.ts` file for a specific
component is generated.
Previously we were doing something like:
```ts
${outputDir}/types/components/${component.tagName}/${component.tagName}
```
This doesn't work if a component is saved in
`src/components/button/button.tsx` but has a tag like `custom-button`.
So to fix this we can instead:
- find the …
=> fix(compiler): fix typedef file generated for dist-custom-elements

.github/workflows/test-browserstack.yml
See 'new behavior' section below
this commit adds a concurrency string, 'run_browserstack_queue' to the
'run_browserstack' job in ci.
the name for the concurrency field was chosen to:
- make it easily identifiable as a part of running browswerstack
- not overlap with the name of the run_browserstack job completely to
avoid any confusion when debugging in the future
this change prevents a condition in ci where two simultaneous browserstack 
runs are attempted at the same time. stencil's browserstack license only
allows for five parallel runs at a given time. as of the time of this
writing, stencil uses three browsers per run of browserstack. as a
result, …
=> chore(browserstack): add concurrency field

src/cli/run.ts, src/compiler/config/test/validate-service-worker.spec.ts, src/compiler/config/validate-config.ts, src/compiler/output-targets/dist-custom-elements/custom-elements-types.ts, src/compiler/output-targets/dist-custom-elements/index.ts, src/compiler/output-targets/output-types.ts, src/compiler/output-targets/test/custom-elements-types.spec.ts, src/compiler/output-targets/test/output-targets-dist-custom-elements.spec.ts, src/compiler/sys/config.ts, src/compiler/types/generate-types.ts, src/declarations/stencil-public-compiler.ts, src/testing/mocks.ts
This makes the `outputTargets` field required on the `ValidatedConfig`
type, allowing us to freely access `.outputTargets` on a validated
configuration object in the compiler code without having to use the `!`
operator, check `=== undefined`, etc.
This includes changes to the places where a `ValidatedConfig` object is
created to default `.outputTargets` to `[]` if no suitable value is
present.
`.outputTargets` is currently not a required field on our `ValidatedConfig` type, which means that we get a null check error every place we access this (very commonly accessed!) property, unless we do `.outputTargets ?? []` or something of the sort everywhere.
We also have a few places …
=> chore(compiler): make outputTargets required on the ValidatedConfig

src/mock-doc/node.ts
NOTE: I have previously created issues and example repositories but since this is a really small PR that does not impact any users directly, I feel that this can be done without an accompanied issue. If you feel differently about this, do say so.
Add missing methods to the mock-doc MockElement class.
The methods that have been added were missing, causing errors.
No error is thrown when your component uses any of the methods while running unit tests.
=> fix(mock-doc): add missing methods to the element mock

src/cli/parse-flags.ts, src/cli/test/parse-flags.spec.ts, src/testing/jest/test/jest-config.spec.ts
This fixes a bug with how these flags were being parsed which was
messing with Jest. Basically, the issue related to how the `knownArgs`
array on the `ConfigFlags` object was being populated. For CLI key-value
args of the format `--argName=value` the whole string
`"--argName=value"` was being added _as well as_ the value string
`"value"`, which had the effect of passing duplicate args to Jest.
This refactors how such arguments are handled to always parse apart the
argument name and the value, adding only the argument name and then the
argument value, so that if you pass, for instance,
`--outputFile=output.json`, the args passed to Jest will look like
```ts
['--outputFile', 'output.json']
```
See https://github.com/ionic-team/stencil/issues/3471 and …
=> fix(cli): fix bug with parsing --fooBar=baz type CLI flags 

src/compiler/types/tests/validate-package-json.spec.ts, src/compiler/types/validate-build-package-json.ts, src/utils/message-utils.ts
This updates the validation around the `module` field in `package.json`
to take the configured output targets into account. In particular, for
`DIST_CUSTOM_ELEMENTS_BUNDLE` it should be something like
`dist/index.js`, whereas for `DIST_CUSTOM_ELEMENTS` it should be
something like `dist/components/index.js`.
Currently if you are using the `DIST_CUSTOM_ELEMENTS` output target we recommend setting the `module` field in the project's `package.json` field to `dist/components/index.js`, the path to the file where we re-export all of the components in the project.
This works great for importing these components in other projects, but, unfortunately, if you also have …
=> fix(compiler): update package.json validation for the 'module' field

src/cli/telemetry/test/telemetry.spec.ts, src/cli/test/run.spec.ts, src/cli/test/task-generate.spec.ts, src/compiler/output-targets/test/custom-elements-types.spec.ts, src/compiler/output-targets/test/output-targets-dist-custom-elements.spec.ts, src/compiler/output-targets/test/output-targets-dist.spec.ts, src/compiler/output-targets/test/output-targets-www-dist.spec.ts, src/compiler/output-targets/test/output-targets-www.spec.ts, src/compiler/service-worker/test/service-worker-util.spec.ts, src/compiler/service-worker/test/service-worker.spec.ts, src/compiler/style/test/optimize-css.spec.ts, src/compiler/style/test/style.spec.ts, src/compiler/types/tests/validate-package-json.spec.ts, src/testing/jest/test/jest-config.spec.ts, src/testing/mocks.ts, src/utils/test/util.spec.ts
Our mocks for configuration entities, both unvalidated and validated, are cumbersome
to override.
this commit adds a new parameter to `mockValidatedConfig`, `overrides`.
the argument is optional, and defaults to an empty object literal. it is
spread over the returned object to override and defaults put in place by
this method. the `sys` argument is also removed, as it now can be safely
derived from the `overrides` argument (and still falls back to a new
`TestingSystem` if `overrides.sys` is falsy
this commit adds an `overrides` parameter to `mockConfig`. `overrides`
is a partial instance of `UnvalidatedConfig`, which defaults to an empty
object literal. …
=> chore(mocks): update mockConfig, mockValidatedConfig to accept any property

src/cli/telemetry/telemetry.ts, src/cli/telemetry/test/telemetry.spec.ts
`Config` is used in a few remaining functions in the `cli/telemetry` directory. This leads to an
inaccurate count of `strictNullChecks` violations
There are three functions that were updated as a part of this PR.
See each commit message for the details, although they're all largely the same, with https://github.com/ionic-team/stencil/pull/3484/commits/775aeee02f57e825b97dece5e3856ca1d7534104 probably being the more interesting of the three
We move the needle forward by _2_ _whole_ violations here.  That's .07949125596% less than we had 🎉 🙃
=> chore(config): propagate ValidatedConfig through telemetry directory

src/cli/parse-flags.ts, src/cli/public.ts, src/cli/run.ts, src/cli/test/parse-flags.spec.ts, src/testing/jest/test/jest-config.spec.ts
This removes some code from our argument parsing implementation which
would look for an environment variable (`npm_config_argv`) set by npm
and, if present, merge CLI flags found their into the ones already
present on `process.argv`.
We want to remove this for two reasons:
- `npm_config_argv` is deprecated in `npm`, so in newer versions of the
package manager it is no longer set and our code referencing it is
effectively doing nothing
- `yarn` v1.x still sets it (presumably for compatibility with `npm`
that hasn't been removed yet, which causes an inconsistency between
`npm` and `yarn` where certain `package.json` scripts will run without
issue in `npm` but fail in `yarn` (see #3482)
Accordingly, this commit deletes the offending function from
`src/cli/parse-flags.ts` and makes a few …
=> fix(cli): remove usage of deprecated npm env var from arg parser

src/cli/run.ts
collecting telemetry on the `info` task has been broken for a bit now
this commit removes a telemetry call from stencil for the info task.
this call has been broken for the debugging/verbose capabilities,
is seldom used, and is something that we don't feel we want or need
to collect.
it also has an additional positive side effect for making the stencil
configuration entity stricter - this call was placed before
loading/validating a configuration (because doing so is not required to
run the info task, making it faster). as `ValidatedConfig` grew in size,
additional fields were added to make a bespoke validated config.
removing this call removes the need …
=> chore(telemetry): remove info task telemetry call

src/cli/parse-flags.ts, src/cli/public.ts
This removes the `sys` parameter from the `parseFlags` function in
`src/cli/parse-flags.ts`. This parameter was more or less deprecated
in #3486 but was not removed at the time because `parseFlags` is part of
Stencil's public API, so we need to wait for a major version change to
change the type signature of the function.
STENCIL-509: remove _sys param from cli/parse_flags.ts::parseFlags
No code behavior change here, just removing a parameter on a public function.
If anyone is using this function in a typescript environment they'll need to update their code to fix a type error (it will be real straightforward though).
unit tests, and building and trying out a Stencil build with …
=> chore(cli): remove sys param from `parseFlags`

src/cli/run.ts, src/cli/telemetry/test/telemetry.spec.ts, src/compiler/compiler.ts, src/compiler/config/load-config.ts, src/compiler/config/validate-config.ts, src/compiler/sys/config.ts, src/declarations/stencil-public-compiler.ts, src/testing/mocks.ts
`sys` is not a required property on `ValidatedConfig`, creating several
`strictNullCheck` violations in the codebase
this commit makes the `sys` property required on `ValidatedConfig`. this
work decreases the number of `strictNullCheck` violations in the
codebase. it does not fix every violation pertaining to `config.sys`
usage - rather, it seeks to be the minimal work necessary to
1. make the `sys` property required on `ValidatedConfig`
2. prevent introducing breaking compilation errors
Unit tests, e2e tests continue to pass (no function signature changes were made).
I tried hard here to replicate the existing behavior (otherwise saying 'tests pass …
=> chore(config): make sys required on ValidatedConfig

src/cli/run.ts, src/cli/task-build.ts, src/cli/task-help.ts, src/cli/test/run.spec.ts
In 66d0476b (#3079), we added a truthy check for `CompilerSystem` entities.
With the recent move to making that entity required on a `ValidatedConfig` entity
(a6a9171 - #3491), these checks can be safely removed.
This PR removes cases throughout the code base where a truthy check is
required in order to call a function that requires it. In every case, we are able to
utilize the fact that the calling function has an instance of `ValidatedConfig`, which
now has a `sys` on it. 
The original belief was that this would need to be a breaking change (this was
months ago when the ticket was originally written). However, the foundation of this
PR  (a6a9171) does …
=> chore(run): remove unneeded CompilerSystem checks

.github/workflows/test-browserstack.yml, .github/workflows/test-e2e.yml
This adds a small check to the end of our end-to-end CI tests which just
tries to ensure that no files were changed or added while the tests were
running.
STENCIL-451: Add CI Checks for a Dirty Git Context
Right now we have no automatic visibility into whether tests running on CI change files that should be committed.
This adds a simple check (implemented using `git`, `grep`, `wc`, and `-ne`) to make sure there aren't any uncommitted changes.
Note that we download a build zip file, so we have a little `grep -v` to ignore that.
I confirmed that this will fail if there is a file changed or added by the tests.
=>  feat(ci): fail the browserstack tests if any files were changed or added 

src/compiler/types/tests/validate-package-json.spec.ts, src/compiler/types/validate-build-package-json.ts
See the GitHub Issue referenced below
GitHub Issue Number: Fixes #3507 
this commit fixes the module directory suggestion for the
`dist-custom-elements` output target. in 47c4ccb, we introduced a bug
where we assumed that the output target's `dir` field did not include a
'components' subdirectory. however, this is not the case, as we add
'components' to the `dir` field at the time of validating the output
target. by removing 'components' from the directory in this commit, we
use the value that is stored in `dir` as the source of truth
this commit moves the check for the `dist-custom-elements` output target
to occur after the `dist` output target check. this results in the …
=> fix(validation): update module location suggestion

src/cli/run.ts, src/compiler/config/test/validate-service-worker.spec.ts, src/compiler/config/validate-config.ts, src/compiler/sys/config.ts, src/declarations/stencil-public-compiler.ts, src/testing/jest/jest-config.ts, src/testing/jest/test/jest-config.spec.ts, src/testing/mocks.ts
`testing` is responsible for several `strictNullChecks` violations in the code
this commit updates `ValidatedConfig` in order to make the `testing`
field required. this is being done in pursuit of dropping the number of
`strictNullChecks` violations in the code, and was a side task of
stencil-501 (the author of this commit was actively in the testing code,
making it a good opportunity to knock this out).
this commit makes `testing` default to an empty object literal, rather
than `null` or prepopulating existing fields. choosing the former would
require additional optional checks throughout the code (which assumes
`testing` is a defined field, and …
=> chore(config): make testing property required field

src/cli/run.ts, src/cli/test/run.spec.ts
The `sys` field on a configuration entity is not considered when
`runTask` is invoked directly. This causes us to configure the compiler
differently/incorrectly
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/3510
this commit updates the generation of a `ValidatedConfig` entity to take
a `sys` property on a user provided `Config` in the context of
`runTask`.
when generating the validated configuration, the `sys` entity takes
precedence over all other configurations, with the belief that in the
event argument was provided, it is the intent of the user to use it. in
the event `sys` is not expressly provided, use the one on the provided
configuration entity. this …
=> fix(task): consider config sys in task runner

src/compiler/bundle/bundle-interface.ts, src/compiler/bundle/bundle-output.ts, src/compiler/bundle/dev-module.ts, src/compiler/bundle/ext-transforms-plugin.ts, src/compiler/bundle/test/ext-transforms-plugin.spec.ts, src/compiler/bundle/worker-plugin.ts, src/compiler/transformers/stencil-import-path.ts
This fixes an issue (#3461) where CSS is being inappropriately mangled
when using the hot-reload dev server. The issue has details about
exactly what the problem is, but basically in short if you are using the
`dist-hydrate-script` output target and running the dev server then any
change to a CSS file will cause all styling to be wiped from the related
component in the browser, making for a pretty inadequate developer
experience.
This commit fixes the issue by changing the conditions under which
original CSS selectors are commented out and 'scoped' so that it is only
done when you are have `scoped: true` set on a component (I believe this
was the original intent but for some reason the code wasn't set up to do
this).
Please …
=> fix(compiler): don't break HMR by mangling CSS

src/cli/find-config.ts
See new behavior 
this commit adds additional types for the function that finds a user's
configuration file on disk in the hope of adding clarity and removing a
type assertion in the function
N/A - compiler continues to pass type checks
i had this commit sitting around, with no great place to add it to an
existing pr. i decided to just put it up on its own instead of continuing to
maintain it locally
=> chore(cli): add types to finding config

src/mock-doc/attribute.ts, src/mock-doc/custom-element-registry.ts, src/mock-doc/node.ts, tsconfig.json
This PR basically just entails fixing (some!) strict null checks errors in a few `mock-doc`-related files. I don't pretend to have fixed them _all_, but mainly tried to adjust the TS types so that they're more inline with how the code is actually used. For instance, we had a number of places where something was typed `string` but actually called with both strings and `null`. I tried to just smooth out some of that inconsistency where I could while changing as little actual code as possible.
I just tried to change the types in `src/mock-doc/node.ts` to reflect the values they actually are at runtime. I think I eliminated the null check errors from that …
=> fix up null checks in some mock-doc code

.github/workflows/build.yml
ci fails when we modify the `scripts/` directory of the project
this is a symptom of a larger issue where the incorrect branch was built for browserstack tests,
we never noticed before because `scripts` contains both compiled and source code we archive,
and this is the first time we've modified it since the bug in CI was introduced
this commit modifies the `build_core` reusable workflow for stencil's ci
to take into account the event name when checking out the code to be
built. depending on the event name, the `HEAD` value used to check out
the code can differ. for event's with name 'pull_request_target', `HEAD`
is the head of the primary branch, in our …
=> chore(ci): fix dirty git context for browserstack

.github/workflows/tech-debt-burndown.yml
the tech-debt burndown fails for forks of this repo, due to security issues
this commit changes the event type on the tech debt burndown list. the
pull_request event does not offer the ability run the
'peter-evans/create-or-update-comment' step (see
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks)
for security reasons. in this commit, we use 'pull_request_target' in an
attempt to fix that.
however, this affects what branch is used from in ci from the branch
that the pr was opened with (pull_request), to the `HEAD` of `main`
(pull_request_target). as a result, `actions/checkout` …
=> chore(ci): run tech debt burndown on forks

package-lock.json, package.json
I believe that we have a `@types` dep that is not needed anymore
Supersedes: #3547
this commit removes `@types/is-glob` from the project's root manifest.
`is-glob` does not appear to be used in the project at this time. it
appears it once was in the project, but was removed prior to v1.16.0
(it was removed in 0522e66b5213cb80de72e544ff5e3185f389dd32,
specifically).
this commit is motivated by dependabot attempting to bump the version of
this package in https://github.com/ionic-team/stencil/pull/3547. rather
than bump the version, we should prefer to remove packages we do not use
Ran the type checker and tests locally, we'll see what CI has to say
=> chore(dev-deps): remove unneeded @types/is-glob

test/todo-app/src/components.d.ts
This just commits a `components.d.ts` file generated by building the
'todo' app as part of the `test.analysis` script.
No behavior changes, just committing a file that changes if you run the `test.analysis` script locally.
=> chore(tests): commit file generated by compiling to 'todo' analysis app (v3)

src/cli/run.ts, src/compiler/config/test/validate-service-worker.spec.ts, src/compiler/config/validate-config.ts, src/compiler/config/validate-paths.ts, src/compiler/sys/config.ts, src/declarations/stencil-public-compiler.ts, src/testing/mocks.ts
This adds `rootDir` to the validated config type, adding some logic
where necessary to set a basic default if it's not present.
Just adding `.rootDir` as a required field on the `ValidatedConfig` type, cutting down our null check violations a little bit.
=> chore(config): add `rootDir` to the validated config type

src/declarations/stencil-private.ts, src/testing/platform/testing-host-ref.ts, src/testing/spec-page.ts
Stencil contains a number of `strictNullChecks` violations
this commit updates the typings for `spec-page.ts` to remove
`strictNullChecks` violations from the aforementioned file. the private
type `CompnentTestingConstructor` has some of its fields widened to
accepted `null` to reflect the state of the the existing assignments.
similarly, optional chaining is added to the conditionals to prevent
assignments/accesses that would otherwise be illegal
this commit also updates the function signature for `getHostRef` in the
testing package, to accept an argument of type undefined. today, it is
possible for the function to accept a value that is `undefined`; …
=> chore(types): remove type-check errors from spec-page 

src/compiler/transformers/decorators-to-static/convert-decorators.ts, src/compiler/transformers/transform-utils.ts
there's a single `strictNullCheck` violation in the file in this PR, which coincidentally has its code
duplicated elsewhere
this commit fixes a single `strictNullChecks` violation where the result of an expression could set a local variable to be of type `string | false`, where `false` was not an accepted value on `Set.prototype.has`. this change ought to be backwards compatible, as no `Set` provided to this function includes `false` (or any value that is coerced to `false`).
the function signature was updated to include a return type, and the function name was updated to provide a better description of what the function does.
the deprecated call to …
=> refactor(decorators): fix `strictNullCheck` violation

.eslintrc.js, .github/ISSUE_TEMPLATE/bug_report.yml, .github/dependabot.yml, .github/ionic-issue-bot.yml, .github/workflows/main.yml, .github/workflows/tech-debt-burndown.yml, .github/workflows/test-analysis.yml, .github/workflows/test-browserstack.yml, .github/workflows/test-e2e.yml, .github/workflows/test-unit.yml, jest.config.js, package.json, rollup.config.js
Our prettier config misses certain files that may be worthwhile to format
this pr is broken into 2 commits:
[68b6c0b](https://github.com/ionic-team/stencil/pull/3598/commits/68b6c0b8b88d71406f5ae0443c93db88755ce832)
this commit updates our prettier configuration to format all yaml files
in the `.github` directory at the root of the the repo. both `.yml` and
`.yaml` were added. although the latter isn't used today, it is added as
a bit of 'future proofing'.
with the updated config, prettier was run on the repo. the only change
that is worth noting is that none of the double to single quote changes
_shouldn't_ be of issue, as the contents of the strings …
=> chore(repo): format additional files in repo

src/cli/task-telemetry.ts
=> chore(cli): fix typo in telemetry command

src/cli/parse-flags.ts, src/compiler/transformers/decorators-to-static/convert-decorators.ts, src/compiler/transformers/decorators-to-static/decorators-constants.ts, src/compiler/transformers/transform-utils.ts, src/utils/util.ts
This converts a Set of decorators that we remove during compilation from `Set<string>` to `ReadonlyArray<string>` because by doing so we get much better type hint popups.
We have two `Set` objects which basically should really be constants, since they are never modified at runtime. This just changes them to be `ReadonlyArray<string>` in order to push that information into the type system (and get some better type hints when you run across these things in a file).
=> chore(compiler): convert a Set to a readonly array

src/utils/logger/logger-typescript.ts
This fixes a small issue where we were accessing a possibly-undefined property on a TypeScript Diagnostic record.
This relates to the issue reported in #3443.
This fixes one part of the issue reported in #3443, basically just ensuring that we aren't assuming that a possibly-undefined property is always present.
One thing to test is to confirm that if you build and install Stencil with this change into an example project you shouldn't see the particular error mentioned in #3443 about `TypeError: Cannot read property 'fileName' of undefined at flattenDiagnosticMessageText`...you very well may see other errors though! This PR only addresses the undefined …
=> fix(logger): fix possibly-null property access in logger-typescript.ts

.npmrc
we're seeing sporadic build errors in ci, which makes us sad
this commit introduces an `.npmrc` file to the project that specifies a new value for `--max-old-space-size`. by default, node allocates 2GB of memory to a process. it is possible for stencil builds to near this limit, causing an out of memory failure. we have seen this more often in continuous integration (github actions) than anywhere else.
an `.npmrc` file was chosen here as an operating system, shell, and build-agnostic solution. that is, this solution is intended to work:
- on linux, macos, and windows (although we only use linux for building, and the team develops solely on macos)
- on …
=> chore(ci): fix build out-of-memory errors

src/cli/find-config.ts, src/cli/ionic-config.ts, src/cli/run.ts, src/cli/telemetry/helpers.ts, src/cli/telemetry/telemetry.ts, src/cli/telemetry/test/helpers.spec.ts, src/cli/test/run.spec.ts, src/declarations/stencil-private.ts
We have over 2158 SNC errors on `main`
[2b9aebb](https://github.com/ionic-team/stencil/pull/3632/commits/2b9aebb7178bd3759afdf8b48cadc9f10f83619b)
this commit explicitly handles the the case of a null task, which we
have decided to allow on a type-level. a new test case is added to
verify the new behavior: when the null task is found, we show the help
prompt
[2a56d33](https://github.com/ionic-team/stencil/pull/3632/commits/2a56d332e3ae97f114e2859da4ef9b05b49147e0)
this commit resolves a type error when finding a configuration. it is a
common paradigm in stencil to declare a 'result' object at the beginning
of a function. however this presents difficulty …
=> refactor(types): drop strictNullChecks count in cli

.github/dependabot.yml
It's currently hard to keep deps up to date - specifically, we can't update every dependency all at once, and the few
PRs dependabot has opened for us take a fair bit of work to actually land. so dependencies are falling behind as a result of this "pr dam" we've built
this commit increments the number of open pr requests that dependabot can have open at any given time. this commit is being done following a discussion during a team refinement session earlier this week, where it's been difficult to work through the existing dependency chain with only 5 open prs at once.
by default dependabot will limit itself to 5 open PRs. 
> By default, Dependabot opens …
=> chore(github): increase dependabot pr limit

src/compiler/build/build-hmr.ts, src/declarations/stencil-public-compiler.ts, src/utils/is-glob.ts
This adds a few docstrings for the setting on the dev server config which allows modules to be excluded from HMR updates (`excludeHmr`).
I just noticed this when looking at #3661 and figured why not add a few comments.
no comments!
Just adding a few comments.
=> docs(compiler): add a few docstrings for `excludeHmr` functionality

src/compiler/transformers/component-lazy/lazy-constructor.ts, src/compiler/transformers/component-lazy/lazy-element-getter.ts, src/compiler/transformers/component-native/native-constructor.ts, src/compiler/transformers/component-native/native-static-style.ts, src/compiler/transformers/create-event.ts, src/compiler/transformers/decorators-to-static/method-decorator.ts, src/compiler/transformers/decorators-to-static/prop-decorator.ts, src/compiler/transformers/decorators-to-static/style-to-static.ts, src/compiler/transformers/define-custom-element.ts, src/compiler/transformers/host-data-transform.ts, src/compiler/transformers/legacy-props.ts, src/compiler/transformers/style-imports.ts, src/compiler/transformers/transform-utils.ts
I started with one file w/ a bunch of `ts.create{Whatever}` calls in it (`src/compiler/transformers/component-native/native-static-style.ts`) and then used a project-wide find and replace to change over the methods used in that file across the whole project. This resulted in changing `ts.createStringLiteral`, `ts.createObjectLiteral`, `ts.createPropertyAssignment`, and `ts.createIdentifier`.
I think this approach of starting with one file and then 'branching out' will let us make some steady progress without having to deal with overly large diffs.
We have calls to a bunch of deprecated typescript methods (all of which are for creating AST nodes).
This moves a few of them to the …
=> convert more `ts.create{Whatever}` methods to `ts.factory.create{Whatever}`

src/cli/telemetry/telemetry.ts, src/cli/telemetry/test/telemetry.spec.ts, src/declarations/stencil-private.ts
This adds the value of the `IS_BROWSER_ENV` helper to our telemetry payload, allowing us to track the usage level of Stencil in the browser.
Is this technically a feature? 🤔 in any case it's a small one!
We don't have much insight into how often Stencil is used in a browser environment.
This just adds the value of the `IS_BROWSER_ENV` variable to our telemetry payload, so we can track this value over time.
This can be tested by building Stencil, installing it into a project, and the running a Stencil sub-command with the `--debug` flag (that will print out the data sent to telemetry as a big JSON blob).
=> chore(telemetry): add isBrowserEnv to telemetry payload

src/testing/jest/jest-config.ts, src/testing/jest/test/jest-config.spec.ts
This adjusts the conversion of CLI args (parsed by our `cli/parse-flags` module) to arguments for Jest to fix a problematic situation when passing an argument which is not recognized by our `parse-flags` module.
A common pattern in Jest is to use a filename filter to narrow which tests are matched and run by the test runner, like so:
```
jest -- some-file-name.test.ts
```
Our CLI arg parsing module recognizes all Jest CLI args (like `--json`, `--watch`, and more) as 'first class' args and parses them into a `ConfigFlags` object. For the arguments shown above (`'--'`, `'some-file-name.test.ts'`), however, it will _not_ recognize them as first-class arguments and will instead preserve them in the `unknownArgs` array on the `ConfigFlags` object.
The flags (known and unknown) parsed by the …
=> fix(jest): adjust conversion of CLI args to Jest args

src/compiler/transformers/component-lazy/lazy-constructor.ts, src/compiler/transformers/component-lazy/lazy-element-getter.ts, src/compiler/transformers/component-native/native-connected-callback.ts, src/compiler/transformers/component-native/native-constructor.ts, src/compiler/transformers/component-native/native-element-getter.ts, src/compiler/transformers/create-event.ts, src/compiler/transformers/define-custom-element.ts, src/compiler/transformers/host-data-transform.ts, src/compiler/transformers/legacy-props.ts, src/compiler/transformers/style-imports.ts, src/compiler/transformers/transform-utils.ts
This updates some more `ts.create` methods to use the equivalent under `ts.factory`. Like in #3713 I selected a file (`src/compiler/transformers/component-native/native-connected-callback.ts`) to 'branch out' from and then did a project-wide find and replace to fix all usages of the `ts.create*` methods used in that particular file.
That turned out to be:
- `ts.createExpressionStatement` -> `ts.factory.createExpressionStatement`
- `ts.createAssignment` -> `ts.factory.createAssignment`
- `ts.createPropertyAccess` -> `ts.factory.createPropertyAccessExpression`
- `ts.createThis` -> `ts.factory.createThis`
- `ts.createCall` -> `ts.factory.createCallExpression`
- `ts.createMethod` -> `ts.factory.createMethodDeclaration`
- `ts.createBlock` -> `ts.factory.createBlock`
Please check if your PR …
=> chore(compiler): update `ts.create*` methods to `ts.factory`

src/cli/telemetry/test/telemetry.spec.ts, src/compiler/config/validate-testing.ts, src/compiler/output-targets/dist-lazy/generate-lazy-module.ts, src/compiler/sys/node-require.ts, src/compiler/transformers/transform-utils.ts, src/compiler/types/update-import-refs.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts, src/dev-server/server-web-socket.ts, src/hydrate/runner/hydrate-factory.ts, src/testing/jest/jest-serializer.ts, src/testing/jest/test/jest-serializer.spec.ts, src/utils/logger/logger-rollup.ts, tsconfig.json
This turns the `strictFunctionTypes` compiler flag on and fixes the errors uncovered by doing so.
`strictFunctionTypes` is turned off.
`strictFunctionTypes` is turned on!
I ran the tests, made sure everything compiles. I believe these are all only typesystem-level changes.
=> chore(types): turn on `strictFunctionTypes` compiler flag

src/compiler/transformers/decorators-to-static/convert-decorators.ts, src/compiler/transformers/test/convert-decorators.spec.ts
This change ensures that statements in an existing constructor are not thrown on the floor in the case that we need to edit a constructor (i.e. when there is a field with `@Prop` that we need to initialize in the constructor).
In f97783029274f9ee5ea58ba74ab15905c5113c93 we made a change to initialize any class fields decorated with `@Prop()` in a constructor. The code to do this would look for a constructor on the class and, if found, update the body of the constructor with statements to initialize the field.
Unfortunately, that commit would drop all existing statements in the constructor on the floor! This broke how some Stencil users initialize fields or do certain side effects, since no code they wrote in their constructors would make it through to the built output.
This commit fixes …
=> fix(compiler): account for an existing constructor in convert-decorators

BREAKING_CHANGES.md, src/declarations/stencil-public-runtime.ts
This updates the event handler names in `src/declarations/stencil-public-runtime.ts` for the composition events to have the correct casing.
Right now we have these cases like `onCompositionStart`, `onCompositionEnd`, etc when they should be `onCompositionstart`, `onCompositionend`.
This just changes the declarations to what they should be, which is all that's needed to get these events working correctly.
GitHub Issue Number: #3235
Now the spelling of the event names has been corrected, so they work! Great!
This is technically a bugfix, and it won't _break_ anyone's code, but it anyone was (for some unfathomable reason) depending on the previous, non-working declarations their …
=> fix(declarations): correct event handler names for composition events

src/cli/config-flags.ts, src/cli/parse-flags.ts, src/cli/test/parse-flags.spec.ts, src/utils/helpers.ts, src/utils/test/helpers.spec.ts, src/utils/util.ts
Jest supports passing certain arguments multiple times. For instance, in the following example:
```
jest --coverage --reporters="default" --reporters="jest-junit"
```
all of the values for the `--reporters` flag ("default" and "jest-junit") should be collected into an array of values, instead of simply recording whichever value is farther to the right (Stencil's behavior before this commit).
To support passing such arguments to the `stencil test` subcommand this commit adds a new recursive-descent parser in `src/cli/parse-flags.ts` to replace the somewhat ad-hoc approach that was there previously. It parses the following grammar:
```
CLIArgments     → ""
| CLITerm ( " " CLITerm )* ;
CLITerm         → EqualsArg
| AliasEqualsArg
| AliasArg
| NegativeDashArg
| NegativeArg
| SimpleArg ; …
```
=> fix(cli): refactor CLI argument parser

src/cli/telemetry/telemetry.ts, src/cli/telemetry/test/telemetry.spec.ts
Values that we're not interested in (ie garbage) can be added to a telemetry payload. We can delete those easily, but we need to stop sending them too.
this commit removes additional properties from our telemetry payload.
these properties have a tendency to allow for free-form keys, are of no
use to us. the properties being removed are:
- commonjs
- env
- rollupConfig
- testing
Unit tests have been updated
All the work is done in the first commit. The second commit alphabetizes the keys, and the third runs the formatter
=> chore(telemetry): remove additional properties

package.json
we do not lint `bin/stencil`
this commit updates our lint configuration to lint the contents of `bin/` which contains the entrypoint of stencil. this is an omission in our linting scripts. we should have always linted this file, but simply missed it
I tested this locally against the `head` of `main` (0ee91f3a86c1ce7e4a930e7a23be3438b33fd4dd). Which yielded
```
➜  stencil git:(ap/reporters-flag) ✗ npm run lint
> @stencil/core@2.19.2 lint
> eslint "bin/*" "src/*.ts" "src/**/*.ts" "src/**/*.tsx"
stencil/bin/stencil
4:1  error  Unexpected var, use let or const instead  no-var
5:1  error  Unexpected var, use let or const instead  no-var
6:1  error …
```
=> chore(lint): lint the bin directory

src/testing/jest/jest-config.ts, src/testing/jest/test/jest-config.spec.ts
This ensures that CLI arguments are ordered correctly when we pass them to Jest. In particular, we want to ensure that all flags of the type `--maxWorkers=0` and the like are _before_ any flags which we don't know about, like `my-spec-file.ts` (the latter being actually a match pattern for which spec files to run).
In other words, if the user passes arguments like this:
```
--e2e foo.spec.ts
```
or
```
--e2e -- foo.spec.ts
```
We need to ensure we use something like
```
["--e2e", "foo.spec.ts"]
```
to generate the Jest config.
The wrinkle is that after we've parsed our known CLI arguments (in the `cli` module) we do some addition modification of the arguments, based on values set in the `Config`, in the `buildJestArgv` function. In particular, we'll look to see if a `maxWorkers` flag is …
=> fix(cli): ensure that argument order is correct for Jest

src/compiler/transformers/test/transform-utils.spec.ts
There are no unit tests for `isMemberPrivate`.
this commit adds unit tests to the `isMemberPrivate` function in the transform-utils module. this is being done in preparation for changes to the function that are to occur in the typescript 4.8 upgrade. adding unit tests will provide additional safety during the upgrade, but aren't strictly necessary for it. the hope is to land this commit to the primary branch prior to the upgrade.
Unit tests continue to pass. I tailed the execution of these in the debugger as well.
=> test(transform-utils): add isMemberPrivate unit tests

scripts/release-tasks.ts, scripts/release.ts
When attempting to release Stencil with a custom version, the ability to
choose a custom semver-compliant name is broken. The prompt for
specifying a version gets skipped as such:
<Hit Enter>
Note the empty version number to the right of the 🌹 vermoji
this commit updates the prompts for the release scripts to allow for
custom versions and tags to be specified. an issue was occurring where
two inputs with the same name would only allow the first to be run. this
commit updates the second version & tag prompts to have a unique name,
where the two values are coalesced after either question is asked.
This PR includes a second commit, …
=> chore(release): re-enable custom release versions

package-lock.json, package.json, src/compiler/optimize/optimize-module.ts
On Monday, 2022.11.28, we had the [v3.0.0-alpha.0 release](7f4968b230903cc4a7e8f444de14b28ad1390c14). Following the release (I did this on Thursday, 2022.12.01), I merged the head of `main` into the `v3.0.0-dev` branch. [CI began to fail for the branch](https://github.com/ionic-team/stencil/actions/runs/3593285846) during our Analysis Tests:
```
TypeError: Cannot read property 'map' of undefined
at new TraceMap (/home/runner/work/stencil/stencil/compiler/stencil.js:9552:38)
at new AnyMap (/home/runner/work/stencil/stencil/compiler/stencil.js:9415:12)
at new SourceMapConsumer (/home/runner/work/stencil/stencil/compiler/stencil.js:9805:32)
at SourceMap$4 …
```
=> revert(terser): terser version bump

src/compiler/types/generate-app-types.ts, src/compiler/types/generate-component-types.ts, src/utils/test/util.spec.ts, src/utils/util.ts, test/end-to-end/src/components.d.ts, test/karma/test-app/components.d.ts
fix https://github.com/ionic-team/stencil/issues/3524
The dock block from the component itself is now copied to the generated components.d.ts file. This
makes it possible for other tools to get the documentation and use it, e.g. an IDE can display the
documentation for a component when it's being used
The doc blocks can be added to a few more places in the generated file, but I was not sure if it should be included everywhere or not. I added it to the places I have used in the past, it should be easy to include the other ones as well if needed.
I added unit tests for the new function I added to `utils.ts`, but did not add any for the changes in `generate-app-types.ts` and `generate-component-types.ts`. I would have added more tests for those files if tests for them already existed, but …
=> feat(compiler): copy doc block from component to generated types

.github/dependabot.yml, package-lock.json, package.json, src/compiler/config/test/validate-dev-server.spec.ts, src/compiler/config/test/validate-hydrated.spec.ts, src/compiler/config/validate-dev-server.ts, src/compiler/config/validate-hydrated.ts, src/compiler/config/validate-service-worker.ts, src/compiler/style/css-parser/parse-css.ts, src/compiler/sys/dependencies.json, test/bundler/package-lock.json, test/bundler/package.json, test/karma/package-lock.json, test/karma/package.json
- https://github.com/ionic-team/stencil-site/pull/939 
We support TS 4.7 (the 4.8 work has landed, just hasn't been released as of this writing)
this commit increments typescript to v4.9 for the project, and updates the dependabot configuration to not create a pull request for a version of typescript newer than 4.9.
the `@types/node` package for the karma test suite is updated as a part of this commit, as the currently installed version has the following error when being type checked by v4.9:
```
[ ERROR ]  TypeScript: ../node_modules/@types/node/globals.d.ts:114:13
Subsequent variable declarations must have the same type. Variable
'AbortSignal' must be …
```
=> feat(typescript): add support for typescript 4.9

src/utils/util.ts
This just adds a JSDoc comment to the utility function `createJsVarName`.
Noticed when working on #3876 that this function didn't have a JSDoc
Now it does!
=> docs(utils): add a JSDoc to `createJsVarName`

.github/dependabot.yml
`@types/node` gets suggested by dependabot to be upgraded for the `test/bundler` dir, when it should not (see #3878). 
- Closes #3878 
this commit adds versions 17 & 18 of `@types/node` to the ignore list for the `test/bundler` directory. we add these valuse because when we run these tests locally & in a continuous integration env, we inherit the version of node that is declared under the `volta` key in this project's root level `package.json` file. to prevent version skew either between the version of node and @types/node within bundler, we need to add this property to the dependabot configuration.
N/A, other than validating the YAML
=> chore(dependabot): ignore @types/node versions for test/bundler

scripts/bundles/compiler.ts, src/compiler/public.ts, src/compiler/transpile.ts
This moves the JSDocs for the `transpile` and `transpileSync` functions from `public.ts` to the file where the function definitions actually are. Those functions are then re-exported from the `public.ts` file to make sure anything importing from that file will continue to work correctly.
The JSDoc comments describing how these functions work aren't collocated with the function declaration.
Basically just moving some code from one place to another, there shouldn't really be any change in how things work.
=> chore(compiler): move JSDoc to function definitions in transpile.ts

src/utils/util.ts, test/end-to-end/src/components.d.ts, test/karma/test-app/components.d.ts
When #3525 merged it contained a list of JSDoc tags which should be suppressed from component-level generated documentation in typedef files. This commit updates that list to add some tags that Framework would not like to have show up all over the place.
Currently the JSDoc tags `@slot`, `@part` and `@virtualProp` are included in docstring output for components.
This suppresses them, in particular to minimize churn in Framework where these tags are very heavily used.
=> chore(util): update list of suppressed JSDoc tags to align with Framework

BREAKING_CHANGES.md, src/app-data/index.ts, src/client/client-patch-browser.ts, src/compiler/app-core/app-data.ts, src/compiler/bundle/core-resolve-plugin.ts, src/compiler/config/test/validate-config.spec.ts, src/compiler/config/validate-config.ts, src/compiler/output-targets/dist-hydrate-script/hydrate-build-conditionals.ts, src/compiler/output-targets/dist-lazy/generate-esm-browser.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts, src/testing/reset-build-conditionals.ts, src/utils/util.ts
This marks the config field as deprecated and also adds TODO comments for STENCIL-661, the ticket for removing the code itself.
We have support for a shim of `import()` which we'd like to remove at some point in the future.
The `dynamicImportShim` is now marked as deprecated, preparing the ground for us to remove it entirely later (and delete the code that implements the shim and so on).
=> chore(config): mark `config.extras.dynamicImportShim` as deprecated

BREAKING_CHANGES.md, src/app-data/index.ts, src/client/client-patch-browser.ts, src/client/client-patch-esm.ts, src/client/client-window.ts, src/client/polyfills/css-shim/css-parser.ts, src/client/polyfills/css-shim/custom-style.ts, src/client/polyfills/css-shim/index.ts, src/client/polyfills/css-shim/interfaces.ts, src/client/polyfills/css-shim/load-link-styles.ts, src/client/polyfills/css-shim/regex.ts, src/client/polyfills/css-shim/scope.ts, src/client/polyfills/css-shim/selectors.ts, src/client/polyfills/css-shim/template.ts, src/client/polyfills/css-shim/test/compiler.spec.ts, src/client/polyfills/css-shim/test/css-shim.spec.ts, src/client/polyfills/css-shim/test/init-css-shim.spec.ts, src/client/polyfills/css-shim/test/utils.spec.ts, src/client/polyfills/css-shim/utils.ts, src/compiler/app-core/app-polyfills.ts, src/compiler/config/test/validate-config.spec.ts, src/compiler/config/validate-config.ts, src/compiler/output-targets/dist-hydrate-script/hydrate-build-conditionals.ts, src/compiler/output-targets/dist-lazy/lazy-build-conditionals.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts, src/runtime/disconnected-callback.ts, src/runtime/styles.ts, src/runtime/update-component.ts, src/testing/platform/testing-platform.ts
This marks the `extras.cssVarsShim` field on the Stencil configuration interface as deprecated, and introduces TODO comments for removing all of the relevant code (that I could find).
We want to remove Stencil's built-in support for including polyfills for old browsers. Before we remove it, we want to mark fields for deprecation.
the field is renamed from `cssVarShim` to `__deprecated_cssVarShim`.
=> chore(config): mark `cssVarShim` as deprecated

BREAKING_CHANGES.md, src/app-data/index.ts, src/client/client-patch-browser.ts, src/compiler/app-core/app-data.ts, src/compiler/config/test/validate-config.spec.ts, src/compiler/config/validate-config.ts, src/compiler/optimize/optimize-js.ts, src/compiler/optimize/optimize-module.ts, src/compiler/output-targets/dist-hydrate-script/generate-hydrate-app.ts, src/compiler/output-targets/dist-hydrate-script/hydrate-build-conditionals.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts, src/testing/reset-build-conditionals.ts, src/testing/spec-page.ts
Stencil v3 will deprecate support for Safari 10, so we no longer need to
support this option. This commit marks it as deprecated, as a
preparation for
removing it later.
BREAKING CHANGES: the `safari10` field is now deprecated. Support for
Safari 10 has been dropped.
- https://github.com/ionic-team/stencil-site/pull/957
This deprecates the `safari10` field on `config.extras`.
Users of the `safari10` field should rename it to `__deprecated__safari10` and look to drop support for Safari 10 soon.
=> chore(config): mark extras.safari10 field as deprecated

src/cli/run.ts, src/compiler/config/test/validate-hydrated.spec.ts, src/compiler/config/test/validate-service-worker.spec.ts, src/compiler/config/validate-config.ts, src/compiler/config/validate-hydrated.ts, src/compiler/sys/config.ts, src/declarations/stencil-public-compiler.ts, src/testing/mocks.ts
This adds the `hydratedFlag` property to the `ValidatedConfig` object, meaning that the field must be present.
Note that this required a change to use null to signify a missing hydrateflag.
this is because when we are building the `ValidatedConfig` type we do
the following:
```ts
type RequireFields<T, K extends keyof T> = T & { [P in K]-?: T[P] };
```
If there is a type `P` in `K extends keyof T` where the type of `T[P]` is
`Foo | undefined` then unfortunately when we do `[P in K]-?: T[P]` we'll
set the output type to just `Foo`, so the type returned by
`RequireFields` for the field in question won't be unioned with `undefined`,
which was previously what we were doing here to try to signify a missing
`HydratedFlag` value.
Instead we can just use `null` which makes it through the `-?` bit. …
=> chore(config): add `hydratedFlag` to ValidatedConfig

src/runtime/profile.ts
This fixes an issue with performance profiling in Chromium 109.
See #3978 for details. Essentiall, in Chromium v109 there was a performance regression where calling the `performance.getEntriesByName` would result in very slow application performance. There is a workaround which consists in passing a second 'type' argument to the function. This PR just makes that change.
GitHub Issue Number: #3978
- performance is fixed in Chrome 109
Check out the reproduction case provided on #3978. Check that:
- if you run that case as-is in Chrome 109 the performance is quite slow (compared with, say, FF)
- if you build and then install Stencil based on this branch the performance is now …
=> fix(runtime): workaround for performance slowing in Chrome 109

src/compiler/output-targets/dist-hydrate-script/generate-hydrate-app.ts
When [generating a hydrateFactory](https://github.com/ionic-team/stencil/blob/main/src/compiler/output-targets/dist-hydrate-script/generate-hydrate-app.ts#L86), rollup may split the output into multiple files. As Stencil [only outputs the content of the first file](https://github.com/ionic-team/stencil/blob/main/src/compiler/output-targets/dist-hydrate-script/generate-hydrate-app.ts#L96) this results in a broken hydrate script. 
`/dist/hydrate/index.js`
```js
// ...
var _appFactoryEntry = require('./@app-factory-entry-5119d8cd.js');
require('punycode');
exports.hydrateApp = _appFactoryEntry.hydrateApp;
// ...
```
When running `stencil build --prerender`:
```
[39:02.7] …
```
=> fix(compiler): ensure rollup outputs a single file for hydrateFactory

src/compiler/output-targets/dist-lazy/lazy-output.ts
=> docs(dist-lazy): add a small note noting a value will be mutated

src/compiler/transpile/ts-config.ts, src/declarations/stencil-public-compiler.ts
This adds a JSDoc comment to the `getTsOptionsToExtend` function is `src/compiler/transpile/ts-config.ts`, previously it was not documented.
This also documents the purpose of the `excludeUnusedDependencies` config parameter.
This documents a previously-undocumented function.
no logic changes, just docs.
=> chore(compiler): add JSDoc to ts-config module

package-lock.json, package.json, scripts/bundles/sys-node.ts
We're currently using an old version of Webpack, which is preventing us from using Node 18 in our CI pipeline
this commit updates stencil version of webpack to v5. webpack is used in stencil for the purpose of bundling external dependencies (said deps can be found in `scripts/bundles/sys-node-bundle-cache` after a build).
in order to perform the migration the steps contained in https://webpack.js.org/migrate/5/ were followed. specifically:
- old typings were removed
- the webpack configuration was un-lined to validate the types of the object
- old node types, `process` and `Buffer` were removed, as they are no longer supported in v5 (and were unused to …
=> chore(deps): upgrade to webpack v5

.github/dependabot.yml, .github/workflows/test-analysis.yml, .github/workflows/test-component-starter.yml, .github/workflows/test-e2e.yml, .github/workflows/test-unit.yml, package-lock.json, package.json, test/bundler/package-lock.json, test/bundler/package.json
- https://github.com/ionic-team/stencil-site/pull/955
Supersedes: https://github.com/ionic-team/stencil/pull/3916
this commit increments the versions of node & npm `package.json#volta`.
this change sets a new baseline for the versions of npm and node that
will be used for the day-to-day development on the project.
to coincide with this change, node 18 has been added to the github
actions workflow.
starting with node 18, we started to have issues where bundler tests 
couldn't run (would fail to proxy the page being served). this happened
both locally and in CI. updating the karma dependencies resolves the
problem (although _why_ is unknown)
CI continues …
=> chore(ci): add node 18

src/compiler/sys/typescript/typescript-sys.ts, src/compiler/transformers/rewrite-aliased-paths.ts, src/compiler/transformers/test/rewrite-aliased-paths.spec.ts, src/declarations/stencil-private.ts, src/testing/jest/jest-runner.ts, src/testing/test-transpile.ts
This adds support for transforming path aliases in spec tests, using the transformer which was added in #4042. Adding such support also revealed a bug with the existing path transformer, notably that it did not produce a valid path for sibling modules. See the diff for a comment explaining the details.
Imports from modules aliases with `paths` in `tsconfig.json` don't work in spec tests.
GitHub Issue Number: fixes #3826
They do! This change reads the `transformAliasedImportPaths` option from the Stencil config and, if it is set to true, will transform such aliased modules to relative paths when the transpiler is being run by Jest. If the user does not set that config value to …
=> feat(testing): add support for transforming path aliases in spec tests

src/client/client-patch-browser.ts
Hey team, this is a very simple fix for [issue 2431](https://github.com/ionic-team/stencil/issues/2431). I was running into the same thing when trying to directly require ionic.cjs.js in my project.
=> fix(runtime): prevent null data-opts access

scripts/utils/options.ts, scripts/utils/test/options.spec.ts
This PR requires the following PR(s) to be approved first:
- https://github.com/ionic-team/stencil/pull/4097
Local Stencil builds (aka "Dev Builds") have some metadata associated with them that I think could be more valuable in terms of getting development builds into the hands of Stencil Users, the Ionic Framework, etc.
this commit changes the method used by the release scripts to generate
the build id and version number for "development builds", where a
"development build" is considered a build of stencil performed outside
using the `npm run release.*` scripts. this includes running `npm run
build` locally and in ci.
build id generation has changed …
=> chore(release): update build id, version generation

src/compiler/transformers/transform-utils.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts
This adds some JSDoc comments to interfaces and functions which relate to the docs-json output target which were previously undocumented. Some of these things aren't particularly intuitive if you don't know what they're for!
A good deal of functions and interfaces relating to the `docs-json` output target are not annotated or documented, and it's a bit confusing as a result to trace around and figure out what's going on.
A few more things are documented!
=> docs(docs-json): add JSDoc to things related to docs-json OT

scripts/bundles/helpers/jest/jest-preset.js, src/compiler/transpile/transpile-module.ts
This adds support for importing from ES modules (w/ the `.mjs` extension) in spec tests by ensuring that
1. files with such an extension are passed to the jest preprocessor (which then runs them through typescript)
2. our typescript helper for string-to-strong transpilation will emit `.mjs` files instead of just dropping them on the floor
Together these changes will allow running specs which import `.mjs` files.
closes #3251
See that issue for details, but in any Stencil version >2.14.0 spec tests will error if any file imports from an ES module with the `.mjs` extension.
This just makes a few small tweaks to ensure that such files are properly transpiled and included!
`.mjs` …
=> fix(test): support importing from ES modules in spec tests

src/compiler/config/test/fixtures/stencil.config2.ts, src/compiler/config/test/load-config.spec.ts, src/compiler/output-targets/dist-lazy/generate-lazy-module.ts, src/declarations/stencil-public-compiler.ts, test/bundler/component-library/stencil.config.ts
GitHub Issue Number: #4148
- `experimentalImportInjection` is deprecated
- Introduced `enableImportInjection` which does 1:1 what the now deprecated flag did (no logic changes, just naming)
-
stencil.config.ts: `experimentalImportInjection` should be replaced with `enableImportInjection` - the old flag will be removed at some point
- Ran all automatic tests in the repo
- Linked the project to our component library with both `enableImportInjection` enabled and disabled
(Documentation repo will receive a separate PR)
=> feat(enableImportInjection): add enableImportInjection flag

.github/workflows/README.md, .github/workflows/actions/publish-npm/action.yml, .github/workflows/release-dev.yml, scripts/utils/options.ts, scripts/utils/test/options.spec.ts
This PR adds the following commits from the `main` (v3) branch to the `v2-maintenance` branch:
- [test(release): add getOptions coverage](https://github.com/ionic-team/stencil/commit/e6668ac3862a516e67049d807b232a5f46997079) - [https://github.com/ionic-team/stencil/commit/e6668ac3862a516e67049d807b232a5f46997079](https://github.com/ionic-team/stencil/commit/e6668ac3862a516e67049d807b232a5f46997079)
- [chore(release): update build id, version generation](https://github.com/ionic-team/stencil/commit/aa9ddba5927f5d2abf7589270cdc9e303f261591) - [https://github.com/ionic-team/stencil/commit/aa9ddba5927f5d2abf7589270cdc9e303f261591](https://github.com/ionic-te …
=> chore(v2): port dev build infrastructure

src/declarations/stencil-public-compiler.ts, src/sys/node/node-sys.ts
the fs-event based file watcher that was shipped in typescript 4.9 does not play nicely with stencil in some cases. we've received error reports of the dev server:
- reloading as a result of continuous recompilation
- not reloading/recompiling projects on file changes
- crashing when files are removed
GitHub Issue Numbers:
- Closes #3952
- Closes #4011
- Closes #4044
this commit updates stencil to use the polling-based file watcher that was used prior to the typescript 4.9 upgrade. in ts 4.9, the ts compiler was updated to use filesystem events. since then, we've received reports of fs events not playing nicely with certain development environments. for this reason, we revert …
=> fix(compiler): use polling events in watch mode

src/declarations/stencil-public-compiler.ts, src/sys/node/node-sys.ts
the fs-event based file watcher that was shipped in typescript 4.9 does not play nicely with stencil in some cases. we've received error reports of the dev server:
- reloading as a result of continuous recompilation
- not reloading/recompiling projects on file changes
- crashing when files are removed
GitHub Issue Numbers:
- Closes #3952
- Closes #4011
- Closes #4044
this commit updates stencil to use the polling-based file watcher that was used prior to the typescript 4.9 upgrade. in ts 4.9, the ts compiler was updated to use filesystem events. since then, we've received reports of fs events not playing nicely with certain development environments. for this reason, we revert …
=> fix(compiler): use file system polling events in watch mode (stencil v2)

src/compiler/transformers/add-component-meta-proxy.ts, src/compiler/transformers/component-native/proxy-custom-element-function.ts, src/compiler/transformers/test/add-component-meta-proxy.spec.ts, src/compiler/transformers/test/proxy-custom-element-function.spec.ts
This fixes an issue (documented in #3434) where when using `@testing-libary/dom` to test a Stencil component wrapped with the React framework wrappers could produce an infinite loop that would cause the tests to fail.
The issue relates to an assumption that `@testing-library/dom` makes about the `.name` property on the constructor for a custom element. In particular, `@testing-library/dom` expects the property to be truthy here:
https://github.com/testing-library/dom-testing-library/blob/fb069c93983bc0300a6e1c91bdec5bf9443b5286/src/DOMElementFilter.ts#L198
When building with the `dist-custom-elements` output target we create an anonymous class expression and inline it into a call in the emitted JS to `proxyCustomElement`, like this:
```js
const MyComponent$1 = /*@__PURE__*/ …
```
=> fix(test): fix infinite loops w/ react and @testing-library/dom

src/compiler/transformers/component-native/native-component.ts, src/compiler/transformers/component-native/native-constructor.ts, src/compiler/transformers/create-event.ts, src/declarations/stencil-private.ts
`native-constructor.ts#updateNativeConstructor` is always called with its fourth formal argument
set to `true`. I came across this while working on the sourcemap race condition (STENCIL-301).
separating refactoring that out into a separate commit
this commit removes an unsed parameter from `updateNativeConstructor` in
`native-constructor.ts`. the function was always called with a value of
`true` for the `hasSuper` argument. with this commit, we remove it and
the related conditionals (as the conditional always evaluated to `true`.
the bodies of the conditionals have been inlined with the rest of the
code
this commit also adds jsdoc to relevant parts of …
=> refactor(compiler): remove unused parameter

scripts/prompts.ts, scripts/release.ts, scripts/test/release.spec.ts, scripts/utils/options.ts
We're in the process of enabling CI-based deployments. Today, this is a manual process that (at a high level), requires two steps:
1. Preparing the release - where we bump the version, generate the changelog, run the tests, etc.
2. Run the release - publish the commit to GitHub, push tags to GH+NPM, create a GH release, etc.
As a part of allowing publishes to occur in CI, those two steps need to be combined. However, the second step ('Run the release') requires a user to answer a few prompts in a terminal window. This limits our options for code reuse when we programmatically prepare a release.
This commit assumes that https://github.com/ionic-team/stencil/pull/4172 has landed, …
=> chore(release): separate prompts from release tasks

src/compiler/transformers/add-component-meta-proxy.ts
this commit combines two pre-existing functions,
`addComponentMetadataProxy` and `createComponentMetadataProxy`. the former is removed, and the creation of an expr statement is moved into the latter.
`createComponentMetadataProxy` is no longer needlessly exported, as it is currently not part of the stencil public api, nor is it directly under test
This work was originally a part of https://github.com/ionic-team/stencil/pull/4200, as I had been considering a fix that changed some of the code in _this_ pull request. I decided to go another route, and felt these changes didn't necessarily belong in #4200
=> refactor(compiler): remove redundant function call

src/compiler/output-targets/dist-custom-elements/custom-elements-types.ts, src/compiler/output-targets/test/custom-elements-types.spec.ts
The `index.d.ts` file for `dist-custom-elements` when setting `generateTypeDeclarations: true` and `customElementsExportBehavior: 'single-export-module'` would not include exported typedefs for the components' `defineCustomElement` functions.
GitHub Issue Number: Closes #4093 
The `index.d.ts` file now includes an export for `defineCustomElement` for each component in the bundle
Verified output in a Stencil starter project and in a consuming application (Angular)
Updated unit tests for the affected code.
=> fix(compiler): write exports for defineCustomElement typedefs

package-lock.json, src/cli/logs.ts, src/compiler/build/compiler-ctx.ts, src/compiler/build/watch-build.ts, src/compiler/output-targets/dist-custom-elements/index.ts, src/compiler/output-targets/output-utils.ts, src/compiler/transformers/add-imports.ts, src/compiler/transformers/component-native/native-component.ts, src/compiler/transformers/component-native/native-constructor.ts, src/compiler/transformers/component-native/tranform-to-native-component.ts, src/compiler/transformers/core-runtime-apis.ts, src/compiler/transformers/remove-static-meta-properties.ts, src/compiler/transformers/test/core-runtime-apis.spec.ts, src/compiler/transformers/test/native-constructor.spec.ts, src/compiler/transformers/transform-utils.ts, src/compiler/transpile/transpiled-module.ts, src/declarations/stencil-private.ts, src/sys/node/node-sys.ts, src/testing/mocks.ts
We have no debug logging for watching builds (which is why I'm adding it 😉) 
this commit is a follow up to https://github.com/ionic-team/stencil/pull/4146. when debugging the file watcher, it's valuable to know what files have been perceived as added/updated/etc. for #4146, we created dev-builds with additional logging statements to help diagnose the issue. in this commit, we add more refined debugging statements that attempt to balance providing useful information while not spamming the output with logging statements.
when starting a dev server, the version of stencil has been added to the `[LOCAL DEV]`. starting with …
=> chore(compiler): add debug statements for file watching

scripts/prompts.ts, scripts/release.ts, scripts/test/prompts.spec.ts, scripts/test/release.spec.ts
We currently mutate an argument to our prompting functions when preparing/performing a release.
this commit eliminates return parameter usage in the release scripts. with this commit, the `opts` argument provided to the prepare-release and release prompting functions shall no longer be mutated by either of them.
to accomplish this, two new types are introduced - `NormalizedPrepareResponses` and `NormalizedReleaseResponses`. both types are intended to be returned by their respective prompting functions and serve as the source of truth when their is user choice (e.g. semver version to use, npm tag) involved with a release. to further this goal, new …
=> chore(release): eliminate return argument usage

.github/workflows/release-production.yml
stencil is manually published. this commit does not enable prod releases, but moves the needle forward.
this commit creates the stub workflow for ci-based stencil releases. it is limited in it's functionality in that it accepts a named semver version and tag from the github, and echoes the input back to the user.
the motivation for this stub workflow (i.e. land it in `main`) is that the release workflow will require the following steps:
1. generate changelog, bump versions in package.json + package-lock.json
2. commit changes in git, push them to github
3. publish tags to git and npm
when testing a more fleshed version of this workflow out, it's …
=> chore(ci): create initial workflow for prod releases

src/runtime/vdom/vdom-render.ts
This is a really small change that I meant to do before, I think when I added a bunch of JSDoc to this file in #3931 but I realized reading through this recently that this function had a not-great name and I thought hey, let's rename that! And that's the story of this PR 📖
None, renaming and documentation change only.
=> docs(runtime): add JSDoc to and rename `callNodeRefs`

src/runtime/update-component.ts
This documents and slightly simplifies code which uses `Promise.then` to enqueue a series of rerendering-related actions which need to take place when a component gets updated. In particular, the previous implementation used a helper function called `then` which was a) `any`-typed and b) not necessary.
This also adds JSDoc to `dispatchHooks` and some explanatory inline comments.
This shouldn't change anything about how components are rendered, but is basically just a small simplification of a bit of code I read through recently and found confusing.
=> refactor(runtime): document Promise-based queueing in dispatchHooks

scripts/release-prompts.ts, scripts/test/release-prompts.spec.ts
this commit fixes a regression introduced in https://github.com/ionic-team/stencil/pull/4235. the commit made the assumption that the npm tag will always be present: https://github.com/ionic-team/stencil/commit/d19538eb33b297c14419e94b73c322a9c790c67a#diff-a8c342d5def4847ce523d42113bc62856f35e802a444ec746839c39018f62017L180-R229. when in fact that is not the case. an npm tag is assumed to be the 'latest' when it is empty. with this commit, the precedence of npm tags is updated to prefer specified tags, a valid npm tag, then null (previously a valid npm tag, a specifed tag, then 'UNKNOWN') was preferred). this allows for a specified tag to continue to …
=> chore(release): fix tagging behavior for prod

src/compiler/config/validate-service-worker.ts, src/declarations/stencil-public-compiler.ts
This adds JSDoc comments to validate-service-worker.ts, and does a (very light) refactor just moving around a bit of logic.
This service worker configuration is using the Workbox library for generating a caching service worker automatically, but at present we do not depend on the published types for Workbox. Since there is an compatibility issue using web worker typings alongside the DOM typings we're already using (by setting the `lib` property in `tsconfig.json`) we can't depend on those published typings directly until we can separately set compilation options in the code (using project references, for instance). As a workaround the current typings for the options interface for Workbox are copied into the code.
Please check …
=> chore(compiler): add JSDoc to validate-service-worker.ts

src/runtime/initialize-component.ts, src/runtime/test/initialize-component.spec.tsx, src/runtime/test/tsconfig.json
GitHub Issue Number: #4221 
The component initialization code did not execute for non-lazy builds if the component did not have styles associated with it.
The conditional check to init component is no longer gated by checks for lazy builds, styles, etc. The component should be initialized in all scenarios (unless it has already been initialized)
Manually tested w/ lazy and non-lazy builds.
Added an automated test for the `initializeComponent` code. I wasn't able to add tests for all the previous conditions we _used_ to gate because the tests only use lazy builds
=> fix(runtime): initialize custom elements even when there is no styles

.github/workflows/test-component-starter.yml
See new behavior section
this commit adds a temporary pinning of `@types/babel__traverse` to the ci workflow to get it to pass again. with v7.18.4 of the library, a change was introduced that does not type check properly. reverting to using 7.18.3 (where this library is a sub-dependency of jest packages) is a temporary workaround.
this was chosen instead of pinning the library in the component starter, as we have no way to educate/inform folks that the pin is no longer necessary.
dependabot/renovate was not updated in this commit. the hope is that we either:
1) revert this this week
2) don't have to apply it (if fixed in the next few hours)
CI begins to …
=> chore(ci): temporarily install specific @types/babel__traverse

src/testing/jest/jest-setup-test-framework.ts, src/testing/jest/test/jest-setup-test-framework.spec.ts
GitHub Issue Number: #4053 
The `disconnectedCallback` will not be called for a component after the test has executed.
This change will call the `disconnectedCallback` as a part of the `afterEach` for each test that is defined when constructing the Jest test environment.
**NOTE:** This behavior will not call the `disconnectedCallback` for child components. For some reason, the MockDoc implementation does not have reference to child/nested components. So, only the `disconnectedCallback` for `my-component` would be called in the following example:
```html
// my-component.tsx
<div>
<p>My component</p>
<my-child-component></my-child-component>
</div>
```
Tested this with the …
=> fix(testing): jest component disconnected callback

.github/workflows/test-browserstack.yml, .github/workflows/test-e2e.yml
There are a few flaky CI jobs that, when they fail, cause pain in the development cycle due to waiting for CI to pass.
this commit wraps the e2e and browserstack tests in the
`nick-fields/retry` action. the goal of this is to provide a temporary &
quick fix for these two test commands, which are flaky (i.e. they may
fail due to reasons outside of changes made in a given commit).
both are configured to try each command three times. should the command
file three times, the job is marked as a failure. this differs from
today's behavior, in that a job is marked as a failure on one.
each is given a timeout configuration that is approximated based on how
long …
=> chore(ci): retry flaky tests

src/utils/test/util.spec.ts, src/utils/util.ts
=> chore(snc): fix a few SNC errors in `src/utils/test/util.spec.ts

renovate.json5
See "New Behavior" below
this commit updates the schedule that renovate runs at. previously, it
was set to create pull requests at 7 am (utc) until https://github.com/ionic-team/stencil/pull/4324.
this was problematic, as it would only allow renovate to create pull
requests at 7 am. with the new schedule, pull requests may be created
before 11am utc on any weekday. this equates to:
- 10 pm to 7 AM (eastern)
- 9 pm to 6 am (central)
- 8 pm to 5 am (mountain)
- 7 pm to 4 am (western)
by having an 11 hour period to open pull request outside of working
hours, the hope is that prs will be created without spamming the team
throughout the day
N/A - we'll have …
=> chore(repo): update renovate schedule

renovate.json5
Renovate will try to upgrade us to the latest version of minimatch, which we cannot support in Stencil v3 due to Node support constraints
this commit is created in direct response to https://github.com/ionic-team/stencil/pull/4346. in #4346, renovate attempted to bump minimatch from v5->9. this led to build (in ci) to fail. to try to get stencil on a slightly newer version of the project, rwaskiewicz attempted to upgrade the patckage from v5->6, hoping that at least one major version increment was possible.
however, in minimatch v6, default exports for commonjs modules have changed. stencil is reliant on `@types/glob@8`, which assumes that the default export found in `minimatch@5` will be present (and type checking fails). unfortunately, we are pinned to our …
=> chore(renovate): add minimatch to ignore list

src/declarations/stencil-private.ts, src/runtime/profile.ts, src/runtime/update-component.ts
This makes the `$hostElement$` property required on the `HostRef` interface. I believe this is actually in line with how this property is already used, since I can't find an instance where we create a `HostRef` without supplying a value for `$hostElement$`. Since this property is accessed a lot throughout the runtime this drops a number of SNC errors.
-
=> chore(snc): fix SNC errors relating to `HostRef.$hostElement$`

.github/workflows/test-analysis.yml, .github/workflows/test-component-starter.yml, .github/workflows/test-e2e.yml, .github/workflows/test-unit.yml, package-lock.json, package.json, renovate.json5, src/utils/test/util.spec.ts
This adds support for node 20 by
- adding it to the node version matrix for CI tests
- bumping the version we specify via Volta in `package.json`
- bumping the version of `@types/node`
- editing the renovate configuration to allow for newer versions of `@types/node`
-
=> add support for node 20

src/compiler/plugin/plugin.ts
This just fixes some SNC errors in `src/compiler/plugin/plugin.ts`, mainly by switching a few type annotations to instead use the `satisfies` operator and also adding some null property access checks w/ the nullish coalescing operator.
=> chore(snc): fix some SNC errors in src/compiler/plugin/plugin.ts

src/compiler/config/test/validate-output-www.spec.ts
We can drop a few here by adding `as OutputTargetWww` casts in a few places.
-
=> chore(snc): drop a few SNC errors from validate-output-www.spec.ts

src/compiler/config/test/validate-testing.spec.ts
Our testing config validation code is missing code coverage. As a part of exploring the refactor to start decoupling testing code from Stencil, I wanted to test these things to verify my understanding of things.
There are 2 commits in this PR:
- the first groups existing "free standing" tests into `describe` blocks for the property they test
- adds tests for any properties we're missing
I recommend reviewing them independently, as the diffs are much nicer (IMO)
I traced/debugged each of these (well, most of them) in a node debugger to verify they did what I claim they do
1. This PR depends on https://github.com/ionic-team/stencil/pull/4375, which needs to land first
=> test(validate-testing): evaluate property checks 

.github/ionic-issue-bot.yml, CONTRIBUTING.md, readme.md
The links point to the Slack community.
- [Stencil is now using Discord instead of Slack](https://twitter.com/stenciljs/status/1658561079767887873). The links now point to the Discord server.
Tested that the new link takes you to the Discord.
=> chore(repo): change slack links to discord links

jest.config.js, package-lock.json, package.json, scripts/bundles/plugins/typescript-source-plugin.ts, src/compiler/sys/typescript/typescript-sys.ts, src/compiler/transformers/test/convert-decorators.spec.ts, src/compiler/transformers/test/parse-styles.spec.ts, src/compiler/transformers/test/proxy-custom-element-function.spec.ts, src/compiler/transformers/test/rewrite-aliased-paths.spec.ts, src/compiler/transformers/test/utils.ts, src/compiler/transpile/run-program.ts, test/end-to-end/tsconfig.json, test/ionic-app/tsconfig.json, test/karma/constants.js, test/karma/karma.config.js, test/karma/package-lock.json, test/karma/package.json, test/karma/test-app/reflect-single-render/karma.spec.ts, test/karma/test-app/scoped-slot-text-with-sibling/karma.spec.ts, test/karma/test-app/scoped-slot-text/karma.spec.ts, test/karma/tsconfig.json, types/ionic-prettier-config.d.ts
This upgrades the version of TypeScript bundled with Stencil to 5.0.4. In order to support the upgrade we have to do a few things:
- edit the Rollup plugin we use to bundle typescript to account for changes in how typescript is bundled now (this changed for the 5.0.0 release)
- fix tests which assert on e.g. transformer output to account for small, mostly one-character differences in output with the strings we have in tests
- move the location where we prevent `.d.ts` files being written to disk during `stencil build` for test files
See also a documentation PR here: https://github.com/ionic-team/stencil-site/pull/1117
-
-
-
=> feat(typescript): upgrade to TypeScript 5

src/mock-doc/test/html-parse.spec.ts
We can drop a fair few in here by adding optional property operators.
-
=> chore(snc): fix snc errors in src/mock-doc/test/html-parse.spec.ts

src/compiler/transformers/test/parse-props.spec.ts
this commit updates the test for prop parsing via `transpileModule` to account for the fact that returned fields may be `undefined`
=> chore(snc): remove snc violations from parse-props.spec

src/compiler/sys/tests/in-memory-fs.spec.ts
this commit removes the `strictNullChecks` violations found in `in-memory-fs.spec.ts`. there are two types of changes found within this file:
1. `fsItem`, a helper function in the suite, has been updated to set it's default values to `undefined` to adhere to `Partial<FsItem>`, fixing assignability issues with setting each field to null
2. retrieval of entries from the `items` map use optional chaining. this was deemed safe as we are not asserting against `undefined` in any of the `get` calls in said tests
=> chore(snc): remove in-memory-fs.spec snc violations

.github/workflows/test-browserstack.yml
ci won't run on the v4 dev branch
this commit enables browserstack for the v4 development branch
N/A
=> chore(ci): enable ci for v4 dev

BREAKING_CHANGES.md, src/app-data/index.ts, src/client/client-patch-browser.ts, src/compiler/app-core/app-data.ts, src/compiler/bundle/core-resolve-plugin.ts, src/compiler/config/test/validate-config.spec.ts, src/compiler/config/validate-config.ts, src/compiler/output-targets/dist-hydrate-script/hydrate-build-conditionals.ts, src/compiler/output-targets/dist-lazy/generate-esm-browser.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts, src/testing/reset-build-conditionals.ts, src/utils/util.ts, test/jest-spec-runner/stencil.config.ts, test/karma/stencil.config.ts, test/todo-app/stencil.config.ts
Remove the dynamic import shim that was marked as deprecated in v3. This is a precursor to #4421 
-
=> chore(compiler): remove dynamicImportShim

BREAKING_CHANGES.md, src/app-data/index.ts, src/client/client-patch-browser.ts, src/compiler/app-core/app-data.ts, src/compiler/config/test/validate-config.spec.ts, src/compiler/config/validate-config.ts, src/compiler/optimize/optimize-js.ts, src/compiler/optimize/optimize-module.ts, src/compiler/output-targets/dist-hydrate-script/generate-hydrate-app.ts, src/compiler/output-targets/dist-hydrate-script/hydrate-build-conditionals.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts, src/testing/reset-build-conditionals.ts, src/testing/spec-page.ts, test/jest-spec-runner/stencil.config.ts, test/karma/stencil.config.ts, test/todo-app/stencil.config.ts
Remove the safari10 extras option that was marked as deprecated in v3. This builds upon #4420 
-
=> chore(compiler): remove safari10 extras flag

.github/workflows/build.yml, .github/workflows/lint-and-format.yml, .github/workflows/main.yml, .github/workflows/test-analysis.yml, .github/workflows/test-browserstack.yml, .github/workflows/test-bundlers.yml, .github/workflows/test-component-starter.yml, .github/workflows/test-e2e.yml, .github/workflows/test-unit.yml
this commit updates all workflows whose status is reported to gate on `main` to include the `merge_group` event trigger. the github documentation[1] states:
> If your repository uses GitHub Actions to perform required checks on
> pull requests in your repository, you need to update the workflows
> to include the merge_group event as an additional trigger. Otherwise,
> status checks will not be triggered when you add a pull request to a
> merge queue. The merge will fail as the required status check will
> not be reported.
it's not abundantly clear if this is needed for reusable workflows explicitly. `merge_group` is added in this commit to avoid the need to configure this feature via multiple prs
[1]: https://docs.github.com/en/repositories/configuring-branches-and …
=> chore(ci): update workflows for merge queue

src/compiler/output-targets/dist-custom-elements/index.ts, src/compiler/transformers/component-lazy/lazy-component.ts, src/compiler/transformers/component-native/native-component.ts, src/compiler/transformers/component-native/proxy-custom-element-function.ts, src/compiler/transformers/decorators-to-static/convert-decorators.ts, src/compiler/transformers/decorators-to-static/convert-static-members.ts, src/compiler/transformers/remove-static-meta-properties.ts, src/compiler/transformers/static-to-meta/component.ts, src/compiler/transformers/test/convert-static-members.spec.ts, src/compiler/transformers/test/parse-members.spec.ts, src/compiler/transformers/test/proxy-custom-element-function.spec.ts, src/compiler/transformers/test/transpile.ts, src/compiler/transformers/update-component-class.ts, src/compiler/types/tests/ComponentCompilerMeta.stub.ts, src/declarations/stencil-private.ts, test/karma/test-app/components.d.ts, test/karma/test-app/static-members/README.md, test/karma/test-app/static-members/index.html, test/karma/test-app/static-members/karma.spec.ts, test/karma/test-app/static-members/static-members-separate-export.tsx, test/karma/test-app/static-members/static-members-separate-initializer.tsx, test/karma/test-app/static-members/static-members.tsx
A component like the following will fail to compile:
```tsx
import { Component, h } from '@stencil/core';
@Component({
})
private static myVar = "input";
render() {
console.log(MyComponent.myVar);
return (<div></div>);
}
}
```
With the following error:
```console
[ ERROR ]  Rollup: Parse Error: <FILE_PATH>
Duplicate export 'MyComponent' (Note that you need plugins to
import files that are not JavaScript) Error parsing: <FILE_PATH>
```
GitHub Issue Number: #4424
this commit fixes a bug where static class members that are initialized
on a stencil component result in 2 `export` statements of a component
class being generated. as a result of 2 `ExportDeclaration`s being
created, the compilation process will fail.
this fix involves detecting …
=> fix(compiler): handle ts 5.0 static members

.github/workflows/main.yml, .github/workflows/test-browserstack.yml
this commit updates our ci workflow to run against the `stencil/v4-dev` branch when the aforementioned branch is pushed to
N/A
=> chore(ci): run ci against stencil/v4-dev on push

package-lock.json, package.json, scripts/bundles/plugins/typescript-source-plugin.ts, scripts/bundles/sys-node.ts, scripts/license.ts, src/compiler/sys/stencil-sys.ts, types/path-browserify.d.ts
This removes some dependencies which I believe to be unused and / or unnecessary after the in-browser compilation support delete (#4317)
Good to make sure that Stencil builds and can be used to build projects like Framework
=> remove unused dependencies after in-browser compilation delete

test/karma/test-app/delegates-focus/karma.spec.ts
starting on 2023.06.12, browserstack started to use microsoft edge 114.0.1823.37. a test that had previously passed began to fail. the test that is skipped in this commit is that test. we were unable to reproduce this locally on macos and windows with the latest version of edge (114.0.1823.42). the hope is that browserstack will move to a newer version of edge in the next day or so to render this change obsolete
-
=> test(delegatesFocus): skip delegatesfocus test

src/runtime/update-component.ts
This fixes an issue with a check used in `updateComponent` to enqueue asynchronous updates (implemented with async functions) to components. In particular, if the global `Promise` object is patched such that it is not equal to the native `Promise` object returned by, for instance, an `async` function, which will return the native, unpatched object even if `window.Promise` has been overwritten.
A previous change in #4250 made a change such that we did a check like this:
```ts
maybePromise instanceof Promise
```
The problem is that if `maybePromise` is the return value of an async function, like
```ts
const foo = await something();
```
and `window.Promise` has been overwritten then this check will unfortunately fail unexpectedly.
The fix is just to first check `instanceof` and then add a …
=> fix(runtime): issue with update-component and patched Promise

src/declarations/stencil-public-runtime.ts
Using 'autoComplete' attributes causes type errors like so:
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/2882
we accept 'on' or 'off' for the attribute
I spun up a component library `npm init stencil component attr-test` and added the text-area elements you see in the screenshot above. I then built + packed this library, and installed it. After installing it, type errors only occur on invalid values:
=> fix(runtime): add autocomplete to textarea

src/compiler/docs/generate-doc-data.ts, src/compiler/docs/readme/markdown-parts.ts, src/compiler/docs/readme/markdown-slots.ts, src/declarations/stencil-public-docs.ts
this commit adds JSDoc to the types and functions that relate to Shadow Parts and JSDocs. it also corrects a typing error with Shadow Parts, where the typing for Slots was used accidentally
N/A
=> refactor(docs): add jsdoc to parts, slots

test/end-to-end/package-lock.json, test/end-to-end/package.json, test/hello-world/package-lock.json, test/hello-world/package.json, test/karma/test-invisible-prehydration/package.json, test/karma/test-sibling/package.json
Our Volta configs don't properly propagate/get picked up by subdirectories
this commit propagates the volta configuration in `test/` subdirectories. `test/karma/` subdirectories extend from `test/karma/package.json`, and all others extend from the project's root level `package.json`.
all v1 lockfiles in `test/*` have been bumped to v2
All `build.*` subcommands continue to build successfully (they can find the correct `package.json` file specifed in the Volta config).
This is a spin off of the work we planned to investigate volta subshells. The work we originally intended to do was done by myself/Tanner [in this commit](https://github.com/ionic-team/stencil/pull/4472/commits/50b1bed285a1b93620a113ee1a94844b587a8888) of #4472. In made more sense for that body of …
=> chore(tests): propagate volta to test/

src/compiler/sys/environment.ts, src/compiler/sys/typescript/typescript-sys.ts, src/compiler/transpile/transpile-module.ts
This just removes a bit of redundant code from `src/compiler/sys/environment`, in particular the `getCurrentDirectory` function which in a node environment is just an alias for `process.cwd`.
For this I think it would be good to just make sure that a Stencil project like Framework will still build correctly and so on.
=> chore(compiler): remove `getCurrentDirectory` from `sys/environment`

src/cli/task-generate.ts, src/cli/task-test.ts
You should be able to use the generation task as normal!
=> chore(cli): remove browser-specific behavior from the generate and test tasks

src/compiler/transformers/rewrite-aliased-paths.ts, src/compiler/transformers/test/rewrite-aliased-paths.spec.ts
This fixes an issue (STENCIL-840) which is mentioned here: https://github.com/ionic-team/ionic-framework/pull/27417#discussion_r1187779290
The problem is that for _certain_ aliased paths more of the resolve filepath is getting cut off than intended. In the example referenced in the discussion above, for instance, the resolved path should look something like `../native/keyboard` but instead it looks like `../native/keyboa`.
In `rewriteAliasedSourceFileImportPaths` we rewrite aliased paths by basically:
1. resolving the full path to the aliased module (so e.g. `@utils` is resolved to `src/utils/index.ts`)
2. calculating the relative path from the importing module (where there is an import like `import { foo } from '@utils';`). This might look something like `../../utils/index.ts`.
3. …
=> fix(compiler): fix issue with aliased paths getting cut off

BREAKING_CHANGES.md, src/compiler/build/write-build.ts, src/compiler/cache.ts, src/declarations/stencil-public-compiler.ts, src/screenshot/connector-base.ts
Caching was disabled in [this commit](https://github.com/ionic-team/stencil/commit/63595bc540db9aa85295f5a8dc8738beb2a37611#diff-a2a3c503f6a2b9ee197d01f14954b0f59a14820ed2b30cd6046e92d5d233e446). 
This commit re-enables build caching and makes a few updates to not conflict with caching when using a screenshot connector.
Automated unit and e2e tests continue to pass.
Did quite a bit of manual benchmarking against Ionic framework. Results can be found [here](https://ionic-cloud.atlassian.net/browse/STENCIL-848?focusedCommentId=21008)
Huge thanks to @George-Payne for pointing this out and doing the work to get this moving in [his PR](#3456)!
This branch/PR was created as an easy means of porting his work over to an updated version of Stencil
=> fix(compiler): re-enable build caching

src/compiler/bundle/bundle-interface.ts, src/compiler/bundle/typescript-plugin.ts, src/compiler/output-targets/dist-custom-elements/index.ts, src/compiler/output-targets/dist-hydrate-script/bundle-hydrate-factory.ts, src/compiler/output-targets/dist-lazy/lazy-output.ts, src/compiler/transpile/run-program.ts
In very specific circumstances, Stencil might not detect the correct `h` and `Host` functions as a result of transforming import paths specified in `tsconfig.json#paths` (see testing section).
this commit reorders the transformations run for rewriting paths to
modules in import statements.
previously, modules in import statements would be rewritten based on
the contents of `tsconfig.json#paths` before any other transformation
was run. this would conflict with the `updateStencilCoreImports`
transformation if `@stencil/core` (or any of its valid subpaths) were
listed in `tsconfig.json#paths`. this would cause the wrong versions of
helpers such as `h` and `Host` to be picked up when a project used the
`--prerender` flag on a component that imported either of the …
=> fix(compiler): reorder tsconfig#path transforms 

package-lock.json, test/docs-json/docs.d.ts
**DO NOT SQUASH**
When we rebased `stencil/v4-dev` against `main`, I found two small issues:
1. we hadn't propagated `engines` changes back to `package-lock.json`
2. due to two separate efforts, one in `main` and one in `stencil/v4-dev`, we had an out of date `.d.ts` generated file as a result of the rebase
the latter is causing CI to fail, but I figured why not just knock 2 out now and merge them as 2 distinct commits?
this commit propagates the changes to the `engines` field that were made
to `package.json` in https://github.com/ionic-team/stencil/pull/4472
this commit propagates jsdoc changes that were landed in
https://github.com/ionic-team/stencil/pull/3683 into the `main` branch.
`stencil/v4-dev` did not include these changes initially, so when we
rebased …
=> chore(v4): post-rebase fixups

BREAKING_CHANGES.md, src/compiler/config/outputs/validate-collection.ts, src/compiler/config/outputs/validate-dist.ts, src/compiler/config/test/validate-config.spec.ts, src/compiler/config/test/validate-output-dist-collection.spec.ts, src/compiler/config/test/validate-output-dist.spec.ts, src/compiler/config/test/validate-service-worker.spec.ts, src/compiler/config/validate-config.ts, src/compiler/output-targets/test/output-targets-collection.spec.ts, src/declarations/stencil-public-compiler.ts, src/testing/mocks.ts, test/karma/test-sibling/stencil.config.ts
the `transformAliasedImportPaths` and `transformAliasedImportPathsInCollection` configuration fields are opt-in (set to `false`) by default.
this commit updates the default values for the
`transformAliasedImportPaths` and
`transformAliasedImportPathsInCollection` configuration fields. both are being updated to be set to `true` if neither a `true` nor `false` value is provided (previously `false` if `false` or nothing was provided).
the latter of the two is used to set the former for, hence its new default.
by setting both of these new defaults to `true`, the hope is that stencil configuration will be simplified for projects using `paths` in their `tsconfig.json`
BREAKING CHANGE: `transformAliasedImportPaths` and `transformAliasedPathsInCollection` both default to …
=> feat(config): set new defaults for transformAliasedImportPaths

src/compiler/types/tests/validate-package-json.spec.ts, src/compiler/types/validate-build-package-json.ts
The `package.json` validation for the `collection` field does not use a normalized path for the comparison. This can result in a warning message to set the field to the value that already exists (can be seen by using the stock Stencil component starter)
The recommended path gets normalized for the string comparison of the existing path and recommended path.
Tested using the component starter.
1. Create a new Stencil project, run `npm i` and `npm run build`. Notice the warning message related to the `collection` field recommends setting the value that already exists in the `package.json`
2. Build and pack this branch. Install in the starter project
3. Run `npm run build` and notice the warning message no longer appears.
4. You can also change the `collection` field …
=> fix(compiler): normalize recommended `collection` path for `package.json` validation

src/compiler/transformers/test/parse-props.spec.ts, src/compiler/transformers/transform-utils.ts
A bit of the code added in #4212 incorrectly assumed a value wouldn't be falsy
You should be able to build and install this in framework and then run `npm run test.spec` without errors. additionally, the output from the `docs-json` output target in `docs/core.json` shouldn't change.
=> fix(compiler): address when a home module cannot be found

src/compiler/transformers/component-native/native-constructor.ts, src/compiler/transformers/core-runtime-apis.ts, src/compiler/transformers/test/core-runtime-apis.spec.ts, src/compiler/transformers/test/native-constructor.spec.ts, test/karma/test-app/custom-elements-delegates-focus/karma.spec.ts
this commit fixes a bug where projects using the `dist-custom-elements`
output target with `externalRuntime: false` would receive the following
error when building their project:
```
[ WARN  ]  Bundling Warning SOURCEMAP_ERROR
Error when using sourcemap for reporting an error: Can't resolve original location of error.
```
the cause of this error was attempting to import a function,
`attachShadow` that is no longer exported from the runtime bundle (as of
https://github.com/ionic-team/stencil/pull/3117). to date, this has not
had an effect on stencil (as the import gets treeshaken away). however,
when trying to generate sourcemaps for a project using this
configuration would cause a mismatch between what was expected to be in
the produced …
=> fix(compiler): sourcemap generation without ext runtime

src/declarations/stencil-public-compiler.ts
`namedExports`, a property on Stencil's `commonjs` configuration, is no longer honored by the rollup commonjs plugin
GitHub Issue Number: Fixes: #2523
this commit deprecates the `namedExports` field on the `BundlingConfig` interface. `@rollup/plugin-commonjs` no longer honors this field as of https://github.com/rollup/plugins/commit/5d2dcf433aaa65d7ebf93d210cac67011fefe29f.
STENCIL-867
Deprecation is now picked up in editors:
=> fix(rollup-config): deprecate BundlingConfig#namedExports

src/declarations/stencil-public-runtime.ts
Stencil improperly types `'color-interpolation-filter'` attribute values. It causes TypeScript to error when 'sRGB' or 'linearRGB' are provided, both of which are valid.
GitHub Issue Number: Fixes: https://github.com/ionic-team/stencil/issues/3354
this commit updates the typings of
`SVGAttributes#color-interpolation-filter` to match the current spec, which states the only accepted values are 'auto', 'sRGB' and 'linearRGB'.
this commit renames 's-rGB' to 'sRGB' and 'linear-rGB' to 'linearRGB'. it also removes 'inherit'.
it is believed this was done by accident in a regex-based replacement of camelCased properties to kebab-cased attributes in 667597dd
Before applying this change:
After:
=> fix(runtime): properly type color-interpolation-filter

src/compiler/config/test/validate-testing.spec.ts
this commit adds tests for valdiating stencil's testing configuration when no flags are provided to the testing validation function.
this changeset was intended to be added in
https://github.com/ionic-team/stencil/pull/4384, but for some reason was missed
=> test(validate-testing): test when no flags are provided

src/compiler/transformers/component-native/native-component.ts, src/compiler/transformers/test/native-constructor.spec.ts
see 'new behavior' and https://github.com/ionic-team/stencil/issues/4260
GitHub Issue Number: Fixes: #4260
this commit fixes an issue where a stencil project that use both the `dist-custom-elements` and `dist-hydrate-script` output targets would see the following error when building their project (with sourcemaps enabled):
```
[ WARN  ]  Bundling Warning SOURCEMAP_ERROR
Error when using sourcemap for reporting an error: Can't resolve original location of error.
```
this commit resolves this error by ensuring the `HTMLElement` core runtime API used by `dist-custom-elements` no longer interferes with the generated code for `dist-hydrate-script`. this is accomplished by using the output-target-specific runtime api slots introduced in #4200. this prevents the `HTMLElement` import from …
=> fix(compiler): sourcemap errors for dist-custom-elements + dist-hydrate-script

src/compiler/config/transpile-options.ts, src/compiler/optimize/autoprefixer.ts, src/compiler/prerender/prerender-worker.ts, src/compiler/sys/environment.ts
Now that we're node-only for compiling components we don't need this any longer (or, put another way, it's just become an alias for `require` anyway)
-
=> refactor(compiler): remove requireFunc

src/compiler/build/build-finish.ts, src/compiler/config/load-config.ts, src/compiler/optimize/autoprefixer.ts, src/compiler/sys/environment.ts, src/compiler/sys/fetch/fetch-utils.ts, src/compiler/sys/fetch/tests/fetch-module.spec.ts, src/compiler/sys/node-require.ts, src/compiler/sys/resolve/resolve-module-async.ts, src/compiler/sys/resolve/resolve-module-sync.ts, src/compiler/sys/resolve/resolve-utils.ts, src/compiler/sys/stencil-sys.ts, src/compiler/sys/typescript/typescript-resolve-module.ts, src/compiler/sys/typescript/typescript-sys.ts
This removes the `IS_NODE_ENV` variable from our environment module which previously was used to switch between browser-specific and node-specific approaches to various things in the Stencil compilation process.
Following the merge of #4317 we only support one runtime, node, for compiling Stencil components, so we can assume that `IS_NODE_ENV` is `true` and delete code accordingly.
-
=> refactor(environment): remove IS_NODE_ENV and delete dead code

src/compiler/transformers/map-imports-to-path-aliases.ts, src/compiler/transformers/test/map-imports-to-path-aliases.spec.ts
The aliased path transformation logic for the `dist-collection` output target does not correctly account for the case where the imported file is a sibling of the importing file. In this case, the generated import path is missing the leading `./`.
This was caused by changes in #4501 
In the case that a generated import path does not start with a `.`, a `./` will be pre-pended to the path
A reproduction can be found [here](https://github.com/tanner-reits/dist-relative-transformed-paths). Brief testing steps can be found in the repro readme.
This is also a problem in v3.4.1. We'll want to backfill this change to the v3 maintenance branch as well
=> fix(compiler): ensures transformed paths are relative paths for `dist-collection`

src/compiler/transformers/component-lazy/lazy-element-getter.ts, src/compiler/transformers/component-native/native-element-getter.ts, src/compiler/transformers/test/lazy-component.spec.ts, src/compiler/transformers/test/native-constructor.spec.ts
Use of the `@Element()` decorator when targeting ES2023 will result in two class members being created on the class declaration: a getter and a class field.
GitHub Issue Number: Fixes: #4528 
With this change, Stencil will only create the getter for grabbing the element reference. This change was made to both the lazy and native transformers.
Unit & e2e tests continue to pass.
Manual testing can be done for the lazy build using the reproduction in the associated issue and a local build of this branch.
Testing of the native build was done using a local lerna project with a Stencil component library and consuming application that leveraged the `dist-custom-elements` output.
I also made sure to test this change in a component that also used at least one other decorator that gets transformed …
=> fix(compiler): only create one class member when transforming `@Element()` decorators

src/utils/shadow-css.ts, src/utils/test/scope-css.spec.ts
Builds for the `dist-hydrate-script` will fail with a PostCSS error when a component's styles contain an `@supports` block with a pseudo-selector:
```css
@supports selector(:host()) {
:host() {
color: red;
}
}
```
Updates the Stencil [scopeCss()](https://github.com/ionic-team/stencil/blob/main/src/utils/shadow-css.ts#L418) method to not transform certain pseudo-selectors (`:host`, `:host-context`, `::slotted`) when they are a part of the CSS selector in an `@supports` block.
With this change, the block defined in the "current behavior" section will transform to something like the following:
```css
@supports selector(:host()) {
.sc-my-cmp-h {
color: red;
}
}
```
**Automated Tests**
Unit tests continue to pass and new tests were added for the `@supports` cases. …
=> fix(compiler): handle `@supports` blocks when scoping css
