.circleci/config.yml
=> feat(testing): try using Circle CI 2.0

src/index.ts, src/util/interfaces.ts
Hi there, this PR add life cycle interfaces to use in components [#212](https://github.com/ionic-team/stencil/issues/212) 
Thanks!
=> adding life cycle interfaces

src/util/interfaces.ts
=> feat(interfaces): make  EventEmitter generic for better type checking

.github/ISSUE_TEMPLATE.md
Just made few tweaks so filling issues is less annoying. I filled them a few in recent days so this is my suggestions for better issue creation DX :)
=> docs(.github): tweak issue template to be more readable

readme.md, scripts/polyfills/template.js, src/compiler/app/app-core.ts, src/compiler/app/test/app-core.spec.ts
=> feat(polyfill): add template element polyfill

STYLE_GUIDE.md
I mean, I suppose it could be a mayor role, but I never voted.
=> fix(doc): change mayor to major

src/compiler/transpile/datacollection/componentDecorator.ts, src/compiler/transpile/datacollection/elementDecorator.ts, src/compiler/transpile/datacollection/eventDecorator.ts, src/compiler/transpile/datacollection/listenDecorator.ts, src/compiler/transpile/datacollection/methodDecorator.ts, src/compiler/transpile/datacollection/propChangeDecorator.ts, src/compiler/transpile/datacollection/stateDecorator.ts, src/compiler/transpile/datacollection/test/fixtures/listen-simple.ts, src/compiler/transpile/datacollection/test/listenDecorator.spec.ts, src/compiler/transpile/datacollection/utils.ts, src/compiler/transpile/transformers/remove-decorators.ts
Support for:
```
@Listen('test')
@Listen('test2, test3', { enabled: false })
protected method() {
}
```
=> fix(transpiler): support for multiple listeners

STYLE_GUIDE.md
URLs updated to use HTTPS protocol where appropriate to improve security and privacy.
=> Docs: Update HTTP -> HTTPS

src/compiler/bundle/bundle-entry-input.ts, src/compiler/manifest/manifest-data.ts, src/compiler/transpile/datacollection/event-decorator.ts, src/compiler/transpile/datacollection/test/event-decorator.spec.ts, src/compiler/transpile/datacollection/test/fixtures/event-simple.ts, src/core/instance/init-event-emitters.ts, src/core/instance/test/init-event-emitters.spec.ts, src/util/data-serialize.ts, src/util/interfaces.ts, src/util/test/data-serialize.spec.ts
=> fix(events): different eventName and method

src/compiler/util.ts
This is the Pull Request correlated to the issue described here: https://github.com/ionic-team/stencil/issues/476
=> Add pcss to recognized web dev extensions

scripts/polyfills/string-startswith.js, src/compiler/app/app-core.ts
Polyfills startsWith for IE. Fix for https://github.com/ionic-team/stencil/issues/481
=> Adds startsWith polyfill

src/client/dev-inspector.ts, src/declarations/dev-inspector.ts
Enhance the component meta format. This should help the consumer skip a lot of repetitive data processing.
=> chore(devInspector): enhance output of component meta

src/compiler/transpile/transpile.ts
Fixes https://github.com/ionic-team/stencil/issues/428
Cannot unit test the commit, because on Windows before and after the patch a lot of tests fail:
Test Suites: 63 failed, 36 passed, 99 total
Tests:       306 failed, 487 passed, 793 total
=> Normalize path for windows

src/client/loader.ts
add crossorigin attribute for script tag
=> support crossorigin for dynamic import

src/testing/testing-fs.ts
=> fix(test) normalize path.relative

src/sys/node/test/node-http-server.spec.ts
=> node-http-server.spec.ts fails on Windows

src/compiler/copy/test/copy-tasks.spec.ts
#639 copy-tasks.spec.ts fails on Windows
=> test(normalize): fix copy-tasks.spec on windows

package-lock.json, package.json
This PR updates Stencil to use the latest version of Workbox.
=> chore(workbox): update workbox to the latest

src/client/css-shim/style-properties.ts, src/client/css-shim/style-util.ts, src/client/css-shim/test/css-shim.spec.ts
Fixes #749 
(This is my first non-trivial PR, so nits on style/syntax are welcome. Thanks!)
=> Prevent IE11 from StackOverflowing when using base64 values as CSS fallback

src/compiler/transpile/test/transpile.spec.ts
This PR is to fix some windows tests around transpiling.
=> Windows Test fixes

src/compiler/transpile/transformers/remove-decorators.ts
Set has a build-in `has` methods which is more efficient that `indexOf` of array.
=> perf(compiler) Use Set over array

src/compiler/style/shadow-css.ts, src/compiler/style/test/scope-css.spec.ts
Test failing because of broken master
=> fix(scoped-css): descendant selectors

CHANGELOG.md
=> chore(typo)

src/compiler/style/css-imports.ts, src/compiler/style/test/css-imports.spec.ts
=> fix(css): strips comments before resolving css imports

src/compiler/transpile/validate-types-main.ts
=> fix(config): remove type checking for config

src/compiler/transpile/datacollection/component-decorator.ts, src/compiler/transpile/datacollection/gather-metadata.ts
- Component must be the only decorator
- Component must be exported
- Component must the only export of a module
=> fix(compiler): adds more compiler checks

src/renderer/dom-api.ts, src/renderer/test/dom-api.spec.ts, test/karma/test-app/components.d.ts, test/karma/test-app/es5-addclass-svg/cmp.tsx, test/karma/test-app/es5-addclass-svg/index.html, test/karma/test-app/es5-addclass-svg/karma.spec.ts
[IE11 does not support classList on SVG](https://caniuse.com/#search=classList) (or MathML)
fixes #1079
=> fix(dom-api): adjust $addClass for IE11 svgs

src/cli/task-test.ts
Remove duplicated "this" world
=> chore(): fix typo

src/declarations/screenshots.ts, src/screenshot/screenshot-compare.ts, src/screenshot/screenshot-connector.ts, src/screenshot/screenshot-fs.ts
TODO: everything having to do with `compare.html`
=> WIP: screenshot updates

src/declarations/jsx.ts
Adding Media Events to JSX, as described in #1119
=> fix(jsx): add Media Events to jsx types #1119

src/core/init-event-emitters.ts, src/core/init-host-element.ts, src/core/test/init-event-emitters.spec.ts, src/declarations/app-global.ts, src/declarations/component-interfaces.ts, src/declarations/dom.ts, src/declarations/platform.ts, src/renderer/dom-api.ts
Allows check on emitted event.defaultPrevented
```
const e = this.myEmitter.emit();
if (e.defaultPrevented) ... [don't] do something
```
=> feat: get event from EventEmitter.emit allow check on e.defaultPrevented

src/compiler/docs/generate-readmes.ts
This fix is related to this issue
https://github.com/ionic-team/stencil/issues/1194
=> fix(compiler): fix doc generation issue for windows

test/karma/test-app/components.d.ts, test/karma/test-app/listen-jsx/cmp-root.tsx, test/karma/test-app/listen-jsx/cmp.tsx, test/karma/test-app/listen-jsx/index.html, test/karma/test-app/listen-jsx/karma.spec.ts
https://github.com/ionic-team/ionic/issues/17136
=> test(karma): adds test for Listen() + jsx event

src/compiler/style/component-styles.ts
Refactored the comment in component-style file
=> refactor(docs): replace stencil.config.js with stencil config

BREAKING_CHANGES.md
Thanks for all your work! 🙏🏻
Fixed some small typos.
=> docs: fixed small typos in BREAKING_CHANGES

src/runtime/context.ts, src/runtime/test/context.spec.tsx
Not entirely sure whether I picked the right return values here?
=> fix(context): return values for isPrerender and isClient

src/compiler/output-targets/output-angular.ts
Also reordered imports in @angular/core while adding ChangeDetectionStrategy import
=> Added ChangeDetectionStrategy.OnPush to generated angular components

src/compiler/style/test/style.spec.ts, src/runtime/test/render-vdom.spec.tsx, src/runtime/vdom/set-accessor.ts, src/runtime/vdom/test/patch.spec.ts
=> fix(vdom): use classList instead of className

src/runtime/vdom/set-accessor.ts, src/runtime/vdom/update-element.ts, test/karma/test-app/input-basic/cmp-root.tsx, test/karma/test-app/input-basic/karma.spec.ts
fixes https://github.com/ionic-team/ionic/issues/18768
fixes https://github.com/ionic-team/ionic/issues/18757
=> fix(vdom): check dom value before assign

src/compiler/transformers/add-imports.ts, src/compiler/transformers/component-hydrate/tranform-to-hydrate-component.ts, src/compiler/transformers/component-lazy/transform-lazy-component.ts, src/compiler/transformers/component-native/tranform-to-native-component.ts, src/compiler/transformers/core-runtime-apis.ts
=> fix(transform): fix addEsmImports

src/mock-doc/serialize-node.ts, src/mock-doc/test/serialize-node.spec.ts, src/runtime/bootstrap-lazy.ts, src/runtime/test/globals.spec.tsx, src/runtime/test/hydrated.spec.tsx, src/runtime/update-component.ts
fixes https://github.com/ionic-team/ionic/issues/18914
=> fix(runtime): always add .hydrated to <html>

src/client/import-shims.ts
Remove once https://bugs.chromium.org/p/v8/issues/detail?id=9558 is fixed
fixes #1765
=> fix(): workaround v8 caching issue

src/client/polyfills/dom.js
Fixes https://github.com/ionic-team/stencil/issues/1897.
=> fix(polyfill): guard against undefined nodes in getRootNode

src/hydrate/platform/index.ts, src/mock-doc/node.ts, src/mock-doc/window.ts, src/runtime/vdom/set-accessor.ts, src/testing/platform.ts
=> fix(vdom): fix onAnimationStart/End

src/compiler/transformers/static-to-meta/vdom.ts, src/declarations/testing.ts, src/runtime/test/jsx.spec.tsx, src/runtime/test/render-vdom.spec.tsx, src/runtime/vdom/h.ts, src/testing/spec-page.ts
=> fix(vdom): fix vdom static analysis

src/compiler/docs/generate-doc-data.ts, src/compiler/docs/vscode/index.ts, src/declarations/docs.ts
=> feat(docs): expose type as array of values

src/runtime/proxy-component.ts
=> fix(components): non mutable properties are in fact inmutable

src/runtime/vdom/h.ts
=> fix(vdom): add dev check for unexpected vnode

package.json
Update to the latest version of Typescript.
=> chore(compiler): Update to typescript 3.7

src/runtime/event-emitter.ts, src/runtime/test/event.spec.tsx
=> fix(event): emit() returns the CustomElement

src/mock-doc/document-fragment.ts, src/mock-doc/document.ts, src/mock-doc/node.ts, src/mock-doc/parse-util.ts, src/mock-doc/test/document-fragment.spec.ts
=> fix(mock-doc): implement  getElementById() in document fragment

package.json, src/compiler/app-core/bundle-app-core.ts, src/compiler/component-lazy/generate-cjs.ts, src/compiler/component-lazy/generate-esm-browser.ts, src/compiler/component-lazy/generate-esm.ts, src/compiler/component-lazy/generate-lazy-module.ts, src/compiler/component-lazy/generate-system.ts, src/compiler/transformers/decorators-to-static/convert-decorators.ts, src/compiler/transformers/decorators-to-static/prop-decorator.ts, src/compiler/transformers/decorators-to-static/state-decorator.ts, src/compiler/transformers/decorators-to-static/watch-decorator.ts, src/compiler/transformers/stencil-import-path.ts, src/compiler_next/bundle/app-data-plugin.ts, src/compiler_next/bundle/bundle-interface.ts, src/compiler_next/bundle/bundle-output.ts, src/compiler_next/bundle/core-resolve-plugin.ts, src/compiler_next/bundle/ext-transforms-plugin.ts, src/compiler_next/bundle/text-plugin.ts, src/compiler_next/bundle/worker-plugin.ts, src/compiler_next/output-targets/dist-custom-elements-bundle/index.ts, src/compiler_next/output-targets/dist-hydrate-script/bundle-hydrate-factory.ts, src/compiler_next/output-targets/dist-lazy/generate-cjs.ts, src/compiler_next/output-targets/dist-lazy/generate-esm.ts, src/compiler_next/output-targets/dist-lazy/generate-lazy-module.ts, src/compiler_next/output-targets/dist-lazy/generate-system.ts, src/compiler_next/output-targets/dist-lazy/lazy-output.ts, src/compiler_next/sys/modules/crypto.ts, src/declarations/stencil-ext-modules.d.ts, src/declarations/stencil-private.ts
- Better error handling
- Pass error as error
- Pass id first
- worker platform => better rollup errors
- Remove proxy
=> Feat workers

src/mock-doc/element.ts, src/runtime/bootstrap-lazy.ts, src/runtime/test/cloneNode.spec.tsx, test/karma/test-app/components.d.ts, test/karma/test-app/dom-reattach-clone/angularjs.html, test/karma/test-app/dom-reattach-clone/cmp-deep-slot.tsx, test/karma/test-app/dom-reattach-clone/cmp-host.tsx, test/karma/test-app/dom-reattach-clone/cmp.tsx, test/karma/test-app/dom-reattach-clone/index.html, test/karma/test-app/dom-reattach-clone/karma.spec.ts, test/karma/test-app/slot-array-basic/index.html
=> fix(runtime): cloneNode for non-shadow-dom components

src/compiler_next/bundle/typescript-plugin.ts
Normalizes paths for Windows support. Fixes #2112
=> fix(next): normalize paths

src/declarations/stencil-public-runtime.ts
=> docs(stencil-public-runtime): swap comment-doc format

notes/2020-03-11.md
Added my notes from the meeting in March and edited them slightly to fit the style of the notes @adamdbradley added earlier.
=> docs(notes): 2020-03-11 Meeting Notes

src/declarations/stencil-public-runtime.ts
=> fix(runtime): add href SVG attribute

src/declarations/stencil-public-runtime.ts
=> fix(runtime): add onSlotchange to slot element attribute

src/compiler/docs/json/index.ts
Required for https://github.com/ionic-team/ionic-docs/pull/1405
=> fix(docs): include parts in top level docs json

src/runtime/dom-extras.ts
=> fix(polyfill): slot child fix

src/compiler/transformers/reserved-public-members.ts, src/declarations/stencil-public-runtime.ts, src/mock-doc/node.ts, src/mock-doc/window.ts
=> feat(): add focusin and focusout event declarations

src/compiler/docs/generate-doc-data.ts, src/compiler/types/generate-app-types.ts, src/compiler/types/generate-component-types.ts, src/compiler/types/generate-event-types.ts, src/compiler/types/generate-method-types.ts, src/compiler/types/generate-prop-types.ts, src/declarations/stencil-private.ts, src/utils/util.ts
=> fix(): emit private types in local component.d.ts

src/declarations/stencil-public-runtime.ts
Add `componentShouldUpdate` docs to `ComponentInterface`
fixes #2489
=> feat: add `componentShouldUpdate` docs

src/testing/puppeteer/puppeteer-events.ts
Closes this [issue](https://github.com/ionic-team/stencil/issues/2524)
=> :bug: fix e2e readiness flag on slow or overloaded computers

src/screenshot/connector-local.ts
=> :bug: fix compare.html in e2e screenshot

src/runtime/vdom/h.ts, src/runtime/vdom/test/h.spec.ts
=> Allow mapping of ChildNode to functional component

readme.md
Hi,
Thanks for signing up for our open source program! We hope you’ve found it valuable. 
Open source projects like yours power the world of tech, and we’re honored to be helping you. We’ve benefitted from hundreds of open source projects, and now's our time to give back.
I have added BrowserStack Logo under “Testing powered by” heading to the Readme
This helps us reach more open source developers like you, ones who can use BrowserStack’s infrastructure for free and build great products.
Naineet Patel
BrowserStack DevRel
=> Added BrowserStack Logo to Readme

src/declarations/stencil-public-compiler.ts, src/dev-server/index.ts
Closes this [issue](https://github.com/ionic-team/stencil/issues/2718)
=> :wrench: make dev server startup timeout configurable

src/compiler/bundle/worker-plugin.ts
Issue: https://github.com/ionic-team/stencil/issues/2848
=> fix(worker-plugin): transfer OffscreenCanvas

scripts/readme.md
There is no documentation to test the Browser API prior to a release
- Add smoke testing documentation prior to a release
N/A
If there's anything you think is worth calling out/expounding on, please LMK!
=> docs(release): add smoke testing documentation for browser api

.github/ISSUE_TEMPLATE/bug_report.yml
- the Stencil version is a textarea (which is probably too big) and not required to be filled out
- the code reproduction url is not required to be filled out
- update the Stencil version textarea to be an input box, require it to be filled out
- update the code reproduction url to be required
- this might be _too_ aggressive, LMK what you think
None, I don't think there's a _good_ way to test this
Link to the GH Docs for Syntax: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#input
=> chore(github): refine bug report template

package-lock.json, package.json
We run Prettier w version 2.3.2. Prettier can yield different results between minor versions. I saw that v2.4.0 was released, so I thought "well I wonder if that breaks anything?". And surprisingly it doesn't
Use Prettier v2.4.0 for formatting - the changelog for this version can be found [here](https://prettier.io/blog/2021/09/09/2.4.0.html)
I ran prettier, and everything passed
=> chore(dependencies): update prettier to v2.4.0

src/compiler/output-targets/dist-custom-elements-bundle/index.ts, src/compiler/output-targets/dist-custom-elements/index.ts, src/compiler/output-targets/dist-lazy/generate-lazy-module.ts, src/compiler/output-targets/dist-lazy/write-lazy-entry-module.ts, src/compiler/transpile.ts, src/utils/sourcemaps.ts, src/utils/test/sourcemaps.spec.ts
While going through the #3005, I realized that we use the source map linking string in multiple places. This isn't ideal, because I _think_ at some point we're going to need to specially encode the URL, and I'd prefer not to update it in several locations
- Extracts the generation of the URL linker into two helper methods
- Added unit tests
- Smoke tested with a sample Stencil app, with a global script defined/created
=> chore(sourcemaps): create linker string util

scripts/readme.md
ATM, Stencil documentation needs to be manually merged. When there's an update to the docs that coincide with a new release, we may hold off on merging the PR in the [Stencil Site](https://github.com/ionic-team/stencil-site/pulls) so as to cause confusion surrounding bug fixes/new features.
Like any manual process, this is easy to forget 🙃 This has the potential to have a similar effect, where we have new/fixed functionality, but no docs around it
Added a little reminder for myself in the interim while we figure out autopublishing
N/A
This may or may not be inspired by real life events
=> chore(docs): add documentation publishing reminder in release steps

src/compiler/entries/component-bundles.ts, src/compiler/entries/default-bundles.ts, src/compiler/html/used-components.ts, src/compiler/output-targets/dist-lazy/lazy-output.ts, src/utils/validation.ts
There's a lot of undocumented code in Stencil as a whole. Since I was digging through bundle code anyway, I decided to JSDoc it. There's only one 'actual' code change here that technically changes the behavior of the program, which I've commented inline in the diff.
Adds a bunch of JSDoc
N/A
=> refactor(compiler): document bundle generation

.github/workflows/browserstack.yml
Browserstack does not run on the v3 branch
add  `v3.0.0-dev` to browserstack pull_request_target.branches to allow PRs that the Stencil team wants to merge into `v3.0.0-dev` to run browserstack tests
add push action for `main` and `v3.0.0-dev` branch to ensure that commits to the v3 branch _and_ `main` branches are evaluated against browserstack tests
I set the base branch in GitHub to v3.0.0-dev to ensure that Browserstack would run
=> chore(browserstack): run browserstack for v3 branch

src/declarations/stencil-public-runtime.ts
In order to remove the type casting for the `ionInput` event types, the emitted type for `DomAttributes` will need to match `InputEvent`.
GitHub Issue Number: https://github.com/ionic-team/ionic-framework/pull/24111
Libraries/applications using Stencil, will have the `input` event strongly typed to `InputEvent` instead of the general `Event` type.
=> fix(runtime): narrow onInput & onCapture event types

.github/workflows/browserstack.yml, .github/workflows/main.yml
attempt to fix push events by picking the ref based on the event name
=> chore(browserstack): fix push events

.github/PULL_REQUEST_TEMPLATE.md
The PR template's testing section could potentially be misunderstood - add a comment to state this could be programmatic and/or manual
add a comment to state this could be programmatic and/or manual
N/A
=> chore(github): update pr template testing instructions

scripts/readme.md
There are a few steps that still need to be remembered when doing a release, which makes it easy to forget
add reminders to perform JIRA and GitHub cleanup during the release
process to ensure nothing gets forgotten
N/A
=> chore(release): add additional release steps

src/mock-doc/node.ts
GitHub Issue Number: #3149 
The `Node.contains` method should return `true` if the passed node is the parent/context node.  [The wording in the spec](https://dom.spec.whatwg.org/#dom-node-contains) is that it should return `true` if the passed node is an "inclusive descendant", which differs from a regular "descendant" in that it includes the object itself (not just the child nodes).
=> Fix mock-doc Node.contains implementation

.github/ionic-issue-bot.yml
N/A
GitHub Issue Number: [N/A](https://github.com/ionic-team/stencil/issues/3186)
Have Ioniton comment on PRs/issues about our holiday break
N/A
=> chore(ionitron): holiday triage 2021

package-lock.json, package.json
We're on Prettier v2.4.0. A new(ish) minor version is out, let's upgrade it!
update prettier to the latest available version of the library, v2.5.1.
continue to use exact version in package.json to prevent accidental
formatting regressions/differences between users
Ran `npm run prettier` locally to verify no changes to the codebase would occur
=> chore(prettier): prettier v2.5.1 upgrade

.github/ionic-issue-bot.yml
Ionitron is commenting on new issues that it'll take a bit for the team to get to them, due to the holiday season
GitHub Issue Number: Reverts #3187, Closes https://github.com/ionic-team/stencil/issues/3186
This reverts commit 4a5da0ff052ed4bd303274b33d23f4989e410654 to end
the 2020 holiday triage season
N/A
=> revert(ionitron): holiday triage 2020 (#3187)

.prettierignore
We run prettier on end to end test output locally 😬 this takes wayyyy longer than it should.
this commit updates the prettier ignore configuration to use globs for
the `dist` and `www` directories under the root `test/` directory. this
prevents files in the `test/end-to-end` directory (and others) from
being formatted
remove `test/browser-compile` to ensure src files are properly
formatted. the test output for this directory is covered by the new
globs
In the `HEAD` of `main`, run the `test/end-to-end` tests locally. Then run prettier (`npm run prettier` from the root of the project). Note all the output files being formatted.
Then checkout this branch, …
=> chore(prettier): ignore additional test output directories

.github/ionic-issue-bot.yml
- 'Request for Comments' labeled issues can be accidentally marked as stale
add 'Request For Comments' to the exempt labels for ionitron.
N/A
This is getting to be a less-than-fun version of whack-a-mole. Although expressive labels are great for communication, the number of permutations here is getting a bit unwieldy, as I'm adding a new label here every week. Going to schedule some work to rework the existing labels in this repo
=> chore(github): add 'Request For Comments' to exempt labels

src/compiler/bundle/bundle-output.ts, src/compiler/bundle/loader-plugin.ts, src/compiler/bundle/typescript-plugin.ts, src/compiler/output-targets/dist-custom-elements/index.ts, src/compiler/transformers/add-component-meta-proxy.ts
There are various parts of cruft in the codebase discovered while working on #3248 
This commit adds several small refactorings that were added as a part of #3248. They are split up by commit to be logically separated. I chose to create a separate PR here in that I did not feel these changes helped one understand #3248  in a meaningful way (and may have led to more churn/confusion). I intend to squash and merge this PR, but left these as separate commits for easier reviewing
N/A, mostly JSDoc. For the few functional changes, I relied on existing tests/the typescript compiler to catch the error for me (admittedly this isn't the right thing to do, feel …
=> refactor(multiple): code cleanup following webpack treeshaking fix

src/runtime/test/parse-property-value.spec.ts
There are no unit tests for certain aspects of the property parsing code base
GitHub Issue Number: https://github.com/ionic-team/stencil/pull/3255
As a follow up to https://github.com/ionic-team/stencil/pull/3255, this PR has four commits that are logically split up to add unit tests to the following scenarios of parsing props:
- parsing boolean values
- parsing string values
- parsing function props for the number, boolean and string type
- parsing non-primitive values
Unit tests were run locally, and in a debugger to validate they work properly
=> test(runtime): add property parsing tests

test/browser-compile/src/components/app-root/app-root.tsx
In https://github.com/ionic-team/stencil/pull/3259, we typed an error as
type `any` as a stopgap measure to allow publishes to occur again. This piece
of debt was left for a future day (which is today).
this commit introduces proper type guards for the browser-compile
project, removing the stopgap 'any' usage that was introduced in
https://github.com/ionic-team/stencil/pull/3259
In this branch, navigate to `test/browser-compile` and:
- `npm run build` to test production builds
- `npm start` to smoke test the application
=> chore(types): update browser-compile typings

bin/stencil, package.json
In https://github.com/ionic-team/stencil/pull/3271, I realized that we weren't running prettier against
the `bin` directory. I fixed that while I was working on #3271, but wanted to hold off on pushing that code
until the Node Deprecation Messaging task had been merged. Now that it has been (merged), adding 
this work so it doesn't get lost
update the prettier command to run against `bin/stencil`
I performed the same testing as #3271, repeated below (I reused the screen shots, for the sake of time)
To start, spin up a new stencil project (`npm init stencil component test-warning-msg`), then pull this branch and build it (`npm ci && npm run build && npm …
=> chore(prettier): update prettier command for bin/

.github/ionic-issue-bot.yml
for each of the labels that are added in this PR, ionitron can potentially mark
the issues as stale
this commit adds additional labels to ionitron to exempt various issues
from being marked as stale
Double checked spelling of new labels....(ctrl-c, move to browser, ctrl-f + ctrl-v)
I'll be using part of my JEDI days to rework the bot, its labels, etc. this is just a stop gap measure
=> chore(github): add additional ionitron stale labels

test/todo-app/src/components/app-root/app-root.tsx
The `v3.0.0-dev` build is currently broken. See the next section for 'why'/'how'
this commit updates the typings for the analysis task. the team
re-enabled these tasks/tests (for the most part) in
https://github.com/ionic-team/stencil/commit/6f99212e4e33760793a6f8161265cc1c9350e805.
in main. at the same time, a commit that updates typings for onInput
events was sitting in the v3.0.0-dev branch,
https://github.com/ionic-team/stencil/commit/8316a62f5767639e3b70661a0d6b902c9e6daf0b.
upon merging main into v3.0.0-dev, the build broke. this commit fixes
the typings to align with the latter commit.
From this branch, I ran `npm run test.analysis` to verify the …
=> chore(types): update typings for analysis task

src/compiler/transformers/transform-utils.ts, src/compiler/types/stencil-types.ts
this commit adds jsdoc parts of the compiler that are responsible for
finding and storing references to types in a stencil project. this
commit was split out from the work being performed to fix type
collisions in type declaration files that stencil produces, as its not
strictly necessary for the fix itself (STENCIL-27)
This commit is largely the addition of JSDoc. I did rename a few  variables here for clarity, but am relying
on existing tests/the TS compiler to find my errors for me here
=> chore(jsdoc): add jsdoc to type reference collection

src/utils/test/validation.spec.ts, src/utils/validation.ts
This just adds tests for a file that didn't have a spec file already (`src/utils/validation.ts`).
Basically just increasing test coverage a bit here! I came across this file while working on a different issue (#2672) and thought I might as well add some tests here.
=> add a specfile for the validateComponentTag function

src/testing/jest/jest-config.ts, src/testing/jest/test/jest-config.spec.ts
GitHub Issue Number: #3328  
`stencil test` will now respect passed flags, (for example `--passWithNoTests`)
- Added test case.
- Tested against repo and reproduction repo.
=> fix(tests): Respect passed flags

.github/workflows/browserstack.yml
In https://github.com/ionic-team/stencil/pull/3331, I accidentally left a change in that sets the minimum value of Browserstack's Node Version to v14. We still support v12, let's set that value back.
Resets the node version used by the CI browserstack job to v12
CI should pass
=> chore(github): set browserstack node to v12

CODE_OF_CONDUCT.md
This PR is to update the Code of Conduct to align with the [Ionic framework code of conduct](https://github.com/ionic-team/ionic-framework/blob/main/CODE_OF_CONDUCT.md), specifically to provide more explicit guidelines.
=> updating code of conduct

src/mock-doc/node.ts, src/mock-doc/test/element.spec.ts
Fix for https://github.com/ionic-team/stencil/issues/3357
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/3357
Now follows the spec as found here https://developer.mozilla.org/en-US/docs/Web/API/Node/contains
-
-
-
I have added all the scenarios describes in the spec.
=> Fix mock doc contains method

src/dev-server/test/dev-server-utils.spec.ts, src/utils/test/util.spec.ts, src/utils/util.ts
This is a small/low priority PR that whittles away at the unused exports burndown list
remove the unused isHtmlFile and isCssFile helpers. there were working/valid tests for
each helper, as well as a similar helper (for each) exist in a different file (`dev-server-utils`).
those tests have been ported to a new test helper file
Unit tests were run/passed locally
=> refactor(utils): remove unused isHtmlFile, isCssFile helpers

src/compiler/docs/readme/docs-util.ts
This removes 6 unused functions from
`src/compiler/docs/readme/docs-util.ts`. These functions are picked up
as unusued exports by `ts-prune`, their names do not appear in any other
modules, and the project builds and runs without them.
-
-
-
=> refactor(compiler): remove unused exports from docs-util

.eslintrc.js, src/cli/test/ionic-config.spec.ts, src/compiler/build/build-stats.ts, src/compiler/bundle/dev-module.ts, src/compiler/config/config-utils.ts, src/compiler/config/test/validate-namespace.spec.ts, src/compiler/output-targets/dist-lazy/generate-lazy-module.ts, src/compiler/transformers/component-native/proxy-custom-element-function.ts, src/compiler/types/stencil-types.ts, src/dev-server/dev-server-utils.ts, src/dev-server/test/util.spec.ts, src/runtime/dom-extras.ts, src/runtime/styles.ts, src/runtime/vdom/h.ts, src/runtime/vdom/set-accessor.ts, src/runtime/vdom/vdom-render.ts, src/sys/node/test/node-lazy-require.spec.ts, src/utils/shadow-css.ts
Adding the `prefer-const` rule to our eslint configuration. This is part
of the recommended eslint configuration.
**note**: this is sort of a proposal! Right now we do seem to have `let` scattered around in places where variables _could_ be declared with `const`. Do we want to go full `const` or remain agnostic?
Note that I pulled this in based on these two files used for creating the `@typescript-eslint` recommended rule list
- https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts 
- https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended.ts
GitHub Issue …
=> chore(lint): turn on prefer-const rule

.eslintrc.js, src/client/polyfills/css-shim/test/css-shim.spec.ts, src/dev-server/dev-server-client/polyfills.ts, src/testing/matchers/events.ts, src/utils/format-component-runtime-meta.ts
adding because it is turned on in the `@typescript-eslint` base eslint rule configuration file, here:
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts#L27
=> chore(lint): turn on the 'no-var' rule

.eslintrc.js, src/compiler/transpile/run-program.ts, src/compiler/worker/worker-thread.ts, src/hydrate/platform/proxy-host-element.ts, src/testing/platform/testing-log.ts, src/testing/testing-logger.ts
See https://eslint.org/docs/rules/prefer-spread for an explanation.
Basically, this rule prefers spreading an array of parameters into a
normal function call over using `Function.prototype.apply`, so
```ts
foo(...params);
```
is preferred over
```ts
foo.apply(null, params);
```
This rule is included in the `@typescript-eslint` recommended eslint
rule list, here:
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts#L30
This PR is a replacement for #3388 which was accidentally closed
I turned the rule on, fixed violations of it, and did just a few small touchups on related code while I …
=> chore(lint): set the 'prefer-spread' eslint rule

src/cli/task-generate.ts, src/compiler/sys/logger/terminal-logger.ts, src/compiler/sys/logger/test/terminal-logger.spec.ts, src/declarations/stencil-public-compiler.ts, src/sys/node/node-logger.ts
This adds tests for the terminal-logger module and also does a little
bit of code cleanup (some light refactoring, JSDoc, etc).
Previously the `terminal-logger` implementation didn't have any tests around it 😱 
This PR adds some tests and does some light refactoring. You can see the history a bit by stepping through the commits, basically what I ended up doing was:
1. Make the changes necessary to get a `Logger` (as returned by `createTerminalLogger`) stood up in a test environment
2. add some tests for the existing functionality
3. do a few small refactors that seemed like obvious wins in terms of code clarity
There is a _lot_ more than could be done here, including looking at …
=> test(compiler): add tests for the terminal-logger module

src/compiler/transformers/component-native/tranform-to-native-component.ts
This removes an unused function from
src/compiler/transformers/component-native/tranform-to-native-component.ts.
-
-
-
=> chore(compiler): delete an unused function

src/compiler/fs-watch/fs-watch-rebuild.ts
This refactors some code in `src/compiler/fs-watch/fs-watch-rebuild.ts` to
DRY up a few things which were revealed by two unused exports in the
file.
-
-
-
=> refactor(compiler): remove unused exports from fs-watch-rebuild 

src/compiler/docs/style-docs.ts, src/compiler/style/css-to-esm.ts, src/declarations/stencil-private.ts
This adds comments and type signature updates to a few files related to
supporting style updates with HMR.
In fiddling around with these files while looking into STENCIL-47 I
noticed these files were generally uncommented, so I added a few
comments and so on to try to clean things up a little.
STENCIL-47 Framework: CSS wiped on Stencil live reload investigation
- this just adds comments and whatnot breaking down what I could glean about what's happening in these files.
I didn't really change any code for this. I may open another PR to increase test coverage on these files in the future.
=> chore(styles): add comments and type signature updates

.github/CONTRIBUTING.md, .github/ionic-issue-bot.yml
We have some stale label information in various parts of the repo
this commit removes the 'reply received' label exemption from ionitron.
we stopped using this label ~3 months ago. in that time, the issues in
the backlog have all been re-triaged, and any issues with this label
today _also_ have an additional exempt label. this is the next step in
removing the label from the repo.
this also renames the 'reply received' label in the contributing guide
to 'awaiting reply' to align with the label we actually use.
the 'help wanted' label mention was removed, as we don't use it today
N/A
The primary motivation for this PR is to clean up some of our …
=> chore(github): clean up github labels

src/compiler/sys/fetch/fetch-utils.ts, src/compiler/sys/fetch/tests/fetch-module.spec.ts
This removes an unused export from src/compiler/sys/fetch/fetch-utils.ts
and inlines a function which was used in only one place. A JSDoc is
added for the function that is changed.
This removes an unused export and inlines one function which was used in only one place.
=> chore(exports): remove unused export from fetch-utils

src/compiler/transformers/add-component-meta-static.ts, src/compiler/transformers/static-to-meta/component.ts, src/compiler/transformers/static-to-meta/parse-static.ts, src/compiler/transformers/static-to-meta/props.ts, src/compiler/transformers/static-to-meta/visitor.ts, src/compiler/transformers/transform-utils.ts, src/declarations/stencil-private.ts
This documents a few functions and interfaces which have to do with
dealing with component properties, as well as some utils which are used
to creating TypeScript IR for values that we're dealing with at
compile-time.
Most of this is just adding JSDoc comments to functions whose, uh, _function_ I tried to figure out.
One code change is removing a parameter on `parseStaticComponentMeta` which was redundant.
this should all pass and work and whatnot
=> chore(compiler): add JSDocs to functions relating to component props

BREAKING_CHANGES.md
Adds link to relevant PR for configuration flag default value changes taking effect in V3
=> docs(breaking-changes): add reference to flag default value changes (v3)

src/testing/jest/jest-preprocessor.ts
There are ~9 `strictNullChecks` violations in our code related to jest preprocessing
this commit removes a handful of strict null check violations that can
be found in stencil's jest preprocessor. most changes are concerned with
making types agree - e.g. if a variable is declared to be of type `T`,
but is assigned by a function that returns `T | U`, the type of the
variable is expanded for agreement.
the two changes that are worth calling out in particular is introducting
a `throw` statement in the event that the `transformOptions` parameter
is falsey both when we process a file and attempt to retrieve a cache
key. from jest 23 thru 27, the function …
=> chore(tests): fix null check errors for jest preprocess

.github/workflows/test-browserstack.yml
when running the TypeScript 4.7 upgrade, I had CI fail on me for our git status
check. I'm not sure what it's picking up, so I'd like to be told what the CI env sees
this commit updates the "Git status check" step
of the browserstack workflow to print the names
of the files that are uncommitted
Ran the script locally with files that were uncommited to verify the output
Verified the script with Shellcheck
=> chore(github): print uncommitted files for browserstack

.github/workflows/build.yml
ci fails when we modify the scripts/ directory of the project
this is a symptom of a larger issue where the incorrect branch was built for browserstack tests,
we never noticed before because scripts contains both compiled and source code we archive,
and this is the first time we've modified it since the bug in CI was introduced
this commit is a sibling to (#3550). it helps prevent dirty contexts
in git by only archiving `scripts/build`, rather than the entirety of `scripts`
during the build process.
Unfortunately, pull_request_target code needs to land to be tested 😢 so we're rolling the dice here 🎲
=> chore(ci): only archive scripts/build/

scripts/bundles/compiler.ts, src/compiler/build/compiler-ctx.ts, src/compiler/bundle/dev-module.ts, src/compiler/bundle/file-load-plugin.ts, src/compiler/cache.ts, src/compiler/index.ts, src/compiler/style/test/css-imports.spec.ts, src/compiler/sys/fetch/fetch-module-async.ts, src/compiler/sys/fetch/fetch-module-sync.ts, src/compiler/sys/fetch/write-fetch-success.ts, src/compiler/sys/in-memory-fs.ts, src/compiler/sys/resolve/resolve-module-async.ts, src/compiler/sys/resolve/resolve-module-sync.ts, src/compiler/sys/tests/in-memory-fs.spec.ts, src/compiler/sys/typescript/tests/typescript-resolve-module.spec.ts, src/compiler/sys/typescript/typescript-resolve-module.ts, src/compiler/sys/typescript/typescript-sys.ts, src/compiler/types/stencil-types.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts, src/testing/test/testing-utils.spec.ts, src/testing/testing-utils.ts
This updates the in-memory FS file with a bunch of comments explaining
what various methods on the `InMemoryFileSystem` object do.
It also refactors where the relevant types live. Instead of having a
separate interface declared outside of the file where the
implementation is, we instead derive the `InMemoryFileSystem` from the
return value of the function which creates the object. This lets us have
comments annotating the implementation code which will also show up as
type hints throughout the codebase.
This does not (or should not!) change how anything works, but is instead just a documentation / cleanup patch.
I confirmed that unit tests are passing and whatnot, and did a bit …
=> chore(compiler): add comments and update types for in-memory FS

package-lock.json
I was getting an error message because we recently upgraded typescript
(#3530) saying that 4.7 wasn't supported by the installed versions of
@typescript-eslint/parser and @typescript-eslint/eslint-plugin. This
just bumps them a little bit to fix that error message.
Doing `npm upgrade` for the two `@typescript-eslint` packages we use makes that error message go away.
=> chore(lint): fix unsupported typescript version error message

src/compiler/config/outputs/validate-collection.ts, src/compiler/config/outputs/validate-dist.ts, src/compiler/config/test/validate-output-dist-collection.spec.ts, src/compiler/config/test/validate-output-dist.spec.ts, src/compiler/output-targets/dist-collection/index.ts, src/compiler/output-targets/test/output-targets-collection.spec.ts, src/compiler/transformers/map-imports-to-path-aliases.ts, src/compiler/transformers/test/map-imports-to-path-aliases.spec.ts, src/declarations/stencil-public-compiler.ts
Currently, aliased import paths are not transpiled at all. A previous PR to add new transpilation behavior would run by default. This PR adds functionality to guard that behavior behind a config flag.
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/2815
This commit adds config flags to enable the transpilation of import path aliases as a part of the `dist-collection` output target. Part of the work for STENCIL-437
Unit tests were added to verify the new behavior only runs when explicitly enabled
=> fix(compiler): add config flags for transpiling path aliases

src/compiler/bundle/server-plugin.ts, src/compiler/output-targets/output-lazy-loader.ts, src/compiler/plugin/plugin.ts, src/compiler/style/global-styles.ts, src/compiler/transpile/run-program.ts, src/testing/testing-utils.ts, src/utils/util.ts
Stencil has a few `nullStrictChecks` violations
this commit propagates the `ValidatedConfig` type to areas of the codebase that drops the number of `strictNullChecks` violations related to the `outputTargets` field.
this commit does not update subfield-related violations of an `OutputTarget` subtype.
Type Checker continues to pass
=> chore(types): propagate ValidatedConfig for outputTargets

src/cli/task-test.ts
the test task has more code in the `try` block than I'd like. I've been sitting on this commit
for longer than I'd like to admit to try to find a "good" place to put it. I want to just commit it
at this point so I can stop keeping it up to date
this commit refactors the test-task to make the `try` block found in the primary function smaller and more focused. items that can/should not throw have been removed from the block
I created a Stencil component library with `npm init stencil component`
After that, I installed this branch into the component library and:
- ran `npm t`
- uninstall puppeteer and ran `npm t` to verify checking for that module failed …
=> refactor(test-task): pull code out of try block

src/declarations/stencil-private.ts
we have a separate import statement for a single interface. which is fine, but
we can make this a little more consistent
update the import statement for `BuildResultsComponentGraph` to the `import type ...` statement. this shouldn't have an effect on much, as its an interface to begin with
CI passes
=> refactor(private): move BuildResultsComponentGraph to type import

src/runtime/proxy-component.ts
Just a small documentation / typing change.
=> docs(runtime): add a basic JSDoc explanation to `proxyComponent`

src/compiler/transformers/component-hydrate/hydrate-runtime-cmp-meta.ts, src/declarations/stencil-private.ts, src/utils/format-component-runtime-meta.ts
This adds JSDoc comments to a few things related to component runtime metadata. There are a few very small improvements in typings as well.
Just trying to document some of what's going on here!
I don't think this will necessitate too much testing, as I don't think the changes should really change how anything works.
=> docs(compiler): add comments to things related to component metadata

test/todo-app/src/components.d.ts
see "new behaviors" section below
this commit updates the typings for the todo-app that exists within the `test/` subdirectory of the project. these changes should have been committed with 846740f (#3296) but were unfortunately missed
CI continues to pass
this was caught by https://github.com/ionic-team/stencil/pull/3625, currently in draft form at the time of this writing
=> chore(tests): update analysis typings

package-lock.json, package.json
Concurrently is quite out of date. We don't use it though so.....
Closes https://github.com/ionic-team/stencil/pull/3648
this commit removes concurrently from our dependency list. it was only used in a single npm script, that wasn't used by the team. rather than try to maintain something that we don't use, let's remove it instead.
I ran `npm run` to make sure the parsing of the package.json file didn't break when I removed the last entry from the "scripts" secion
=> chore(dev-deps): remove concurrently

src/compiler/output-targets/test/custom-elements-types.spec.ts
this commit fixes a lint error that is the result of the following course of actions:
- https://github.com/ionic-team/stencil/pull/3621/files updated eslint-plugin-jest, which now errors on aliased mathers
- the changes in the aforementioned PR were pulled into the v3.0.0-dev branch
- the new lint rules didn't run on that branch until the merge, catching one violation in the v3 branch that wasn't in the v2 branch
- 
- Linting/format was run locally.
- The unit test continues to pass
=> chore(lint): fix lint in v3 after v2.18.1 merge

.github/dependabot.yml
This commit adds rules to dependabot to ignore upgrading inquirer and @types/inquirer dependencies. They will be removed once the release scripts are changed.
Closes https://github.com/ionic-team/stencil/pull/3637
=> chore(dependabot): prevent PRs for inquirer and @types/inquirer

src/compiler/bundle/bundle-interface.ts, src/compiler/bundle/core-resolve-plugin.ts, src/declarations/stencil-public-compiler.ts
This adds a few small comments around the `externalRuntime` behavior for `dist-custom-elements`
=> docs(dist-custom-elements): add code comments for `externalRuntime`

src/compiler/sys/stencil-sys.ts, src/sys/node/node-sys.ts
Just some simple docstrings for these functions (as well as return type annotations).
-
-
-
=> chore(sys): add JSDocs to createNodeSys, createSystem

src/compiler/bundle/bundle-output.ts, src/compiler/bundle/constants.ts, src/compiler/bundle/dev-module.ts, src/compiler/bundle/dev-node-module-resolve.ts
Two changes were necessary to remove a circular dependency relationship between `bundle-output.ts` and `dev-module.ts`:
- two constants are moved to a new file, `constants.ts`
- functionality relating to resolving node module IDs is moved to a new file (`dev-node-module-resolve.ts`)
-
-
-
=> chore(compiler): remove circular dependency in bundle

src/declarations/stencil-public-docs.ts
I forgot to apply a non-blocking comment in https://github.com/ionic-team/stencil/pull/3766
this commit applies
https://github.com/ionic-team/stencil/pull/3766#discussion_r1004888178, which was missed prior to merging the pull request
N/A
=> chore(jsdoc): apply reword suggestion to JsonDocsComponent field

.eslintrc.js
in `bin/stencil` script, there is some `eslint` error info about `var`
avoid `eslint` error info in stencil script by override the eslint config [overrides](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#how-do-overrides-work)
-
-
=> chore: bin files eslint rule override

src/cli/task-generate.ts
- [] E2E Tests (`npm run test.karma.prod`) were run locally and passed
avoid unexpected Error because of prompt `undefined` result ;
when run `stencil generate`
and  operate `ctr + c` before input or select any string
it will throw error about `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined` or `TypeError: (intermediate value) is not iterable` 
-
-
-
=> fix: generate task unexpect error

.github/workflows/build.yml, .github/workflows/lint-and-format.yml, .github/workflows/tech-debt-burndown.yml, .github/workflows/test-analysis.yml, .github/workflows/test-browserstack.yml, .github/workflows/test-bundlers.yml, .github/workflows/test-e2e.yml, .github/workflows/test-unit.yml
Today, CI started to fail when we perform our bundler tests:
```
08 12 2022 15:51:12.909:INFO [launcher]: Starting browser ChromeHeadless
08 12 2022 15:51:14.283:ERROR [launcher]: Cannot start ChromeHeadless
DevTools listening on ws://127.0.0.1:9222/devtools/browser/9c353de5-4e6d-445a-9e2c-aca2afe3b555
[1208/155113.030568:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[1208/155113.179045:ERROR:gpu_process_host.cc(995)] GPU process exited unexpectedly: exit_code=159
[1208/155113.179070:WARNING:gpu_process_host.cc(1309)] The GPU process has crashed 1 time(s)
[1208/155113.186693:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader …
```
=> chore(ci): downgrade ubuntu

src/compiler/types/tests/generate-app-types.spec.ts
See new behavior
this commit adds jsdoc to the output of the tests for app type generation, following https://github.com/ionic-team/stencil/pull/3525 landing in `main`, then merging `main` into `v3.0.0-dev` caused tests present in the v3 branch to begin to fail.
the alignment of the jsdoc being generated is off. in the name of time, we assume tech-debt and will rectify this in stencil-660
Unit tests pass again
=> test(app-types): update tests following jsdoc generation

.github/ionic-issue-bot.yml
When a new issue is added to GH, it is labeled with "Triage"
this commit updates ionitron to label new issues as 'holiday triage' while the team takes a year-end break. this commit is intended to be reverted around 2022.01.04
N/A - we can only verify this after it lands 😢
=> chore(github): add holiday triage

package-lock.json, package.json
our current dependency is at v19.3.0. https://github.com/ionic-team/stencil/pull/3880 couldn't be targeted to v3-dev (because dependabot created it), so I recreated it here
this commit bumps the puppeteer minor version from 19.3.0 to 19.4.0
Build this branch with `npm ci && npm run clean && npm run build && npm pack`, then `cd tmp/` and
`npm init stencil component pptr-test`. Install the generated tarball, and `npm t`
=> chore(deps-dev): bump puppeteer to 19.4.0

.github/ionic-issue-bot.yml
GitHub Issue Number: Closes #3922
this reverts commit 82cd15d355c8b3e991a6d60afbe26e839d27de66, removing the holiday triage messaging that was introduced in https://github.com/ionic-team/stencil/pull/3923
N/A - we ran `git revert 82cd15d355c8b3e991a6d60afbe26e839d27de66` to code that was in a previously "good state" that has not changed between the original change and this revert
=> chore(github): remove 2022 holiday triage

.github/workflows/pr-assign.yml
The auto-assign action will currently run on all PRs opened, including draft PRs
This commit adds a conditional check that will prevent the action from execution on draft PRs
Initially opened this PR as a draft and the action was successfully skipped
=> fix(actions): add conditional to skip auto-assign action on draft PRs

src/declarations/stencil-public-compiler.ts
No functional changes
this commit formats the v3 codebase after upgrading prettier to v2.8.2 in the `main` branch of stencil and merging `main` into the v3 development branch
Prettier passes again
The v3 branch will fail all CI checks until we merge this 😢
=> chore(format): run prettier v2.8.2

package-lock.json, package.json
our current dependency is at v19.4.0. https://github.com/ionic-team/stencil/pull/3969 couldn't be targeted to v3-dev (because dependabot created it), so I recreated it here
GitHub Issue Number:
- Closes: https://github.com/ionic-team/stencil/pull/3969
this commit bumps the puppeteer minor version from 19.4.0 to 19.5.0
Build this branch with `npm ci && npm run clean && npm run build && npm pack`, then `cd tmp/` and
`npm init stencil component pptr-test`. Install the generated tarball, and `npm t`
=> chore(deps-dev): bump puppeteer to 19.5.0

.github/workflows/main.yml, .github/workflows/test-component-starter.yml
N/A - non-existent 
this commit adds a new workflow, test-component-starter, to the ci
workflow. it's purpose is to smoke test proposed changes in a pull
request in a stencil project. it accomplishes this by testing the
proposed changes, build stencil, install it in an instance of the
starter template, and run the template's build/test steps.
Logs tailed to verify the behavior https://github.com/ionic-team/stencil/actions/runs/3903522456/jobs/6668094925
I'll need to update the required checks should we accept this
=> chore(ci): test component starter

readme.md
When Twitter yanked API permissions, it broke our README badge:
Fix said badge
open the rich diff view to verify this works:
(Note, you'll see the old one in the diff as well, 'cause of the way GH renders removing the old on
=> chore(readme): fix twitter link

src/compiler/entries/component-bundles.ts
This updates some comments, changes one variable name, and removes an unused export in `src/compiler/entries/component-bundles.ts'.
Just a JSDoc PR.
=> chore(compiler): update JSDoc, remove unused export

src/utils/helpers.ts
This rounds out the JSDoc comments in the `helpers` file, which was a bit under-documented before.
Just a JSDoc change
=> doc(utils): round out JSDocs in `src/utils/helpers.ts`

.github/workflows/main.yml, .github/workflows/test-browserstack.yml
This branch has now been merged to `main`, so we can go ahead and remove it.
-
-
-
=> chore(ci): remove v3.0.0-dev branch from github workflows

.github/dependabot.yml
dependabot will attempt to update `@types/fs-extra` to a version of the package that stencil cannot support
- closes #4004 
this commit adds `@types/fs-extra` to the dependabot ignore list until stencil drops support for node 14. the latest versions of this package assume that `@types/node` >= 16 is installed. we cannot (or, choose not to) upgrade `@types/node` at this time, as our browserstack tests currently run on v14 of node. we do not plan on changing this until we drop support for node v14 (in stencil 4) at this time.
N/A, copies format of other ignores
=> chore(dev-deps): ignore @types/fs-extra upgrade

.github/workflows/test-browserstack.yml
Browserstack tests don't run against feature branches 
this commit updates our ci pipelines to run against feature branches of the format 'v3.(VAL)-feature' where VAL matches zero or more characters (not matching the '/' character)
this is being done so the team can try out feature branches in v3 of stencil and take advantage of browserstack tests
N/A, as we need this to land before we can test it
=> chore(ci): run browserstack against v3 feature branches

package-lock.json
In the most recent rebase of `v3.1-feature`, I broke the build :-(
this commit updates the package-lock file after rebasing the branch atop
`main`. it appears that a puppeteer upgrade that landed in `main`, which
requires the `mitt` library, were not properly carried over after merge
conflicts were resolved in this branch
Browserstack build succeeds again
I'd like to figure out a better way to handle conflicts moving forward - I don't love messing up (and having to put up a PR to fix these things) if there's a better way to handle these conflicts
=> chore(lock): sync package-lock.json 

.github/dependabot.yml, .github/workflows/test-analysis.yml, .github/workflows/test-browserstack.yml, .github/workflows/test-component-starter.yml, .github/workflows/test-e2e.yml, .github/workflows/test-unit.yml, package-lock.json, package.json, scripts/bundles/sys-node.ts, src/cli/run.ts, src/compiler/config/test/validate-config.spec.ts, src/compiler/config/test/validate-service-worker.spec.ts, src/compiler/config/transpile-options.ts, src/compiler/config/validate-config.ts, src/compiler/sys/config.ts, src/compiler/sys/typescript/typescript-resolve-module.ts, src/compiler/sys/typescript/typescript-sys.ts, src/compiler/transformers/rewrite-aliased-paths.ts, src/compiler/transformers/test/rewrite-aliased-paths.spec.ts, src/compiler/transformers/test/transpile.ts, src/compiler/transpile/run-program.ts, src/compiler/transpile/transpile-module.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts, src/testing/jest/jest-runner.ts, src/testing/mocks.ts, src/testing/test-transpile.ts, test/bundler/package-lock.json, test/bundler/package.json
this pull request includes all commits landed to the `v3.1-feature` branch
=> sync(): feature 3.1

src/cli/task-info.ts
when `npx stencil info` is run, part of the output contains a typo. e.g.:
```
Plaform: darwin (22.2.0)
```
this commit fixes a typo in the output of running `npx stencil info`,
where 'Plaform' is corrected to 'Platform'
I built this branch locally, installed the tarball in an `npm init stencil` project, and verified the change/alignment 
```
System: node 16.16.0
Platform: darwin (22.2.0)
CPU Model: Apple M1 (8 cpus)
```
=> fix(typo): fix info task output

.github/ISSUE_TEMPLATE/bug_report.yml
We're a little hand-wavy about the information that we capture at bug report time
this commit adds `npx stencil info` to the environment box in the bug report issue template, so that we can try to capture more information at the time of bug report
N/A
=> chore(github): add npx stencil info to bug report

scripts/utils/test/options.spec.ts
This PR is the base of a PR Train
The code is untested 😨 
this commit adds test coverage to the `options.ts#getOptions` helper function used when cutting a release of stencil, validating the build, and generating the license file.
the motivation for this change is to provide a baseline of tests for this function, which will change in order to facilitate ci-driven builds
Unit tests pass - I followed a 'TDD-esque' style of writing these. Since the code was already written, I made it such that I failed each test with a non-falsy value before I fixed the assertions.
=> test(release): add getOptions coverage

src/declarations/stencil-public-compiler.ts
this commit marks a few interfaces that are publicly exposed as deprecated. they will be removed in stencil v4. this commit is a spin-off of a separate body of work where we are investigating issues with the stencil dev-server. these were found while performing that investigation, and do not need to be in the pull request fixing said issues
N/A - only JSDoc changes. Linting/format should still pass.
=> chore(compiler): mark unused interfaces as deprecated

.github/workflows/test-browserstack.yml
without this, so long as the stencil github repo has a required status check for browserstack, commits cannot be merged without overriding these checks/guards
this commit updates the configuration for the browserstack ci configuration to run when either:
- a pull request is opened against the branch
- a push occurs to the branch
N/A
=> chore(v2): add v2-maintenance to browserstack ci runs

.github/dependabot.yml
Dependabot will try to bump TS
this commit updates the dependabot configuration to ignore typescript 5.0 for the auto-assign tool. we wish to keep the versions of typescript between this tool and stencil in sync, and missed adding this when adding it to the dependabot config the first time around
=> chore(github): ignore typescript 5.0 for auto-assign

src/compiler/transformers/test/core-runtime-apis.spec.ts
`core-runtime-apis.ts` is not under test
this commit adds testing around the functions exported by `core-runtime-apis.ts`. while the number of tests are small/trivial, these build a baseline for changes that we expect to make in order to help fix an issue where SOURCEMAP_ERROR is printed to the console (STENCIL-301).
=> test(compiler): add tests for core-runtime-apis

.github/dependabot.yml
Dependabot wants us to upgrade dts-bundle-generator
this commit ignores dts-bundle-generator@8.0.0 and higher. the reason for this ignore is that starting with v8, this package requires TypeScript v5.0 or higher. until stencil has support for TS 5+, ignore this package
N/A
=> chore(github): add dts-bundle-generator to dependabot ignore

test/hello-world/stencil.config.ts
A few of these slipped by when we marked them as deprecated a while ago (#3894, #3895, #3898, #3899).
-
-
-
=> chore(test): remove deprecated options from the 'hello world' app

src/declarations/stencil-public-runtime.ts
GitHub Issue Number: #4267 
Currently, trying to bind to the `cancel` event for an HTML `dialog` elements when writing a Stencil component will result in an error since the `onCancel` binding/attribute doesn't exist in our declarations. 
Adds the signature for `onCancel` to our `DialogHTMLAttributes`
Verified the ability to bind to the event handler without experiencing a lint or build error in the reproduction case
MDN spec [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/cancel_event#syntax)
=> fix(declarations): add `onCancel` to dialog element attributes

src/declarations/stencil-private.ts, src/testing/platform/testing-constants.ts, src/testing/platform/testing-host-ref.ts, src/testing/platform/testing-platform.ts, src/testing/platform/testing-task-queue.ts, src/testing/reset-build-conditionals.ts, src/testing/spec-page.ts
This code is not well documented
this commit updates/adds jsdoc to various parts of our testing infrastructure. this was pulled out of a separate effort to determine how to best support the jest 28+ upgrade. it is not strictly comprehensive (i.e. not everything is documented), but pulling this out simplifies the future pull request reviews for the jest 28+ support work
N/A - documentation only
=> chore(test): add jsdoc to testing

CONTRIBUTING.md
the existing url doesn't include the protocol. not a huge problem, but an easy nit to attack
this commit updates the URL for volta to include the protocol
N/A
=> chore(docs): update link in CONTRIBUTING.md

.github/ionic-issue-bot.yml, CONTRIBUTING.md, readme.md
we use a dead link when referring folks to slack
this commit updates the links to the stencil slack throughout the project. the entrypoint heroku app is no longer maintained. with this commit, we update our README, contributing guide, and bot replies to use a link directly to the stencil slack.
Tested that the links resolve to the Stencil slack
The component starters tests are failing due to an unrelated change (see the (Ionic workspace) Stencil slack)
=> chore(repo): update links to stencil slack

renovate.json5
Renovate isn't creating new PRs, and I believe its due to the schedule config
this commit removes the global renovate schedule (temporarily). the original schedule was too narrow/poorly defined, which caused updates to never get created. previously, updates would get scheduled if it was 7am utc. there is no guarantee the check for updates will run at that time, causing updates to be missed.
the intent is to restore _a_ schedule in the near future, one that is less restrictive
N/A
=> chore(renovate): remove schedule

.github/workflows/test-component-starter.yml
This reverts commit 8ca90584b6a56fbb378e5785b85fb93948703ca9, as a fixed version of the package has been pushed to NPM
=> chore(ci): rm @types/babel__traverse workaround

src/sys/node/test/worker-manager.spec.ts
We have SNC violations in the codebase
this commit fixes two types of violations that were found in `worker-manager.spec.ts`:
1. assertion that the `id` property exists on a `NodeWorkerMain` returned from `getNextWorker`
2. stubs for worker tasks cannot be `null` - instead provide a proper stub that conforms to the interface (only providing required fields)
=> chore(test): fix worker-manager snc violations

src/utils/normalize-path.ts, src/utils/test/normalize-path.spec.ts
this commit removes an unused property, `params`, from the return value of `normalizeFsPathQuery`. this property does not ever appear to be used, and was causing a handful of strictNullChecks violations in the corresponding tests. rather than patch the tests, we remove the property wholesale.
this commit also fixes an additional SNC violation for testing that `normalizePath` throws when a non-string is passed as an argument to the function
I tried to find any externalizations of this function, or usages of the removed property. I couldn't find any, but please check my work!
=> chore(types): remove property on path normalization

src/compiler/html/test/remove-unused-styles.spec.ts
SNC violations are like bed bugs, they're everywhere and hard to get rid of
this commit removes a handful of strictNullChecks violations from the tests for `remove-unused-styles`. all fixed violations were caused by an assumptions that the return value of `querySelector` would be non-null. while that is true (since we wrote the tests), it doesn't properly type check.
~9 SNC violations removed
=> chore(test): remove strictNullChecks from remvoe-unused-styles

.github/PULL_REQUEST_TEMPLATE.md
See 'new behavior' below
this commit removes parts of the pull request template that have outlived their purpose. they're serving as a bigger pain to update and not providing the value they once did. as a result, remove them.
N/A
⚠️ Treat this as a proposal. We don't have to do it, just something I mentioned in Slack the other day. This was an easy JEDI day PR while I shepherd Renovate PRs 😉 ⚠️
=> chore(repo): remove pull request template sections

renovate.json5
It's more difficult than I would like to gauge the current status of renovate without parsing the log 
this commit enables the dependency dashboard feature of renovate. upon applying this commit, renovate will create an issue in the repo that will include a glimpse into the status of renovate from within github.
config documentation: https://docs.renovatebot.com/configuration-options/#dependencydashboard
N/A
=> chore(repo): enable dependency dashboard

.eslintrc.js
Turn on the 'no-cond-assign' eslint rule which disallows doing assignment with a conditional, so you can't do something like
```ts
let foo = { bar : "baz" };
let keyValue = "bizboz";
if (foo.bar = keyValue) {
otherStuff();
}
```
This is generally a good idea to avoid because assignment in JavaScript evaluates to the assigned value, so assigning to a truthy value will evaluate to a truthy value while assigning a falsy value will evaluate to a falsy value. Thus if you put an assignment in a conditional the value it evaluates to will depend on the value which is assigned, and _not_ on what the variable or property already holds.
In the example above, rather than checking that `foo.bar` is equal to the value `"bizboz"` we're actually checking that `"bizboz"` is truthy. In this case that means …
=> chore(lint): turn on the 'no-cond-assign' rule

src/declarations/stencil-private.ts, src/screenshot/connector-base.ts, src/screenshot/screenshot-compare.ts, src/testing/puppeteer/puppeteer-screenshot.ts
We can drop a bunch of SNC errors here by sprinkling a few `satisfies` keywords around and also making some properties non-null.
-
=> chore(snc): fix some SNC errors relating to screenshot stuff

.github/workflows/tech-debt-burndown.yml
https://github.com/ionic-team/stencil/pull/4369 broke the output of the burndown report that makes it _very_ hard to read
the processing of the burndown report has been reworked to handle multline strings properly.
the post-processing of special characters is no longer needed, and has been removed.
A temporary pull_request workflow trigger was added to this PR to get GH to pull the changes from this PR, rather than `main`
=> chore(repo): fix output of burndown report

readme.md
this commit adds a badge to the discord to the readme
Render the rich preview, click the badge
=> chore(readme): add discord to readme

src/dev-server/client/app-error.ts, src/dev-server/client/logger.ts
=> refactor(snc): fix SNC errors in app-error.ts

.github/workflows/pr-assign.yml
this commit disables our auto-request-review functionality. the team will be exploring github's default round-robin functionality, which requires we disable this. should round-robin work out, we will remove this action. otherwise, we'll re-enable it
=> chore(repo): disable auto-request review

BREAKING_CHANGES.md
this commit backfills + adds additional details to the `BREAKING_CHANGES.md` file in the repo
N/A - spell check passes 
This commit has a sibling PR in the Doc Site repo - https://github.com/ionic-team/stencil-site/pull/1150
=> docs(v4): backfill v4 breaking_changes

readme.md
remove legacy browser mention now that stencil v4 has been released
N/A
=> chore(readme): remove legacy browsers

src/cli/telemetry/telemetry.ts, src/cli/telemetry/test/telemetry.spec.ts, src/declarations/stencil-private.ts
=> refactor(telemetry): remove browser-specific code from telemetry

scripts/build.ts, scripts/bundles/internal.ts, scripts/bundles/utils.ts, src/cli/find-config.ts, src/cli/run.ts, src/compiler/build/build-ctx.ts, src/compiler/build/build-stats.ts, src/compiler/build/test/build-stats.spec.ts, src/declarations/stencil-private.ts, src/utils/index.ts, src/utils/result.ts, src/utils/test/result.spec.ts
This commit was initially added in #4281 and then reverted in #4415.
This adds a new way to handle return types like those of the `generateBuildStatus` function. See here for some previous conversation about this:
At present in `main` this function returns `d.CompilerBuildStats | { diagnostics: d.Diagnostic[] }`:
https://github.com/ionic-team/stencil/blob/b5dc6d533f7961641e4876fe3411834884748b2f/src/compiler/build/build-stats.ts#L11-L14
We use this sort of pattern in a few places throughout the codebase, where basically if a function could generate diagnostic messages it will return either it's 'normal' return value _or_ an object holding those diagnostics. We then typically have some manual checking to see which of the two it is, or perhaps just a type assertion.
This pattern works …
=> refactor(compiler): add a Result union type for polymorphic returns

scripts/readme.md
this commit fixes a few minor issues with the readme that includes the instructions for releasing stencil:
1. fixes local links to follow-up steps
2. adds a template for thanking members of the community that contribute commits to the release
N/A
Was giving this a read over prior to Monday's release - and I missed a couple things (here's the ones that I realized I missed 🙃)
=> chore(release): update readme

src/declarations/stencil-private.ts
We have several types in the compiler that appear to be unused. This expands the size of the codebase, and makes it hard to reason about what's actually needed/used in modern Stencil.
this commit removes several types that are unused in the stencil codebase. these have previously gone undetected due to their being exported by `src/declarations/index.ts`.
I built this branch (`npm run clean && npm ci && npm run build && npm pack`) and installed it into the Framework's `feature-7.3` branch. I spun up the local dev server, and played around with datetime and accordion to see if anything was logged.
these types are not used within the stencil codebase. _however_ it is possible that a consumer is reaching into our internal type declarations to use these types. those …
=> chore(declarations): remove unused types

src/compiler/transformers/decorators-to-static/convert-decorators.ts
These important functions were previously undocumented.
-
=> docs(compiler): add JSDoc to convert-decorators.ts

src/utils/logger/logger-rollup.ts
Just fixing a few SNC errors I found in here
-
=> chore(snc): fix 5 SNC errors in logger-rollup.ts

RELEASE.md
this commit adds a few additional clarifying notes following the v4.2.0 release
N/A
=> chore(repo): update release instructions

RELEASE.md
Just found one ambiguity and one lil typo as I was doing the release today.
-
=> docs(release): update RELEASE.md after releasing 4.2.1 

test/karma/test-app/delegates-focus/karma.spec.ts
this commit reverts #4471
Browserstack tests continue to pass
Found this while culling the backlog yesterday afternoon, felt like a good/quick win to just close out
=> test(delegates-focus): re-enable test

src/declarations/stencil-public-compiler.ts
this commit splits off jsdoc from a proof-of-concept branch to prevent the docs from getting lost/dropped
N/A
=> chore(jsdoc): add jsdoc to TestingRunOptions

renovate.json5
this commit re-enables renovate on the karma directory. we're doing this now as we're currently looking to fix up some of the dependencies in the karma directory (#4810). in doing so, we believe that this will help keep the versions of typescript used in the projects in sync
We'll have to wait and see after we merge this - worst case scenario, we end up reverting it
=> chore(repo): enable renovate on karma directory

scripts/tech-debt-burndown-report.ts
this commit removes the `TSError` message field from the table printed in pull requests. it was causing the team to go over the limit of github comment character limits, causing the comment to be truncated
https://github.com/ionic-team/stencil/pull/4813#issuecomment-1724330889 is no longer truncated :-)
=> chore(ci): remove messages from tech debt burndown

src/client/client-host-ref.ts, src/declarations/stencil-private.ts
Add documentation to `src/client/client-host-ref.ts`
-
=> docs(runtime): document `HostRef`

src/runtime/runtime-constants.ts, src/runtime/vdom/vdom-render.ts
Adding some documentation reflecting what I _think_ all these things are for!
-
=> docs(vdom): comment some slot-related code

src/testing/jest/jest-27-and-under/matchers/text.ts
There's a couple SNC violations in this matcher that I wanted to resolve before "porting" them over to Jest 28.
resolve two strictNullChecks violations in the `toEqualText` jest matcher:
1. ensure that when `textContent` on an `HTMLElement` is `null`, default to an empty string before replacing 2+ contiguous spaces in the text.
2. simplify conditional if the input is _not_ an `HTMLElement`. the start of the matcher already throws if the provided input argument is nullish. as a result, the `else if` conditional is redundant
Pull down this branch and build it. Make note of the location of the generated tarball:
```bash
npm run clean \                   
&& npm ci \
&& npm run build \
&& npm pack
```
Next, create a new stencil component library with that tarball: …
=> chore(snc): resolve errors in text matcher

src/declarations/stencil-private.ts, src/dev-server/client/hmr-components.ts, src/runtime/bootstrap-lazy.ts, src/runtime/hmr-component.ts, src/runtime/initialize-component.ts
This adds JSDoc and inline comments to some HMR related code, mainly just recording my understanding of what this code does / is supposed to do.
Most of this stuff isn't documented at all!
Now it is 😅
This should be a comment-only change so I don't think any functionality should be meaningfully impacted.
=> docs(hmr): document some HMR related functions

src/dev-server/client/hmr-images.ts, src/dev-server/client/hmr-inline-styles.ts, src/dev-server/client/hmr-util.ts
Add some documentation to `src/dev-server/client/hmr-util.ts` and friends
This should be a comment-only change
=> docs(dev-server): document hmr utils

src/compiler/bundle/ext-format-plugin.ts, src/compiler/fs-watch/fs-watch-rebuild.ts, src/utils/logger/logger-utils.ts, src/utils/path.ts, src/utils/test/path.spec.ts
SNC violations are bad
There are less of them 🎉 
Tests continue to pass
=> chore(utils): handle a few SNC violations related to path extensions and diagnostics

RELEASE.md
I wrote the original instructions without blog posts in mind. Since we have one dropping on Wednesday-ish, let's update those instructions!
update the documentation to:
1. call out telling devrel about the blog post
2. posting the blog in Discord
the instruction to end the code freeze has been moved up, as we don't need to wait so long to end it (and haven't in practice.
N/A
=> chore(release): update instructions for blog posts

src/testing/jest/README.md
create a README file that instructs folks how to add support for a new version of jest
n/a - readme only (although these steps are being followed/created as we add support for newer versions of jest, so I suppose technically we're testing it)
I wanted to push this up & get it out of my Jest 28+ branch. I'll mark it ready for review once Jest 28 is ready for review.
=> chore(jest): add directions for adding new jest support

src/compiler/output-targets/output-www.ts
Just adding jsdoc to this file
no docs!
docs!
=> docs(output-targets): document WWW OT

src/compiler/prerender/prerender-main.ts, src/compiler/sys/stencil-sys.ts, src/compiler/sys/worker/sys-worker.ts, src/compiler/worker/main-thread.ts, src/compiler/worker/worker-thread.ts, src/declarations/stencil-private.ts, src/declarations/stencil-public-compiler.ts, src/sys/node/node-worker-controller.ts, src/sys/node/node-worker-main.ts, src/sys/node/node-worker-thread.ts, src/sys/node/worker.ts
This documents a bunch of code related to our node.js worker setup.
Decided to do this while working on #5010. I didn't understand this code much before! Now I understand it a bit better.
This mainly adds JSDoc but also does a little bit of typing improvements.
=> refactor(worker): document worker code, improve types

src/testing/testing-utils.ts
Just adding some checks that values are the right type before we use them to fix a few SNC errors.
I think if CI is all green then we should be good!
=> chore(snc): fix snc errors in src/testing/testing-utils.ts

src/testing/test-transpile.ts
Just fixing some snc errors in this file
There's a few errors here!
There are now fewer errors! Amazing!
I think if CI is passing and whatnot we should be good.
=> chore(snc): fix snc error in src/testing/test-transpile.ts

src/testing/testing.ts
Just fixing a few SNC errors in `src/testing/testing.ts`
Errors!
Errors? Well yes still errors, but fewer!
=> chore(snc): fix snc errors in src/testing/testing.ts

scripts/bundles/compiler.ts
This removes some code which purportedly rewrote the compiler bundle to remove a call to `process.binding` because it's deprecated.
The only `process.binding` call that _would_ otherwise be included in the bundle comes from the
[`builtin-modules`](https://github.com/sindresorhus/builtin-modules/) package which is included because it's a dependency of Rollup's node-resolve plugin and `eslint-plugin-jsdoc`
`process.binding` is an internal API which has to do with how node.js interfaces with native code. `builtin-modules` uses it here as a fallback way to get a list of builtin modules:
https://github.com/sindresorhus/builtin-modules/blob/0d234f3ad3965c57d8cc5b9ca198c505fe032452/index.js#L9-L11
The motivation for removing this rewrite from the compiler bundle is that the code of interest …
=> refactor(build): stop removing process.binding in compiler

CONTRIBUTING.md
we do not prescribe that folks should link a GH issue to a pr in our contributing guidelines. these guidelines are also used by the stencil team and are our primary source of commit message guidelines. 
add a not regarding 'fixes' text to the git commit message footer section
N/A - if spell check passes, we should be OK!
=> chore(contributing): update footer info

CONTRIBUTING.md
I don't think our `CONTRIBUTING` instructions are as clear as they could be
split feature request steps out from "reporting an issue" to provide some additional clarity around the feature request process.
update the issue reporting steps to clarify that we'd prefer 1 issue per report
Docs update only. Please double check my spelling/grammar 😅
=> chore(repo): clarify issues/feature requests

src/compiler/build/validate-files.ts
We have a series of strictNullChecks violations in our codebase
update the function signature of `validate-files#validateBuildFiles` to observe pre-existing `null` return values. doing so resolves two strictNullChecks violations
the commit here only affects the type system, where the function signature's return type is updated to match what the function actually returns. as a result, there's no functional changes to the codebase (it doesn't affect end users). if the type checker passes, this should be good to go
=> chore(snc): update validateBuildFiles fn signature

RELEASE.md
we have a few out of date steps in our release guide
remove the #whathappened Slack channel instructions from the release steps. this channel no longer exists and a new automated channel has been stood up in its place (#github_releases). since there was one item under the 'left folks in Ionic know...' section, remove the section 'header' and just replace it with the discord/blog post stuff.
N/A - markdown only
=> chore(repo): update release notification steps

.github/PULL_REQUEST_TEMPLATE.md
We don't have a 'docs' section in this template
add a documentation section to the pull request template in order to serve as a reminder to link an implementation with its documentation.
the dash/bullet point in the 'new behavior' section is removed, as i don't believe anyone uses it 
Verified that this template still renders properly in GH using the 'rich diff' view
=> chore(repo): add docs section to pr template

src/mock-doc/serialize-node.ts
Just a little SNC PR for `src/mock-doc/serialize-node.ts`. This is mostly possibly-undefined property access related issues.
I don't think this should result in any runtime behavior changes.
=> chore(snc): fix snc errors in src/mock-doc/serialize-node.ts

scripts/bundles/testing.ts, scripts/esbuild/testing.ts
This ports the fix which we landed in #5145 from the Rollup build to Esbuild. This will ensure that if Stencil is built with Esbuild and then installed in a puppeteer-free context it will still work!
We have a previous issue (#4526) which reported this issue with the Rollup build (well, with a published version of Stencil) but the fix for that issue (#5145) wasn't ported over to Esbuild SO if you build Stencil with Esbuild and then, for instance, install it in Framework you can reproduce the same problem. No good!
This pulls out the fix from the Rollup build as a separate function and then adds it to the Esbuild script for building `testing/`.
First make sure you can repro the issue on `main` with Framework.
On `main`:
- do
```sh
npm run build.esbuild && npm pack
```
- install the …
=> chore(): port puppeteer.d.ts patch fix to esbuild

test/karma/test-app/components.d.ts, test/karma/test-app/scoped-slot-text/index.html, test/wdio/scoped-slot-text/cmp.test.tsx, test/wdio/scoped-slot-text/cmp.tsx
=> chore(test): migrate scoped-slot-text

test/karma/test-app/components.d.ts, test/karma/test-app/svg-attr/index.html, test/wdio/svg-attr/cmp.test.tsx, test/wdio/svg-attr/cmp.tsx
Another day, another wdio port.
GitHub Issue Number: #5458
=> chore(wdio): port svg-attr test suite to wdio

RELEASE.md
We've got switched parens/brackets for the changelog link in the release instructions
fix a link to the changelog in the release steps. simply a case of broken markup
N/A
N/A
=> chore(release): fix link to changelog

CONTRIBUTING.md
A community member let us know that our CONTRIBUTING docs weren't up to date - this fixes that
update the instructions for installing dependencies. jest is currently a requirement for building stencil itself - now that we have a dedicated script for this, i didn't see any harm of folks running it.
created based on a conversation in the discord community - https://discord.com/channels/520266681499779082/1228314767505227798/1228314767505227798
N/A
N/A
=> chore(repo): update jest dependency instructions

test/wdio/slot-ref/index.html
Just removing an html file which doesn't appear to be necessary.
You can confirm the tests work by doing
```sh
cd test/wdio
npm run build
npm run wdio -- --spec slot-ref
```
=> chore(wdio): remove unnecessary html file

package-lock.json, package.json
This reverts commit e7f8129827ee279b8c3cbf07e749f581dd8b3c5a.
=> Revert "chore(deps): update dependency execa to v9 (#5758)"

src/runtime/bootstrap-lazy.ts, test/end-to-end/src/miscellaneous/test.e2e.ts
Class names aren't sorted an appear in random order.
GitHub Issue Number: #2808
Sort them.
Added an e2e test for this.
n/a
=> chore(runtime): sort hydration class names

package.json, test/end-to-end/exportMap/index.js
GitHub Issue Number: fixes #5906
Another missing export in our map.
n/a
Added e2e test.
n/a
=> fix(core): add missing screenshot export

src/runtime/bootstrap-lazy.ts
=> fix(runtime): clean `deferredConnectedCallbacks` array on `disconnectedCallback`

src/runtime/client-hydrate.ts, src/runtime/test/hydrate-shadow-in-shadow.spec.tsx, test/wdio/ssr-hydration/cmp.test.tsx, test/wdio/ssr-hydration/custom-element.html
GitHub Issue Number: https://github.com/stenciljs/core/issues/6293
fixes https://github.com/stenciljs/core/issues/6293
=> fix(ssr): retain slotted node order in serializeShadowRoot: `scoped`

.github/SECURITY.md
Currently, the Stencil project does not have a formal security policy or threat model documentation. Developers and security researchers lack clear guidance on:
- How to report security vulnerabilities
- Understanding the security implications of different Stencil components
- Best practices for secure Stencil application development
- Threat prioritization and mitigation strategies
This PR adds a comprehensive `SECURITY.md` file that includes:
1. **Security Reporting Policy**: Clear instructions for reporting security vulnerabilities via email instead of public GitHub issues
2. **Comprehensive Threat Model**: Detailed analysis of 14 security threats across all Stencil components:
- Stencil Compiler (3 threats)
- Dev Server (3 threats) 
- Client-side Runtime (3 …
=> docs(security): add SECURITY.md with threat model

src/runtime/vdom/vdom-render.ts, test/wdio/ssr-hydration/cmp.test.tsx, test/wdio/ssr-hydration/slow-prop.tsx
GitHub Issue Number: https://github.com/stenciljs/core/issues/6324
Fixes https://github.com/stenciljs/core/issues/6324
=> fix(ssr): slow property hydration, incorrect rendering

src/runtime/client-hydrate.ts, src/runtime/test/hydrate-shadow-in-shadow.spec.tsx, test/wdio/ssr-hydration/cmp.test.tsx, test/wdio/ssr-hydration/order-cmp.tsx, test/wdio/ssr-hydration/scoped-parent-cmp.tsx, test/wdio/ssr-hydration/shadow-child-cmp.tsx
- https://github.com/stenciljs/core/issues/6337
- https://github.com/stenciljs/core/issues/6339
Fixes https://github.com/stenciljs/core/issues/6337
Fixes https://github.com/stenciljs/core/issues/6339
=> fix(ssr): `scoped: true` components forwarded slots

src/compiler/transformers/static-to-meta/class-extension.ts, src/compiler/transformers/static-to-meta/visitor.ts, src/runtime/test/extends-basic.spec.tsx
GitHub Issue Number: #6399
Fixes #6399
=> fix(test): trigger @Watch decorators on inherited classes in jest env
