.github/workflows/test-component-starter.yml

Smoke tests for the component starter will fail under node 14 with the following:
```
[03:11.4]  @stencil/core
[03:12.2]  [LOCAL DEV] v3.4.1-dev.1688761098.7e0fe1b
[03:12.4]  testing e2e and spec files
[ ERROR ]  Unexpected token '??='
D:\a\stencil\stencil\tmp-component-starter\node_modules\puppeteer-core\lib\cjs\puppeteer\common\util.js:399
```
this commit pins the version of puppeteer used by the component starter smoke tests. newer versions of puppeteer use the `??=` operator, which node 14 doesn't know how to parse. since the component starter's versioning is only expressed in git (and the cli doesn't know how to download a specific version backed by a git-sha), we pin the version of puppeteer to a known working version for node 14.
CI passes for all component …

chore(ci): pin puppeteer for node 14 starter tests (v3)

---

.github/workflows/test-browserstack.yml

this commit updates the `test-browserstack` workflow to allow for browserstack to run when the `v3-maintenance` git branch is either a pull request target (i.e. someone created a PR against the branch) or when the branch is pushed to (i.e. someone merged a PR).
N/A - Browserstack should run (note the target branch is `v3-maintenance`), but we have to merge this first 😢

chore(ci): add v3-maintenance to test-browserstack (v3)

---

src/compiler/transformers/map-imports-to-path-aliases.ts
src/compiler/transformers/test/map-imports-to-path-aliases.spec.ts

This is just a back-port of a fix made in v4. See #4552 for details of this change and testing steps

fix(compiler): ensures transformed paths are relative paths for `dist-collection` (v3)

---

src/compiler/bundle/typescript-plugin.ts
src/compiler/sys/typescript/typescript-resolve-module.ts
src/compiler/sys/typescript/typescript-sys.ts
src/compiler/transformers/collections/add-external-import.ts
src/compiler/transformers/collections/parse-collection-components.ts
src/compiler/transformers/collections/parse-collection-manifest.ts
src/compiler/transformers/collections/parse-collection-module.ts
src/compiler/transformers/static-to-meta/import.ts
src/compiler/transformers/static-to-meta/parse-static.ts
src/compiler/transformers/static-to-meta/visitor.ts
src/compiler/transformers/test/transpile.ts
src/compiler/transpile.ts
src/compiler/transpile/transpile-module.ts

This propagates the `ValidatedConfig` in place of the `Config`, branching out from `src/compiler/transpile.ts`
Not enough `ValidatedConfig`
A bit more `ValidatedConfig`
I don't think this should affect anything, and should really only give us more safety, so just make sure that things are working as they should be!

refactor(compiler): propagate `ValidatedConfig`

---

src/compiler/output-targets/dist-lazy/lazy-output.ts
src/compiler/output-targets/output-lazy-loader.ts

This fixes an issue with the type for `defineCustomElements` that we set in output-lazy-loader.ts. In #4419 we changed the return type of the function to be `void` (at runtime) but we didn't make a corresponding adjustment to the type declaration for the function that we generate here:
https://github.com/ionic-team/stencil/blob/7d5dc6cf5e0d2020c513cc87b6b2e5b93eece9bc/src/compiler/output-targets/output-lazy-loader.ts#L88
This change adjusts that type declaration to have a `void` return value, instead of `Promise<void>`.
You'll get a type error when you're actually using things correctly, while code that type-checks will not work at runtime. Not good!
The runtime behavior is now accurate described by the type declaration.
On #4589 there is a reproduction case linked. If you clone that …

fix(lazy): adjust the type of `defineCustomElements`

---

renovate.json5

we're ignoring a few packages that we don't need to anymore in renovate
this commit removes a handful of packages that were being ignored by renovate either due to requiring us to drop Node 14 or adopt TypeScript 5. now that we've done both, let's get these packages back up to date.
N/A - if something should come up (e.g. we can't upgrade a package) we can always re add it to the list

chore(repo): remove package ignores

---

scripts/release-tasks.ts
scripts/utils/conventional-changelog-config.ts
scripts/utils/release-utils.ts

When we run the release scripts, conventional-changelog parses the git commit
messages from the last release to the HEAD of the `main` branch in order to determine
what should be included in the changelog. Stencil uses the Angular preset to inform
conventional-changelog that we use Angular's flavor of conventional commits.
The Angular preset defaults the "issue prefix" setting to "#". As a result, when a commit
is being parsed, any time a "#" is found, conventional changelog assumes that it is an issue
and adds the "closes #[NUMBER]" text to the changelog. This can prove to be wrong more
often than not, especially when the team cross references issues/pull requests. As an example,
commit https://github.com/ionic-team/stencil/commit/1d79672809dcaa3b56ec3761e46f9d1ef51915ad includes the …

chore(release): override angular issue prefixes 

---

src/cli/check-version.ts
src/declarations/stencil-public-compiler.ts

this commit updates the typings of `check-version` functions, to make it clear that they can return `null` (in theory). in practice, i don't believe this is possible. however, fixing that would require a breaking change. for now, we'll fix the typings for 4.X and come back and remove null checks for 5.x.
N/A

refactor(cli): update check-version typings

---

.github/workflows/release-production.yml
package.json
scripts/readme.md
scripts/release-tasks.ts
scripts/release.ts

I (@rwaskiewicz) manually release Stencil. This is problematic for a few reasons, so let's fix that so anyone on the team can release!
this commit allows for production releases to be kicked off from a ci workflow (github actions). it updates the `release-production` workflow automate the following manual tasks:
1. running the prerelease scripts, which bundles stencil, validates the output, runs tests, etc.
2. commits the changes
3. pushes the release artifact/tag to npm
4. pushes the git tag to github
this commit is a stopgap to enable the rest of the team to be able to perform releases. it is not our long term solution. rather, it fixes the blocker that is rwaskiewicz when he goes on vacation ;-)
I've been hacking at this for a bit, but the proof is probably in …

chore(ci): enable production ci releases

---

src/declarations/stencil-public-runtime.ts

Currently stencil is lacking the `onSelect` attribute on the `<input>` and `<textarea>` html elements, so trying to use them fails to compile.
https://github.com/ionic-team/stencil/issues/4617
-  adds the attribute to these elements.
I monkey patched this into my app which then was able to compile and the attribute was added to the html element correctly.
Apparently this has been around for ages and is well supported:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select_event
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/select_event

fix(runtime): add onSelect to textarea and input

---

src/compiler/transformers/static-to-meta/encapsulation.ts
src/declarations/stencil-private.ts
src/utils/constants.ts

No JSDoc :-(
this commit adds jsdoc to stencil's `CMP_FLAGS` enumeration, to help clarify the usage of each variant in the enum. this is intended to help guide the discussion around slots, scoped components, etc. as we work to improve various bugs related to this part of the code over the next few weeks
N/A - added JSDoc/filled in existing types to function signatures

chore(jsdoc): add docs to component flag values

---

src/compiler/output-targets/dist-hydrate-script/bundle-hydrate-factory.ts
src/compiler/output-targets/dist-hydrate-script/generate-hydrate-app.ts

this commit removes an unused function for getting `BuildConditionals` for the hydrate output target.
`src/compiler/output-targets/dist-hydrate-script/bundle-hydrate-factory.ts#bundleHydrateFactory` had a declared parameter `_build`, whose value is unused in the body of the function. `bundleHyrdateFactory` is not exported by stencil, and only has one callsite at
`src/compiler/output-targets/dist-hydrate-script/generate-hydrate-app.ts#generateHydrateFactory`. the argument passed to `bundleHydrateFactory` was generated by calling a `generate-hydrate-app#getHydrateBuildConditionals` function. however, the build conditionals have not been used since a refactor that occurred in dd6f1e177bd57f649f713fb01aec8252848d5e80, where it was used by the legacy hydrate build …

refactor(hydrate): remove unused build conditionals

---

src/app-data/index.ts
src/compiler/app-core/app-data.ts
src/compiler/bundle/app-data-plugin.ts

How `BUILD` gets set isn't super clear.
- this commit adds a small explanation as to how BUILD conditionals get set at compile time of a Stencil project
I did tighten some types (`Config` -> `ValidatedConfig`). The type checker ought to catch any issues

chore(build): document build conditionals

---

src/declarations/stencil-private.ts
src/declarations/stencil-public-runtime.ts
src/runtime/update-component.ts
src/runtime/vdom/set-accessor.ts
src/runtime/vdom/vdom-render.ts
test/karma/test-app/components.d.ts
test/karma/test-app/host-attr-override/host-attr-override.tsx
test/karma/test-app/host-attr-override/index.html
test/karma/test-app/host-attr-override/karma.spec.ts

This adds a runtime check for attributes set on the host element instance ('from outside') before the attributes set on the `Host` component ('from inside') are set on it, to allow developers to, for instance, override a `role` attribute set on `Host` (see #3052 for instance)
I have a reproduction case up here: https://github.com/alicewriteswrongs/stencil-host-override
If you build that project with this branch of Stencil you should see that the `role` set on the custom element in HTML wins out over the value set on the `Host` element.

fix handling of host attributes

---

src/declarations/stencil-public-compiler.ts
src/testing/puppeteer/puppeteer-declarations.ts
src/testing/puppeteer/puppeteer-page.ts

The implementation for the existing `emulate` field on the testing config is very unclear. This value only come into effect when screenshot testing is enabled.
GitHub Issue Number: Fixes #4601 
- Removes the logic in the `newE2EPage()` related to the `emulate` config value.
- Updates the documentation on the `emulate` field to make it clear that it only applied to screenshot testing
- A follow-up PR for the Stencil documentation (https://github.com/ionic-team/stencil-site/pull/1191) will add a recipe to the documentation for emulating device viewports in e2e tests
Automated unit and e2e tests continue to pass.
**Manual tests**
1. Clone the repro in the associated issue (https://github.com/jongirard/stencil-emulate-viewport-bug)
2. Add the following code snipped to the …

fix(testing): remove use of `emulate` field in `E2EPage()`

---

src/compiler/output-targets/dist-custom-elements/custom-elements-types.ts
src/compiler/output-targets/test/custom-elements-types.spec.ts

If the `dist-custom-elements` output target is configured to write to the top-level distribution directory (i.e `dist`), the paths generated that reference the typedef files are invalid.
GitHub Issue Number: Fixes #4630 
Generated paths will be correctly "relativized" 
Unit tests continue to pass and a new test was added for this use case
**Manual tests**
1. Create a component starter (`npm init stencil components <name>`)
2. Update the output targets in the `stencil.config.ts` to set the `dist-custom-elements` target as follows:
```ts
{
type: 'dist-custom-elements',
dir: 'dist',
customElementsExportBehavior: 'single-export-module',
}
```
3. Run `npm run build`. Open `dist/my-component.d.ts` or `dist/index.d.ts` and observe there are invalid paths
4. Install a build of …

fix(compiler): custom elements relative typedef import paths

---

renovate.json5

this commit (temporarily) adds glob, minimatch to the renovate ignore list. a ticket has been added to the stencil backlog to address this item of tech debt, as it's more effort than originally envisioned to 'simply' upgrade this (see ticket for additional info)
N/A
The upgrade is blocked by our rollup upgrade, sadly :-(
I'll close #4611 and #4625 (temporarily) since I don't think we're going to get to this this quarter

chore(repo): add glob, minimatch to renovate ignore list

---

src/declarations/stencil-public-runtime.ts

GitHub Issue Number: Fixes: #4643 
this commit adds function declarations for the following events:
- [`onTransitionCancel`](https://developer.mozilla.org/en-US/docs/Web/API/Element/transitioncancel_event)
- [`onTransitionRun`](https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionrun_event)
- [`onTransitionStart`](https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionstart_event)
note that `onTransitionCancel` was  not natively supported by Chrome & Edge until v87. this version falls _after_ stencil's currently supported version of v79+ for both. this commit does not transpile code for the event/provide a polyfill for versions of Chrome/Edge released before 2020.11.17
1. Pull down the reproduction provided in #4643 and install the dependencies, OR
```
npm init …
```

fix(typings): add additional transition events to DOMAttributes

---

src/compiler/sys/typescript/tests/typescript-config.spec.ts
src/compiler/sys/typescript/typescript-config.ts

When `tsconfig.json#include` contains a relative path:
```
"include": [
"./app/javascript"
],
``` 
and `tsconfig.json#srcDir` includes the non-relative version of that path:
```
srcDir: 'app/javascript',
```
then you receive a very confusing error:
```
[ WARN  ]  tsconfig.json "include" required
In order for TypeScript to improve watch performance, it's recommended the "tsconfig.json" file should have
the "include" property, with at least the app's "app/javascript" directory listed. For example: "include":
["app/javascript"]
```
GitHub Issue Number: #4667 
this commit fixes a bug where a user was unable to use relative paths in the `include` property of their `tsconfig.json` file if `srcDir` was also specified. 
- Unit tests have been added to the function in question
- Tested a dev build …

fix(compiler): match tsconfig include paths properly

---

jest.config.js

We have a jest config that is shared both internally and externally, and is one of the blockers to the jest 28+ upgrade.
this commit separates stencil's internal testing jest configuration (used when running unit tests on the stencil project itself), and the jest configuration used by stencil projects (when a stencil user runs `npm t` in their project).
with this commit, we remove the inheritance on the jest configuration that we bundle with stencil for end users. in order to ensure that stencil's internal tests continue to function, the internal jest config has been updated to have near parity with the external one. the intent of this commit is _not_ to optimize the jest config, but rather separate the two so that we can begin to bring support for newer versions …

chore(repo): split internal and user-facing jest config

---

src/runtime/test/globals.spec.tsx
src/runtime/update-component.ts
src/testing/platform/testing-build.ts
test/end-to-end/src/build-data/build-data.spec.ts

The changes to testing build conditionals made [here](https://github.com/ionic-team/stencil/commit/b203263482140fde31edfb7a91ac6054f5f98460#diff-4bb40df78659571d0bbbd5cd771c28484c1a1c9beefd451d6d004c7d4ed0c80f) were causing tests to fail in the Ionic Framework.
This commit adds a check for `isTesting` in addition to `isBrowser` so that the forceUpdate logic can run in test environments without needing to change the testing build conditional values. These changes were causing tests to fail in Framework.
Installed a build of this branch in the framework `feature-7.3` branch and confirmed the reported test failures are resolved. Also confirmed that all internal Stencil tests (unit & e2e) continue to pass.

fix(runtime): adds a testing check to the forceUpdate method

---

src/declarations/stencil-public-runtime.ts

GitHub Issue Number: #4685 
this commit adds the `crossorigin` html attribute for image tags (`img`) to stencil's public runtime typings. upon applying this commit, projects using stencil should be able to type the following in their `render` function and not receive a typing error:
```tsx
render() {
return <img crossorigin="anonymous"></img>
}
```
A type error is shown in editors and the output of the build command in v4.0.4:
```
stencil build --docs
[55:43.3]  @stencil/core
[55:43.4]  v4.0.4 🍧
[55:44.3]  build, img-test, prod mode, started ...
[55:44.3]  transpile started ...
[55:45.4]  transpile finished in 1.07 s
[ ERROR ]  TypeScript: src/components/my-component/my-component.tsx:32:14
Type '{ crossorigin: string; }' is not assignable to type …
```

fix(typings): add crossorigin html attr to img

---

src/compiler/output-targets/dist-custom-elements/custom-elements-types.ts
src/compiler/output-targets/dist-custom-elements/index.ts
src/compiler/output-targets/test/custom-elements-types.spec.ts
src/compiler/output-targets/test/output-targets-dist-custom-elements.spec.ts

`getAssetPath` is not exported from the generated `index.js` file for the `dist-custom-elements` build
- Adds `getAssetPath` to the generated export statement
- Add a function declaration for `getAssetPath` to the typedef file generation
Updated unit tests so `getAssetPath` is included in checked output string
1. Build, pack, & install this branch into a component starter
2. Run `npm run build`
3. Verify that the `export` statement in `dist/components/index.js` includes `getAssetPath`
4. Verify that there is a type declaration in `dist/components/index.d.ts` for `getAssetPath`

feat(compiler): include `getAssetPath` in generated export statement

---

.github/workflows/create-production-pr.yml

our automated release process for production isn't compatible with the merge queue we have set up
this commit creates a new action that will (eventually) go on to create
pull requests for the stencil team when it is time to release a new
version of the library. the (eventual) intent is for stencil engineers
to run this workflow, which will generate a pull request that includes:
- version bumps in package.json & package-lock.json
- changelog, notice, and license generation
this commit currently only creates a new branch and commit. the branch
includes the version string, as well as the run/attempt in github
actions to tie us back to the run that created it.
at this point, the creation of the pull request is not included. the
intended library to use …

chore(repo): create initial pull request action

---

src/compiler/config/test/validate-config.spec.ts
src/compiler/config/validate-config.ts
src/declarations/stencil-public-compiler.ts

Docs PR here: <https://github.com/ionic-team/stencil-site/pull/1196>
Too many different slot fix config values!
if you set `config.extras.experimentalSlotFixes` to `true` then you'll automatically get all the other slot fix configuration options set to `true` as well.
Try setting the value to `true`! You should see relevant values in `config.extras` get set to `true` as well.

feat(config): add experimentalSlotFixes config value

---

readme.md

this commit fixes the discord badge. previously, it was not clickable/did not link properly to the stencil discord. instead, it opened the badge image in a new tab. now, clicking the badge should link to discord
- View the rich diff, click the badge

chore(readme): fix discord badge

---

scripts/release-tasks.ts

The work-in-progress workflow to create a pull request for a release is slow to test, as we do a bunch of duplicate work before we generate the changelog, bump versions, etc.
this commit updates the prerelease scripts to skip entries that are covered by github actions. when we (eventually) can run this workflow to create a pull request with the version bump, changelog generation, etc., certain steps will be run by github actions for us (as we gate on them to land code):
- getting dependencies
- building stencil
- unit/karma tests
- validating the output build
this 'speeds up' the prerelease task by avoiding a bunch of duplicate work
I've tested this by running a special one-off branch in GH Actions. The purpose of this commit is really to speed up the development …

chore(release): skip prerelease tasks covered by github actions

---

src/compiler/transformers/decorators-to-static/decorator-utils.ts
src/compiler/transformers/decorators-to-static/decorators-constants.ts

This adds a new `ReadonlyArray` called `STENCIL_DECORATORS` which holds a list of the named decorators supported in Stencil and also adds a new type derived from that value called `StencilDecorator`. This type is then used to annotate the `isDecoratorNamed` function as an additional guard against typos.
This just adds some type-level assurance that when we're checking for decorator names we're not making any typos.
I don't think this should have any runtime impact, so if the test suite passes I think we should be good!

refactor(compiler): add types for supported decorators

---

.github/workflows/create-production-pr.yml
RELEASE.md

this commit adds the initial workflow step to create a pull request using the action. it currently has a few limitations regarding access tokens, but is usable with a small workaround (noted in RELEASE.md)
I ran the workflow per the instructions in `RELEASE.md`, whose results can be seen [here](https://github.com/ionic-team/stencil/actions/runs/5931698742).
[This created a PR](https://github.com/ionic-team/stencil/pull/4715), which I closed/re-opened to verify the workflows ran
in that PR, you'll notice that some of the license text is removed. As far as I can tell, some of the TXT/MD files aren't getting picked up in GH Actions. I'm not sure if they're not there (I need to check), or if something else is awry. I'm also simultaneously trying to chase down what our …

chore(ci): create release pull requests

---

src/compiler/transformers/decorators-to-static/component-decorator.ts

This adds JSDoc comments to functions responsible for transforming the `@Component` decorator to static which were previously undocumented. It also includes a few code changes to make it a bit more obvious what one function is doing (variable renames and the like).
These functions are just sitting there!
Just documenting a few functions!
The code changes are limited to renaming things and type-level changes, so I don't have too many concerns there.

docs(compiler): add JSDoc to `component-decorator.ts`

---

src/compiler/output-targets/dist-custom-elements/index.ts
src/compiler/output-targets/dist-lazy/generate-lazy-module.ts
src/utils/sourcemaps.ts
src/utils/test/sourcemaps.spec.ts

Typing is just a little bit insufficient here, we can clean it up!
I think this knocks down the SNC errors by just a few.

chore(snc): fix errors stemming from `rollupToStencilSourceMap`

---

src/compiler/transformers/component-native/native-component.ts
src/compiler/transformers/component-native/native-connected-callback.ts
src/compiler/transformers/component-native/native-element-getter.ts
src/compiler/transformers/component-native/tranform-to-native-component.ts
src/compiler/transformers/watcher-meta-transform.ts

This adds JSDocs for several functions involved in the `native-component` transformer, which is used in the `dist-custom-elements` output target to transform Stencil components into standalone custom elements.

docs(compiler): add JSDoc for 'native-component' transformers

---

src/compiler/transformers/decorators-to-static/component-decorator.ts
src/compiler/transformers/decorators-to-static/prop-decorator.ts
src/compiler/transformers/test/parse-props.spec.ts
src/compiler/transformers/transform-utils.ts

Stencil will not resolve an implicit enum type on a `Prop()`:
```ts
export enum Mode {
DEFAULT = 'default'
}
@Prop() mode = Mode.DEFAULT
```
would result in an `any` type used in the generated `components.d.ts` file(s).
GitHub Issue Number: Fixes #2243 
Stencil will now correctly infer the type for the enum so long as it is exported (either from a separate file, or the component file). 
Added a unit test for the case where an enum is exported from the component file that uses it. Testing the case where the type lives in a separate file is not possible with the current test setup and `transpileModule` methods.
**Manual tests**
Tested both cases for exported types in a component started. The generated `component.d.ts` files correctly imported and re-exported the …

fix(compiler): resolve implicit enum types

---

src/compiler/style/css-parser/serialize-css.ts

this commit updates the function signature of `serializeCssMapVisit` to
replace `void` as an argument type with `undefined | null`, which
matches that of a all other arguments provided to this function in its
actual usage
this commit also fixes cases where we did not handle possibly undefined variables correctly
Tests continue to pass

chore(snc): drop snc count for serialize-css

---

src/compiler/sys/stencil-sys.ts
src/sys/node/node-sys.ts

We had two occurrences of
[TS2774](https://github.com/microsoft/TypeScript/blob/512d6328e17c07a51fe07f58c332c0f51478447b/src/compiler/diagnosticMessages.json#L3390-L3393) in Stencil. This fixes them while adding a bit more assurance that things are the right "shape" at runtime.
-

chore(snc): eliminate TS2774 errors

---

src/compiler/config/test/load-config.spec.ts
src/compiler/config/test/validate-testing.spec.ts
src/compiler/optimize/minify-js.ts
src/declarations/stencil-public-compiler.ts
src/dev-server/test/Diagnostic.stub.ts
src/hydrate/platform/hydrate-app.ts
src/hydrate/runner/render-utils.ts
src/utils/logger/logger-rollup.ts
src/utils/message-utils.ts
src/utils/test/message-utils.spec.ts

This interface has two properties on it, `absFilePath` and `relFilePath`, which are habitually instantiated as `null` throughout the codebase but were previously typed `string | undefined`. This changes the type on the interface declaration to be `string | undefined | null` to match the interface to the usage.
This technically constitutes a breaking change, since it is modifying the type of a public interface, but in practice it should not be a problem since the type is just being widened (and widened to what it actually will be at runtime in a lot of cases).
- 
A public interface is being changed. However, as the type is being widened, it shouldn't be possible for this to generate any new type errors for users, and in fact this change makes the type declaration …

chore(snc): bring type of string props on `Diagnostic` inline with use

---

src/compiler/transformers/component-native/native-component.ts
src/compiler/transformers/component-native/native-constructor.ts
src/compiler/transformers/decorators-to-static/convert-decorators.ts
src/compiler/transformers/transform-utils.ts

We previously had some exceptionally similar code hanging around. This just reuses a helper called `updateConstructor` that was introduced a while back to cut down a bit on code duplication.
As part of that change, the `updateConstructor` function was moved from `convert-decorators.ts` to `transform-utils.ts`.
- 
I ran this through Framework as well as our test suite and didn't notice anything amiss.

refactor(compiler): use updateConstructor helper in native-constructor.ts

---

src/compiler/transformers/component-lazy/lazy-component.ts
src/compiler/transformers/component-lazy/lazy-constructor.ts
src/compiler/transformers/component-lazy/lazy-element-getter.ts
src/compiler/transformers/component-lazy/transform-lazy-component.ts
src/compiler/transformers/component-native/tranform-to-native-component.ts

Just adding some documentation about how the transformers in `src/compiler/transformers/component-lazy` work (and what they're supposed to do).
-

doc(compiler): add JSDoc for the lazy component transformers

---

src/utils/test/message-utils.spec.ts

this commit fixes a single strict null check violation for the message utils tests
N/A - the SNC no longer appears

chore(snc): remove snc violation in message-utils test

---

src/compiler/transformers/decorators-to-static/convert-decorators.ts
src/compiler/transformers/transform-utils.ts

Pull some code out of `convert-decorators.ts` into a helper function in our transformer utility module for getting the name of a property declaration as a string. If you had a class like this:
```ts
class {
foo: "bar";
}
```
this utility would let you get the string `"foo"` given the TypeScript syntax tree node corresponding to the `foo: "bar";` line in the source.
-

refactor(compiler): create a util function for name of a property decl

---

src/compiler/transformers/component-hydrate/hydrate-component.ts
src/compiler/transformers/component-lazy/lazy-component.ts
src/compiler/transformers/component-lazy/lazy-constructor.ts
src/compiler/transformers/transform-utils.ts

This updates the lazy component transform to use the `updateConstructor` helper, similar to the changes made in #4741.
This is a small refactor to bring the code here in line with how things are done int he native-component transform.
-

refactor(compiler): use updateConstructor in lazy transform

---

src/compiler/transformers/component-native/native-component.ts

This fixes an issue that surface in the stencil / ionic-framework nightly tests, where a `super()` call was mistakenly omitted from native components.
This was occurring after changing to use the `updateConstructor` helper function in #4741 in the native transform. When that function updates the constructor on a class it inspects the class declaration's heritage clauses to determine if a `super()` call needs to be present in the constructor, and adds one if needed.
In the native component transform, however, the transformer to add an `extends HTMLElement` heritage clause and transform the constructor were called separately and then combined into a single updated class declaration using `updateComponentClass`. This meant that when the `updateConstructor` function was called the class …

fix(compiler): add heritage clauses earlier in native transform

---

.github/workflows/release-nightly.yml

this commit updates the nightly release script to allow the workflow to be run on demand (via GitHub).
the motivation for this is that we had a failing nightly build, but the fix for the failures were merged. we wanted to run the framework nightly tests before a release of stencil, but couldn't kick if off manually (workaround was a dev build of stencil)
N/A - unable to test this until we merge it

chore(release): allow nightly to be run on demand

---

src/testing/testing.ts

this commit resolves a handful of strict null checks violations in `testing.ts`. most violations involved widening the type of some variable to explicitly state it could be null. this ought to be a safe operation, as we were already assigning `null` to these variables already - the change only aligns the type system with what was originally happening at runtime.
an extraneous call to `getAppStyleUrl` was removed as well. there are no known side effects that occur as a result of that function call, which ought to make this refactor safe
Type checker remains happy - there's only one section that could _potentially_ change how Stencil runs, I'll call that out below

chore(snc): resolve snc in test init

---

src/compiler/app-core/app-data.ts
src/compiler/config/test/validate-config.spec.ts
src/compiler/config/validate-config.ts
src/declarations/stencil-public-compiler.ts

A user can currently set both the `experimentalSlotFixes` flag and any of the other scoped slot patch flags (like `slotChildNodesFix`). So a config may look like:
```ts
// stencil.config.ts
extras: {
experimentalSlotFixes: true,
slotChildNodesFix: true
}
```
This can be confusing since the `experimentalSlotFixes` flag will override any of the other patch flags.
The config type (and downstream validation logic) will only allow the individual patch flags to be set if `experimentalSlotFixes` is omitted or explicitly set `false`
```ts
// stencil.config.ts
extras: {
experimentalSlotFixes: true,
slotChildNodesFix: true // <-- valid
}
```
```ts
// stencil.config.ts
extras: {
experimentalSlotFixes: false,
slotChildNodesFix: true // <-- valid
}
```
```ts
// …
```

fix(compiler): restrict config extras slot fix flags

---

src/compiler/build/test/build-stats.spec.ts
src/compiler/cache.ts
src/compiler/style/test/css-imports.spec.ts
src/compiler/style/test/optimize-css.spec.ts
src/declarations/stencil-private.ts
src/testing/mocks.ts

This just fixes a few SNC errors that stem from code in `src/compiler/cache.ts`.
I think that if unit tests and CI is all passing then we're probably good here

chore(snc): fix SNC errors stemming from `src/compiler/cache.ts`

---

src/compiler/config/transpile-options.ts

Currently, file compiled through `stencil test` do uses the new ECMA decorators, contrary to the output of `stencil build` which always uses legacy TS decorators.
This, combined with what I think might be an issue with how TypeScript handles class modifiers updates, causes the behavior described in #4631.
GitHub Issue Number: #4631 
Fixing/bypassing the TypeScript update behavior leaves us using the new decorators for `stencil test`, but the legacy ones for `stencil build`. The difference in behavior between the test & the source is not a good thing, obviously.
Ensure we do set the `experimentalDecorators` in the compiler options used by `stencil test`
- `patch-package` the behavior in https://github.com/Aadhisivam/stencil-demo/, runs the tests ✅ 
- Tested on github.com/coveo/ui-kit. ✅ …

fix(test): ensure legacy decorators are used when using transpile

---

src/compiler/config/validate-config.ts
src/compiler/output-targets/dist-lazy/generate-lazy-module.ts
src/declarations/stencil-public-compiler.ts
src/testing/mocks.ts

this commit updates the `ValidatedConfig` interface to include `extras`. doing so eliminates ~25 strictNullChecks violations from the codebase. 
The type checker should continue to pass.
I updated any cases of using optional chaining on `extras` in the codebase that I could find.
I can see a world where there's an argument to _not_ make this required. LMK what you think!

chore(snc): add 'extras' to ValidatedConfig

---

test/karma/test-app/prerender-test/karma.spec.ts
test/karma/test-prerender/src/components.d.ts
test/karma/test-prerender/src/components/hydrate-svg/hydrate-svg.tsx
test/karma/test-prerender/src/index.html

This adds a regression test for the issue reported in https://github.com/ionic-team/stencil/issues/4278, which doesn't currently occur on `main` but does occur in the branch associated with https://github.com/ionic-team/stencil/pull/2938 (a PR containing a bunch of changes for fixing bugs with slots).
This regression test will give us a bit more safety as we go to add more slot behavior fixes in the future.
GitHub Issue Number: #4278 
- 
Cherry-pick the commit on this branch over the top of #2938 and then confirm that the relevant test fails (due to how the prerender karma tests work what you'll see is actually all tests in that suite failing).
In order to do so you'll need to:
```sh
npm run clean && npm i && npm run build && npm run test.karma.prod
```
(after doing the cherry-pick)

test(hydrate): add a regression test for hydrating SVG children

---

src/compiler/transformers/decorators-to-static/convert-decorators.ts
src/compiler/transformers/decorators-to-static/prop-decorator.ts
src/compiler/transformers/decorators-to-static/state-decorator.ts
src/compiler/transformers/decorators-to-static/watch-decorator.ts
src/declarations/stencil-private.ts
src/runtime/bootstrap-lazy.ts
src/runtime/proxy-component.ts
src/utils/format-component-runtime-meta.ts
test/karma/test-app/components.d.ts
test/karma/test-app/input-basic/karma.spec.ts
test/karma/test-app/watch-native-attributes/cmp.tsx
test/karma/test-app/watch-native-attributes/index.html
test/karma/test-app/watch-native-attributes/karma.spec.ts

Stencil does not allow developers to watch native HTML attributes via the `@Watch()` decorator. So, syntax like the following is not valid:
```tsx
@Watch('aria-label')
onAriaLabelChange() {
// do something
}
```
In fact, the compiler will throw an error if the string provided to the decorator is not a Stencil class "member" (state or prop).
The `@Watch()` decorator can now be used with both Stencil class "member" (state or prop), as well as any native HTML attributes like aria attributes, `src`, etc.
**Automated Tests**
All existing tests continue to pass and a new e2e test was added to test the behavior with a native attribute.
**Manual Tests**
I tested this with both lazy and custom-elements builds. A build of this commit can be used to test in a component …

feat(runtime): watch native HTML attributes

---

src/compiler/transformers/decorators-to-static/component-decorator.ts
src/compiler/transformers/decorators-to-static/convert-decorators.ts
src/compiler/transformers/decorators-to-static/decorator-utils.ts
src/compiler/transformers/decorators-to-static/event-decorator.ts
src/compiler/transformers/decorators-to-static/listen-decorator.ts
src/compiler/transformers/decorators-to-static/prop-decorator.ts
src/compiler/transformers/decorators-to-static/state-decorator.ts
src/compiler/transformers/decorators-to-static/watch-decorator.ts
src/compiler/transformers/test/convert-decorators.spec.ts
src/compiler/transformers/test/decorator-utils.spec.ts
src/compiler/transformers/transform-utils.ts
test/karma/test-app/components.d.ts
test/karma/test-app/computed-properties-prop-decorator/cmp-reflect.tsx
test/karma/test-app/computed-properties-prop-decorator/cmp.tsx
test/karma/test-app/computed-properties-prop-decorator/index.html
test/karma/test-app/computed-properties-prop-decorator/karma.spec.ts
test/karma/test-app/computed-properties-state-decorator/cmp.tsx
test/karma/test-app/computed-properties-state-decorator/index.html
test/karma/test-app/computed-properties-state-decorator/karma.spec.ts
test/karma/test-app/computed-properties-watch-decorator/cmp.tsx
test/karma/test-app/computed-properties-watch-decorator/index.html
test/karma/test-app/computed-properties-watch-decorator/karma.spec.ts

GitHub Issue Number: Fixes #4350 
- Using computed property names is not valid for Stencil decorators. Trying something like:
```ts
enum MyEnum {
first = 'first'
}
...
@Prop() [myEnum.first]: string;
```
Will result in the string `[myEnum.first]` being used as the prop name.
- Using computed values is not valid for Stencil decorator arguments. Trying something like:
```ts
enum MyEnum {
first = 'first'
}
...
@Prop() first: string;
@Watch(MyEnum.first) 
firstChanged() { }
```
Will throw the following error:
> [ ERROR ]  invalid decorator argument: MyEnum.first at getDeclarationParameter
- Type checker looks up the symbol reference for a property access expression or computed property name to find the actual value.
- This allows any of the above examples to generate valid Stencil output …

feat(compiler): computed properties can be used with Stencil decorators

---

src/compiler/app-core/app-es5-disabled.ts
src/compiler/app-core/app-polyfills.ts
src/compiler/app-core/bundle-app-core.ts
src/compiler/build/compiler-ctx.ts
src/compiler/build/watch-build.ts
src/compiler/bundle/app-data-plugin.ts
src/compiler/bundle/core-resolve-plugin.ts
src/compiler/bundle/dev-module.ts
src/compiler/bundle/dev-node-module-resolve.ts
src/compiler/bundle/ext-format-plugin.ts
src/compiler/bundle/plugin-helper.ts
src/compiler/bundle/test/core-resolve-plugin.spec.ts
src/compiler/bundle/typescript-plugin.ts
src/compiler/bundle/user-index-plugin.ts
src/compiler/output-targets/dist-hydrate-script/relocate-hydrate-context.ts
src/compiler/sys/typescript/tests/typescript-sys.spec.ts
src/compiler/sys/typescript/typescript-sys.ts
src/compiler/transformers/static-to-meta/visitor.ts
src/compiler/types/generate-app-types.ts

this commit updates a handful of function parameter types from the unvalidated `Config` type `ValidatedConfig`. this has 2 benefits:
1. it "naturally" fixes a handful of strictNullChecks violations in cases where the caller of the function updated already had a ref to the `ValidatedConfig`
2. it helps with future refactorings of `ValidatedConfig` where we add new keys to be required on the object, as it allows us to: 
1. find new violations where a property is needed a bit easier in these converted functions 
1. in theory, automatically dismisses strictNullChecks violations when a key is added to the type, since it can now be properly checked
Tests should continue to pass
This is the amount of work I could (safely) do/test over ~15 minutes, so it's by no means …

chore(snc): replace config argument types

---

src/compiler/fs-watch/fs-watch-rebuild.ts
src/compiler/html/add-script-attr.ts
src/compiler/html/inject-sw-script.ts
src/compiler/html/inline-esm-import.ts
src/compiler/html/update-global-styles-link.ts
src/compiler/output-targets/copy/hashed-copy.ts
src/compiler/prerender/prerender-main.ts
src/compiler/prerender/prerender-template-html.ts
src/compiler/sys/typescript/typescript-config.ts
src/compiler/transpile/run-program.ts
src/compiler/transpile/validate-components.ts
src/compiler/types/update-import-refs.ts
src/utils/logger/logger-rollup.ts
src/utils/output-target.ts

Please review, ~but do not merge.~ Parent landed
Depends on https://github.com/ionic-team/stencil/pull/4794.
this commit updates a handful of function parameter types from the unvalidated `Config` type `ValidatedConfig`. this has 2 benefits:
1. it "naturally" fixes a handful of strictNullChecks violations in cases where the caller of the function updated already had a ref to the `ValidatedConfig`
2. it helps with future refactorings of `ValidatedConfig` where we add new keys to be required on the object, as it allows us to: 
1. find new violations where a property is needed a bit easier in these converted functions 
1. in theory, automatically dismisses strictNullChecks violations when a key is added to the type, since it can now be properly checked
Tests should …

chore(snc): replace addtl config arg types

---

.github/workflows/test-analysis.yml
.github/workflows/test-e2e.yml
.github/workflows/test-unit.yml

this commit finishes the revert of
https://github.com/ionic-team/stencil/pull/3888. the ubuntu versions in the changed github matrices can't be properly updated/detected by renovate, which is why they fell behind in the first place
STENCIL-755
All test workflows updated here continue to pass.
You can see new 'ubuntu-latest' checks occurring/passing here, and the old v20 ones obviously won't run
I will probably wait to merge this until after Monday's release. Reason being is that I need to update the CI checks that we gate on, and I don't wanna cause a snowball of rebases right before the release.
I found this while culling the backlog yesterday, and thought it'd be a nice/quick win for something we could easily "just close out"

chore(repo): use latest ubuntu in tests

---

src/compiler/config/load-config.ts
src/compiler/config/validate-config.ts
src/compiler/sys/config.ts
src/declarations/stencil-public-compiler.ts
src/testing/mocks.ts

This adds `logLevel` to the list of properties from `Config` which are required on `ValidatedConfig`. This doesn't actually fix any SNC errors but does let us deduplicate some logic that was present in both `compiler/config/load-config.ts` and `compiler/sys/config.ts`.
We have some duplication where we have the same logic for setting `config.logLevel` in two places. This just pulls that into the `validate-config.ts` file and makes the field required on the validated config to ensure it's present.
I tested this out with a sample project locally to make sure that the default logging behavior was the same as on `main`, and it looks like nothing changed. Unit tests and whatnot are also passing.

chore(): add logLevel to ValidatedConfig

---

src/compiler/prerender/prerender-main.ts
src/compiler/style/css-imports.ts
src/compiler/style/optimize-css.ts
src/compiler/transformers/decorators-to-static/component-decorator.ts
src/compiler/transformers/decorators-to-static/convert-decorators.ts
src/compiler/transformers/decorators-to-static/method-decorator.ts
src/testing/jest/jest-config.ts
src/utils/test/util.spec.ts
src/utils/util.ts

this commit updates a handful of function parameter types from the unvalidated `Config` type `ValidatedConfig`. this has 2 benefits:
1. it "naturally" fixes a handful of strictNullChecks violations in cases where the caller of the function updated already had a ref to the `ValidatedConfig`
2. it helps with future refactorings of `ValidatedConfig` where we add new keys to be required on the object, as it allows us to: 
1. find new violations where a property is needed a bit easier in these converted functions 
1. in theory, automatically dismisses strictNullChecks violations when a key is added to the type, since it can now be properly checked
Tests should continue to pass
This is the amount of work I could (safely) do/test over ~15 minutes, so it's by no means …

 chore(snc): replace config argument types (pt 3)

---

test/karma/package-lock.json
test/karma/package.json

This reverts commit 7e7122706e4313eb0c49e60b1901efd59505ac8d, #4824.
This commit was causing flakiness in our karma tests (or so it's believed).
When 7e7122706e4313eb0c49e60b1901efd59505ac8d was applied, we'd see some flakiness to the tune of the following in our karma tests:
> Firefox 117.0 (Windows 10) prerender server componentDidLoad Order FAILED
>	Error: console.error was called, this is not allowed in a unit test run thrown
While we did introduce this error recently, I believe this has more to do with the polyfills more than anything
It's a revert! Go back to the version that worked (for now) 
Tested this locally. Let's exercise it on CI too

revert(test): update dependency rollup-plugin-node-polyfills to ^0.2.0

---

scripts/release.ts
scripts/utils/vermoji.ts

we generate 2 vermoji during the release process. this is due to a small error in not forwarding the one generated during prerelease to the actual release process.
as an example, in stencil 4.3.0, the vermoji shown in `npx stencil info` is 🐫 , but the changelog shows 🎱 
this commit fixes a bug in our release scripts where the vermoji generated in the prerelease step of the process would not be properly propagated to the release step. when the entire process was manual, we'd do it all in one fell swooop, writing a tiny file to disk and reading that.
in lieu of that, we can pull the vermoji off of the head of the CHANGELOG.md! this ensures consistency between the two - running `stencil info` and looking at the changelog should show the same emoji.
note that this …

chore(release): ensure correct vermoji baked into distributable

---

CHANGELOG.md

this commit fixes the changelog emojis for multiple stencil releases. when we moved to automated releases, there was a bug that would not propagate the emoji generated in the prerelease step to the release step. this caused a new emoji to be generated and baked into the distributable that did not match the one in the changelog. since stencil releases are immutable, we choose to go back and edit the changelog to match the emojis that were baked in as a part of the release process.
Pulled down each version of Stencil from the latest (4.3.0) in a starter project and ran `npx stencil info` - I grabbed the emoji from that output and put it in the changelog. Repeated the process until I met a match (4.1.0)
#4836 fixes the root issue. this is just …

chore(changelog): reconcile changelog emoji

---

renovate.json5

When we started to allow renovate to bump deps in the karma sub dir (#4816), it started to try to bump npm/node versions as well. We don't exactly want that!
this commit updates the renovate configuration to prevent renovate from bumping node, node typings, and npm to versions that we do not want to run against at this time. historically, we've tested against the oldest LTS (even if it's not supported by Node anymore, just so long as we support it). this helps continue that.
I've validated that the changes are valid renovate syntax, but I'm not 100% sure that these are the right settings. We'll have to merge and see 😢 I did look through their docs and GH discussions, and this seems ot be the most promising

chore(repo): add karma test config to renovate

---

src/compiler/bundle/bundle-output.ts
src/compiler/bundle/dev-node-module-resolve.ts
src/hydrate/platform/hydrate-app.ts
src/runtime/dom-extras.ts
src/testing/puppeteer/puppeteer-page.ts
tsconfig.json

This turns on the `strictBindCallApply` typescript compiler option and then does what I _think_ is something like the minimal set of changes to get the build to pass with that option on.
From [the TypeScript docs](https://www.typescriptlang.org/tsconfig#strictBindCallApply):
> When set, TypeScript will check that the built-in methods of functions `call`, `bind`, and `apply` are invoked with correct argument for the underlying function[...] Otherwise, these functions accept any arguments and will return `any`
I didn't quite realize that without this option doing a `.call` on a function was basically a big type hole! Not good!
Unit tests and whatnot are passing, but would be good to check also that framework builds without issues.

chore(ts): enable strictBindCallApply ts compiler flag

---

.github/workflows/test-component-starter.yml
src/sys/node/node-sys.ts

When a user attempts to use jest 24, they are greeted with an error:
```console
$ npm t
> new-test@0.0.1 test
> stencil test --spec --e2e
[51:38.0]  @stencil/core
[51:38.1]  v4.3.0 🐫
[ ERROR ]  Please install supported versions of dev dependencies with either npm or yarn.
npm install --save-dev jest@27.0.3
```
this commit updates the check for the minimum allowed version of jest from v24.9.1 to v24.9.0. while working on the jest refactoring, it was discovered that v24.9.1 does not exist, making it impossible for anyone to use v24
You can validate the bug exists today by trying to use Jest 24 in a new component starter project:
```bash
cd /tmp \
&& npm init stencil@latest component jest-24-test \
&& cd $_ \
&& npm i jest@24 jest-cli@24 @types/jest@24 \
&& npm t
> …
```

fix(jest): use correct minimum jest version

---

package-lock.json
package.json
renovate.json5
scripts/tsconfig.json

This does the TS 5.2 upgrade. In order to get the project to build I didn't have to do much other than install the package.
I did have to adjust the `module` setting in `scripts/package.json`, to account for this change: <https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#module-and-moduleresolution-must-match-under-recent-node-js-settings>
Yucky, old, awful typescript 5.1!
TypeScript 5.2
After upgrading the package I built it locally and installed it into Framework and checked that Framework builds with no issues and the tests run.

feat(typescript): update to typescript 5.2

---

package.json

There seems to be a `start` script that is of no use anymore. The original `watch` task was removed in https://github.com/ionic-team/stencil/pull/3665
- removed `start` script
n/a
n/a

chore(repo): clean up start script

---

.github/workflows/test-component-starter.yml

We added the Jest version to the matrix for the component starter test in #4851 which increases the number of tests being run for the component starter but the names of the tests don't signify which version of jest is being installed in each one.
Here we just adjust the name to include the node and jest versions directly, just so it's easier to see what's up if something is failing.
The names should be different!

chore(ci): adjust component start test name to include jest version

---

src/testing/jest/jest-27-and-under/jest-config.ts
src/testing/jest/jest-27-and-under/jest-preprocessor.ts
src/testing/jest/jest-27-and-under/jest-runner.ts
src/testing/jest/jest-27-and-under/jest-setup-test-framework.ts

When I copied Jest infrastructure in #4847, I failed to address/remove TODOs in the code that no longer applied
remove a handful of TODOs from the Jest 27 and under section of the codebase. these TODOs were originally written when we planned to have to continue to maintain the internally used version of Jest and the one users use, keeping them in sync. now that these two versions of jest are independent, we can remove these TODOs (as the Jest 27 and under code is not expected to be changed for Jest 28).
I only removed comments, no testing applies (obviously CI should still pass)

chore(test): remove old jest todos

---

renovate.json5

this commit attempts to fix a renovate configuration issue where we wish
to ignore npm, node and `@types/node` from getting bumped in the karma
subdirectory of the project. currently, renovate is trying to bump
these. update `matchPackageNames` to `matchDepNames` and the path to
`package.json` for node/npm to see if that picks up correctly. the node
typings will continue to use `matchPackageNames`, and have therefore
been moved to their own package rule
We can't run renovate based on a non-base branch (non-`main`). I've validated the syntax is OK with their offline validator (`renovate-config-validator`), but that more-or-less type checks the config file. We won't know for sure until this merges and renovate runs again :-(

chore(renovate): fix volta karma node management

---

src/declarations/stencil-private.ts
src/runtime/hmr-component.ts
src/runtime/update-component.ts

This has been present in the hmr related runtime code for quite a while but does not appear to do anything.
-

refactor(runtime): remove unused s-hmr-load callback

---

src/compiler/config/test/validate-dev-server.spec.ts
src/compiler/config/test/validate-docs.spec.ts
src/compiler/config/test/validate-stats.spec.ts

We have >1000 strict null check violations
this commit fixes a few minor strictNullChecks violations related to accessing the `flag` field on unvalidated configs
N/A, only the bang operator was added to a few (three) existing tests. They still pass 😆

chore(snc): fix instances of config.flag ref

---

cspell.json

update the cspell configuration to ignore all node_modules directories. when we introduced new `jest`-version subdirectories in https://github.com/ionic-team/stencil/pull/4847, we failed to update cspell's configuration. as a result, cspell would run against the `node_modules` directory in
`src/testing/jest/jest-27-and-under` (e.g. `npm run spellcheck`). this change excludes _all_ `node_modules` cspell's eyes
Prior to this commit, if you run `npm run spellcheck`, you get something like:
```
npm run spellcheck
...
./src/testing/jest/jest-27-and-under/node_modules/xmlchars/xmlchars.d.ts:9:31 - Unknown word (Dubeau)
./src/testing/jest/jest-27-and-under/node_modules/xmlchars/xmlns/1.0/ed3.d.ts:4:28 - Unknown word (Dubeau) …
```

chore(repo): update cspell to ignore all node_modules

---

src/testing/jest/jest-27-and-under/jest-runner.ts
src/testing/jest/jest-27-and-under/jest-screenshot.ts
src/testing/jest/jest-27-and-under/jest-setup-test-framework.ts
src/testing/jest/jest-27-and-under/test/jest-config.spec.ts
src/testing/jest/jest-27-and-under/test/jest-setup-test-framework.spec.ts
src/testing/platform/testing-log.ts

there's a handful of strictNullChecks in the Jest v27 infra. before I start on the jest 28+ work, I'd like to sqaush these
resolve strictNullCheck violations in `src/testing/jest/jest-27-and-under` that only require updating the types on function/variable declarations, or a type assertion in the case of tests not understanding that a property will be added to an object
Unit tests should continue to pass.
The updates in this PR _shouldn't_ cause a functional change, but let me know if something smells fishy to you!
I didn't squash all of the SNC violations for this directory - there are a handful of them in the matchers dir that require some additional investigation (which may require more work), so I'll put that in a separate PR

chore(snc): resolve (most) jest strictNullChecks

---

.github/workflows/test-unit.yml

Unit tests in CI started to fail sporadically earlier this week for both
Windows and Ubuntu on Node 20. Hoping this was sporadic, we did not
investigate immediately. Starting this morning, no CI workflows
containing our unit tests on Node 20 were passing, blocking us from landing
code.
Looking across all CI workflows that ran in the past week/week and a
half, splitting them by those that passed and those that failed
It appears the issues that plagued us during the Node 20.5 upgrade
where Jest fails when finding a file on disk (or writing it) are back
In our unit tests, we always pull the latest minor of the LTS versions of
Node we support (16. 18, 20). We’ve started getting Node 20.8 in CI,
hence the failure.
In so far as I can tell, this is only Jest test …

chore(repo): tmp pin unit test node version

---

src/cli/task-test.ts

this behavior isn't the clearest, and as a part of working on #4883, I now have an answer as to _why_ we do this 
add a comment explains why we need to dynamically import the testing submodule at runtime.
comment only change, N/A

chore(test): document dynamic import of testing submodule

---

src/runtime/vdom/test/update-element.spec.ts

We have quite a few SNCs! This is today's 15 minutes of work to drive these down
this commit updates the types of multiple VNode variable instances to
`null` from `VNode`. in each of these usages, an old VNode
instance is instantiated as `null` for testing purposes to call
`updateElement`. since the old VNode can be `null` according to the
`updateElement` function signature, this is considered to by a safe
operation (i.e. does not adversely affect the tests).
for one test in particular, this commit updates VNode init by providing
the VNode with non-null values. the test that initializes these VNodes
doesn't use these values stored on the VNode, making this a safe
operation in terms of the test
Unit tests continue to pass - reading through the code and tests, I …

chore(snc): fix violations in update-element.spec

---

scripts/bundles/helpers/jest/jest-environment.js
scripts/bundles/helpers/jest/jest-preprocessor.js
scripts/bundles/helpers/jest/jest-runner.js
scripts/bundles/helpers/jest/jest-setuptestframework.js
src/testing/index.ts
src/testing/jest/jest-27-and-under/jest-config.ts
src/testing/jest/jest-27-and-under/jest-facade.ts
src/testing/jest/jest-27-and-under/jest-runner.ts
src/testing/jest/jest-27-and-under/test/jest-config.spec.ts
src/testing/jest/jest-apis.ts
src/testing/jest/jest-facade.ts
src/testing/jest/jest-stencil-connector.ts
src/testing/jest/test/jest-stencil-connector.spec.ts
src/testing/testing.ts

stencil will always assume that jest v27 is being used for testing.
this is a result of years  of using the same files for all jest infrastructure for end users.
while this pr does not do away with always picking jest v27, it gets us one step closer
add a new abstraction layer to stencil's jest testing configuration/running such that the version of jest is detected when jest is run. based on the version that is detected, defer to the correct piece of versioned infrastructure to setup and run tests.
in https://github.com/ionic-team/stencil/pull/4847, the directory structure of the testing submodule was updated to look something like:
```
├── src/testing/jest/
│   └── jest-27-and-under
│       ├── jest-config.ts                 
│       ├── jest-environment.ts
│ …
```

refactor(jest): detect jest version for testing

---

src/client/client-patch-browser.ts

We polyfill `performance.mark` and `performance.measure` in case it is not supported. After taking a look into MDN it seems that support for these primitives is way advanced and pretty much given across all environments:
__`performance.mark`__
__`performance.measure`__
Removing the polyfill and reduce some bytes in bundle size.
Looking at Stencils [browser support policy](https://stenciljs.com/docs/support-policy#browser-support) non of the browser we marked as supported miss these web platform features.
n/a
n/a

chore(client): remove performance.mark and performance.measure polyfill

---

src/compiler/output-targets/dist-lazy/generate-esm.ts

A `polyfills` directory disappears on every other build on Windows.
Fixes: https://github.com/ionic-team/stencil/issues/4661
in #4317 (b042d8b), a polyfill for node's `path.join` was [removed](https://github.com/ionic-team/stencil/pull/4317/files#diff-734f69edf83052dfd5ce6df10429550680537c6da66ef9b7cfbda11efdff5117L36), but wasn't backfilled with stencil's `@utils` package version in `generate-esm.ts`. without this change, the destination computed for the polyfills is not normalized for users of Windows OS's.
when the destination path is not normalized here (but is normalized in other parts of the code), it creates a situation where stencil's in memory-fs both:
1. marks the polyfills to be copied
2. marks the _previous_ polyfills to be removed
normally, if we're performing a copy …

fix(compiler): persist polyfills on build

---

src/declarations/stencil-public-runtime.ts

prior to this commit, users attempting to properly type a `<source/>` element in JSX would run into TypeScript errors:
```tsx
render() {
return <picture><source height={100} width={100}/></picture>;
}
```
```
[ ERROR ]  TypeScript: src/components/my-component/my-component.tsx:31:29
Type '{ height: number; width: number; }' is not assignable to type
'SourceHTMLAttributes<HTMLSourceElement>'.Property 'height' does not exist on type
'SourceHTMLAttributes<HTMLSourceElement>'.
L30:  render() {
L31:    return <picture><source height={100} width={100}/></picture>;
L32:  }
[26:05.7]  build failed in 1.12 s
```
fixes: #4942
add the height and width properties for the `SourceHTMLAttributes`. 
adding these typings as optional numbers resolves these types of compile-time errors
I created a dev build …

fix(runtime): add height, width Source attrs

---

.github/workflows/build-esbuild.yml
.github/workflows/main-esbuild.yml
.github/workflows/test-analysis.yml
.github/workflows/test-bundlers.yml
.github/workflows/test-component-starter.yml
.github/workflows/test-e2e.yml
.github/workflows/test-unit.yml
package-lock.json
package.json
scripts/esbuild/build.ts
scripts/esbuild/cli.ts
scripts/esbuild/util.ts
scripts/utils/options.ts
scripts/utils/test/options.spec.ts
tsconfig.json

This adds a support for building Stencil with [esbuild](https://esbuild.github.io/). This comprises:
- a new subdirectory `scripts/esbuild` which holds all the esbuild-related stuff
- support for bundling the `cli/` bundle with esbuild
- new `package.json` scripts `build.esbuild` and `build.esbuild.watch` for doing a "hybrid" build
- new CI workflows to build Stencil with esbuild and then run the existing unit and e2e test suites against the build artifact
Right now this new build / bundle setup exists parallel to the existing, rollup-based build setup. The idea is that we'll continue to use rollup for building and releasing, but we'll gradually increase the scope of the esbuild-based pipeline until it can build all of stencil. As noted above, this PR starts with just the `cli/` module. …

chore(build): build the CLI module with esbuild

---

src/compiler/output-targets/dist-lazy/generate-cjs.ts
src/compiler/output-targets/dist-lazy/generate-esm-browser.ts
src/compiler/output-targets/dist-lazy/generate-esm.ts
src/compiler/output-targets/dist-lazy/generate-system.ts

We have ~1400 SNC failures
resolve a handful of dist-lazy strictNullChecks violations where `undefined` values were not properly being filtered out of the arrays being passed to `generate-lazy-module`.
in all code paths, this code would be failing if `undefined` were in these arrays in practice, as the values are used in `path.join` calls (which error in the event of `undefined` being provided as an arg)
I'm relying on existing tests/the assumption that I'm correct in that all code paths would result in an `Error` being thrown if `undefined` actually made it in to these data structs

chore(snc): resolve dist-lazy violations

---

src/testing/jest/jest-27-and-under/jest-facade.ts

remove the import aliases used in `jest-facade.ts`. the aliases were renaming the imports to be '27-specific'. however, we're already in a 'jest-27' directory and working on the `Jest27Stencil` class (which is kept with the '27' to help differentiate this class further). having these extra import aliases made the instructions for adding a new version of jest more onerous than it needed to be
These aliases were internal only to this file - I don't expect them to affect any other parts of the code.

refactor(jest): remove version qualifiers in v27 facade impl

---

src/app-data/index.ts
src/compiler/app-core/app-data.ts
src/compiler/output-targets/dist-hydrate-script/hydrate-build-conditionals.ts
src/declarations/stencil-private.ts
src/runtime/bootstrap-custom-element.ts
src/runtime/bootstrap-lazy.ts
src/runtime/vdom/vdom-render.ts
src/testing/reset-build-conditionals.ts
test/karma/test-app/components.d.ts
test/karma/test-app/scoped-slot-in-slot/child.tsx
test/karma/test-app/scoped-slot-in-slot/host.tsx
test/karma/test-app/scoped-slot-in-slot/index.html
test/karma/test-app/scoped-slot-in-slot/karma.spec.ts
test/karma/test-app/scoped-slot-in-slot/parent.tsx

Slotted content may incorrectly get the `hidden` attribute applied when slotted through multiple levels of components. This is especially noticeable when the final destination does not wrap the `slot` in an additional element (like a `span` or `div`) since we could not correctly resolve an "anchor" for the node to be relocated.
Essentially, our slot relocation algorithm would identify that the node is slotted content that should live in a different location than it's original "host" element. This works fine until you try slotting content through many Stencil components. In that case, we identify the node as needing relocation, but eventually find ourselves in a situation where we think the node needs to move, but can't resolve where to move it to (because it's already there), so we think …

fix(runtime): prevent additional attempted move of slot content

---

renovate.json5
src/testing/jest/jest-27-and-under/package-lock.json
src/testing/jest/jest-27-and-under/package.json

See next section
add `jest@27` as a dev dependency (as it is not a part of the production build) to the `jest-27-and-under` directory/package. previously, `@jest/types` imports in this directory would resolve to the root level `node_modules/`, which is not what we want when we start to upgrade jest internally for stencil
The build continues to pass (`tsc`), and our smoke tests for the component starter continue to pass.

refactor(jest): resolve v27 typings correctly

---

.github/workflows/test-component-starter.yml
renovate.json5
src/sys/node/node-sys.ts
src/testing/jest/jest-29/jest-config.ts
src/testing/jest/jest-29/jest-environment.ts
src/testing/jest/jest-29/jest-facade.ts
src/testing/jest/jest-29/jest-preprocessor.ts
src/testing/jest/jest-29/jest-preset.ts
src/testing/jest/jest-29/jest-runner.ts
src/testing/jest/jest-29/jest-screenshot.ts
src/testing/jest/jest-29/jest-serializer.ts
src/testing/jest/jest-29/jest-setup-test-framework.ts
src/testing/jest/jest-29/matchers/attributes.ts
src/testing/jest/jest-29/matchers/class-list.ts
src/testing/jest/jest-29/matchers/events.ts
src/testing/jest/jest-29/matchers/html.ts
src/testing/jest/jest-29/matchers/index.ts
src/testing/jest/jest-29/matchers/screenshot.ts
src/testing/jest/jest-29/matchers/text.ts
src/testing/jest/jest-29/package-lock.json
src/testing/jest/jest-29/package.json
src/testing/jest/jest-29/test/__snapshots__/jest-serializer.spec.ts.snap
src/testing/jest/jest-29/test/jest-config.spec.ts
src/testing/jest/jest-29/test/jest-preprocessor.spec.ts
src/testing/jest/jest-29/test/jest-runner.spec.ts
src/testing/jest/jest-29/test/jest-serializer.spec.ts
src/testing/jest/jest-29/test/jest-setup-test-framework.spec.ts
src/testing/jest/jest-29/test/tsconfig.json
src/testing/jest/jest-stencil-connector.ts

Stencil lacks support for Jest 29
This PR is meant to follow along with the steps for adding a new version of Jest, currently ready for review (https://github.com/ionic-team/stencil/pull/4952). I suggest reading that in tandem with this PR, each commit in this PR can be directly tied back to a step (there may be >1 commit per step) in that document.
This PR is a child of #4979. I plan on merging that first, then this one. I'll probably wait until both are approved to begin the merging/squashing/rebasing of the two branches 
Add support for Jest 29 to Stencil
To test, I generated a dev build of the branch - `@stencil/core@4.6.0-dev.1698239124.bd2fbc0`
- [Dev Release Workflow](https://github.com/ionic-team/stencil/actions/runs/6640809983)
- [NPM Registry …

feat(test): jest 29 support

---

src/utils/path.ts
src/utils/test/path.spec.ts

This adds two new wrapped / patched path utils to our `@utils/path` module.
As part of addressing our ongoing woes with `path` we want to make sure we have all the utils we'll need here.
-

chore(utils): add path utils for 'resolve' and 'normalize'

---

src/compiler/html/html-utils.ts
src/compiler/html/inline-esm-import.ts
src/compiler/html/test/update-esm-import-paths.spec.ts

This fixes a bug where subsequent `www` builds would not always produce working output. In particular, prior to this change a 'clean' `www` build (i.e one done after deleting all previous output) would produce a working build but subsequent builds would not.
This had to do with an optimization that Stencil attempts to do during the `www` build where it will attempt to inline the JS code for the main entry point into the `index.html` that it produces.
As part of doing this it needs to rewrite some relative paths for any module specifiers that are part of that entry point, since the HTML file is found at `www/index.html` while the JS entry point will be typically found at `www/build/project-name.js`. Thus if that entry point has an import like `import foo from './bar.js'` that will need to …

fix(www): fix an inconsistency between www builds

---

src/runtime/vdom/set-accessor.ts
src/runtime/vdom/test/set-accessor.spec.ts
test/karma/test-app/components.d.ts
test/karma/test-app/event-listener-capture/cmp.tsx
test/karma/test-app/event-listener-capture/index.html
test/karma/test-app/event-listener-capture/karma.spec.ts

Our element interfaces include capture type events (like `onClickCapture`, `onInputCapture`, etc.), but our runtime does not correctly bind the event listeners for these types. So, currently, nothing happens when using these attributes since they were bound like this:
```ts
el.addEventListener('clickCapture', <handler>, false)`
```
but should be bound like this:
```ts
el.addEventListener('click', <handler>, true)`
```
Fixes: #4955 
The runtime has been updated to correctly bind the listeners for capture events based on the "Capture" suffix in the event attribute
1. Add an `onClickCapture` to any element in a Stencil component starter that just logs out the event. Notice nothing gets logged clicking the element.
2. Build and install this branch into the starter
3. Event …

fix(runtime): support "capture" style events

---

src/compiler/html/inline-esm-import.ts
src/compiler/output-targets/index.ts

This fixes an issue where the `www` build and, in particular, some code that attempts to inline the entry point for the `www` build into the `index.html` file that the build outputs, was depending on a file which, in certain circumstances, would not yet be built. This produced inconsistency across builds, where the `www` build would pick up and inline the entry point from the _previous_ build (if the build wasn't deleted) instead of from the current build.
fixes #4948
See the linked issue. Basically, with the `www` output target at present if you do
```sh
stencil build --dev --watch --serve
```
in a Stencil project and _then_ you run a build (without deleting `www/`) like
```sh
stencil build
```
You'll get a non-working build. Not good!
Why does this happen? We have this function which is …

fix(www): ensure that files necessary for www build are on disk

---

src/runtime/vdom/vdom-render.ts
test/karma/test-app/components.d.ts
test/karma/test-app/slot-nested-default-order/cmp-child.tsx
test/karma/test-app/slot-nested-default-order/cmp-parent.tsx
test/karma/test-app/slot-nested-default-order/index.html
test/karma/test-app/slot-nested-default-order/karma.spec.ts

It is possible for slot content that gets relocated to a nested component to appear in the wrong order with the nested component's other non-slotted elements. This was due to logic we had for keeping relocated content in the correct order _within_ a slot executing when it shouldn't and changing our relocation node. 
Fixes: #2997 
- The culprit code has been wrapped in a check to only execute in certain situations that make sense (i.e. when the slot has other relocated elements)
- Documented the code responsible for determining where to insert the relocated node for posterity
- Cleaned up some of the code to make things more readable
All existing unit and e2e tests continue to pass. Added an e2e test for the reproduction case from the linked issue
This is only available with the …

fix(runtime): slotted content order with sibling elements

---

src/compiler/output-targets/copy/hashed-copy.ts

This just adds some JSDoc to this function, which it was sorely lacking.
-

docs(output-targets): document generateHashedCopy function

---

src/utils/index.ts
src/utils/regular-expression.ts
src/utils/shadow-css.ts
src/utils/test/regular-expression.spec.ts
src/utils/test/scope-css.spec.ts

Using a `::slotted` pseudo-selector outside a shadow DOM component can result in styles not working as expected. The issue is with how we transform the CSS to account for our pseudo-slot behavior (relocation).
GitHub Issue Number: #3977 
The CSS in transformed into the correct rule(s) to account for nested elements. Also updated the logic so we replace _all_ instances of the pre-transformed string in the CSS text, rather than just the first.
Updated the existing tests to account for the change in logic (which is what they should have been in the first place)
Install a build of this branch into the linked issue reproduction case and verify the button styles for the "scoped" button are applied as expected to match the other buttons.

fix(compiler): correctly generate CSS rules using `::slotted` outside shadow DOM

---

src/compiler/transpile/run-program.ts

Building a Stencil project that uses the component starter template can result in build errors if the `src/components.d.ts` file doesn't already exist. This is because the TS program used for the build generates the semantic error diagnostics before we generate the typedef file. This bug was introduced by #4938 since we no longer early-abort before the TS diagnostics are pushed into our own diagnostics. 
Fixes: #4999 
This is a temporary fix to prevent the build errors without needing to early abort and revert all the changes from #4938. If the typedef file was changed, we ignore the TS diagnostics.
Tested in a component starter by deleting the `src/components.d.ts` file before running a build.

fix(compiler): ignore TS diagnostics on builds where typedef file changes

---

src/client/client-task-queue.ts
src/hydrate/platform/index.ts

prior to this fix, building a stencil/ionic project using stencil would result in a warning in the console similar to the following:
```
vite v5.0.0-beta.14 building for production...
node_modules/.pnpm/@stencil+core@4.7.0/node_modules/@stencil/core/internal/client/index.js (3800:17) A comment
"/*@__PURE__*/"
in "node_modules/.pnpm/@stencil+core@4.7.0/node_modules/@stencil/core/internal/client/index.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
```
remove `/*@__PURE__*/` comment pragma warnings from vite v5/rollup v4 from a pragma that was applied to a variable assignment that rollup can't understand.
1. Check out this branch and build it (`npm run clean && npm ci && npm run …

fix(vite): resolve PURE comment warnings

---

src/compiler/config/outputs/validate-docs.ts

We use string literals instead of their constant variable representations
use the const variables for validating docs-readme and docs-json instead of their string literal representation. this ought to aid in "finding" cases where stencil is doing "something" with documentation generation
I didn't - this should be a straightforward swap

refactor(compiler): use doc const types

---

src/compiler/types/stencil-types.ts
src/compiler/types/tests/stencil-types.spec.ts

We have a handful of SNC's in `stencil-types.ts`
resolves two strictNullChecks violations that were caused
by improperly handling a variable that was of type `string|undefined`
and assuming that it was of type `string`.
I ran the unit tests with coverage, and verified the [new/existing branches](https://github.com/ionic-team/stencil/pull/5026/files#diff-9520ec3dc9b12aac1a3735d5bc8a2808c1cf32a7c560ab81874b9e6aa10b9f37R56-R62) were covered. I ran the tests in the debugger with breakpoints in each conditional body, to verify they were actually called when I expected them to be.
I also repeated the same steps above without the code changes applied (but with the new test) to verify that the behavior for `undefined` being returned by our little helper method …

chore(snc): resolve SNC for stencil-types.ts

---

src/utils/path.ts
src/utils/test/path.spec.ts

I was questioning some divergent behavior between our `path.resolve` wrapper and the underlying Node call. Specifically:
```
// Node.JS console
> path.relative('foo/bar/file.js', 'foo/bar/file.js')
'' // empty string
```
```js
// Our code
import { relative } from '@utils';
// ...
const foo = path.relative('foo/bar/file.js', 'foo/bar/file.js');
console.log(foo); // print '.'
```
add additional tests to stencil's wrapped version of `path.relative`, adding additional documentation to how the wrapped function work. specifically, add tests to verify the following behavior:
1. when there is a single directory of overlap between `from` and `to`
2. when there is multiple directory overlap, but no divergences between `from` and `to`
3. when there is complete overlap …

test(path): add additional tests to relative

---

src/utils/path.ts
src/utils/test/path.spec.ts

I was questioning some divergent behavior between our `path.join` wrapper and the underlying Node call with respect to trailing slashes. This led to adding additional tests/docs
add additional tests to stencil's wrapped version of `path.join`, adding additional documentation to how the wrapped function works. specifically, add tests to verify the following behavior:
1. how trailing slashes are treated by the function
2. how 1+ string arguments of '/' are handled
3. how relative paths going 'up' one directory level are handled such that only a file is resolved
No functional changes have occurred - only adding unit tests. I did track the execution of the tests in a debugger and walked through `normalizePath` to verify they were hitting the code points that I …

test(path): add additional tests to join

---

src/testing/jest/jest-stencil-connector.ts

prior to this fix, building a stencil project with jest 29 installed could lead to an error such as:
```
TypeScript: node_modules/@stencil/core/testing/jest/jest-stencil-connector.d.ts:81:31
Could not find a declaration file for module '@jest/types/build/Config'.
'/PROJECT_DIRECTORY/node_modules/@jest/types/build/Config.js' implicitly
has an 'any' type.If the '@jest/types' package actually exposes this module, try adding a new declaration
(.d.ts) file containing `declare module '@jest/types/build/Config';`
```
GitHub Issue Number: #5030 
patch `getJestPreset` in the jest-stencil connector to return `any` instead of an inferred type for the function. 
Explicitly setting this return type to `any` is a temporary measure to unblock adopters. A TODO for STENCIL-1003 has been added to resolve …

fix(test): don't fail build when jest typings can't be resolved

---

scripts/esbuild/build.ts
scripts/esbuild/cli.ts
scripts/esbuild/sys-node.ts
scripts/esbuild/util.ts
src/sys/node/worker.ts

This adds a new esbuild-based bundle for the sys-node bundle, which includes the `CompilerSystem` implementation for node.js (currently our only full implementation).
-

chore(esbuild): build sys-node bundle with esbuild

---

src/utils/path.ts
src/utils/test/path.spec.ts

I was questioning how this function behaves/should behave was the impetus for this change - I didn't understand what I was seeing at first when debugging some Stencil 4.x related path related bugs. this commit is spun out from that work.
add additional tests to stencil's wrapped version of `path.normalize`, adding additional documentation to how the wrapped function works. specifically, add tests to verify the following behavior:
1. how an empty string behaves
2. how relative paths ('.', '..') behave
3. how absolute paths ('/' for POSIX and '\\' for Windows) behave
No functional changes - added unit tests only
related to: #5029, #5032

test(path): add additional tests to normalize

---

src/testing/jest/jest-apis.ts
src/testing/jest/jest-facade.ts
src/testing/jest/jest-stencil-connector.ts

We have a small piece of technical debt introduced in #5031 where we use an `any` type for the Jest infrastructure. This PR fixes it!
this commit is a follow up to #5031 (5df16e6). it narrows the return type of the `JestFacade#getJestPreset` function from `any` to an alias to Jest's `Config.InitialOptions`.
prior to #5031, the return type of `getJestPreset` would be inferred by the TypeScript compiler, and a dynamic import to an internal Jest type declaration file would be generated for the typing of the function:
```ts
// a snippet of what was generated in `jest-stencil-connector.d.ts
export declare const getJestPreset: () => Partial<{
coverageReporters: import("@jest/types/build/Config").CoverageReporters;
// other fields omitted
}>;
```
however, stencil …

refactor(jest): narrow getJestPreset typings

---

.github/workflows/test-unit.yml

revert the changes from #4900 (9bb1994a). with node 20.8+ unblocked as of #4897 (e1858ea), we no longer need to pin to v20.7.
Verified the correct version of Node runs our unit tests (and doesn't fail!)
I'll need to change our CI gate checks after this lands
STENCIL-964

chore(ci): unpin node minor version

---

scripts/bundles/plugins/parse5-plugin.ts
src/compiler/docs/json/index.ts
src/compiler/types/generate-app-types.ts
src/compiler/types/generate-component-types.ts
src/compiler/types/generate-event-detail-types.ts
src/compiler/types/generate-event-listener-types.ts
src/compiler/types/tests/generate-app-types.spec.ts
src/compiler/types/tests/generate-event-detail-types.spec.ts
src/compiler/types/tests/generate-event-listener-types.spec.ts

This removes a strange bit of code from our `parse5Plugin`, which bundles `parse5` for inclusion in the compiler and mock-doc bundles.
That code is here:
https://github.com/ionic-team/stencil/blob/bb0b1d46f63175dc09d0a23445be4d4a0d891a01/scripts/bundles/plugins/parse5-plugin.ts#L41-L54
Essentially what this does is any place in the bundled code where there are four space characters it convert it into two space characters instead.
This produces the weird behavior where when we're generating files like `components.d.ts` somewhat 'by hand' we have code that looks like this:
https://github.com/ionic-team/stencil/blob/bb0b1d46f63175dc09d0a23445be4d4a0d891a01/src/compiler/types/generate-app-types.ts#L133-L135
One would think that this would produce lines indented by 8 spaces, but actually when …

refactor(build): remove whitespace edit from parse5Plugin

---

src/mock-doc/node.ts
src/mock-doc/test/attribute.spec.ts

Use of pseudo selectors in Stencil tests can result in errors due to mock elements not having the `getAttributeNode` method used by Sizzle
Closes: #3043, #3588 
Adds a definition for `getAttributeNode` to Mock Doc's `MockElement`
Verified fix via reproduction case for #3588 
Added unit tests to Mock Doc's test suite for the new method

fix(mock-doc): add `getAttributeNode` to mock elements

---

src/cli/task-serve.ts
src/compiler/build/build-stats.ts
src/compiler/bundle/bundle-output.ts
src/compiler/optimize/optimize-css.ts
src/compiler/optimize/optimize-module.ts
src/compiler/output-targets/dist-lazy/generate-lazy-module.ts
src/compiler/output-targets/dist-lazy/generate-system.ts
src/compiler/style/css-to-esm.ts
src/compiler/transformers/static-to-meta/component.ts
src/compiler/transformers/test/parse-encapsulation.spec.ts
src/compiler/transformers/transform-utils.ts
src/sys/node/logger/terminal-logger.ts

This fixes a bunch of errors caused by passing `boolean | undefined` where a property or parameter is actually typed `boolean`. This isn't likely to actually cause too many issues at runtime since `undefined` is falsy, but it does cause `strictNullChecks` errors that we'd like to get rid of.
To fix the issues we can just do a `!!` coercion of the falsy `undefined` value to `false`.
-

chore(snc): fix some boolean-related snc errors

---

.github/workflows/actions/get-core-dependencies/action.yml
CONTRIBUTING.md
src/testing/jest/README.md
src/testing/jest/install-dependencies.sh

until now, all jest-related types in `src/testing/jest/jest-*` have resolved to stencil's root-level `node_modules/jest*` directories (jest-27) in ci. this hasn't been an issue, as many of the types were effectively typed as `any` (or something nearly equally as wide). as we begin to narrow the typings in `src/testing/jest`, we will need these typings to be available to us (otherwise ci will fail).
add a shell script for installing jest-related dependencies for the `src/testing/jest/jest-*` subdirectories. this allows a developer to install all dependencies in one command, rather than chaining N number of directory changes and `npm ci` commands for every N directories.
this script has been wired up to the `get-core-dependencies` github action as well. this ensures …

chore(ci): install jest dependencies script

---

src/hydrate/runner/patch-dom-implementation.ts

In certain environments, such as Angular Universal (with Angular 16 or newer), the `baseURI` patch code will be eliminated from the final bundle. Javascript optimizers will treat the code as deadcode and eliminate it. 
This causes issues in Ionic Framework: https://github.com/ionic-team/ionic-framework/issues/28077
- `baseURI` patched implementation is assigned, so that it is not eliminated from the bundle.
- Ionic Framework (v7) works with Angular Universal with Angular 16 or newer
- Ryan provided a dev-build of this change for Stencil (`4.4.1-dev.1697216096.18bf460`)
- Ionic Framework was updated with the dev-build and a new dev-build was created/posted here: https://github.com/ionic-team/ionic-framework/issues/28077#issuecomment-1761950254
- Installed the …

fix(hydrate): prevent dead code elimination of patch dom implementation

---

.github/workflows/actions/get-core-dependencies/action.yml
package.json
src/testing/jest/README.md

Knowing where the shell script for jest scripts shouldn't necessarily be on one's mind when trying to develop for Stencil + Jest
add an `install.jest` script to `package.json` to make it easier to install jest dependencies within the project. the motivator for this change is the following suggestion in a pull request that was a child PR of the one that implemented this functionality - https://github.com/ionic-team/stencil/pull/5068#pullrequestreview-1732217554
I was able to run `npm run install.jest` locally 
I tailed the logs and found the command still runs:
```Run npm ci \
npm ci \
&& npm run install.jest
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
added 947 packages, and audited 948 packages in 11s
131 packages are looking for funding
run `npm …
```

chore(repo): add package.json jest install script

---

src/declarations/stencil-public-runtime.ts

Stencil's JSX declarations do not support `popover` or associated popover attributes
Closes: #4745 
- Adds the `popover` attribute to the base `HTMLAttributes`
- Adds `popoverTargetAction`, `popoverTargetElement`, and `popoverTarget` to the declarations for button and input
Can't run automated tests because `popover` is not supported in all browsers we run e2e tests against via BrowserStack
Installed a build of this branch in a started project and was able to build a demo using popovers and triggers.
`popover` is not yet supported in all browsers. It will be up to the developer to decide when they can leverage these APIs

feat(declarations): add popover attributes to JSX declarations

---

scripts/bundles/testing.ts
src/testing/jest/jest-27-and-under/jest-runner.ts
src/testing/jest/jest-28/jest-runner.ts
src/testing/jest/jest-29/jest-runner.ts
src/testing/jest/jest-apis.ts
src/testing/jest/jest-facade.ts

**Note:** Depends on #https://github.com/ionic-team/stencil/pull/5069 - please review when this PR is moved out of draft state
We use `any` to type our Jest Test Runner, which we'd like to narrow.
the original goal of this effort was to remove the `any` type on `jest-apt.ts`'s `JestTestRunner` type. doing so revealed a handful of subtle errors in the implementation of the jest runner for stencil.
1. `jest-facade.ts#getCreateJestTestRunner` was incorrectly typed. _technically_ this was correct in that it returned `any`, which can be a function. however, we were not explicit/clear that this was a function being returned in the JSDoc.
2. `jest-runner.ts#createTestRunner` was incorrectly typed. Again, this was _technically_ correct in that it used `any`, but it was …

fix(test): pass jest args correctly for v28/29

---

src/testing/jest/jest-apis.ts
src/testing/jest/jest-facade.ts
src/testing/jest/jest-stencil-connector.ts

We have a handful of types in our `jest/` submodule that use `any` due to some issues with reconciling Stencil declarations.
resolves an issue where adding typings from `@stencil/core/internal` were causing failures of the build validation step in CI (`npm run test.dist`). this had caused argument types for a handful of functions to be typed as `any` as opposed to known types provided by stencil.
previous to this change, naively adding types to use stencil declarations in `./src/testing/jest/jest-facade.ts` would cause the following error when running the build validation step against a build of stencil:
```
> node scripts/build --validate-build
🐡  Validated packages
Error: 🧨  testing/jest/jest-stencil-connector.d.ts(29,55): error TS2307: Cannot find module …
```

refactor(test): resolve typing import issues

---

src/mock-doc/document.ts
src/mock-doc/element.ts
src/mock-doc/node.ts
src/runtime/vdom/set-accessor.ts
src/runtime/vdom/test/set-accessor.spec.ts
src/utils/constants.ts

While going through `set-accessor.ts` I was wondering why we would try/catch the prop setting part. My assumption is for cases where we set readonly properties like e.g. `namespaceURI`. This actually is compliant with what the browser does:
This patch adds a test for this case.
n/a

test(vdom): setting readonly props is ignored

---

src/runtime/proxy-component.ts
test/karma/test-app/form-associated/cmp.tsx

This fixes an issue where form-associated lifecycle callbacks were not being called with the correct `this` value, making it impossible to set something like a `@State` value from within a callback.
The right `this` value isn't resolved for the form-associated callbacks.
GitHub Issue Number: fixes #5106
It's resolved the same way it is for other similar lifecycle callbacks.
I added some code to our current karma test for this functionality which functions as a regression test, i.e. it will cause a test to fail without this fix.

fix(runtime): call form-associated lifecycle callbacks w/ `this`

---

scripts/esbuild/build.ts
scripts/esbuild/screenshot.ts

This adds a new, Esbuild-based build script which handles the built
files for `screenshot/`.
- 
I will fully admit to not really knowing what I'm doing with the screenshot functionality! _However_ what I did to confirm that this is at least working was:
- I started a new example project (`npm init stencil@latest...`) and installed `@stencil/core@latest` in it
- I then followed the steps here to add a basic screenshot test to my project: https://stenciljs.com/docs/screenshot-visual-diff
- then I built and packed this branch locally:
```sh
npm run clean && npm run build.esbuild && npm pack
```
- I then installed that in the project and confirmed that the screenshot test passed
and it looks like everything is working - if anyone has more expertise with how this works …

chore(esbuild): port screenshot bundle to esbuild

---

scripts/bundles/testing.ts
src/testing/jest/jest-27-and-under/jest-environment.ts
src/testing/jest/jest-28/jest-environment.ts
src/testing/jest/jest-29/jest-environment.ts
src/testing/jest/jest-apis.ts
src/testing/jest/jest-facade.ts

We use `any` as a result of our work to implement Jest 29 support. This removes that `any`
narrow the type used for jest/puppeteer environments from `any` by introducing new types that accurately reflect the objects that are returned by all underlying `JestFacade` implementations.
a dynamic import that was previously used in  each `JestEnvironment` was hoisted/removed in favor of a build-time import of the class. this led to stronger typing within the anonymous class returned from the retrieval function itself.
by removing the dynamic import within the `jest-environment.ts` implementations for each respective version of jest, stencil's bundler would not resolve the node environment properly, causing userland tests to fail. jest's `jest-environment-node` module was …

refactor(test): narrow jest/puppeteer environment

---

src/testing/puppeteer/puppeteer-element.ts

Fixes a regression caused by the removal of a few `asElement()` calls in 91cfa2c9adb50f27c823653511a4913d320398b1. Turns out these are necessary for the case where the handle is `null`. To avoid type errors, we cast the returned value to be of type `ElementHandle<Element>` rather than `ElementHandle<Node`.
Fixes: #5113
No more errors 🙂
1. Open the repro case in the linked issue
2. Run `npm run test` and observe a failure on the second call to `page.find` in the e2e test
3. Install a build of this branch
4. Run `npm run test` and observe no more errors and tests pass!

fix(testing): re-add Puppeteer `asElement()` calls

---

src/runtime/bootstrap-lazy.ts

I introduced a regression in v4.7.2 via 72c1f1a352e8b9ce3c965f6dc751e16acd9cb3ae. The issue is that the style tag is inserted into the DOM prior to the `nonce` attribute being set which results in a CSP violation error.
Fixes: #5102 
This commit makes it so that the `nonce` value gets set prior to the DOM insert operation
**Manual tests**
1. Spin up a new component starter.
2. Install v4.7.2 (`npm i @stencil/core@4.7.2)
3. In `src/index.html`, replace _all_ content in the document `head` with the following snippet:
```html
<meta http-equiv="Content-Security-Policy" content="style-src 'nonce-111'; script-src 'nonce-111';" />
<meta name="csp-nonce" content="111" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, …
```

fix(runtime): apply nonce to data styles before DOM insert

---

src/compiler/transformers/add-static-style.ts
src/compiler/transformers/component-native/native-static-style.ts
src/compiler/transformers/stencil-import-path.ts
src/compiler/transformers/style-imports.ts
src/compiler/transformers/test/lazy-component.spec.ts
src/compiler/transformers/test/parse-styles.spec.ts
src/compiler/transformers/test/transform-utils.spec.ts
src/compiler/transformers/transform-utils.ts
src/runtime/test/fixtures/cmp-a.tsx

Currently if multiple style urls are provided, as described in the docs:
```ts
@Component({
styleUrls: ['reset.scss', 'roboto.scss', 'css-variables.scss', 'core.scss'] 
})
// ...
}
```
Only the first (`reset.css`) style would get applied to the component.
GitHub Issue Number: #5016
Instead of just compiling the first external style, I make it loop through all external styles and join the style strings together. Here is an example:
```ts
const barCss = ":host{display:block}";
const fooCss = ":host{display:none}";
const MyComponent = class {
// ...
};
MyComponent.style = barCss + fooCss;
```
export { MyComponent as my_component };
Working on adding unit tests and integration tests for it.

fix(compiler): support multiple styleUrls in components

---

scripts/esbuild/compiler.ts

This adds the `getBaseEsbuildOptions` function to the Esbuild configuration for the `compiler/` bundle. This ensures that the following options are set consistently:
- [`logLevel`](https://esbuild.github.io/api/#log-level)
- [`legalComments`](https://esbuild.github.io/api/#legal-comments)
- [`bundle`](https://esbuild.github.io/api/#bundle)
This was accidentally omitted from #5027.
-

chore(esbuild): ensure base esbuild options are set for compiler

---

src/runtime/vdom/vdom-render.ts
test/karma/test-app/components.d.ts
test/karma/test-app/slot-parent-tag-change/cmp-root.tsx
test/karma/test-app/slot-parent-tag-change/cmp.tsx
test/karma/test-app/slot-parent-tag-change/index.html
test/karma/test-app/slot-parent-tag-change/karma.spec.ts

Stencil can re-render incorrectly when content is slotted in from the "implementation layer" (i.e. from `index.html`) and a `slot`s parent element tag changes (e.g. from `p` to `span`). This is only an issue when using slots outside the Shadow DOM. 
The issue is caused by our vDOM algorithm relocating slotted content back to its _original_ location when it determines that a child node has changed. When this happens, we call `putBackInOriginalLocation()` which will relocate a node back to where it was original defined. But, this can result in the node no being re-relocated if it was put back into a location inside another Stencil element that has already gone through its render cycle. In this case, the node will stay in its original location rather than being relocated through the DOM …

fix(runtime): relocate slotted content when slot parent element tag changes

---

src/compiler/transformers/add-static-style.ts
src/compiler/transformers/component-native/native-static-style.ts
src/compiler/transformers/style-imports.ts
src/compiler/transformers/test/lazy-component.spec.ts
src/compiler/transformers/test/parse-styles.spec.ts
src/compiler/transformers/transform-utils.ts
test/karma/test-app/components.d.ts
test/karma/test-app/style-plugin/bar.scss
test/karma/test-app/style-plugin/foo.scss
test/karma/test-app/style-plugin/index.html
test/karma/test-app/style-plugin/karma.spec.ts
test/karma/test-app/style-plugin/multiple-styles.tsx

Currently if multiple style urls are provided, as described in the docs:
```ts
@Component({
styleUrls: ['reset.scss', 'roboto.scss', 'css-variables.scss', 'core.scss'] 
})
// ...
}
```
Only the first (`reset.css`) style would get applied to the component.
fixes: #5016
STENCIL-999
Instead of just compiling the first external style, I make it loop through all external styles and join the style strings together. Here is an example:
```ts
const barCss = ":host{display:block}";
const fooCss = ":host{display:none}";
const MyComponent = class {
// ...
};
MyComponent.style = barCss + fooCss;
export { MyComponent as my_component };
```
I've added a bunch of unit and e2e tests to verify this change. You can verify the new behavior by bootstrapping a …

fix(compiler): reapply changes to style import transformer

---

scripts/esbuild/build.ts
scripts/esbuild/mock-doc.ts
scripts/utils/bundle-dts.ts

This adds support for building the mock-doc top-level-module using esbuild.
- 
CI passing with both the Rollup- and Esbuild-based builds is a good signal that things are alright here. I also build and packed the project locally and then installed it in a sample project, ensuring that I could then run a basic `stencil test --e2e --spec` without issues.

chore(esbuild): build mock-doc with esbuild

---

scripts/bundles/testing.ts

Currently it seems required to have Puppeteer installed to build a Stencil component. It seems that the compiler imports parts of the testing module to compile a project which causes "/testing/puppeteer/puppeteer-declarations.d.ts" to be loaded.
STENCIL-881
fixes #4526
To solve the type dependency the easiest is to add a Rollup plugin that simply adds a "@ts-ignore" before the import. If Puppeteer is not installed, it will not throw any errors, if it is installed, all types are propagated correctly.
To verify this change:
- create a new stencil project `npm init stencil`
- install all dependencies via `npm install`
- build project `npm run build` and see build succeeding
- now remove Puppeteer as dependency `rm -r ./node_modules/puppeteer`
- build project `npm run build` and see build …

fix(testing): make Puppeteer an optional dependency

---

src/runtime/bootstrap-custom-element.ts
src/runtime/bootstrap-lazy.ts
src/runtime/dom-extras.ts
test/karma/test-app/components.d.ts
test/karma/test-app/scoped-slot-text-with-sibling/karma.spec.ts
test/karma/test-app/scoped-slot-text/karma.spec.ts
test/karma/test-app/text-content-patch/cmp-scoped-slot.tsx
test/karma/test-app/text-content-patch/cmp-scoped.tsx
test/karma/test-app/text-content-patch/index.html
test/karma/test-app/text-content-patch/karma.spec.ts

Stencil's current `textContent` patch for `scoped` elements only deals with a component's default slot. However, the team has recently agreed that our `scoped` component behavior should mimic a `shadow` component as closely as possible.
Fixes: #3977 
The `textContent` patch now behaves like the native implementation for an element with a Shadow Root. The getter will return the combined `textContent` of all child nodes that are located in slot references. And the setter will replace all content within slot reference nodes with a single text node in the default slot reference (if one exists).
1. Create new component starter
2. Enable `extras.experimentalSlotFixes` in Stencil config
3. Update `my-component` to the following:
```tsx
@Component({ …
```

fix(runtime): update `textContent` patch to mimic Shadow Root

---

src/compiler/transformers/add-static-style.ts
src/compiler/transformers/component-native/native-static-style.ts
src/compiler/transformers/test/native-component.spec.ts

Currently our nightly build is broken due changes introduced in #5131 (see https://github.com/ionic-team/ionic-framework/actions/runs/7124408050). Investigating this issue was difficult as it happens to be random behavior. However I found that the static style property wasn't applied correctly in the failing cases which gave me a hint to the location of this fix.
I made changes in the order of if statements in [`getSingleStyle`](https://github.com/ionic-team/stencil/blob/735d45afdda420420f6d3992662cb63ded2c937e/src/compiler/transformers/add-static-style.ts#L103)  and [`getMultipleModeStyle`](https://github.com/ionic-team/stencil/blob/735d45afdda420420f6d3992662cb63ded2c937e/src/compiler/transformers/add-static-style.ts#L69) 
and have recognised a file with similar implementation features: …

fix(compiler): make style getter behavior consistent between default and native components

---

src/runtime/dom-extras.ts
src/runtime/vdom/vdom-render.ts
test/karma/test-app/components.d.ts
test/karma/test-app/remove-child-patch/cmp.tsx
test/karma/test-app/remove-child-patch/index.html
test/karma/test-app/remove-child-patch/karma.spec.ts

Stencil does not patch the HtmlElement `removeChild()` method. This is causing issues in some of our Framework wrappers as frameworks are using these methods during rendering dynamic content (like looping through arrays and generating/removing elements).
Fixes: #3278, #2259
We provide a patch for `removeChild()` that works with our pseudo-slot behavior for `scoped` components.
Gonna give abbreviated testing steps since most of it can be achieved following the [React framework wrapper guide](https://stenciljs.com/docs/react) and the associated issues' repro cases.
1. Follow the [React framework wrapper guide](https://stenciljs.com/docs/react) to get a working React app with Stencil proxied components.
2. Create the Stencil components and React app from …

fix(runtime): patch `removeChild` for `scoped` components

---

src/compiler/style/optimize-css.ts
src/compiler/style/test/optimize-css.spec.ts

We have quite a few SNC violations in our code!
resolve `strictNullCheck` violations for `optimize-css#optimizeCss` unit tests. the `fileName` argument doesn't appear to be used by `optimizeCss` in any meaningful way that (other than an additional path normalization call).
`optimizeCss` is a part of stencil's public api. as a result, we cannot remove this otherwise unused function parameter without it constituting a breaking change. add a TODO for now, to be completed in the next major version of stencil.
add a type assertion to invalid styling input. this allows us to test invalid css being passed to the optimizatiton function, without widening the type signature of `optimizeCss`
`filePath` only seems to be used here (highlighted in green):
where the only …

chore(snc): resolve errors for optimize-css tests

---

src/compiler/events.ts

we have several SNC violations in the codebase
remove a single strictNullCheck violation for `events.ts`. this change only affects the type system, no functional changes have been made to the codebase.
specifically:
- the type of the internal (non-exported) `EventCallback#eventName` property has been widened to accept `null` in addition to `string`s.
- the type of the `eventName` local variable when parsing `arg0` in `on()` has been changed from `string`->`null`. this aligns us closer with the value we're assigning, and prevents 'implicit `any`' errors from the type checker
The change here only affects the type system. Since the interface that I'm changing is local only to the file it's contained in, and we have the value `null` assigned to the property I'm …

chore(snc): resolve compiler event.ts violation

---

src/compiler/transformers/test/proxy-custom-element-function.spec.ts

See "New Behavior" section
use the (now) existing stub creation function for building a `Module` entity, rather than using an object literal asserted to be a `Module`.
I traced the code in a debugger for the tests - I kicked off each test with a breakpoint in the function under test, and ensured that the code was interacted with:
STENCIL-379 Use `mockModule` in tests

chore(test): use mock module function in proxy-custom-element-function

---

src/compiler/output-targets/dist-lazy/test/generate-lazy-module.spec.ts

see 'new behavior'
add comprehensive testing to how component metadata is sorted. the motivation for this pull request is there are several strict null check violations in the code that is put under test. however, i didn't feel comfortable making any changes without tests in place, hence this commit
I ran each test through my local debugger, and set breakpoints to validate that the returned values were coming from the correct branch.
We do now have 100% code coverage in this function now (but obviously, we need the former testing check to verify the tests actually evaluate the branches that they say they do)

test(compiler): test bundle sorting

---

src/compiler/transformers/decorators-to-static/attach-internals.ts
src/compiler/transformers/decorators-to-static/convert-decorators.ts
src/compiler/transformers/decorators-to-static/decorator-utils.ts
src/compiler/transformers/decorators-to-static/element-decorator.ts
src/compiler/transformers/decorators-to-static/event-decorator.ts
src/compiler/transformers/decorators-to-static/import-alias-map.ts
src/compiler/transformers/decorators-to-static/listen-decorator.ts
src/compiler/transformers/decorators-to-static/method-decorator.ts
src/compiler/transformers/decorators-to-static/prop-decorator.ts
src/compiler/transformers/decorators-to-static/state-decorator.ts
src/compiler/transformers/decorators-to-static/watch-decorator.ts
test/karma/test-app/components.d.ts
test/karma/test-app/import-aliasing/cmp.tsx
test/karma/test-app/import-aliasing/index.html
test/karma/test-app/import-aliasing/karma.spec.ts

It is not possible to use aliases (i.e. "as") when importing Stencil decorators because of the compiler's meta-to-static conversions of all Stencil decorators.
GitHub Issue Number: #3137 
Import aliasing is now possible as we map aliased imports back to their original decorator name. The aliased name is then passed to all the transformation functions.
- This can be easily tested in a Stencil component starter by aliasing any Stencil decorator used in a component. 
- Also manually tested in a project using a CE build
Added e2e test that tests a subset of Stencil decorators with aliased import names.
PR to update relevant docs: https://github.com/ionic-team/stencil-site/pull/1292

feat(compiler): Stencil decorator import aliasing

---

src/compiler/docs/generate-doc-data.ts
src/compiler/transformers/decorators-to-static/method-decorator.ts
src/compiler/transformers/test/parse-comments.spec.ts
src/compiler/transformers/test/parse-methods.spec.ts
src/compiler/types/tests/ComponentCompilerMethod.stub.ts
src/compiler/types/tests/generate-method-types.spec.ts
src/declarations/stencil-private.ts
test/docs-json/docs.d.ts
test/docs-json/docs.json
test/end-to-end/src/components.d.ts
test/end-to-end/src/event-cmp/event-cmp.tsx
test/end-to-end/src/event-cmp/readme.md
test/end-to-end/src/method-cmp/method-cmp.tsx
test/end-to-end/src/method-cmp/readme.md

Parsing parameters from a Stencil component currently relies on a JSDoc string and not actually on the types defined by the user in TypeScript. With that most method types were not documented at all.
fixes #4394
STENCIL-846
I updated the part where we propagate parameter informations and now propagate a parameter name and type to the resulting JSON as well as made updates so that these types are correctly set in the markdown docs.
No changes to any public TS interfaces.
To test this behavior:
- create a new Stencil project
- add a method to the component, e.g.:
```ts
/**
* @param active foobar some description
*/
@Method()
async setActive(active: string) {
this.active = active;
}
```
- add `docs-json` output target, e.g.
```ts
{
type: 'docs-json',
file: 'components.json',
},
```
- run …

fix(compiler): fix transforming method parameters into docs

---

src/runtime/test/hydrate-no-encapsulation.spec.tsx
src/runtime/vdom/vdom-render.ts

This makes it possible to set a `key` attribute on a nested Stencil component without messing up how hydration works. I noticed that this was not working correctly when working on #5143.
There's a regression test which will reproduce the issue if run in the context of `main`. In short, if you have two components like so:
```tsx
@Component({ tag: 'cmp-a' })
class CmpA {
render() {
return (
<Host key="test">
<cmp-b key="my-test-key">light-dom</cmp-b>
</Host>
);
}
}
@Component({ tag: 'cmp-b' })
class CmpB {
render() {
return (
<Host>
<slot key="key1"></slot>
<footer key="key2"></footer>
</Host>
);
}
}
```
You'll get rendering issues where comments that need to be present for slot relocation and whatnot to work aren't appearing. Not good!
This ensures that we only start to check whether …

fix(runtime): allow setting `key` attr on nested Stencil components

---

src/screenshot/screenshot-compare.ts

Currently if we for some reason throw an error within the pixel-match process, the test stales because the promise that waits for the process to emit a "done" message never resolves
refs #4866
STENCIL-962
Listen on the `exit` event and reject the promise. This doesn't completely addresses the issue highlighted in #4866 but fixes one problem of it.
To test the new behavior:
- check out the example project from mentioned issue
- run `yarn run test`: all should be fine
- change the component and rerun: now the test process stales
After checking out this branch, you will see that the error is now properly propagated.
I am still not sure why the test fails. It seems like the picture is far larger in byte size than mine created on the Mac. I assume here that screenshots made in the CI machine …

fix(screenshot): reject pixel match process on exit

---

src/compiler/transformers/static-to-meta/component.ts
src/declarations/stencil-private.ts

we have several SNCs related to the fields listed below.
make the following fields non-optional on `ComponentCompilerMeta`:
- dependents
- dependencies
- directDependents
- directDependencies
these fields were previously marked as optional as they are not set when the metadata for a component is created, as we need to generate the metadata for all components in order to set these fields.
with this constraint in mind, we stub the initial fields with an empty array.
Removing the optional aspect of the backing type only affects our type system - insofar as I can tell, we do not expose that type publicly in such a way that it would break our existing API's typings.
However, as a result of changing those types, I had to make an internal change such that each of the …

chore(compiler): make dependency fields non-optional

---

src/cli/task-help.ts
src/cli/task-info.ts
src/cli/task-telemetry.ts

This fixes a few snc errors resulting from the typing of `sys.details` as `SystemDetails | undefined` that show up in `src/cli`.
Ideally we'd fix the typing but it's a public type, so for now the best thing is just to add some optional chaining.
This is just adding some optional chaining property accesses, so I believe there should not be any runtime changes here to worry about. If the build is passing and the tests are green I think we're good.

chore(snc): fix four snc errors relating to `sys.details` in `cli/`

---

src/declarations/stencil-private.ts
src/sys/node/test/worker-manager.spec.ts

We had some optional properties on this interface which are always supplied in practice, so we can drop a few snc errors by making them required.
This PR is _mainly_ a type-level change, but does also require a small change to a mock. As long as the build is green I believe we're safe!

chore(snc): make properties on `CompilerWorkerTask` required

---

package-lock.json
scripts/bundles/plugins/content-types-plugin.ts
scripts/bundles/sys-node.ts
scripts/esbuild/build.ts
scripts/esbuild/dev-server.ts
scripts/esbuild/util.ts
src/dev-server/server-web-socket.ts

This patch adds an esbuild step for compiling the `dev-server` package. Some note worthy comments:
- I've found some required build steps, e.g. for creating `open-in-editor-api.js`, `ws.js`, `visualstudio.vbs` and `xdg-open` in sys-node bundle and migrated them over. They only seem to be connected to `dev-server` features.
- because of that I moved the `buildSysNode` step as pre-requisite of other the CLI and dev-server build scripts as I discovered race conditions (e.g. `@sys-api-node` -> `./sys/node/index.js` not being able to get resolved by `dev-server.js`
- there were some esbuild plugins necessary to transpile the source code in a similar way as we have done with rollup, rollup was a bit better compiling down from ESM to CJS
- The dev server works the same …

chore(build): build the dev-server module with esbuild

---

src/compiler/config/test/validate-dev-server.spec.ts

We have quite a few SNC violations in the code base!
update testing for `devServer#port` values:
1. add a test for `undefined` to verify the desired behavior (setting a
default port if one is not specified)
2. add a type assertion to suppress SNC violation when the port is set
to null
update testing for `devServer#historyApiFallback` values:
1. add a test for `undefined` to verify the desired behavior (setting a
default port if one is not specified)
2. add a type assertion to suppress SNC violation when the port is set
to null
add the bang operator to assertions where we have previously verified
the existence of a property (using `toBeDefined`)
I've run the new tests locally to verify they pass and are hitting the code paths they intend to (with a local debugger) …

chore(snc): resolve validate-dev-server.spec errors

---

src/declarations/stencil-private.ts

the `.text` property on the `PrintLine` interface was previously marked optional, but there are no locations in the Stencil codebase where we do not supply a value for it, so we can safely remove a few snc violations by typing it as just `string` instead of `string | undefined`.
I believe this is safe to do because this is not a public type, but instead is an internal type used for logging and so on.
This is just a type-level change so we should be good as long as the build is green!

chore(snc): make optional property required on `PrintLine`

---

src/testing/puppeteer/puppeteer-emulate.ts

This fixes 6 SNC errors by switching from explicit annotation to using the `satisfies` keyword.
This is a type-level only change, no runtime behavior should change.
This is only changing type annotations, so I think as long as the build is passing and unit tests are green we should be good!

chore(snc): fix some snc errors in puppeteer-emulate.ts

---

src/compiler/build/build-finish.ts

after https://github.com/ionic-team/stencil/pull/5185, there's one SNC left in this file
reorder an `if` statement such that a strictNullCheck violation for `diagnostic.absFilePath` being of type `string|undefined` where `isRemoteUrl` only accepts `string`s is reported. 
since `isRemoteUrl` returns `false` for falsy values with no side effects, this was deemed a safe change to make - let me know if there's anything specific you'd like to see here

chore(snc): resolve final build-finish error

---

src/mock-doc/element.ts
src/mock-doc/global.ts
src/mock-doc/test/element.spec.ts

When Stencil's mock-doc creates an `HTMLUListElement`, we create an element that does not descend from `HTMLUListElement`
Fixes: #3382
add a definition for `HTMLUListElement`. this allows `createElement` calls to return a mocked version of `HTMLUListElement` that passes `instanceof` calls.
prior to this commit, folks attempting to use an `HTMLUListElement` in a stencil test like so would receive an error:
```ts
describe('my-component', () => {
it('using HTMLUListElement works', async () => {
const unorderedList = document.createElement('ul');
console.log(unorderedList instanceof HTMLUListElement);
});
});
```
```
[46:08.8]  jest args: --spec --e2e --max-workers=8
FAIL  src/my-component.spec.ts
my-component
✕ using HTMLUListElement works (4 ms)
● my-component › using HTMLUListElement works …
```

fix(mock-doc): add HTMLUListElement

---

.github/workflows/actions/download-archive/action.yml
.github/workflows/actions/upload-archive/action.yml
.github/workflows/tech-debt-burndown.yml

see 'new behavior'
we are seeing too many timeouts wiht the new v4 action. revert to v3 for now. this does not have any impact on users
Revert "chore(deps): update actions/download-artifact action to v4 (#5191)"
This reverts commit 5e9e629180cc3682c0df6446e0eab84f2ab8bd75.
n/a

chore(repo): revert to artifact actions v3

---

src/compiler/build/build-finish.ts

We have quite a few SNC's in the codebase!
update `build-finish#logHmr` to take a reference to the `HotModuleReplacement` object from the build context, as we check for the object's truthiness right before calling `logHmr`. this prevents us from updating several accessor calls on `hmr`, the instance of the `HotModuleReplacement` object, or wrapping the majority of the function in an `if` statement.
First, let's build the branch:
```
npm run clean \
&& npm ci \
&& npm run build \
&& npm pack
```
Then installed it in the output of creating a new stencil component library:
```bash
cd /tmp \
&& npm init stencil@latest component hmr-test \
&& cd $_ \
&& npm i [PATH_TO_STENCIL]
```
Start the dev server (`npm start`), then edit the `my-component.css` file generated by …

chore(snc): resolve hmr logging-related errors

---

.github/ionic-issue-bot.yml

the team is about to go on a small break for the holidays. 
update ionitron to use the label "holiday triage" over the 2023 holiday break & comment appropriately.
We can't test this until it merges :-(
This is the same message as last year, FWIW (with the GH issue number changed).
**I'll merge this next week** and update the linked issue. I just wanted to get something in place for review while I had a minute.

chore(repo): add 2023 holiday triage

---

renovate.json5

see 'new behavior' section
group github's `actions/download-artifact` and `actions/upload-artifact` into a single renovate job. in #5191 and #5192, renovate created a pr for each of these individually for the v4.0 release of each library. however, they have a peer dependency on one another, making it such that we could merge neither.
this was solved by cherry-picking the commit from the latter onto the former. going forward, let's group these for all dependencies. we should (hopefully) only run into this across majors, but we'll err on the 'safe' side of things for now
Not much we can do, other than tail the logs once we merge it.
I did run `renovate-config-validator` locally, which validated our config conforms to the JSON schema as a quick check (but that …

chore(renovate): group download & upload artifact

---

scripts/bundles/internal.ts
scripts/utils/bundle-dts.ts
src/declarations/child_process.ts
src/declarations/stencil-private.ts

We need to make sure our type declarations don't depend on types we don't bundle!
fixes #5162
STENCIL-1077
- 
There's a reproduction case on #5162. You could test that this fixes the issue by building and packing this locally, installing it in that reproduction case, and confirming that you don't get a type error when building.

fix(declarations): bundle child_process type for portability

---

scripts/esbuild/compiler.ts
scripts/esbuild/mock-doc.ts

This adds a call to the fs-extra `emptyDir` before we run the whole esbuild-based bundle and build step for the `compiler/` and `mock-doc/` dirs to ensure that there's nothing hanging around from a previous build.
Just something I noticed was missing when reviewing #5200!
Currently we don't clear out the previous build before we run esbuild to bundle the compiler. Since we normally run the rollup-based build first (because we don't yet build everything with esbuild) this could potentially mean something from the rollup build is sticking around for the `compiler/` bundle, which could in turn give us a false confidence in the ability of the esbuild-based script to stand alone. This fixes that issue!
we call `fs.emptyDir` when we should.
Exercise the relevant functionality after building …

chore(esbuild): ensure that compiler dir is empty before we run esbuild

---

scripts/esbuild/screenshot.ts

The ESBuild task to build the screenshot component of Stencil doesn't re-compile pixel-match.
Make sure that the core screenshot component and pixel-match are compiled correctly. I changed the implementation of it to make this type of error less likely to happen again with the compromise of making the code less flexible. Happy to revert that if seen needed.
n/a
n/a

fix(build): compile pixel-match file correctly

---

.github/workflows/release-dev.yml

This adds an output from the `release-dev` workflow which will let other calling workflows get the version which has just been released.
Right now if the `release-dev` workflow is called by another workflow there isn't a way for the calling workflow to get the version number which was just released.
This adds an `output` to the whole workflow so that a calling workflow can get the version number, for instance so that something like #5229 can run a dev release, get the version number, and then write a comment out to the user.
See the documentation for workflow outputs (as opposed to _job_ outputs) here: https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow
There's not a great way to test this without it being on `main` unfortunately. …

chore(ci): add a version number output from the release-dev task

---

package-lock.json
package.json
renovate.json5
scripts/bundles/plugins/replace-plugin.ts
src/compiler/bundle/bundle-output.ts

We're on quite an old version of `@rollup/plugin-replace`! The version here is from 2020 😱 
upgrade stencil's dependency on `@rollup/plugin-replace` from v2.x to
v5.x. this package is being done as a part of a larger effort to upgrade
stencil's version of rollup to v2 (which itself is a part of a larger
effort to move to v4). this package has been updated on its own, as:
1. doing so allows us to cut scope/size of other upgrade PRs
2. this package relies on rollup v1.20.0+, and no other sibling
packages, making this upgrade less involved than others.
update replace plugin calls to use preventAssignment.
`preventAssignment` was added in rollup v2.40.0. when we attempt to
build stencil with the latest v5.x release of the replace-plugin, we
received the following …

chore(deps): upgrade rollup/plugin-replace to v5

---

src/runtime/vdom/vdom-annotations.ts

Just fixing a few SNC errors in `src/runtime/vdom/vdom-annotations.ts`. These mainly related to possibly-undefined or possibly-null values which could be addressed with optional chaining.
We have a fair number of snc errors in this file
I don't believe this will change any behavior, other than possibly preventing some runtime errors. I think though that, as is often the case in the Stencil codebase, things are typed `Foo | undefined` when they're always `Foo` in practice, so I don't think we'll have too much to worry about.
I think if the automated tests are all passing we should be good.

chore(snc): fix snc errors in vdom-annotations.ts

---

.github/ionic-issue-bot.yml

Holiday triage is still enabled.
This patch reverts #5184 
n/a
n/a

chore(repo): revert 2023 holiday triage

---

renovate.json5

We are currently not using the latest TypeScript version.
Have Renovate update to latest TypeScript.
n/a
Given their v5.3 announcement I expect no breaking changes nor updates required to our current code base.

chore(repo): allow Renovate to update to TypeScript 5.3

---

src/compiler/app-core/app-data.ts
src/compiler/config/test/validate-config.spec.ts
src/compiler/config/validate-config.ts
src/compiler/output-targets/dist-hydrate-script/hydrate-build-conditionals.ts
src/declarations/stencil-private.ts
src/declarations/stencil-public-compiler.ts
src/runtime/dom-extras.ts
src/runtime/vdom/vdom-render.ts
src/testing/reset-build-conditionals.ts
test/karma/stencil.config.ts

We made changes in #5146 and #5135 to alter the behavior of `slot`s inside scoped components. The changes aligned Stencil's slot polyfill with behavior in the native shadow DOM and were placed behind the `experimentalSlotFixes` extra flag in a project's Stencil config. However, these changes negatively impacted the Ionic Framework causing automated tests to fail.
This commit adds a new extras flag, `experimentalScopedSlotChanges`, that is used to change logic in a few places to align Stencil's `scoped` encapsulation to work more like the native Shadow DOM when using slots.
Changes in #5146 and #5135 are changed from being gated by the `experimentalSlotFixes` flag to this new flag so they can be toggled independently.
This will be considered a breaking change once …

feat(runtime): add extras flag for scoped slot changes

---

src/runtime/bootstrap-custom-element.ts
src/runtime/bootstrap-lazy.ts
src/runtime/dom-extras.ts
test/karma/test-app/dom-reattach-clone/cmp-deep-slot.tsx
test/karma/test-app/dom-reattach-clone/cmp-host.tsx
test/karma/test-app/dom-reattach-clone/cmp.tsx

A few changes made behind the `experimentalSlotFixes` flag were resulting in screenshot test failures in the Ionic Framework
- Fixes the conditional responsible for patching element methods for the pseudo shadow DOM when `experimentalSlotFixes` is enabled.
- Updated the `appendChild` patch to force a re-render of the patched element
See commit messages for more information
- Stencil unit and e2e tests continue to pass.
- A build of Stencil containing these changes (and changes from the other "slot regressions" branches) was used in a manually triggered run of the Stencil nightly build and succeeded. Run results: https://github.com/ionic-team/ionic-framework/actions/runs/7280624127

fix(runtime): slot regressions from experimental slot fixes

---

scripts/bundles/testing.ts
scripts/esbuild/build.ts
scripts/esbuild/mock-doc.ts
scripts/esbuild/testing.ts
scripts/esbuild/util.ts
src/testing/jest/jest-27-and-under/test/jest-setup-test-framework.spec.ts
src/testing/jest/jest-28/test/jest-setup-test-framework.spec.ts
src/testing/jest/jest-29/test/jest-setup-test-framework.spec.ts
src/testing/mock-fetch.ts

Testing module is compiled with Rollup.
STENCIL-993
Testing module is compiled with ESLint.
n/a
n/a

chore(esbuild): add esbuild-based testing bundle

---

renovate.json5

Renovate tries to upgrade `open`
Open v10 has a single breaking change, in that it requires Node v18+ to be used. Stencil v4 still supports Node 16, and must continue to use Open v9 as a result. We cannot drop support for Node 16 without a breaking change, so we’ll hold off on this work until Stencil v5.
We can't fully test this until it's merged unfortunately.
I did validate the config is correct locally with: `npm i -g renovate && renovate-config-validator`.
Replaces: #5213

chore(repo): prevent renovate from upgrading open

---

src/screenshot/screenshot-compare.ts

Currently the `ScreenshotOptions` passed into the `compareScreenshot` command aren't recognised as fully as `width` and `height` are overwritten by the value stored in the `emulateConfig` which is hard coded in [`validateConfig`](https://github.com/ionic-team/stencil/blob/bb0b1d46f63175dc09d0a23445be4d4a0d891a01/src/compiler/config/validate-testing.ts#L173-L174).
refs #4866
fixes #5208
Just take `width` and `height` provided by the command.
To verify this change:
- `git clone git@github.com:Spirielle/bug-stencil-getMismatchedPixels.git`
- `cd bug-stencil-getMismatchedPixels`
- `npm i`
- `npm test` -> test pass
- go into `src/components/my-component/my-component.e2e.ts` and comment out line 13 and comment in line 16
- `npm run test` -> test fail due to `Image data size does not match …

fix(screenshot): recognise clip options

---

src/runtime/vdom/vdom-render.ts

There is a memory leak in the Stencil runtime related to a retained reference to a "content ref" comment. This is only an issue when the runtime patches slot behavior for use outside the Shadow DOM.
This commit resolves a memory leak in the runtime related to a global reference that existed in the vDOM algorithm. The content ref would get set when entering the render cycle for a component, but was never cleared so the reference would exist after execution. So, now we clear that value at the end of the `renderVdom()` function execution.
Automated unit & e2e tests continue to pass.
1. Perform all steps using [this](https://github.com/ionic-team/ionic-framework/tree/ld/5519) branch of the Ionic Framework
2. Navigate to …

fix(runtime): resolve memory leak caused by global content ref

---

src/compiler/transformers/decorators-to-static/element-decorator.ts

We have many strictNullChecks violations
fix a single strictNullCheck for the file by adding a type guard to the final `filter` call against a class's decorated members. this allows the typescript compiler to understand that the collection `elementRefs` is a collection of `string`, rather than a `(string | null)[]`, based on the return type of the local function `parseElementDecorator`
This only affects the type system, and therefore shouldn't change any runtime values. As such, I only tested this by running our strict null checks counter, unit and karma tests locally.

chore(compiler): resolve strictNullCheck for element-decorator

---

src/compiler/config/test/validate-custom.spec.ts
src/compiler/config/validate-config.ts
src/declarations/stencil-public-compiler.ts
src/testing/mocks.ts

we have a stencil configuration option that is part of our public configuration api, `nodeResolve#customResolveOptions`. This option will no longer be honored by newer options of `@rollup/plugin-node-resolve` - we need to remove it in the future (a breaking change). for now, we can start the process by logging a warning.
deprecate the `nodeResolve#customResolveOptions` configuration option in a Stencil configuration. this field is used to configure `@rollup/plugin-node-resolve` when generating any non-documentation output target artifacts. the contents of this option get propagated by the rollup plugin to `resolve`, which does the actual resolution of files in stencil's in-memory filesystem.
in newer versions of `@rollup/plugin-node-resolve`, this option has been …

feat(compiler): deprecate customResolveOptions config option

---

package-lock.json
package.json

**DO NOT MERGE!** I want to squash this as a `feat()` to surface the changes in the changelog. While I've tested this pretty well (subjective, I know 😉), I want folks to see this core piece of infra is being updated, as it impacts them as well. 
Our rollup infrastructure is lagging behind the latest. We're currently working on a few different modernization efforts for handling newer JS paradigms + infra; this is one of them.
upgrade rollup to v2.56.3 and `@rollup/plugin-commonjs` to v21.1.
this commit raises these libraries to the highest version as possible
without introducing breaking changes. v2.57 has a bug in it that
requires `@rollup/plugin-commonjs@22` for handling CJS-ESM interop.
that version of `@rollup/plugin-commonjs` requires …

feat(deps): upgrade rollup, commonjs plugin

---

src/client/client-host-ref.ts

This fixes an issue where HMR updates which changed arguments to the `@Component` decorator would crash the application because a `HostRef` for the component could not be located.
This occurred because HMR updates caused a new version of the component's lazy bundle to be fetched, which in turn would bundle the `getHostRef` function and the corresponding `hostRefs` variable, which is declared here:
https://github.com/ionic-team/stencil/blob/0041dc27b9deb45cfd1434a3d82d563793e56056/src/client/client-host-ref.ts#L18
Because the newly fetched lazy entry point for the updated component did not have access to the `hostRefs` variable which was in-scope in the _old_ bundle, the `getHostRef` function would always return `undefined` on the first render after the HMR update, causing issues in …

fix(hmr): allow changes to component decorators when using HMR

---

src/compiler/transformers/static-to-meta/component.ts

This fleshes out a bit further how this functions behaves, in particular that it will perform a side-effect of creating a `ComponentCompilerMeta` object and then sticking that into a few other objects.
Documentation-only change, so if lint, spellcheck, and format are passing we're good I think.

chore(jsdoc): clarify how `parseStaticComponentMeta` behaves

---

src/compiler/build/compiler-ctx.ts

This adds some documentation for the two functions in here.
Just noticed this randomly and in particular wanted to call out how `getModuleLegacy` works.
Documentation only change, so as long as lint and spellcheck are passing I think we're good.

chore(jsdoc): add JSDoc to `src/compiler/build/compiler-ctx.ts`

---

readme.md

stencil's README tries to resolve an image that no longer exists
the link to browserstack's logo currently no longer resolves. remove it, as a link out to their offerings ought to be enough
I reviewed the preview of this markdown file beforehand, no broken image placeholder gets shown anymore

chore(readme): remove broken image

---

RELEASE.md

This adds a step to the release flow which consists of creating a new version of the docs on the stencil-site repo, if necessary. Since we already have good documentation of how that process works over there (https://github.com/ionic-team/stencil-site/blob/main/RELEASE.md#creating-a-new-version-section) we can just point to that.
documentation-only PR, no testing needed

chore(docs): add a step for creating a new version of the stencil docs

---

src/compiler/sys/typescript/typescript-config.ts

We have several strictNullChecks in our code
resolve the two strictNullChecks for `typescript-config.ts` by removing type assertions on fields that are always assigned when an object is returned by the function
I didn't do much testing on this beyond running tests locally - I can provide some examples of walking this through a debugger if folks would prefer, but AFAICT every code path that returns an object never returns a `null` property

chore(snc): resolve strictNullChecks for typescript-config

---

src/declarations/stencil-public-compiler.ts

Add a JSDoc string to the `buildDist` config option, documenting the effect that it has on the Stencil build process.
No documentation!
Documentation!
Documentation-only change
I've also got a PR on the stencil site here: https://github.com/ionic-team/stencil-site/pull/1333

chore(config): add some documentation to the `buildDist` option

---

RELEASE.md

see 'new behavior' 
fix the indentation on documentation release steps so that the render properly in a rich markdown viewer. github's markdown renderer does not see the steps beginning with 'Merge any open PRs' and 'If the current release' as children of the doc site step, causing them to be rendered as follow up steps:
```md
2. Navigate to the Stencil Site repo and:
3. Merge any open PRs...
4. If the current release...
```
N/A - fixes local documentation for releasing stencil
Before (at 89816e1032c7dbd853e6a824d5cffeca0d6d4355): 
After (apply this commit):

chore(release): fix docs steps for release

---

src/runtime/vdom/vdom-render.ts
test/karma/test-app/components.d.ts
test/karma/test-app/slot-dynamic-name-change/cmp-scoped.tsx
test/karma/test-app/slot-dynamic-name-change/cmp-shadow.tsx
test/karma/test-app/slot-dynamic-name-change/index.html
test/karma/test-app/slot-dynamic-name-change/karma.spec.ts

Stencil's runtime will not change the name of a `slot` element when the `name` attribute is bound to a `@Prop()`. This is an issue for both shadow and non-shadow components.
Fixes: #2982 
The runtime will now correctly update the `name` attribute of slots and pseudo-slots to render the correct content on re-renders. 
https://github.com/ionic-team/stencil-site/pull/1337
**Automated Testing**
New e2e tests were added for this use case
**Manual Testing**
1. Spin-up a new Stencil component starter
2. Enable `extras.experimentalSlotFixes` in the Stencil config
3. Update the contents of `my-component.tsx` to the following:
```tsx
import { Component, Prop, h } from '@stencil/core';
@Component({
styleUrl: 'my-component.css',
scoped: true,
})
/**
* …
```

fix(runtime): dynamic slot name change

---

src/mock-doc/selector.ts
src/mock-doc/test/selector.spec.ts

This improves the error message shown when there is an error on the jQuery side when running `querySelector` and friends by selectively making an addendum to the error message to just explain a bit better what's going on.
STENCIL-1108
If you try to use the [`:scope` pseudo-selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope) you'll get an error message which is a little less than helpful.
This adds to that error message by adding a `try / catch` around `jQuery.find` and in cases where 1) an error was thrown and 2) the selector used has `:scope` in it we prepend some explanatory text to the error message before re-throwing it.
I added some unit tests which exercise this functionality and check for the right error message.
It's also a good idea to check out how this works in …

fix(mock-doc): improve error message when `:scope` selector is used

---

.github/workflows/main.yml
.github/workflows/pack-and-comment.yml

This adds a new workflow which runs after `build_core` and will basically:
1. download the build archive
2. run `npm pack`
3. upload the resulting tarball so that it gets a URL where you can download it
4. put a comment on the PR with this URL so you can quickly install it in a test project or framework or something
I've just been 'manually' testing this by iterating on the branch and running it on Github. I also used [actionlint](https://github.com/rhysd/actionlint) to check the yaml before pushing.

chore(ci): pack and upload a tarball for every PR

---

.github/workflows/pack-and-comment.yml

Just a quick version bump to sync the versions in the `pack-and-comment` workflow with the ones we already use in the tech debt burndown.
I also realized we want to ensure that this workflow doesn't run on CI when not in the context of a pull request.

chore(ci): update comment actions to same versions as tech debt burndown

---

.github/workflows/pack-and-comment.yml

Put an `if` on the job so that things will only run when we're on a pull request.
I thought I'd gotten this right in #5333 but I had not!

chore(ci): ensure that the 'pack and comment' only runs on a PR

---

.github/workflows/main.yml
.github/workflows/pack-and-comment.yml

This changes the workflow from being a `workflow_call` triggered workflow which is intended to be called from _another_ workflow (`main`) and instead makes it a `pull_request_target` workflow which is "standalone". This means that no special privileges will be necessary to run it and that will in turn allow the `create-or-update-comment` action to work properly.
See these resources for more details:
- https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks
- https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
Our little tarball packing / commenting workflow doesn't work on community PRs! E.g. https://github.com/ionic-team/stencil/pull/5337
This should enable it to work on any PR …

chore(ci): refactor pack-and-comment workflow to support community PRs

---

src/compiler/config/test/validate-paths.spec.ts

This eliminates some SNC errors via judicious use of `!`, in places where its use is well-justified (I think so anyway!).

chore(snc): silence some SNC errors in validate-paths.spec.ts

---

renovate.json5

ignore dependency bumps for puppeteer for versions 22 and higher. starting with v22, puppeteer dropped support for node 16, which stencil v4 still supports.
N/A - internal change
I tested the using Renovate's validator tool:
```
`npm i -g renovate`
`renovate-config-validator`
```
This section also matches others that we have for ignoring Node 16-related packages

chore(repo): add puppeteer to the renovate ignore list

---

src/compiler/transformers/automatic-key-insertion/utils.ts

This fixes an issue where this couldn't be resolved in some cases.
fixes https://github.com/ionic-team/stencil/issues/5358
Check out hte reproduction case linked in #5358. First confirm you can reproduce the issue! Then build and install this branch in the repro, and confirm that it's fixed.

fix(compiler): point crypto import at `crypto` instead of `node:crypto`

---

scripts/bundles/internal.ts
scripts/bundles/plugins/alias-plugin.ts
scripts/esbuild/build.ts
scripts/esbuild/internal-app-data.ts
scripts/esbuild/internal-platform-client.ts
scripts/esbuild/internal-platform-hydrate.ts
scripts/esbuild/internal-platform-testing.ts
scripts/esbuild/internal.ts
scripts/esbuild/testing.ts
scripts/esbuild/util.ts
scripts/test/validate-build.ts
src/client/client-load-module.ts
src/compiler/style/css-to-esm.ts
src/compiler/transformers/add-static-style.ts
src/compiler/transformers/component-native/native-static-style.ts
src/runtime/initialize-component.ts
tsconfig.json

This adds an Esbuild script for the `internal/` directory to the project, allowing us to build all the various modules that need to be in there with Esbuild.
I've built and installed this in framework and example projects and I believe that everything is working correctly. However! This is a somewhat more complicated 'bundle' than some of our other directories, so it would be good to test quite extensively.
In particular, these things should be exercised:
- 'e2e' tests in a sample project
- building and using Framework (w/ react, angular, etc wrappers too ideally)
- using the hydrate script (perhaps using https://github.com/alicewriteswrongs/stencil-hydrate-example as a starting point)
I feel confident that things are working but it's entirely possible I have missed something that needs …

chore(build): use esbuild to build internal directory

---

.github/workflows/create-production-pr.yml
.github/workflows/release-production.yml
scripts/release-tasks.ts

**Do not merge, waiting for parent to land first**
We have a good deal of code related to releases that no longer runs.
now that stencil releases are largely automated, release tasks that
were skipped during manual releases can be removed. this commit removes
all tasks that were skipped with `isCI` is was `true` (as it's always
`true` these days).
additional conditionals that use logical-AND with `isCI` have been
updated, as that part of the conditional is now always `true`.
remove the `--otp` flag, as it is only used for manual releases
as a result of these removals, the `--any-branch` flag can be safely
removed from our release pipeline, as its no longer used.
N/A - this old process being removed had no documentation 🙈 
I kicked off a dev publish of Stencil …

chore(repo): remove old release scripts pt2

---

package.json

This removes the dependence of the esbuild-based build on the existing Rollup-based build. Previously we needed to run the Rollup-based build first so that certain files which could not yet be built with Esbuild would be present on disk, but since we can now build everything with Esbuild we don't need to take this step anymore.
We do, however, continue to need to run the TypeScript compiler in order to generate up-to-date typedef files.
Part of STENCIL-1016
This is blocked by #5276 and CI will not pass until that merges
If CI is passing this is a strong indication that we're in a good position to make this change.

chore(build): make esbuild standalone

---

scripts/build.ts
scripts/bundles/compiler.ts
scripts/bundles/dev-server.ts
scripts/bundles/plugins/alias-plugin.ts
scripts/bundles/plugins/content-types-plugin.ts
scripts/bundles/plugins/parse5-plugin.ts
scripts/bundles/plugins/pretty-minify.ts
scripts/bundles/plugins/terser-plugin.ts
scripts/bundles/sys-node.ts
scripts/esbuild/dev-server.ts
scripts/esbuild/testing.ts
scripts/esbuild/util.ts
scripts/release.ts
scripts/test/validate-build.ts
scripts/tsconfig.json
scripts/types/rollup-plugin-node-resolve.d.ts
scripts/types/rollup-plugin-sourcemaps.d.ts
scripts/utils/options.ts
scripts/utils/test/options.spec.ts
scripts/utils/write-pkg-json.ts

This turns on the `strict` option in the tsconfig for our build scripts. I then fixed the resulting errors by:
- making optional types required on `BuildOptions`
- reconfiguring the function that builds a `BuildOptions` object so that when the object is created all those fields are present
- fixed various other random errors here and there, like the `.code` property on minification results and a few things like that.
There are a few non-type-level changes but they're pretty contained, so I'm not terribly worried about the impact. I built and packed Stencil and installed it in Framework with no issues after these changes as well.

chore(scripts): turn on 'strict' tsconfig option

---

scripts/utils/options.ts

After we removed the old release scripts recently this option is no longer used anywhere, so we can delete it.
No behavior change, just removing an unused field from an interface.
This is just a type-level change, so if CI is passing I think we're good!

chore(scripts): remove an unused option from BuildOptions

---

.npmrc

See the 'new bheavior' section
the url that pulls down chrome images seems to be intermittently failing
in github actions. when we go to install dependencies (`npm ci`), we're
greeted with an error:
```
npm ERR! code 1
npm ERR! path /home/runner/work/stencil/stencil/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.mjs
npm ERR! Error: ERROR: Failed to set up chrome-headless-shell v121.0.6167.85! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
```
this appears to be a result of an intermittent failure (if it's
intermittent it to-be-determined). reports online suggest bumping to
puppeteer v22, which we cannot do at this moment due to it dropping
support for node 16. instead, set the base url environment variable to
tell …

chore(ci): fix puppeteer downloads

---

scripts/bundles/internal-platform-client.ts
scripts/bundles/plugins/replace-plugin.ts
scripts/esbuild/internal-platform-client.ts
src/client/client-load-module.ts

When we added a script for building the modules in `internal/` with Esbuild in #5276 we needed to make a change to the function that Stencil uses at runtime to lazy-load components (in
`src/client/client-load-module.ts`). Prior to #5276 we had a dynamic import statement which looked like so:
```ts
import(
`./${bundleId}.entry.js${BUILD.hotModuleReplacement && hmrVersionId ? '?s-hmr=' + hmrVersionId : ''}`
)
```
This constructs a filepath to the module for a given Stencil component, accounting for HMR versioning, and then imports the module. All well and good, but unfortunately this dynamic import does not play well with Esbuild. As described
[here](https://esbuild.github.io/api/#non-analyzable-imports) when Esbuild is in 'bundle' mode and it encounters an `import()` _and_ the imported …

fix(build): address issue with dynamic import and vite

---

src/declarations/stencil-public-compiler.ts

This interface is currently undocumented, so let's add some JSDoc. We can also reference this on the docs site in order to improve the quality of https://stenciljs.com/docs/copy-tasks.
STENCIL-1047

chore(docs): document `CopyTask` interface

---

src/mock-doc/test/element.spec.ts
src/mock-doc/window.ts

resolve strict null checks related to mock-doc element tests - throw
an error when a window is not cloned (and we expect to be). this allows
us to assert that the cloned window is truthy, resolving errors related
to accessing a possibly undefined obj
add checks when querying the dom for title text, preventing snc errors
related to accessing an undefined field
n/a
Unit tests/type checks continue to pass
n/a

chore(snc): element.spec.ts strictNullChecks 

---

renovate.json5

update the renovate configuration such that typescript version bumps will be prefixed with 'feat(typescript):', rather than the default value of `chore(deps):`. this will allow us to properly call out typescript version bumps in the stencil changelog generator, which do not occur today (as chore()'s are ignored)
N/A - renovate config
I ran `npm i -g renovate && renovate-config-validator` to verify this config filewas still valid.
Since I couldn't test this directly in our repo, I spun up a private one to verify the behavior here.
For a package.json file with TS 5.3.2 as a dev dep:
And a configuration that matches this repo's:
The following well formatted PR was created by renovate
The reproduction I put above begs the question "Is a …

chore(renovate): have renovate mark typescript bumps as 'feat'

---

src/declarations/stencil-public-compiler.ts

`esmLoaderPath` has currently no type documentation.
`esmLoaderPath` has type documentation
Addition PR to the Stencil docs has been raised in https://github.com/ionic-team/stencil-site/pull/1364
n/a
n/a

docs(compiler): add type docs for `esmLoaderPath`

---

.github/workflows/build-rollup.yml
.github/workflows/main-rollup.yml
package.json

This swaps over from Rollup to Esbuild for the main `npm run build` script in `package.json`. The existing Rollup based script is preserved as `build.rollup`.
This change causes our main CI run (`.github/workflows/main.yml`) to now use the Esbuild-based build, so the existing, supplemental CI run which previously was based on the Esbuild-based build pipeline now uses the 'legacy' (or nearly so) Rollup-based version. This requires a bit of renaming and so on.
STENCIL-1016
To test this out in the context of our GH-based releases I ran the dev and nightly releases against this branch:
- dev release: https://github.com/ionic-team/stencil/actions/runs/8087583103
- nightly release: https://github.com/ionic-team/stencil/actions/runs/8087594210
Both builds finished …

chore(scripts): swap from rollup to esbuild for main build

---

src/compiler/output-targets/dist-custom-elements/custom-elements-build-conditionals.ts
src/compiler/output-targets/test/build-conditionals.spec.ts
src/runtime/initialize-component.ts

Components hydrated on the server are hydrated wrongly on the client using the `dist-custom-elements` output target.
GitHub Issue Number: #3319 
By setting `build.hydrateClientSide = true` in `custom-elements-build-conditionals.ts` and by disabling lazy loading, the components are rendered correctly.
Reproduction repo:
https://github.com/andrew9994/stencil-hydrate-dist-custom-elements-bug
To completely unit test these modifications a change in the `spec-page.ts` would be needed and I was not sure that I should change that. Instead I added unit tests to check for the default values, and added missing unit tests for the`hasHydrateOutputTargets` logic in the `lazy-build-conditionals.ts`
Before:
After:

fix(custom-elements): hydrate on client side

---

src/cli/run.ts

This moves the version logging earlier in the `run` function for our CLI so that it's possible to log the version by doing any of
- `stencil version`
- `stencil -v`
- `stencil --version`
Prior to this change only `stencil version` would work, although we had code which was clearly intended to log the version in the case that `-v` or `--version` is passed.
Background: Stencil's CLI distinguishes between _tasks_ and _flags_.
A _task_ is the first CLI argument and does not start with a leading dash. It's basically treated as a subcommand, so in a CLI invocation of Stencil like `stencil build` the _task_ for Stencil will be `build`. We already support `version` as a valid task.
A _flag_, by contrast, is a CLI option which controls an aspect of how Stencil runs. It's passed at the command-line …

fix(cli): move version logging earlier in CLI to allow `-v`, `--version`

---

CHANGELOG.md

I meant to add a link to the _issue_, but I added a link to the _pr_. This fixes that.
Fixing a typo in the changelog

chore(changelog): fix typo

---

src/compiler/output-targets/dist-custom-elements/index.ts
src/compiler/output-targets/dist-custom-elements/test/dist-custom-elements.spec.ts

If you have a plain component like this:
```ts
@Component({
// styleUrl: 'my-component.css',
shadow: true,
})
/**
* The first name
*/
first: string;
}
```
and try to export it via:
```ts
{
type: 'dist-custom-elements',
customElementsExportBehavior: 'single-export-module'
},
```
the compiler will fail with:
```
[ ERROR ]  Rollup: Parse Error
Unexpected token (Note that you need plugins to import files that are not
JavaScript) 2: export { getAssetPath, setAssetPath, setNonce,
setPlatformOptions } from '@stencil/core/internal/client'; 3: export * from
'@user-index-entrypoint'; 4: export { {MyComponent } from 'MyComponent'; ^ 5:
6: globalScripts();
```
The change was originally introduced here: …

fix(compiler): fix generated import statement

---

src/declarations/stencil-public-compiler.ts

This JSDoc comment is currently outdated because it makes reference to a browser-specific `Logger` impl which we no longer have (it was deleted in #4317).
Documentation-only change

chore(docs): update JSDoc for the `Logger` interface

---

src/runtime/dom-extras.ts
src/runtime/vdom/vdom-render.ts

Stencil's patch for `appendChild` for slot emulation includes a call to `forceUpdate()` that is no longer needed and should not have been included in the first place (see new behavior section for more info).
This commit removes a call to `forceUpdate` that was added to Stencil's patch for `appendChild` for slot emulation. The call was originally added to fix a failing test in Framework that we've now identified was the result of the patch's DOM manipulation in tandem with a mutation observer in framework.
Instead, the mutation observer in framework was modified to observe changes in the element subtree, removing the need for this call.
STENCIL-1192
N/A
Automated unit and e2e tests continue to pass.
Tested this in a use case in Framework (see …

fix(runtime): remove `forceUpdate` in `appendChild` patch

---

src/cli/run.ts

A conspicuous omission! Now it is corrected.
Add a JSDoc to this method.

chore(docs): add a bit of JSDoc to `run` in `src/cli/run.ts`

---

src/compiler/optimize/optimize-js.ts

We already have JSDoc on the declaration for this function here:
https://github.com/ionic-team/stencil/blob/5b2c399f31cb689098f438eda4db2ee55c5412e1/src/compiler/public.ts#L73-L77
this ports it to the implementation.
Documentation-only change

chore(docs): add JSDoc to optimizeJs

---

src/compiler/config/test/validate-dev-server.spec.ts
src/compiler/config/validate-dev-server.ts
src/declarations/stencil-public-compiler.ts
src/dev-server/request-handler.ts
src/dev-server/test/req-handler.spec.ts

The Stencil dev server will "spin up" prior to the accompanying project build completing. This can cause issues for processes (such as E2E testing tools like Playwright), that rely on the dev server to work correctly. 
A new route is added to the dev server request handler. This route will return a 200 response once the Stencil build is completed and successful. If a build fails, or another error is encountered, the route will return a 500 error.
This route is configurable via the `devServer` object on the Stencil config. If the route is explicitly set to `null`, no route will be registered with the handler. 
https://github.com/ionic-team/stencil-site/pull/1363
Unit tests were added to the request handler and validation test suites.
**Manual …

feat(dev-server): add "ping" route

---

src/compiler/config/load-config.ts
src/compiler/config/test/load-config.spec.ts

It doesn't seem like `rootDir` is respected as part of Stencils config. As a developer building an unplugin for Stencil I need ot be able to create a stencil config on the fly in a temporary directory and tell the Stencil compiler that the root directory is somewhere else.
If the user provides a Stencil config path to the compiler we respect the `rootDir` property in there to define the root dir for Stencils compiler
Added a small unit test. Let me know if you like to add more testing.
n/a

fix(compiler): allow to set custom root directory

---

renovate.json5

We are currently not using the latest TypeScript version.
Have Renovate update to latest TypeScript.
n/a
Given their v5.4 announcement I expect no breaking changes nor updates required to our current code base.

chore(repo): allow Renovate to update to TypeScript 5.4

---

test/wdio/tsconfig-stencil.json

If you need to write a wdio test which references a host element interface the test will not compile correctly, complaining that it can't resolve the interface. I ran into that working on https://github.com/ionic-team/stencil/compare/ap/wdio/form-associated, where the component has a method like this:
```tsx
formAssociatedCallback(form: HTMLFormAssociatedElement) {
form.ariaLabel = 'formAssociated called';
// this is a regression test for #5106 which ensures that `this` is
// resolved correctly
this.internals.setValidity({});
}
```
The `HTMLFormAssociatedElement` interface is defined in `test/wdio/src/components.d.ts` and should be part of the global type namespace for the `test/wdio` project, but our `include/` in `test/wdio/tsconfig-stencil.json` wasn't including the component types …

chore(wdio): include the right path for the wdio-specific .d.ts file

---

renovate.json5

We just merged our initial WebdriverIO infrastructure. Renovate is trying to upgrade our Node version in https://github.com/ionic-team/stencil/pull/5466. We don't want that, as we want to continue to test against our oldest Node version
block node from being upgraded by renovate for the wdio directory, as we wish to continue to run these tests on the oldest version of node that stencil supports
I did the following to test this the best I could (as Renovate doesn't have dry runs):
- `npm i -g renovate && renovate-config-validator` to verify I hadn't copy/pasted this incorrectly (this verifies the json5 is still well formed) 😆 
- `cat test/wdio/package.json` to verify the path was correct
Otherwise, this is a near copy of the Karma directory rule directly above it

chore(repo): add wdio directory to renovate

---

src/compiler/transformers/decorators-to-static/event-decorator.ts
src/compiler/transformers/decorators-to-static/method-decorator.ts
src/compiler/transformers/decorators-to-static/prop-decorator.ts
src/compiler/transformers/transform-utils.ts

It currently seems that we have implemented a validation that would prevent returning a type that collides with the name of any imported Stencil type. As far as I understood the situation is as following: given I have a type name that has the same name as one of Stencils decorators (e.g. `Element`, `Event`, `Listen`, `Method`, `Prop`, `PropDidChange`, `PropWillChange`, `State` or `Watch`) it will throw a meaningless error. This can be easily reproduced in many ways:
```ts
// in src/utils/utils.ts
interface Method {}
export function returnSomethingInvalid(): Method {
return {}
}
```
Then having the following component decorator will fail:
```ts
// in src/components/my-component/my-component.tsx
import { Component, Prop, h, Method, EventEmitter, Event } from '@stencil/core';
import { …
```

fix(compiler): don't validate references for @Prop, @Method and @Event decorator

---

test/wdio/event-custom-type/cmp.tsx

See "New Behavior"
fix a build issue where running `npm run build` twice in the `test/wdio` directory would result in the following failure:
```
[47:48.5]  aborted build, 343ms  MEM: 359.2MB
[ ERROR ]  TypeScript: event-custom-type/cmp.tsx:3:44
Cannot find module '../components' or its corresponding type declarations.
L3:  import { EventCustomTypeCustomEvent } from '../components';
[47:48.5]  build failed in 343 ms
```
This was introduced in https://github.com/ionic-team/stencil/pull/5493, where the import statement was not correctly ported over. As a result, type resolution would fail under `tsconfig.json#moduleResoution` having a value of 'Node16'
Check out this branch and run `npm run build` 2+ times. You should not see an error

chore(wdio): fix build issues

---

src/mock-doc/document.ts
src/mock-doc/node.ts
src/mock-doc/test/element.spec.ts

Currently MockDoc doesn't provide a [`localName`](https://developer.mozilla.org/en-US/docs/Web/API/Element/localName) property for elements.
GitHub Issue Number: #5342
Adding that property.
n/a
Added some unit tests. Let me know if I should extend these.
n/a

fix(mock-doc): provide a local name

---

test/wdio/scoped-basic/cmp.test.tsx

This de-flakes things a bit. This test was sometimes not passing on CI in the style assertions where it checks things like `color` and `backgroundColor`, in particular I think because of some differences in how computer styles for these things are set and formatted.
I wasn't seeing this test failure locally, but only on CI when the tests are running in Firefox.
To run the tests locally you can do
```sh
CI=true npm run test.wdio
```

chore(test): make scoped-basic less flakey

---

.eslintrc.js
package-lock.json
package.json
test/wdio/scoped-basic/cmp.test.tsx
test/wdio/scoped-conditional/cmp.test.tsx

This adds `eslint-plugin-wdio` so that we can get some Webdriver-specific linting rules added to our configuration. In particular, we can specify that the `expect` function is prefixed with `await`, ensuring that we don't have dangling promises.
This rule is activated only for files in `test/wdio`.
We don't have a linting rule for this and I, in particular, keep forgetting to `await` everything.
Everything must be awaited!
If CI passes we're good.

chore(lint): add eslint-plugin-wdio, turn on rule for awaiting `expect`

---

renovate.json5

webdriverio packages are going to get bumped separately of one another. after asking christian (see link below in 'new behavior' section), he suggested we group these
configure renovate to group all `@wdio/` scoped npm packages and the `expect-webdriverio` package into a single pr when renovate detects version bumps.
the impetus for this work was a comment made during the wdio migration, available [here](https://github.com/ionic-team/stencil/pull/5498#discussion_r1528771603)
1. Ran `npm i -g renovate && renovate-config-validator` locally to verify no syntax errors
2. This matches the setup of our rollup config, so it _should_ work 🤞 
STENCIL-1191

chore(repo): group webdriverio + related pkgs in renovate

---

test/karma/karma.config.js

We have seen BS/Karma test failing increasingly for no particular reason. I looked into these failures and they seem to be mostly caused by Firefox and Edge.
In order to not get blocked on these flaky tests I removed these browser from the matrix to get the last test PR merged faster.
n/a
n/a

chore(test): remove FF and Egde from the browser matrix

---

.github/workflows/README.md
test/wdio/README.md

this change:
- adds an entry to the README in `.github/workflows` which briefly describes what the webdriverio workflow does
- adds a section to `test/wdio/README.md` which outlines how to create a new test suite from scratch

chore(wdio): expand wdio-related readme content

---

test/wdio/svg-attr/cmp.test.tsx

I've noticed an intermittent failure of the `svg-attr` webdriver test suite that looks like this:
```
Expected: null
Received: "rotate(45 27 27)"
[chrome-headless-shell 123.0.6312.58 linux #0-0] Error: expect(received).toBe(expected) // Object.is equality
[chrome-headless-shell 123.0.6312.58 linux #0-0]
[chrome-headless-shell 123.0.6312.58 linux #0-0] Expected: null
[chrome-headless-shell 123.0.6312.58 linux #0-0] Received: "rotate(45 27 27)"
[chrome-headless-shell 123.0.6312.58 linux #0-0]     at Context.<anonymous> (http://localhost:36575/home/runner/work/stencil/stencil/test/wdio/svg-attr/cmp.test.tsx:24:44)
```
The test looks like this on `main`:
https://github.com/ionic-team/stencil/blob/b62c28dbc275c8a9692b2427f9503d2eccff3adc/test/wdio/svg-attr/cmp.test.tsx#L17-L19
This PR changes …

test(wdio): make svg-attr test more robust

---

src/runtime/vdom/update-element.ts
test/wdio/ref-attr-order/cmp.test.tsx
test/wdio/ref-attr-order/cmp.tsx

Sort attribute names before calling `setAccessor` with their changed values in order to ensure that the `ref` attribute is handled by `setAccessor` after all other attributes have been handled. This prevents the execution order for `ref` callbacks from being dependency on the order in which attributes are declared in the JSX.
STENCIL-737
fixes #4074
At present `ref` callbacks are, like other attributes, handled in declaration-order, i.e. they are called based on the order in which they are declared in the JSX for a component.
This means that in a component like this:
```tsx
import { Component, h, State } from '@stencil/core';
@Component({
tag: 'ref-attr-order',
shadow: true,
})
export class RefAttrOrder {
render() {
return (
<div
ref={(el) => {
console.log(el.tabIndex);
}}
tabIndex={0}
> …
```

fix(runtime): prevent ref callbacks from being called too early

---

src/compiler/transformers/collections/add-external-import.ts

See 'new behavior`
GitHub Issue Number: #2319 
this commit fixes an issue where stencil builds that followed a successful build  would result in the following error:
```
[ ERROR ]  Component Tag Name "my-component" Must Be Unique
Please update the components so "my-component" is only used once:
./src/components/my-component/my-component.tsx ./dist/collection/components/my-component/my-component.js
```
this issue manifested on windows machines when building the ionic framework after a successful build. we were able reproduce this with a minimal stencil-component-starter that included the following in its `tsconfig.json`:
```json
{
paths: {
"@utils/*": ["src/utils/*"]
}
}
```
the import alias would be used as such:
```ts
// src/utils/helpers.ts
export const foo = () => console.log('hello'); …
```

fix(compiler): don't mistake aliased paths for collections imports

---

src/compiler/transformers/automatic-key-insertion/automatic-key-insertion.spec.ts
src/compiler/transformers/automatic-key-insertion/index.ts

This expands the scope of the automatic key insertion feature that was added in #5143. Previously the feature stopped at the border of any `JsxExpression` syntax node (a bit of arbitrary JavaScript wrapped in curly braces and then inserted into JSX) so that if you were doing something like:
```tsx
<div>{ someCondition && <span>when condition is true</span>}</div>
```
the compiler would insert a key into the `<div>` syntax tree node but _not_ the node for the `<span>`. We did this to just be a bit cautious with the feature because there are a lot of different things that could be going on within a `JsxExpression` node, and some things which could be written within curly braces which would not be safe to transform, such as the following:
```tsx
<div>{ xs.map(x => <span>{ x }</span>) }</div> …
```

feat(compiler): perform automatic key insertion in more situations

---

package.json

`npm run test.prod` fails due to the missing `test.sys.node` command in `package.json`. We removed this in #3332 and never caught this 😬 (just goes to show how often I actually run this command these days 🙃) 
fix the `test.prod` npm script, which attempts to run the `test.sys.node` command, which was removed in #3332
N/A
`npm run test.prod` runs locally again 🎉

chore(repo): fix test.prod package.json script

---

src/dev-server/templates/directory-index.html
src/dev-server/templates/initial-load.html

Late at night when I am tippy tapping on my keyboard while working with my favorite web component compiler and in the safety of my dark mode color scheme, Stencil's dev server will open and blind my soul with the eternal brightness of its light theme. 
GitHub Issue Number: Resolves #5643
Adds dark mode support to the dev server launcher and directory pages based on the system preferences. 
1. Work until late at night (this is important) with auto color scheme or manually set it to dark mode.
2. Launch Stencil's dev server.
2.5. Put on sunglasses. Solar eclipse glass will also work, get your money's worth out of them.
3. Observe: Stencil's super bright dev server. Don't stare too long though. 
4. Apply the changes from this PR.
4.5. Remove sunglasses.
5. Observe: Stencil super beautiful …

feat(dev-server): dark mode support

---

scripts/bundles/mock-doc.ts
scripts/esbuild/mock-doc.ts

In #5012 when we put together a script to build `mock-doc/` with Esbuild we refactored a custom, hand-built `.d.ts` bundler that was used in the Rollup build to instead use `dts-bundle-generator`, a library that we depend on elsewhere. Although in theory a better option for avoiding NIH syndrome the output is just too different, so we want to switch to using the old rollup approach in our new, Esbuild-based build script for `mock-doc/`.
To accomplish this we can just export the existing function from the Rollup script and then call it in the Esbuild script.
STENCIL-1246
To test this you can do the following:
```sh
npm run build.rollup
cp mock-doc/index.d.ts /tmp/rollup-mock-dock-index.d.ts
npm run build
co mock-doc/index.d.ts /tmp/esbuild-mock-doc-index.d.ts
``` …

chore(build): port d.ts bundling for mock-doc from rollup to esbuild

---

.gitignore
CONTRIBUTING.md
scripts/esbuild/cli.ts
scripts/esbuild/compiler.ts
scripts/esbuild/dev-server.ts
scripts/esbuild/util.ts
src/compiler/sys/stencil-sys.ts

This removes sourcemaps from the cli, compiler, and dev-server bundles and also removes the unused minified compiler build. All these changes are made to the esbuild-based build.
We realized recently that the minified compiler is no longer necessary (it was previously used for in-browser compilation support, and was removed in #4317) and the sourcemaps are similarly not useful, but do take up a significant amount of space.
Without this change a packed Stencil tarball is around 12MB, and with this change it drops to 3.5MB.
STENCIL-1242
Test that you can build and use Stencil with this change.
Also try out the 'debug' build, which is building like so:
```sh
DEBUG=true npm run build
```
that should produce sourcemaps for all the files bundled with Esbuild.

chore(build): remove sourcemaps, minified compiler build

---

scripts/esbuild/sys-node.ts

This uses the `externalAlias` plugin to 'externalize' the `graceful-fs` package from our `sys/node/index.js` bundle while also aliasing it to the file that we ship as part of the Stencil package at `sys/node/graceful-fs.js`.
We did a similar thing in #5625
Although we ship a bundled version of `graceful-fs` in `sys/node/graceful-fs.js` our bundle at `sys/node/index.js` is also inlining that module, so we have a little code duplication there.
The `sys/node/index.js` bundle now externalizes the bundled `graceful-fs` module so we're not duplicating it anymore.
You can first convince yourself that `graceful-fs` is being bundled in the current build by running the build and then inspecting `sys/node/index.js`. It's not a huge file, but if you just search in there for `graceful-fs` you'll see …

chore(build): exclude graceful-fs from the sys/node/index.js bundle

---

src/cli/parse-flags.ts
src/cli/test/parse-flags.spec.ts

This fixes a bug related to parsing of Boolean CLI arguments using the `--argName=value` type syntax.
We intend to support using that syntax to pass a boolean CLI flag (like `--watch`) but actually at present the way it is 'parsed' will result in such flags always being set to true! Not good!
This is because we were setting the value of the boolean CLI flag to `Boolean('false')` if you pass `--argName=false`, which does _not_ result in a value of `false` but instead a value of `true`. This is changed to instead use a check that the value equals `'true'` to turn the value into a boolean, and regression tests are added.
This was noticed when investigating #5640, but that bug actually has to do with how we convert CLI arguments into a Jest configuration.
If you pass a boolean CLI flag with …

fix(cli): fix a bug in CLI argument parsing

---

src/compiler/style/scope-css.ts

There's only one function exported from that module (`getScopeId`) but let's document it!

chore(jsdoc): add jsdoc to `src/compiler/style/scope-css.ts`

---

renovate.json5

see 'new behavior' section
GitHub Issue Number: Supersedes https://github.com/ionic-team/stencil/pull/5666
add eslint v9 (and above) to our renovate configuration. with this change, any updates to v9 and higher will not result in a version bump pull request from renovatebot. this is temporary, as we are blocked from upgrading until typescript-eslint support eslint v9
N/A
I ran the renovate validator locally:
`npm i -g renovate && renovate-config-validator`
Otherwise, there's not much we can do here until we land it

chore(repo): ignore eslint v9 from renovate updates

---

.github/workflows/test-wdio.yml
test/wdio/wdio.conf.ts

This refactors a bit how we control what browsers are used in our webdriverio tests. Instead of it being chrome or all browsers, where all browsers are activated by setting the `CI` environment variable, this adds a check for a `BROWSER` environment variable. How this works is that the webdriverio configuration file reads the environmen variable and if it's one of `FIREFOX`, `CHROME`, or `EDGE` it will set the tests to use that browser. If it's _not_ set (or set to an unrecognized value) we'll default to using chrome (as we do now), and if it's set to `ALL` it will run all of the browsers.
This also makes it easier for us to separate the test runs in separate browsers into separate jobs, so a failure only on Edge will show up more easily (and we'll get some more parallelism).
You need to …

test(wdio): add a browser matrix for our wdio tests

---

src/compiler/docs/generate-doc-data.ts
src/compiler/docs/readme/output-docs.ts
src/declarations/stencil-public-compiler.ts
test/docs-readme/custom-readme-output/components/styleurls-component/readme.md
test/docs-readme/stencil.config.ts

On the `docs-readme` output target it's possible to set a custom output location with the `.dir` property and the README files generation for components will then be output to relative paths (like `my-component/readme.md`) within that directory.
This fixes a bug where that behavior didn't properly respect any manually-entered content in those readme files, so that if, for instance, you set the output to `custom-readme-output` and had `"My Custom Text"` at the top of
`custom-readme-output/components/my-component/readme.md` then running a build would overwrite your custom text.
This changes things so that we read the content of the custom readme and use that as the basis for the new text that we're going to write to disk. This has the effect of preserving the custom text that a user might …

fix(docs): respect custom README content when writing to a custom path

---

.github/workflows/main.yml
.github/workflows/test-docs-build.yml
package.json
test/package.json

This adds a new GH actions workflow (`.github/workflows/test-docs-build.yml`) which runs `stencil build` in the `test/docs-json` and `test/docs-readme` directories. These two directories contain Stencil projects which exercise the `docs-json` and `docs-readme` output targets, respectively. The output for each project is checked in to the repo, so running a build on CI and then checking for a dirty git context serves as a test that the output of the output targets hasn't changed.
STENCIL-1272

test(docs): add a gh actions workflow for testing docs output targets

---

package.json
scripts/esbuild/build.ts
scripts/index.ts
scripts/release-tasks.ts

This changes our release process for `@stencil/core` to use the ESbuild-based build pipeline instead of our now-legacy Rollup-based build setup.
This change is intentionally made as small as possible in order to make it easy to diagnose any problems and easy to revert if needed. We have a follow-up ticket for removing the Rollup-related stuff more thoroughly.
STENCIL-1017
It's difficult for us to test this out thoroughly without actually running a release.

chore(release): switch release scripts to use ESbuild

---

src/compiler/types/validate-primary-package-output-target.ts

chore(validation): remove unneeded path arg 

---

.github/workflows/test-component-starter.yml
scripts/esbuild/cli.ts
scripts/esbuild/util.ts

this pr is motivated by a scenario where running `npx stencil generate`
would result in either an error or an early return:
```
npm run generate
> gen-test-1@0.0.1 generate
> stencil generate
[49:23.1]  @stencil/core
[49:23.2]  v4.17.0 ♨️
```
note: the reported error was never reproduced locally, only the early
return.
technically, this was introduced in v4.17.0, when we switched over to
using esbuild for production builds. however, this has been present in
any build that is esbuild-based since we migrated the cli submodule to
esbuild (where we had a mixed rollup-esbuild build during the migration
for dev builds).
removing this alias eliminates dynamic imports in the CJS output of the
cli submodule:
```
const {
prompt: r
} = await …
```

fix(cli): prevent generate task from crashing 

---

test/wdio/svg-attr/cmp.test.tsx
test/wdio/svg-class/cmp.test.tsx
test/wdio/text-content-patch/cmp.test.tsx

Some e2e tests have shown to be not stable. This patch rewrites them to use WDIO primitives that run these tests in a more async fashion and therefor will make them more stable.
More stable tests.
n/a
n/a
n/a

chore(test): improve stability of some e2e tests

---

src/runtime/vdom/update-element.ts

This adds some JSDoc to this function and also removes an unused parameter.

chore(jsdoc): add JSDoc to the `updateElement` function

---

src/compiler/docs/style-docs.ts
src/compiler/docs/test/style-docs.spec.ts

Stencil's doc generation does not support loud comments (comments starting with `/*!`). Loud comments prevent the comment block from being stripped from the output during the sass compilation.
Fixes: #5623 
The doc generation now matches against either a traditional comment block (`/**`) or a loud comment block (`/*!`).
N/A
Added an automated test for loud comment blocks.
Manually tested various combinations of comment blocks in a started project. This included no comment blocks, only loud comments, only traditional comments, and mixing both loud and traditional blocks.
I tested this with Stencil's postcss library as well ([`@stencil-community/poscss`](https://www.npmjs.com/package/@stencil-community/postcss)) and didn't run into any issues.

fix(compiler): recognize loud comments when generating style docs

---

src/compiler/docs/generate-doc-data.ts
src/compiler/docs/test/generate-doc-data.spec.ts

See 'new behavior' for the motivation here. But tl;dr - we didn't have tests, now we do 😉 
add unit tests for `src/compiler/docs/generate-doc-data.ts#getDocsStyles`. this was pulled out into a separate pull request from another effort, where we wish to add the `mode` that a stylesheet is associated with by a component's `@Component({})` decorator to the output of `docs-json`. these tests aren't strictly needed for that effort, but establish a baseline for tests taht will be added in the future.
the `getDocsStyles` function was exported in order to test it.
additional jsdoc and type annotations have been added to differentiate fields that are compiler metadata, and those that are used in our documentation intermediate representation.
Tests were made to fail/'red' …

test(docs): unit test style doc generation

---

scripts/esbuild/internal-platform-client.ts
scripts/esbuild/internal-platform-hydrate.ts
scripts/esbuild/internal-platform-testing.ts
scripts/esbuild/internal.ts
src/runtime/dom-extras.ts
src/utils/constants.ts
tsconfig.json

This one is a little involved to test because the full reproduction involves ionic framework and an ionic angular project.
So! We need to do some setup.
First, you should get Stencil linked up to ionic-framework. In the Stencil repo you can do:
```sh
npm link
```
Then in Framework do:
```sh
cd core
npm link @stencil/core
cd ..
```
then for testing purposes you'll need to apply this patch:
https://gist.github.com/alicewriteswrongs/1a1967bfe4171546f5393a91bcabee95
This adds a script for building the `@ionic/core` and `@ionic/angular` packages called `./build_angular.sh` and also makes some changes to `tsconfig.json` which are necessary for the `npm link` business to work correctly.
Once you have that in place you should also clone this reproduction of the issue: …

fix(build): address dist bundle size issue

---

src/runtime/styles.ts

This adds explanations for what goes on in this file, since before things were a bit mysterious.

chore(jsdoc): add JSDoc to src/runtime/styles.ts

---

src/mock-doc/serialize-node.ts
src/mock-doc/test/serialize-node.spec.ts

GitHub Issue Number: Fixes: #2994
add `track` to the list of "EMPTY" elements (void elements) that is referenced when we serialize nodes.
prior to this fix, the output of running `renderToString` as such:
```js
const hydrate = require('./hydrate/index.js');
const src = `<video>
<source src="x" type="video/mp4">
<track
kind="subtitles"
src="x"
>
</video>`;
hydrate.renderToString(src, { prettyHtml: true })
.then(result => console.log(result.html));
```
would result in the following being printed:
```html
<!doctype html>
<html class="hydrated" data-stencil-build="shc9pw4e">
<head>
<meta charset="utf-8">
</head>
<body>
<video>
<source src="x" type="video/mp4">
<track kind="subtitles" src="x"></track>
</video>
</body>
</html>
```
With this fix applied, we print …

fix(hydrate): output track elements as void elms

---

CONTRIBUTING.md

It is not straight forward to connect a local Stencil build with a test project. This likely has changed with our Esbuild release.
Update docs to reflect changed conditions and allow to build projects.
n/a
n/a

chore(docs): Update contributing guidelines to use local Stencil build

---

src/compiler/bundle/ext-transforms-plugin.ts
src/compiler/docs/generate-doc-data.ts
src/compiler/docs/style-docs.ts
src/compiler/docs/test/generate-doc-data.spec.ts
src/compiler/docs/test/style-docs.spec.ts
src/compiler/style/css-to-esm.ts
src/declarations/stencil-private.ts
src/declarations/stencil-public-docs.ts
test/docs-json/docs.d.ts
test/docs-json/docs.json
test/docs-json/src/components/my-component/my-component.ios.css
test/docs-json/src/components/my-component/my-component.md.css
test/docs-json/src/components/my-component/my-component.tsx
test/docs-json/stencil.config.ts

add a style mode to the output of the `docs-json` output target. when a stencil component is declared using the `styleUrls` property, a user may choose to apply styles depending on a "mode" that they set at runtime:
```tsx
// https://stenciljs.com/docs/component#styleurls
import { Component } from '@stencil/core';
@Component({
tag: 'todo-list',
styleUrls: {
ios: 'todo-list.ios.scss',
md: 'todo-list.md.scss',
}
})
export class TodoList {}
```
where the `todo-list.ios.scss` stylesheet will be applied with the mode is set to 'ios' at runtime, and `todo-list.md.scss` will be applied if the mode 'md' is set at runtime.
with this change, documented css properties will be associated with their respective modes in the output of the `docs-json` output target.
for …

feat(docs): add style mode to `docs-json` output

---

src/declarations/stencil-private.ts
src/runtime/test/scoped.spec.tsx
src/runtime/vdom/vdom-render.ts
test/wdio/scoped-id-in-nested-classname/cmp-level-1.scss
test/wdio/scoped-id-in-nested-classname/cmp-level-1.tsx
test/wdio/scoped-id-in-nested-classname/cmp-level-2.tsx
test/wdio/scoped-id-in-nested-classname/cmp-level-3.scss
test/wdio/scoped-id-in-nested-classname/cmp-level-3.tsx
test/wdio/scoped-id-in-nested-classname/cmp.test.tsx

sass compiler adds root scope id to the nested child elements too, therefore nested element selectors are not working from the root component since the root scope id is not adding as classname to the nested children elements
#5702
GitHub Issue Number: #5702

fix(runtime): add root scope id to the nested child as classname

---

src/testing/platform/testing-platform.ts
src/testing/spec-page.ts
src/testing/test/__fixtures__/cmp.tsx
src/testing/test/functional.spec.tsx
src/testing/test/tsconfig.json

The original issue claimed a Rollup error when writing functional components in tests. However I wasn't able to reproduce this behavior.
Instead, trying to render a functional component in unit tests would fail with the error:
```
TypeError: Cannot read properties of undefined (reading 'tagName')
3122 | var registerComponents = (Cstrs) => {
3123 |   Cstrs.forEach((Cstr) => {
> 3124 |     cstrs.set(Cstr.COMPILER_META.tagName, Cstr);
|                                  ^
3125 |   });
3126 | };
3127 | function registerModule(bundleId, Cstr) {
at ../../../Users/christian.bromann/Sites/Ionic/projects/stencil/internal/testing/index.js:3124:34
at Array.forEach (<anonymous>)
at registerComponents (../../../Users/christian.bromann/Sites/Ionic/projects/stencil/internal/testing/index.js:3123:9)
at …
```

fix(testing): support functional components in unit tests

---

src/compiler/output-targets/dist-lazy/generate-esm.ts
src/compiler/output-targets/output-lazy-loader.ts
src/compiler/output-targets/test/output-lazy-loader.spec.ts

Prior to this change Stencil will copy polyfills to the `dist` output target whether or not the user has indicated they'll be necessary.
The polyfills comprise two things: copying the polyfills themselves into the 'loader' path, and adding code to the lazy-loader entry points which loads those polyfills. Instead of just assuming that the user wants this, we now gate this behavior on whether `buildEs5` is set on the Stencil configuration.
fixes #5416
STENCIL-1288
Right now we copy a bunch of polyfills which won't be necessary outside of an ES5-only environment even when `buildEs5` is not set. This adds some extra bulk to the `dist` build output.
See #5416 for more details.
If the user has set `buildEs5` to true then we copy the polyfills, otherwise we don't do anything.
The best way to …

fix(build): do not copy polyfills to the `dist` OT unless building es5

---

src/compiler/output-targets/index.ts
src/compiler/output-targets/output-custom.ts
src/compiler/output-targets/output-docs.ts
src/declarations/stencil-public-compiler.ts

GitHub Issue Number: #5514
In this PR, I've added logic so that OutputTargetCustom can be called in dev mode and not just during build.
OutputTargetCustom can choose when it runs by adding a `task` property to the declaration object.
Run stencil tests + manual test with npm link

fix(compiler): Allow OutputTargetCustom to be called on devMode

---

src/app-data/index.ts
src/compiler/app-core/app-data.ts
src/compiler/output-targets/dist-hydrate-script/hydrate-build-conditionals.ts
src/declarations/stencil-private.ts
src/declarations/stencil-public-compiler.ts
src/testing/reset-build-conditionals.ts

Stencil supports a way to inject options into the script tag that then will be parsed into the runtime e.g. to set the `syncQueue` flag in [`CustomElementsDefineOptions`](https://github.com/ionic-team/stencil/blob/1d0fd962ed2211afea4a7e5e42222723b0a6184a/src/declarations/stencil-public-runtime.ts#L1865). This doesn't seem to be commonly used anymore so it is fine to deprecated and remove in v5.
Depcreate the `scriptDataOpts` option.
Raised PR with docs updates in https://github.com/ionic-team/stencil-site/pull/1425
n/a
n/a

fix(compiler): deprecate `scriptDataOpts`

---

.github/workflows/test-analysis.yml
.github/workflows/test-component-starter.yml
.github/workflows/test-docs-build.yml
.github/workflows/test-e2e.yml
.github/workflows/test-unit.yml
package-lock.json
package.json
renovate.json5
src/utils/test/util.spec.ts
tsconfig.json

Updating to support node v22
it's node v22! you can see some details about what's included in the release here: https://nodejs.org/en/blog/announcements/v22-release-announce
If all of our automated tests are passing and you can build a sample project without issues then this should be good!

chore(node): update support to node v22

---

cspell-wordlist.txt
src/runtime/set-value.ts

There are case where user can load components that are not compatible to each other, e.g. loading a lazy-loading component into an application that doesn't use lazy loading. This can also happen when a component is loaded twice, e.g. via an import __and__ through the loader script.
A fix for this issue would be out of scope as it requires research on how to avoid this generally in Stencil. I created internal tickets to kick of this effort in the upcoming sprints. For now, this error message should better direct users on what to do.
n/a
n/a

chore(runtime): provide better error message for edge case where multiple runtimes are being used

---

src/mock-doc/node.ts

Fixing some strictNullChecks errors in `src/mock-doc/node.ts`, pretty much relating to when values could be `null`.
Automated tests should be good!

chore(snc): fix snc errors in src/mock-doc/node.ts

---

src/compiler/transformers/static-to-meta/visitor.ts
src/compiler/transpile/transpile-module.ts

Fixing some snc errors here by changing around a few typecasts or assertions.
If the automated tests are passing we should be good!

chore(snc): fix some snc errors in transpile-module.ts

---

src/runtime/connected-callback.ts
src/runtime/dom-extras.ts
src/runtime/test/shadow.spec.tsx
src/runtime/vdom/vdom-annotations.ts
src/runtime/vdom/vdom-render.ts
test/wdio/scoped-id-in-nested-classname/cmp-level-1.scss
test/wdio/scoped-id-in-nested-classname/cmp-level-1.tsx
test/wdio/scoped-id-in-nested-classname/cmp.test.tsx

fix(runtime): add root scope id to the user provided nested children as classname

---

CHANGELOG.md
package-lock.json
package.json

This reverts commit e7f8129827ee279b8c3cbf07e749f581dd8b3c5a.
This breaks our release process at present so we're going to back out the upgrade.

Revert "chore(deps): update dependency execa to v9 (#5758)"

---

src/testing/puppeteer/puppeteer-element.ts
test/end-to-end/src/element-cmp/element-cmp.e2e.ts

The `E2EElement.getComputedStyle()` method would not return values for CSS variables assigned to the element directly.
GitHub Issue Number: #5681
This small tweak includes CSS variables assigned to the host element directly.
n/a
Added an e2e test.
n/a

fix(e2e): allow to fetch CSS variables assigned to host elements

---

src/client/client-load-module.ts
src/hydrate/platform/index.ts
src/runtime/initialize-component.ts

Due to the fact we don't have strict null checks we missed this area where `Cstr` can be null at a point where we wanted to access a property (e.g. `isProxied`).
GitHub Issue Number:
fixes #5759
I removed the condition that errors are only thrown if `(BUILD.isDev || BUILD.isDebug)` is truthy. It doesn't make much sense to me why we only would want this error to be elevated in these conditions.
n/a
n/a
n/a

fix(runtime): always throw if component can not be loaded

---

src/compiler/app-core/app-data.ts
src/compiler/bundle/app-data-plugin.ts
src/compiler/bundle/test/app-data-plugin.spec.ts
src/compiler/output-targets/dist-hydrate-script/bundle-hydrate-factory.ts
src/compiler/output-targets/dist-hydrate-script/generate-hydrate-app.ts
src/compiler/output-targets/dist-hydrate-script/hydrate-build-conditionals.ts
src/compiler/output-targets/test/build-conditionals.spec.ts
src/declarations/stencil-private.ts
src/runtime/update-component.ts

fixes #3606
STENCIL-609
At present the values set on the `hydratedFlag` configuration option in the Stencil configuration aren't really respected by the hydrate script -- see the attached issue for details.
GitHub Issue Number: #3606
This ensures that the right hydration stuff is set on the build conditionals for the hydrate script.
You can verify this works by taking a look at the issue and confirming that this branch fixes the issue.

fix(hydrate): respect `HydratedFlag` configuration in hydrate script

---

src/runtime/initialize-component.ts
test/wdio/setup.ts
test/wdio/watch-native-attributes/custom-tag-name.test.tsx

If users define their component with a custom tag name, the `@Watch` decorator doesn't work.
GitHub Issue Number: #3554
STENCIL-546
Instead of using the component meta data we just pick the tag name for the component directly.
n/a
Added an unit test for this.
n/a

fix(runtime): support watch for components with custom tag names

---

scripts/updateSelectorEngine.ts

Found this obsolete `!` in this `console.log` statement which was properly a debugging thing I added.
Removing this.
n/a
n/a

chore(scripts): minor wording fix in console.log

---

scripts/esbuild/sys-node.ts

With Stencil v4.18.1 Stencil broke support for Jest v26 due to the fact that transient dependencies for `glob` in `sys/node/glob.js` started to use imports with `node:` prefixes.
GitHub Issue Number: #5766
I enhanced the sys node build script to remove these prefixes. This won't have any impact on the script and allows us to keep support for Jest v26.
- Check out https://github.com/deleonio/kolibri-library/tree/reproduction-5766
- run `pnpm install` and verify that test pass with `npm test`
- now update Stencil to latest, rerun test and verify that test fail due to `no such file or directory, open 'node:path'`
- now install `@stencil/core@4.18.2-dev.1716246842.b6713e1` (dev build of this branch) and rerun tests, verify that tests pass
I was under the assumption that we are testing running …

fix(esbuild): remove all `node:` imports from glob script to keep support for Jest v26

---

src/mock-doc/element.ts
src/mock-doc/test/element.spec.ts

The current canvas class in Mock Doc didn't support `toDataURL`.
Support method.
Added a unit test.
This was originally proposed in https://github.com/ionic-team/stencil/pull/2923 which I closed in favor of this one. @rwaskiewicz I hope this addresses your comment.

fix(mock-doc): support toDataURL method in canvas

---

src/compiler/transpile/run-program.ts

This fixes a bug introduced in #4315, which upgraded to TypeScript 5. In that PR we had to change the way that we prevented certain files from being emitted by the typescript compiler because in the 5.0 release our previous approach stopped working.
However, in porting over to a new approach that worked with TS 5.0 there was an oversight. I misunderstood the intent of the old code as being to merely prevent writing `.d.ts` files in the output, when actually it was about preventing the compiled JavaScript from being written for `.e2e.ts` and `.spec.ts` files.
This change ensures that we no longer emit these files.
fixes #5788
STENCIL-1325

fix(emit): don't emit test files

---

src/cli/run.ts
src/compiler/transformers/add-static-style.ts
src/compiler/transformers/core-runtime-apis.ts
src/compiler/transpile/transpiled-module.ts
src/compiler/types/tests/ComponentCompilerEvent.stub.ts
src/compiler/types/tests/ComponentCompilerMeta.stub.ts
src/compiler/types/tests/ComponentCompilerMethod.stub.ts
src/compiler/types/tests/ComponentCompilerProperty.stub.ts
src/compiler/types/tests/ComponentCompilerTypeReference.stub.ts
src/compiler/types/tests/ComponentCompilerVirtualProperty.stub.ts
src/compiler/types/tests/TypesImportData.stub.ts
src/declarations/stencil-private.ts
src/testing/mocks.ts
src/utils/output-target.ts

This fixes some `@link` tags in JSDoc which weren't resolving correctly. Since the Typedoc tool reports on `@link` tags which it can't resolve we can use that to find them.
Some of these links don't actually resolve! It's a bit hard to see this, but one way that I can test if the `{@link Foo}` is correctly resolving the symbol `Foo` is to ask the LSP about it in my editor. If the name can be resolved then I'll see some info about it, otherwise I won't. This shows the before and after of this in `src/cli/run.ts`:
https://github.com/ionic-team/stencil/assets/6207644/5b416c3b-af86-4c17-85d2-08407fbc8271
We have `import type * as d from '../declarations';` at the top of the file, so `d.CompilerSystem` can be resolved but `CompilerSystem` cannot. 
Several of these are fixed! A few where it …

chore(jsdoc): fix some JSDoc `@link` tags

---

renovate.json5

Lowers the frequency at which Renovate runs from twice a week, to once a month. This will cut down on the noise of update PRs. Many of these updates tend to not be useful to Stencil and/or can cause unforseen breaking changes. Some dependencies may be manually updated on a case-by-case basis.
Merge and find out if it works. The schedule was taken directly from renovate's examples so should work 🤞

chore(renovate): lower update frequency

---

src/compiler/build/test/write-export-maps.spec.ts
src/compiler/build/write-build.ts
src/compiler/build/write-export-maps.ts
src/compiler/config/validate-config.ts
src/compiler/types/validate-primary-package-output-target.ts
src/declarations/stencil-public-compiler.ts

Stencil does not generate export maps for any entry points.
Stencil will generate export maps at build time. This include the default entry point, entry points for the lazy-loader (if applicable), and each custom element (if applicable).
This behavior is gated behind a new config flag.
https://github.com/ionic-team/stencil-site/pull/1443
Unit tests were added for the new behavior.
This feature can be manually tested by installing a build of this branch into the component starter and enabling the `generateExportMaps` config flag.

feat(compiler): generate export maps on build

---

src/declarations/stencil-private.ts
src/testing/puppeteer/puppeteer-screenshot.ts
src/testing/puppeteer/test/puppeteer-screenshot.spec.ts

fixes #3188
This patch exposes the `captureBeyondViewport` option to the `pageCompareScreenshot` as requested in given issue.
Added a unit test for this.
n/a

feat(testing): expose captureBeyondViewport in pageCompareScreenshot

---

src/mock-doc/global.ts

fixes #3260
This patch exposes `DocumentFragment` and `ShadowRoot` into the global scope.
n/a
n/a

fix(mock-doc): expose ShadowRoot and DocumentFragment globals

---

src/runtime/update-component.ts

There is a discrepancy between how Stencil handles errors in synchronous vs asynchronous component lifecycle methods. In synchronous components, the error is thrown, but the component will still render. For async, the error block component rendering.
Fixes: #5824 
The runtime will now catch errors thrown from async lifecycle methods, log them, and then continue the render cycle.
Validated fix in the associated issue's reproduction case.

fix(runtime): catch errors in async lifecycle methods

---

src/testing/jest/jest-27-and-under/jest-environment.ts
src/testing/jest/jest-27-and-under/jest-setup-test-framework.ts
src/testing/jest/jest-28/jest-environment.ts
src/testing/jest/jest-28/jest-setup-test-framework.ts
src/testing/jest/jest-29/jest-environment.ts
src/testing/jest/jest-29/jest-setup-test-framework.ts
src/testing/puppeteer/puppeteer-element.ts
test/end-to-end/src/miscellaneous/test.e2e.ts

Currently Stencil tears down all pages in an `afterEach` hook which causes issues when you re-use a page object across multiple it blocks, e.g.:
```tsx
import { type E2EPage, newE2EPage } from '@stencil/core/testing';
describe('do not throw page already closed if page was defined in before(All) hook', () => {
let page: E2EPage
beforeAll(async () => {
page = await newE2EPage()
})
it("first test", async () => {
const p = await page.find('html')
expect(p).not.toBeNull()
})
it("second test", async () => {
const p = await page.find('html')
expect(p).not.toBeNull()
})
})
```
fixes #3720
Let's not remove all pages after each `it` block and instead do it after all it blocks or when the user is creating a `newE2EPage` object.
n/a
Added an e2e test to verify this expected behavior works.
n/a

fix(testing): allow to re-use pages across it blocks

---

src/compiler/types/generate-app-types.ts
src/compiler/types/tests/ComponentCompilerEvent.stub.ts
src/compiler/types/tests/generate-app-types.spec.ts
src/compiler/types/tests/stencil-types.spec.ts
src/compiler/types/update-import-refs.ts
src/declarations/stencil-private.ts

Stencil does not correctly handle aliased types when generating the `components.d.ts` file. If a type import is aliased, the generated file will try to import _only_ the aliased name, which cannot be resolved.
Closes: #2335 
Stencil will now import and cast (`as`) from the original type name to the aliased name in the generated `components.d.ts` file.
N/A
Tested the behavior in a component starter example.
Added a unit test for the new behavior.

feat(complier): support type import aliasing

---

src/runtime/initialize-component.ts
src/runtime/styles.ts

Fixes ionic-team/ionic-framework#29593
The type fix I initially did suggested a different type ob the style object so this fix makes this more clear that `Cstr.style` can be either a `string` or a `Record<string, string>`.
n/a
n/a

fix(runtime): properly assign style declarations

---

src/testing/puppeteer/puppeteer-declarations.ts
src/testing/puppeteer/puppeteer-page.ts

fixes #2572
This patch allows users to change the behavior to not log failing network requests.
n/a
n/a

feat(testing): allow to disable network error logging via 'logFailingNetworkRequests' option

---

src/declarations/stencil-public-runtime.ts

fixes #3473
Remove support for `htmlfor` type which is not valid for labels.
n/a
n/a

fix(typescript): remove unsupported label property

---

src/declarations/stencil-private.ts
src/testing/jest/jest-27-and-under/matchers/events.ts
src/testing/jest/jest-27-and-under/matchers/index.ts
src/testing/jest/jest-28/matchers/events.ts
src/testing/jest/jest-28/matchers/index.ts
src/testing/jest/jest-29/matchers/events.ts
src/testing/jest/jest-29/matchers/index.ts
test/end-to-end/src/components.d.ts
test/end-to-end/src/event-cmp/event-cmp.e2e.ts
test/end-to-end/src/event-cmp/event-cmp.tsx
test/end-to-end/src/event-cmp/readme.md

Stencil offers event matchers for `toHaveFirstReceivedEventDetail` and `toHaveNthReceivedEventDetail`.
GitHub Issue Number: Closes #2488 
Adds a matcher for `toHaveLastReceivedEventDetail` that will check the `detail` content of an event emitted from a Stencil component
Tested the matchers (for first and last event) in a component starter.

feat(testing): add `toHaveLastReceivedEventDetail` event spy matcher

---

src/declarations/stencil-private.ts

Stencils Nightly build is failing due to a type change made in #5792. The original intention was to reflect reality better because `getHostRef` may return `undefined`. However it seems easier to just revert this change for now to ensure we don't break Ionic when releasing the change.
Reverted particular change.
n/a
n/a
Stencil nightly build: https://github.com/ionic-team/ionic-framework/actions/runs/9640370566/job/26608094616

fix(declarations): fix nightly build

---

src/compiler/types/stencil-types.ts

When updating type names for component type imports, Stencil will match based on the original type name string. This can result in string partials getting replaced if they match the replacement string. For instance, having a type `Setting` that gets aliased to `Setting1` to avoid type collisions, can result in another type, like `TextSetting` getting changed to `TextSetting1` since the compiler will replace all instances of `Setting` with `Setting1`
Fixes #3975 
The compiler will only replace full matches of the string. So, `Setting` will still become `Setting1`, but `TextSetting` wouldn't change.
N/A

fix(compiler): match full type name when doing type name replacement

---

renovate.json5

Changes Renovate's schedule config to a cron job. Since changing to natural language syntax, Renovate has been running more frequently. After some quick online investigation, it appears that support for natural language syntax may not be as stable as Renovate's documentation can lead to believe.
We can give this a shot and update our other repositories once we're confident this is working as expected

chore(renovate): change to cron schedule

---

src/compiler/app-core/app-data.ts
src/runtime/proxy-component.ts
test/wdio/watch-native-attributes/cmp-no-members.test.tsx
test/wdio/watch-native-attributes/cmp-no-members.tsx

`@Watch()` callbacks will not fire for native HTML attributes if there is not at least one Stencil member (`@State` or `@Prop`) within the component. 
Fixes #5854
Watch callbacks will no correctly fire even if no Stencil members are present
New e2e test added for use case and verified fix in reproduction

fix(runtime): allow watchers to fire w/ no Stencil members

---

src/cli/task-generate.ts
src/cli/test/task-generate.spec.ts

This feature was requested in #2155 but the community PR (https://github.com/ionic-team/stencil/pull/2334) was never reviewed. Let's get this in as it seems generally useful.
We recognise the Less or Sass plugin now, if it exists and generate a proper style file. In case Sass is used, we also ask which format they want to use (`.sass` vs `scss` files).
n/a
n/a
@tanner-reits you made [this comment](https://github.com/ionic-team/stencil/issues/2155#issuecomment-1235827720) to enhance the `create-stencil` package, can you elaborate what you were thinking?

feat(cli): support generation of sass and less files

---

src/compiler/transformers/type-library.ts

7ffb25d259de5b863e7dc3bc43270265cc786557 introduced a regression when generating the `components.d.ts` file. The logic for import aliasing did not account for external packages, resulting in broken import/export statements like `import { as MyType } from 'external-package';`
Fixes #5859 
The compiler will now generate a stub id for external packages so we can keep track of the original type name.
N/A
Verified fix on the reproduction case
This does technically change the output generated for the `docs-json` output target. Previously, the id for imports in these cases would be an empty string, now it will be a mocked id in the form of `node_modules::<type_name>'

fix(compiler): account for package imports in aliasing

---

src/hydrate/runner/render.ts
test/end-to-end/package.json
test/end-to-end/src/declarative-shadow-dom/test.e2e.ts
test/end-to-end/stencil.build.config.ts
test/end-to-end/tsconfig.build.json

We have received feedback that people were running into type issues with the `hydrateDocument` function resolving in returning a `Readable` by default. This goes against our objective of supporting DSD without a breaking change.
Change the order of function overwrites to have TS resolve into a Promise first.
Added an e2e test for this.
Thanks @sean-perkins for the hint!

fix(hydrate): change type resolve order

---

package.json
test/end-to-end/exportMap/index.js
test/end-to-end/exportMap/index.mts
test/end-to-end/package-lock.json
test/end-to-end/package.json

We recently added an export map to Stencil and didn't include the `cli` sub modules which has been used by the community.
Add the `cli` sub module to the export map.
Will work on a test for this separately.
n/a

fix(internal): add cli sub package to export map

---

package.json
test/end-to-end/exportMap/index.js
test/end-to-end/exportMap/index.mts

There was an export target missing. Something that is no where documented that you can just use the Jest testrunner and test Stencil components by just passing in `preset: '@stencil/core/testing',`.
GitHub Issue Number:
fixes #5871
fixes #5868
Enable this use case again.
Added unit tests for this.
n/a

fix(testing): add testing sub module to export map

---

src/hydrate/platform/hydrate-app.ts
test/end-to-end/src/components.d.ts
test/end-to-end/src/declarative-shadow-dom/dsd-listen-cmp.css
test/end-to-end/src/declarative-shadow-dom/dsd-listen-cmp.tsx
test/end-to-end/src/declarative-shadow-dom/test.e2e.ts
test/end-to-end/src/miscellaneous/test.e2e.ts

Server side rendering fails when the component has a event listener attached to it. e.g.:
```ts
import { Component, Element, Host, h, Listen } from '@stencil/core';
@Component({
tag: 'my-whatever-component',
styleUrl: 'my-whatever-component.css',
shadow: true,
})
export class MyWhateverComponent {
@Element() hostElement;
private slotRef: HTMLSlotElement;
@Listen('click', { capture: true }) // Crashes, incorrect binding in hydrate index.js
handleKeyPress(): void {
}
render() {
return (
<Host>
<slot ref={(el: HTMLSlotElement) => this.slotRef = el}></slot>
</Host>
);
}
}
```
Culprit here was that `addHostEventListeners` was called without `this` attached to it, causing the function to throw an error and stopping the vdom annotation process to continue, leaving some nested components without …

fix(hydrate): support server side rendering of components with listener

---

src/hydrate/runner/render.ts
test/end-to-end/src/declarative-shadow-dom/test.e2e.ts

GitHub Issue Number: fixes #5884
Ensure beforeHydrateFn and afterHydrateFn are always returning a function.
Added e2e test to ensure we don't run into any future regressions.
thanks @tweis for filing the original PR for this in #5885

fix(hydrate): ensure beforeHydrateFn and afterHydrateFn always return a function

---

src/runtime/vdom/test/vdom-render.spec.tsx
src/runtime/vdom/vdom-render.ts

Stencil believes two nodes are the same on initial render, in cases were are comparing slots with no name attached to them. This causes rendering issues and the slot node being removed.
Instead, Stencil should not re-order its VDOM and properly hydrate the VDOM first.
Added some unit test to check this case.
Discovered this as part of my work on #5831

fix(runtime): make isSameVnode return false on initial render in a hydration case

---

src/compiler/bundle/bundle-output.ts
src/compiler/bundle/ext-transforms-plugin.ts
src/compiler/bundle/test/ext-transforms-plugin.spec.ts
src/compiler/config/transpile-options.ts
src/compiler/style/css-to-esm.ts
src/compiler/transformers/add-static-style.ts
src/compiler/transformers/component-hydrate/hydrate-runtime-cmp-meta.ts
src/compiler/transformers/component-native/native-static-style.ts
src/declarations/stencil-private.ts
src/hydrate/platform/hydrate-app.ts
src/hydrate/platform/proxy-host-element.ts
src/hydrate/runner/inspect-element.ts
src/hydrate/runner/render.ts
src/mock-doc/serialize-node.ts
src/runtime/bootstrap-lazy.ts
src/runtime/initialize-component.ts
src/runtime/styles.ts
src/runtime/test/shadow.spec.tsx
src/runtime/vdom/vdom-render.ts
src/utils/shadow-css.ts
src/utils/test/scope-css.spec.ts
test/end-to-end/src/components.d.ts
test/end-to-end/src/declarative-shadow-dom/__snapshots__/test.e2e.ts.snap
test/end-to-end/src/declarative-shadow-dom/cmp-dsd.css
test/end-to-end/src/declarative-shadow-dom/cmp-dsd.tsx
test/end-to-end/src/declarative-shadow-dom/cmp-with-slot.tsx
test/end-to-end/src/declarative-shadow-dom/test.e2e.ts
test/end-to-end/src/miscellaneous/renderToString.e2e.ts
test/end-to-end/test-end-to-end-hydrate.js

With previous versions of Stencil where we didn't not had support for DSD, we used to comment selectors and transform them so that shadow components can by hydrated as scoped components. To have the styles applied properly, we would transform them and keep the original selector commented, e.g.:
```diff
- div {font-size:50px;}}';
+ /*!@div*/div.a {font-size:50px;}}';
```
GitHub Issue Number: fixes #5880
Since component styles are handled at compile time there is no easy way for us to just render define this behavior when calling `renderToString`. Hence this PR will change the behavior of how shadow components are being serialized. It now __doesn't__ render the shadow DOM anymore if the `serializeShadowRoot` is set to false. Before Stencil would transform a shadow component into a scoped …

fix(compiler): no need for commenting selectors anymore

---

package-lock.json
package.json
scripts/release-tasks.ts

In https://github.com/ionic-team/stencil/commit/e7f8129827ee279b8c3cbf07e749f581dd8b3c5a we upgraded `execa` which we are using for the release script. In the next release we discovered that it would cause the pipeline to [stale](https://github.com/ionic-team/stencil/actions/runs/9066025905/job/24907994505) which lead us to revert the [change](https://github.com/ionic-team/stencil/pull/5761).
This patch resolves the issue we've faced which is likely a result of the incompatibility of rxjs dealing with Buffer streams. `execa` has replaced usage of Buffer in favor of [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array).
n/a
We may want to update the release script and move off `Listr` which hasn't seen released in 6 years.

chore(release): update execa and fix incompatibility with Listr

---

package.json
test/end-to-end/exportMap/index.js

When requiring `@stencil/core/testing/jest-preset` your import will fail as the module is not exported.
GitHub Issue Number: fixes #5896
Adding this to the export map. It wasn't very clear before which files are being used by users. So this fixes a regression I introduced by adding these export maps.
n/a
Added a test for this.
n/a

fix: add @stencil/core/testing/jest-preset to export map

---

src/compiler/output-targets/index.ts

The copy task is run at the same time as other output targets which doesn't allow users to include any of the build artifacts into the copy task.
GitHub Issue Number: fixes #5592
Run the copy task after all build artifacts are generated. Since `outputCopy`, `outputWww`, `outputDocs`, `outputTypes` and `outputCustom` are not dependent on each other I wrapped them into a `Promise.all` so we don't increase the build time due to more sequential calls.
Not sure how to properly test this, hence if current build passes I would feel confident moving forward.
STENCIL-1327

fix(compiler): run copy task after other output targets

---

src/compiler/transformers/static-to-meta/component.ts
src/compiler/transformers/test/parse-component.spec.ts

We have discovered an issue where a user is running into hydration issues due to the fact that they have defined a component getter like so:
```ts
/**
* Gets shadow root of nearest host element if one exists
*/
private get shadowRoot() {
return this.host.getRootNode() as ShadowRoot;
}
```
The compiler now detects this class member in a Stencil components and throws a nice error making users aware that this is not allowed.
This can potentially break for people that do this but don't do any client side hydration.
Added sufficient unit tests.
n/a

fix(compiler): don't allow shadowRoot getter to avoid hydration issues

---

src/runtime/client-hydrate.ts
src/runtime/vdom/vdom-render.ts
test/end-to-end/src/declarative-shadow-dom/test.e2e.ts

In order to support Next.js we have to inject the hydration comment into the template tag to properly supported nested components. This requires us to hydrate the shadow root first before hydrating the light dom.
When hydrating the component, walk through the shadow root first before light dom.
I did some manual test and it all seems fine. Not sure how we should test this from end to end or if a unit test makes sense.
n/a

fix(runtime): hydrate shadow dom first

---

src/runtime/styles.ts
test/end-to-end/src/miscellaneous/renderToString.e2e.ts

The `<style />` tag for scoped components is added before any link tag. The behavior was implemented in https://github.com/ionic-team/stencil/commit/05d242d5d6ba558896495df3f7b923ca109c70d9 without any concrete description as to why. As reported in below linked issue it can cause links with `preconnect` attribute to be loaded later hence negatively impacting the performance of an application.
GitHub Issue Number: fixes #5915
Attach styles at the end of the `<head />` so that the browser can already load assets marked with `preconnect` before all styles are streamed over the wire.
An alternative would be to make this configurable but I don't think there is a viable reason why someone would want to have styles injected first. If someone reports the requirement for this we can add it to the …

fix(runtime): render component styles at the end of the head tag

---

renovate.json5

Renovate tries to update these packages but they require an update to Eslint v9 which we have planned to do but haven't gotten around just yet.
Ignore updates to these packages for now.
n/a
n/a

chore(deps): don't update `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` until we update Eslint

---

CHANGELOG.md
src/declarations/stencil-public-compiler.ts

I missed to apply documentation to changes made in #5892 to the `serializeShadowRoot` flag.
GitHub Issue Number: fixes #5924
STENCIL-1368
Better documentation.
n/a
n/a

fix(typescript): fix documentation on 'serializeShadowRoot' flag

---

src/runtime/styles.ts

The runtime will throw an error when trying to apply styles to a Shadow component
Styles will be applied without throwing an error
N/A

fix(runtime): provide second arg to `insertBefore`

---

src/runtime/styles.ts
test/end-to-end/src/miscellaneous/renderToString.e2e.ts
test/end-to-end/tsconfig.json

This is an enhancement to a fix we made in in #5926 which caused our Nightly build to fail due to the inability to place custom styles in the HTML template as all component styles were injected last in the `<head />` tag.
STENCIL-1372
Place scoped component styles after existing preconnect links but allow custom styles to be set at the end of the `<head />` tag.
I will raise a separate PR to the docs page mentioning this behavior.
Enhanced existing e2e test.
n/a

fix(runtime): place scoped component styles after preconnect links but before custom styles

---

src/compiler/transformers/static-to-meta/component.ts

GitHub Issue Number: fixes #5940
Check for the parent member before calling `ts.isClassDeclaration` on it.
n/a
n/a

fix(compiler): verify parent node when validating component members

---

src/runtime/styles.ts

Inserting styles inside shadow components calls to `prepend` with a `null` node (i.e. `prepend(styles, null)`). This causes a text node with "null" to be rendered.
Removes the `null` node from the call to `prepend`.
N/A

fix(runtime): update call to `prepend` to remove `null` node

---

src/app-data/index.ts
test/wdio/custom-elements-hierarchy-lifecycle/cmp-child.tsx
test/wdio/custom-elements-hierarchy-lifecycle/cmp-parent.tsx
test/wdio/custom-elements-hierarchy-lifecycle/cmp-util.ts
test/wdio/custom-elements-hierarchy-lifecycle/cmp.test.tsx

Currently, the `dist-custom-elements` build does not respect the behavior of certain lifecycle methods executing for child components, prior to parent components (as mentioned in the [Stencil documentation](https://stenciljs.com/docs/component-lifecycle#lifecycle-hierarchy)).
Fixes: #3580
This commit updates the default behavior for `BUILD.asyncLoading` to `true`. This change is necessary because the custom elements build does not customize the build conditionals like the lazy build. So, this value was never being set to `true` even in applicable scenarios.
This does have a slight impact on treeshaking (since any `if` statement testing this condition will now always be `true`) and runtime performance. 
N/A
Tested in the reproduction case from #3580 and added a e2e test to ensure the …

fix(compiler): default `asyncLoading` build conditional to `true`

---

src/compiler/types/generate-app-types.ts
src/compiler/types/tests/generate-app-types.spec.ts

GitHub Issue Number: fixes #5882
We have missed a case where an import type can come with an empty id.
Enhanced existing unit test.
n/a

fix(compiler): prefer `localName` over `originalName` by running an empty check on `originalName`

---

src/mock-doc/element.ts
src/runtime/vdom/set-accessor.ts
src/runtime/vdom/test/set-accessor.spec.ts

Trying to set properties without a setter fails silently in Stencil.
GitHub Issue Number: #2703
Check if property has a setter and use `setAttribute` otherwise.
Added unit test.
n/a

fix(runtime): only use setter if existing

---

src/runtime/styles.ts

The Ionic Framework nightly build is failing. After some investigations it seems that the page had a missing style tag in the header which caused the component to be rendered without padding:
_> Left side is the working version, right side is the Playwright trace_
I don't know why the style tag with the styles for `ion-list` isn't rendered only in CI. I have to assume that it has to do with Playwright behaving funky here. I can't reproduce it locally at all.
Added an `else` statement in cases none of the previous if statement match which should never happen but may have happened here. Worth a try.
n/a
n/a

fix(runtime): have fallback for style setting

---

src/declarations/stencil-public-runtime.ts

An accidental `any` can leak as that's what JSX returns when `JSX.Element` is missing ([TS playground](https://www.typescriptlang.org/play/?jsxFactory=h&ts=5.5.4#code/PTAEAECsGcA8C5QCcCmBDAxgFwLACgQIZYAxTLAeyQE9EALfASwFsAHKrUAb1DtAF9QAMyQVmoAOThoWFADsMjADbAMVFBNCEs1VimiIALADoATAAZj5-PjVyZoFEtABeUAB4AJowBuwAHz4hKAhAHoA-EA))
```ts
// @jsx: react
// @jsxFactory: h
import { h } from '@stencil/core' // types: 4.20.0
const el = <div/> // any
```
This PR reuses the already defined `LocalJSX.Element` as `JSX.Element`. The resulting type is still pretty permissive (it's an empty interface) but at least it's not `any`.
N/A
Manual testing of how types are resolved with this.
discovered here https://github.com/microsoft/TypeScript/pull/59584#issuecomment-2286943503

fix(types): expose missing `JSX.Element` on `h`

---

src/compiler/output-targets/output-custom.ts

Do not generate custom output target on test
fixes: #5950
GitHub Issue Number: #5950 
No generating the custom output target on test build
Manual testing

fix(compiler): no generate custom output

---

src/declarations/stencil-public-runtime.ts

GitHub Issue Number: fixes #5963
Added missing event handlers to the public runtime. I am not sure if `onBeforeToggleCapture` or `onToggleCapture` are a thing but it seems it makes sense to follow the existing pattern. Happy to remove these.
n/a
n/a

fix(declarations): add missing event handler types

---

.github/workflows/build.yml
.github/workflows/main.yml
.github/workflows/test-wdio.yml
scripts/esbuild/cli.ts
scripts/esbuild/compiler.ts
scripts/esbuild/dev-server.ts
scripts/esbuild/internal-platform-client.ts
scripts/esbuild/internal-platform-hydrate.ts
scripts/esbuild/internal-platform-testing.ts
scripts/esbuild/screenshot.ts
scripts/esbuild/sys-node.ts
scripts/esbuild/testing.ts
scripts/esbuild/utils/index.ts
scripts/test/validate-build.ts
scripts/test/validate-testing.js
scripts/tsconfig.json

Stencil fails when trying to build it on a Windows machine.
STENCIL-1369
It turns out that the alias path needed to get normalized allowing Esbuild to pick up the right file and acknowledge it as external dependency.
This patch will also make some tweaks to the pipeline to run the `build` and `linter` tasks first and then run everything else. Before we were running WebdriverIO immediately.
Updated our pipeline to have the project being build on Windows so we ensure we don't introduce regressions.
n/a

fix(scripts): fix Esbuild scripts to allow to run on Windows

---

.github/workflows/test-wdio.yml
src/compiler/build/watch-build.ts

Fixes: #3443
When renaming a file in watch mode, it is possible to run into two errors:
1. A build error resulting from the compiler believing that two components exist with the same tag name (one from the old file name, and one from the new)
2. An HMR issue where the new file name is not correctly registered with the file watcher. So, changes to the renamed file did not trigger an HMR reload
Addresses both of the issues mentioned above by updating the watched files and compiler context whenever a change is detected that triggers the watch callback
N/A
This is a difficult issue to test (especially the HMR since that was not always consistent), so I was only able to perform manual tests

fix(compiler): handle file rename in watch mode

---

src/runtime/dom-extras.ts
test/wdio/scoped-slot-insertion-order-after-interaction/cmp.test.tsx
test/wdio/scoped-slot-insertion-order-after-interaction/cmp.tsx

fix(runtime): scoped slot append/prepend correct order after interaction

---

src/runtime/styles.ts

GitHub Issue Number: #5993
With this bugfix, only a style node within the styleContainerNode is searched for.
--
--
--

fix(runtime): ensure referenceNode is child node of styleContainerNode

---

src/compiler/transformers/reserved-public-members.ts

add `popover` keyword
fixes: #6000
GitHub Issue Number: #6000
Add `popover` has reserved keywork to avoid developer to name a property in a component with this name to do not have unexpected comportment outside stencil dev mode
Manual testting

fix(compiler): add `popover` reserved keyword

---

scripts/esbuild/internal-platform-hydrate.ts

The hydrate platform esbuild is missing an alias for `@app-globals`, causing it to be resolved to the `noop` in `src/app-globals/index.ts`. This results in the globals not being correctly included in hydrate apps.
Adding the alias returns hydrate to it's previous behaviour.
GitHub Issue Number: #6002
Hydrate app now includes global script.
_none_
See #6002

fix(hydrate): Add missing alias to hydrate build to fix app globals

---

src/mock-doc/serialize-node.ts
test/end-to-end/src/components.d.ts
test/end-to-end/src/declarative-shadow-dom/nested-child-cmp.tsx
test/end-to-end/src/declarative-shadow-dom/parent-cmp.tsx
test/end-to-end/src/declarative-shadow-dom/test.e2e.ts

If a user would try to serialize a component that contains a declarative shadow dom, e.g.:
```ts
const { html } = await renderToString(`
<nested-cmp-parent>
<nested-cmp-child custom-hydrate-flag="" s-id="3">
<template shadowrootmode="open">
<div c-id="3.0.0.0" class="some-other-class">
<slot c-id="3.1.1.0"></slot>
</div>
</template>
Hello World
</nested-cmp-child>
</nested-cmp-parent>
`,
{
fullDocument: false,
prettyHtml: true,
},
);
```
Stencil would serialize the shadow root twice:
```html
<nested-cmp-parent custom-hydrate-flag="" s-id="1">
<template shadowrootmode="open">
<div c-id="1.0.0.0" class="some-class">
<slot c-id="1.1.1.0"></slot>
</div>
</template>
<nested-cmp-child custom-hydrate-flag="" s-id="2">
<template shadowrootmode="open">
<div c-id="2.0.0.0" class="some-other-class"> …
```

fix(mock-doc): avoid double hydration of components

---

src/compiler/output-targets/dist-hydrate-script/hydrate-factory-closure.ts
src/mock-doc/resize-observer.ts
src/mock-doc/window.ts

Yet another Web API to mock out in MockDoc.
Make components using this primitive not fail when hydrating it.
n/a
n/a

fix(mock-doc): provide mock for resize observer

---

src/compiler/output-targets/dist-hydrate-script/hydrate-factory-closure.ts
src/mock-doc/shadow-root.ts
src/mock-doc/window.ts

The [`ShadowRoot`](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/styleSheets) class is currently not defined in MockDoc.
Added a mocked implementation of it.
n/a
n/a

fix(mock-doc): add missing ShadowRoot window primitive

---

src/mock-doc/window.ts

Using Stencil in a server side rendering context with Nuxt, causes issue due to the fact that Nuxt fails to do its auto importing feature with `Cannot find module '#app/compat/interval'`. It turns out it has to do with using `setTimeout` which probably is lazy loaded in Nuxt from a special polyfill.
While this is technically not an issue with Stencil , I found a workaround we can apply to make it work. I think this makes it generally safer to obtain the function from `globalThis`.
n/a
n/a

fix(mock-doc): get native primitive from `globalThis`

---

src/declarations/stencil-public-runtime.ts

prior to this commit, using the `controlslist` attribute in a `video` or `audio` element would result in a type checking error. with this commit, we allow the attribute to take one of three values:
- nodownload
- nofullscreen
- noremoteplayback
note that at the time of this writing, only chromium browsers support this attribute. it is the responsibilty of end users to determine if using this attribute is appropraite for their projects.
Adding a `video` or `audio` element to a stencil component like so no longer creates type errors:
```html
<>
<video controlslist="noremoteplayback"></video>
<video controlslist="nofullscreen"></video>
<video controlslist="noremoteplayback"></video>
</>
```
fixes: #6015

fix(types): add controlslist to html declarations

---

src/compiler/docs/readme/markdown-props.ts
src/compiler/docs/test/markdown-props.spec.ts

fixes #6024 
Types or default values that include a backtick are escaped with two backticks and a space.
See the new unit tests in `markdown-props.spec.ts`. If you think the logic for this bug fix should exist somewhere else, let me know!

fix(docs): escape backticks in type or default value columns

---

src/runtime/vdom/vdom-render.ts

This fixes an issue we encountered in several of our projects: when using scoped components, scoped classes for child elements in the component is not set correctly, which causes style problems on the child elements. 
Apparently this is caused by usage of a spread operator on a Set of scope ids (it is a known issue on the typescript https://github.com/Microsoft/TypeScript/issues/8856), this small fix enables to set the scope ids on child element correctly. 
GitHub Issue Number: [6042](https://github.com/ionic-team/stencil/issues/6042)

fix(runtime): scope id fix for component children for typescript issue

---

src/sys/node/node-copy-tasks.ts
test/copy-task/stencil.config.ts

#5899 introduced a lot of regressions:
A breaking change in copy behavior: #5983
file to file copying broken: #5956
EBUSY: resource busy: #5966
Directories from above the root dir are copied outside of the output dir. 
This PR restores the old copy behavior, but uses the passed filter list, rather than the hardcoded one.
This isn't an optimum fix, as it changes the copy back to `dir` to `dir` (or `file` to `file`), so ignore patterns aren't matched against child files. Only glob matches are ignored (as was the previous behavior). IMO it's better than the large number of regressions, especially as this can now be worked around (e.g. in the case of #5781) by the user moving to a glob copy, with the new ignore option.
none
Tested on own repo.
fixes: #5983
fixes: #5956
fixes: #5966

fix(compiler) restore old copy behaviour, with new ignore option

---

src/runtime/bootstrap-custom-element.ts
test/wdio/event-listener-capture/event-re-register.css
test/wdio/event-listener-capture/event-re-register.test.tsx
test/wdio/event-listener-capture/event-re-register.tsx
test/wdio/setup.ts

For dist-custom-elements we didn't ensure that events are only registered once.
GitHub Issue Number: fixes #4135
Verify whether events were registered already.
n/a
n/a

fix(runtime): ensure event listener are not registered twice

---

src/mock-doc/element.ts

If an anchor element in mock-doc has to `href` property, getting the `pathname` will fail. 
Instead it should return an empty string.
fixes #6047
n/a
n/a

fix(mock-doc): return empty string if anchor has no href attribute

---

src/compiler/config/validate-config.ts
src/declarations/stencil-private.ts
src/runtime/bootstrap-custom-element.ts
src/runtime/bootstrap-lazy.ts
src/runtime/dom-extras.ts
src/runtime/test/dom-extras.spec.tsx
src/runtime/vdom/vdom-render.ts
test/wdio/attribute-basic/cmp.test.tsx
test/wdio/attribute-boolean/cmp.test.tsx
test/wdio/delegates-focus/cmp.test.tsx
test/wdio/text-content-patch/cmp.test.tsx

GitHub Issue Number: Fixes https://github.com/ionic-team/stencil/issues/6054
TLDR ... `customElement.childNodes`, `customElement.children` monkey-patches are never actually switched-on in Stencil atm. `scopedSlotTextContentFix` doesn't fully patch the `textContent`.
...
Contrary to documentation, the `experimentalSlotFixes` or `slotChildNodesFix` flags have no effect on the `childNodes` or `children` accessors. The patches are only applied if the deprecated `needsShadowDomShim` flag is fulfilled. 
This must be a mistake / a hangover from supporting legacy browsers.
Additionally `scopedSlotTextContentFix` alone doesn't fully patch the `host.textContent` accessor. It adds a half-way patch - which I believe to be more confusing than useful. 
To get the full `textContent` patch users much add …

fix: `patchChildSlotNodes` & `scopedSlotTextContentFix` not being applied

---

src/compiler/config/validate-config.ts

Given stencil.config options
```
extras: {
experimentalSlotFixes: true,
},
```
a warning shows:
```
If the 'experimentalSlotFixes' flag is enabled it will override any slot fix flags which are disabled. In
particular, the following currently-disabled flags will be ignored: experimentalScopedSlotChanges. Please
update your Stencil config accordingly.
```
This was introduced in https://github.com/ionic-team/stencil/pull/6055 due to `experimentalScopedSlotChanges` not being explicitly set (and defaulting to `false`) when `experimentalSlotFixes` is set.
No warnings

fix: stop 'experimentalScopedSlotChanges' warning msg on startup

---

src/runtime/dom-extras.ts

Stencils runtime tries to access `Node` which may not be defined when server side rendering components.
Have a check for `Node` before accessing it.
fixes https://github.com/ionic-team/stencil-ds-output-targets/issues/537
We will have to put some tests in place to ensure we can build the Output targets project. This should be a separate effort.
n/a

fix(runtime): ensure Node is defined

---

src/runtime/bootstrap-custom-element.ts
test/wdio/event-listener-capture/event-re-register.test.tsx

When a component with event listeners is mounted multiple times, the event listeners are only registered for the first instance. This leads to unexpected behavior for subsequent instances.
GitHub Issue: fixes #6066
Event listener registration is now handled on a per-instance basis. This ensures that each mounted instance of the component registers and manages its event listeners independently.
No updates required. 😊
A new test has been added to verify that event listeners are correctly registered and fired when a component is mounted twice. This ensures consistent behavior across instances.
The bug was introduced as a result of change #6052.

fix: Change hasHostListenerAttached from var to protoype property

---

src/declarations/stencil-private.ts
src/mock-doc/serialize-node.ts
src/runtime/client-hydrate.ts
src/runtime/connected-callback.ts
src/runtime/dom-extras.ts
src/runtime/runtime-constants.ts
src/runtime/test/hydrate-no-encapsulation.spec.tsx
src/runtime/test/hydrate-scoped.spec.tsx
src/runtime/test/hydrate-shadow-child.spec.tsx
src/runtime/test/hydrate-shadow-in-shadow.spec.tsx
src/runtime/test/hydrate-shadow-parent.spec.tsx
src/runtime/test/hydrate-shadow.spec.tsx
src/runtime/test/hydrate-slot-fallback.spec.tsx
src/runtime/test/hydrate-slotted-content-order.spec.tsx
src/runtime/vdom/set-accessor.ts
src/runtime/vdom/vdom-annotations.ts
src/runtime/vdom/vdom-render.ts
test/end-to-end/src/components.d.ts
test/end-to-end/src/declarative-shadow-dom/test.e2e.ts
test/end-to-end/src/scoped-hydration/non-shadow-forwarded-slot.tsx
test/end-to-end/src/scoped-hydration/non-shadow-wrapper.tsx
test/end-to-end/src/scoped-hydration/non-shadow.tsx
test/end-to-end/src/scoped-hydration/readme.md
test/end-to-end/src/scoped-hydration/scoped-hydration.e2e.ts
test/end-to-end/src/scoped-hydration/shadow-wrapper.tsx
test/end-to-end/src/scoped-hydration/shadow.tsx
test/end-to-end/stencil.config.ts

There are lots of rough edges around the use of Stencil's proprietary non-shadow components during SSR
- Fixes https://github.com/ionic-team/stencil/issues/6065
- Fixes https://github.com/ionic-team/stencil/issues/6064
- Fixes https://github.com/ionic-team/stencil/issues/6063
- Fixes https://github.com/ionic-team/stencil/issues/6062
- Fixes https://github.com/ionic-team/stencil/issues/5198
A partial re-write of `client-hydrate.ts` (and few minor tweaks in the accompanying files) fixes all these issues.
^ no breaking changes, but I should mention that during / after hydrating now, there are some changes to the outputted markup:
- A couple more internal tags / comments from the server generated markup
- Fewer Stencil-generated comment nodes left behind after hydration …

fix: rewrite SSR client-side hydration

---

src/mock-doc/node.ts

An error message is shown when user render a component using element internals via SSR.
GitHub Issue Number: fixes #6073
Error message is only shown when using Stencil testrunner.
There hasn't been any tests for this error message in the first place and creating one would be too much effort for the value it provides.
n/a

fix(mock-doc): don't show error message for SSR workflows

---

src/runtime/vdom/set-accessor.ts
test/wdio/declarative-shadow-dom/cmp-svg.test.tsx
test/wdio/declarative-shadow-dom/cmp-svg.tsx

An error is thrown during the virtual DOM render when attempting to parse the class list of an `svg` tag inside a custom element. This occurs because the `class` property on an `svg` element is not a `string` but an object of type `SVGAnimatedString`.
Correctly parse the class list of a `svg` elements.
None.
Added a new wdio test, which checks for `console.error` logs.
None.

fix: correctly handle svg class attribute within `parseClassList`

---

src/client/client-host-ref.ts
src/hydrate/platform/index.ts
src/runtime/bootstrap-custom-element.ts
src/runtime/bootstrap-lazy.ts
src/runtime/disconnected-callback.ts
src/runtime/styles.ts
src/runtime/vdom/update-element.ts
src/testing/platform/index.ts
src/testing/platform/testing-host-ref.ts
src/utils/constants.ts
test/wdio/dom-reattach/cmp.test.tsx

There seems to be a memory leak within Stencil that causes performance problems as documented in:
- https://github.com/ionic-team/ionic-framework/issues/28189
- #5181
- #5172
- #3607
- and possibly #3158
It turns out that Stencil doesn't properly clear up its `hostRefs` global when elements are removed from the DOM. Given that the `hostRefs` global is never garbage collected, all its value will remain in memory which requires us to do some manual cleanup. Furthermore, we have been using references in another global variable called `rootAppliedStyles` which also never gets cleaned up.
This patch enhances the `disconnectedCallback` hook to clean up detached nodes from the `hostRefs` and `rootAppliedStyles` maps.
I am investigating if we can add some memory checks through Puppeteer and …

fix(runtime): clear up rootAppliedStyles

---

src/hydrate/platform/proxy-host-element.ts
src/mock-doc/element.ts
src/mock-doc/test/element.spec.ts

GitHub Issue Number: https://github.com/ionic-team/stencil/issues/2830
Within `mock-doc` (i.e SSR hydration and spec tests) the native `assignednodes` and `assignedElements` methods for a `<slot />` are not available.
A new `MockSlotElement` has been added to the mock-doc `element.ts` with the new methods.
Fixes: https://github.com/ionic-team/stencil/issues/2830
- New spec tests for the `<slot />` methods have been added

feat(mock-doc): `assignednodes` and `assignedElements`

---

src/runtime/proxy-component.ts
src/runtime/test/prop-warnings.spec.tsx

Prototypes used to be re-written with every spec test. Because we re-use accessors now this re-writing no longer happes.
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/6104
A simple flag is set on the incoming prototype in `proxyComponent` during testing to make sure we don't re-augment it. 
- A new unit test to catch this has been added

fix(test): stop re-running prototype augment in spec tests.

---

src/compiler/output-targets/dist-custom-elements/custom-elements-build-conditionals.ts
src/compiler/output-targets/test/build-conditionals.spec.ts
src/runtime/initialize-component.ts

This reverts commit d809658635280e115d67f1403dba946cce1bb01b.
When compiling for `dist-custom-element`, there is no need to include the lazy load functionality into the runtime. In fact it causes issues with Next.js and Turbopack when using SSR:
The original PR (see commit above) fixed a rendering issue that occured with Stencil v4.7. However the origin of the problem is not apparent anymore as we have moved to Declarative Shadow DOM for SSR rendering.
Don't include the lazy load components as part of the `dist-custom-element` runtime.
n/a
n/a

Revert "fix(custom-elements): hydrate on client side (#5317)"

---

src/compiler/bundle/bundle-output.ts
src/compiler/bundle/core-resolve-plugin.ts
src/compiler/output-targets/test/output-targets-dist-custom-elements.spec.ts

Setting the `externalRuntime: false` on a `dist-custom-elements` output, *whilst at the same time* including a 3rd party component / lib that `import`s from `@stencil/core`, causes the whole stencil runtime to be included twice:
- once as custom runtime (dictated by flags set via features detected on components at build-time). 
- second as the whole runtime (dictated by the 3rd party lib's `import`)
This duplication in-turn, breaks certain lifecycle events as different internals call different (duplicate) `@stencil/core` functions.
- https://github.com/ionic-team/stencil/issues/6040
- https://github.com/ionic-team/stencil/issues/4135
My naive solution is to make sure the same `@stencil/core` rollup id is included for both 3rd party libs and the direct component …

fix(dist-custom-elements): stop duplicate `@stencil/core`

---

src/runtime/styles.ts

addStyle function causes NotFoundError in for some components in our micro front end app.
GitHub Issue Number: [6106](https://github.com/ionic-team/stencil/issues/6106)
referenceNode's parentNode is checked to prevent insertBefore throwing NotFoundError method.
If the referenceNode is not a direct child of the element receiving the styleNode as the child, referenceNode is not used.

fix(runtime): fix NotFoundError in addStyle function with referenceNode parent check

---

src/runtime/vdom/set-accessor.ts
src/runtime/vdom/test/set-accessor.spec.ts

fixes #6117
Properly parses class lists with `null` values.
Added unit tests.
n/a

fix(runtime): allow classList to be null

---

src/runtime/client-hydrate.ts
src/runtime/test/hydrate-shadow-child.spec.tsx
src/runtime/test/hydrate-shadow-in-shadow.spec.tsx
src/runtime/test/shadow.spec.tsx
test/wdio/ssr-hydration/cmp.test.tsx
test/wdio/ssr-hydration/cmp.tsx

`client-hydrate.ts` is currently stripping out extra comment nodes of `shadow: true` components (this was originally to remove stencil's "internal" comments, which could pollute the component), but in doing so it removes slotted comment nodes which can be used by external tools / libs.
After testing, I see stencil's internal comments are removed during other stages of client-side hydration so this extra comment removal is unnecessary (the only time extra comments are seen is during unit tests due to a limitation / difference in how components are rendered on 'server')
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/6120
Fixes https://github.com/ionic-team/stencil/issues/6120
- New unit test
- New wdio test

fix(ssr): stop stripping comment nodes 

---

src/hydrate/platform/proxy-host-element.ts
test/end-to-end/src/ssr-runtime-decorators/ssr-runtime-decorators.e2e.ts

A regression added (https://github.com/ionic-team/stencil/pull/6084) during hydration, caused the value to be set on / got from the enclosure to the last component instance.
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/6125
Fixes: https://github.com/ionic-team/stencil/issues/6125
The prototype 'get' now uses the current instance ref to get the initial value
- additional e2e test

fix(ssr): multiple component instances sharing initial properties

---

src/hydrate/platform/proxy-host-element.ts
src/runtime/proxy-component.ts
test/wdio/ssr-hydration/cmp.test.tsx
test/wdio/ssr-hydration/cmp.tsx

A regression added in `hydrate/proxy-host-element.ts` < the more of the same component rendered on the page, the more times the prototype would be augmented - causing an ever deepening chain of getters.
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/6127
A simple property is added to the incoming prototype, making sure we only add augment it once.
Fixes https://github.com/ionic-team/stencil/issues/6127
- A new wdio perf test has been added

fix(ssr): exponential perf slow down

---

src/runtime/client-hydrate.ts
src/runtime/vdom/vdom-render.ts
test/wdio/ssr-hydration/cmp.test.tsx
test/wdio/ssr-hydration/cmp.tsx

GitHub Issue Number: https://github.com/ionic-team/stencil/issues/6130
Slots can get incorrectly rendered / resolved during client-side hydration from SSR content
Slot elements are given their respective `$name$` when the SSR > VDOM is created. 
This means old to updated VDOM (then DOM) is correctly correctly resolved - slots are no longer overwritten.
Fixes https://github.com/ionic-team/stencil/issues/6130
- New wdio test

fix(ssr): correctly resolve slots during hydration

---

src/compiler/output-targets/dist-custom-elements/custom-elements-build-conditionals.ts
src/compiler/output-targets/test/build-conditionals.spec.ts
src/runtime/initialize-component.ts

This is a revert of a revert as we see issues with rendering SSR components in Next.js

Revert "Revert "fix(custom-elements): hydrate on client side (#5317)" (#6111)"

---

src/runtime/initialize-component.ts

When compiling for `dist-custom-element`, there is no need to include the lazy load functionality into the runtime. In fact it causes issues with Next.js and Turbopack when using SSR:
The [original PR](https://github.com/ionic-team/stencil/pull/1953) does seem to provide any hints as to why this was introduced.
Don't include the `loadModule` function within `dist-custom-element` runtimes when a `hyrdate` output target is used.

fix(runtime): don't include loadModule logic in hydrate runtime

---

src/client/client-host-ref.ts
src/declarations/stencil-private.ts
src/hydrate/platform/index.ts
src/runtime/bootstrap-custom-element.ts
src/runtime/bootstrap-lazy.ts
src/runtime/vdom/vdom-annotations.ts
src/testing/platform/index.ts
src/testing/platform/testing-constants.ts
src/testing/platform/testing-host-ref.ts
src/testing/platform/testing-platform.ts

GitHub Issue Number: Fixes #6148 
Remove WeakMap and hold each `HostRef` on the actual DOM Element. Which makes the `Weakmap` itself not necessary anymore.
Issue to discuss:
- ~Circular structure of HTMLElement (element -> $hostRef$ -> $hostElement$ -> $hostRef$ -> ...)~ Solved by using `getHostRef`
- ~Add `HostRef` (containing vdom structure) to regular DOM (Performance ?) => Checked the performance haven't found any issues yet.~ Solved by using `getHostRef`
- ~WebDriver.IO cannot convert element to JSON (Circular structure of HTMLElement) which results in failing tests atm.~ Solved by using `getHostRef`
Use existing tests, not added new ones.

refactor(runtime): make WeakMap obsolete  

---

src/runtime/dom-extras.ts

GitHub Issue Number: #6140 
If patched node (this) is not the same node of currentChild, it uses appendChild to insert the newChild to patched node

fix(runtime): append newChild if parent node doesn't match with patched node

---

src/compiler/types/generate-component-types.ts
src/compiler/types/generate-prop-types.ts
src/compiler/types/tests/generate-app-types.spec.ts
src/compiler/types/tests/generate-prop-types.spec.ts
src/declarations/stencil-private.ts
src/hydrate/platform/proxy-host-element.ts
src/runtime/vdom/set-accessor.ts
test/end-to-end/src/components.d.ts
test/end-to-end/src/hydrate-props/hydrate-props.e2e.ts
test/end-to-end/src/hydrate-props/my-cmp.tsx
test/end-to-end/src/hydrate-props/my-jsx-cmp.tsx
test/end-to-end/src/hydrate-props/readme.md
test/wdio/src/components.d.ts
test/wdio/ts-target-props/components.d.ts

Component properties can be read in the following 2 environments:
- an HTML template, e.g. a Stencil runtime is loaded within an HTML page or you pass in a template to a `renderToString` function.
- a JSX template, e.g. within the `render` method of a component
According to the [property casing](https://stenciljs.com/docs/properties#variable-casing) docs we expect camelcase in JSX and dash-case case in html templates. It appears however that Stencil supported dash-casing in JSX templates as well, though only at runtime (e.g. not in the hydrate module).
fixes #6150
This patch adds support for dash-casing in JSX templates when running the hydrate script, to align with the runtime behavior. In general, dash-casing should only be used in HTML templates and not in JSX. However removing this …

fix(hydrate): support dash-case case in hydrate mode

---

src/runtime/slot-polyfill-utils.ts
src/runtime/test/hydrate-slot-fallback.spec.tsx
test/wdio/slot-fallback-with-forwarded-slot/child-component.tsx
test/wdio/slot-fallback-with-forwarded-slot/cmp.test.tsx
test/wdio/slot-fallback-with-forwarded-slot/parent-component.tsx

GitHub Issue Number: https://github.com/ionic-team/stencil/issues/6170
When assessing whether to hide / show fallback slot content,  it now additionally strips out any nested `<slot />` nodes.
Fixes: https://github.com/ionic-team/stencil/issues/6170
- New wdio tests

fix(runtime): `scoped: true` slot fallback with forwarded slot

---

src/client/client-patch-browser.ts
src/client/client-window.ts
src/compiler/docs/style-docs.ts
src/hydrate/platform/hydrate-app.ts
src/hydrate/platform/index.ts
src/runtime/bootstrap-lazy.ts
src/runtime/client-hydrate.ts
src/runtime/connected-callback.ts
src/runtime/host-listener.ts
src/runtime/styles.ts
src/runtime/test/bootstrap-lazy.spec.tsx
src/runtime/vdom/vdom-render.ts
src/testing/platform/index.ts
src/testing/platform/testing-window.ts
test/wdio/package.json
test/wdio/test-end-to-end-import.mjs

Importing the `dist-custom-elements` components in Node.js is failing due to the `doc.querySelectorAll` in `hydrateScopedToShadow`. This can cause issues when SSR components in Next.js.
Enhance the document mock with an additional method to make the function a noop and fix the failure.
Added an e2e test for this.
cc @johnjenkins

fix(runtime): mock querySelectorAll

---

package.json
src/compiler/types/generate-component-types.ts
src/compiler/types/generate-prop-types.ts
src/compiler/types/tests/generate-app-types.spec.ts
src/compiler/types/tests/generate-prop-types.spec.ts
src/declarations/stencil-private.ts
test/end-to-end/package-lock.json
test/end-to-end/src/components.d.ts
test/wdio/package-lock.json
test/wdio/src/components.d.ts
test/wdio/ts-target-props/components.d.ts

We have recently pushed a change to the compiler to notify users about the deprecation of using kebab-casing in JSX environments. While this may have been a good idea in theory, it has caused more confusion and devx issues. Let's get rid of it again.
fixes #6184
fixes #6183
Don't deprecate these attributes and make sure the v5 release notes highlight this breaking change visible enough.
n/a
n/a

fix(compiler): revert deprecation changes to components.d.ts

---

.github/CODEOWNERS
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/ionic-issue-bot.yml
BREAKING_CHANGES.md
CHANGELOG.md
CONTRIBUTING.md
RELEASE.md
package.json
readme.md
scripts/utils/test/release-utils.spec.ts
src/compiler/config/test/validate-custom.spec.ts
src/compiler/config/validate-config.ts
src/declarations/stencil-public-compiler.ts
src/mock-doc/serialize-node.ts
src/runtime/set-value.ts
src/runtime/test/render-vdom.spec.tsx
src/sys/node/node-stencil-version-checker.ts
src/utils/constants.ts
test/copy-task/package.json
test/docs-readme/custom-readme-output/components/styleurls-component/readme.md
test/wdio/ref-attr-order/cmp.tsx
test/wdio/static-members/README.md

There are plenty of references to the old repository that we want to update. Even though all links have an automatic redirect we still want to show the updated link.
Reference the new Stencil home.
n/a
n/a

fix(internal): fix references to old repository

---

src/declarations/stencil-public-runtime.ts

I wanted to use the `details` html element with the `name` property in Stencil's TSX and got the error:
```
Type '{ name: string; }' is not assignable to type 'DetailsHTMLAttributes<HTMLElement>'.Property 'name' does
not exist on type 'DetailsHTMLAttributes<HTMLElement>'.
```
The `name` property seems to be missing here: https://github.com/stenciljs/core/blob/30fc9f5985120e636eec8acbe2253145c97072d9/src/declarations/stencil-public-runtime.ts#L922
The `name` attribute is part of the web standard and allows grouping multiple `details` elements: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#multiple_named_disclosure_boxes
The name attribute is added to the definitions and can be used in TSX.

fix: add missing name attribute for details html element

---

src/compiler/transpile/create-watch-program.ts

GitHub Issue Number: #6190
The file watcher sometimes fails to trigger a rebuild:
This is caused by the "Back up files before saving" option in my editor.
When this option is disabled the file watcher works just fine.
However, the "Back up files before saving" option is enabled per default and Stencil should be able to handle this.
> The above demo was recorded on a clean install of Stencil. It should be fairly simple to reproduce the issue as long you're using "Back up files before saving". (I don't know if it's just PHPStorm or other editors as well.)
After applying these changes the watcher behaves beautifully with or without "Back up files before saving" option enabled.
–
I tested the code with a custom `@stencil/core` build in my application running `stencil build --watch --verbose`. …

fix(compiler): fix file watcher sometimes doesn't trigger rebuild

---

package-lock.json
package.json

This fixes e.g. failing builds on Apple Silicon.
fixes: #6195
GitHub Issue Number: #6195
Build is failing on e.g. Apple Silicon:
```bash
stencil build
[59:05.5]  @stencil/core
[ ERROR ]  uncaught cli error: Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional
dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both
package-lock.json and node_modules directory.
```
Build runs just fine on Apple Silicon.
```bash
stencil build
[01:31.0]  @stencil/core
[01:31.1]  [LOCAL DEV] v4.28.0-dev.1741780803.d0b8b4a 🎁
[01:31.6]  build, stencil-rollup, prod mode, started ...
[01:31.6]  transpile started ...
[01:32.6]  transpile finished in 975 ms
[01:32.6]  generate custom elements + source maps started ...
[01:32.6]  generate …
```

fix(build): add more platform specific optionalDependencies (#6195)

---

src/compiler/output-targets/output-lazy-loader.ts

The auto-generated `package.json` that Stencil inserts within the `loader` dir seems unnecessary now. 
The auto-generated `package.json`: 
- overrules settings within the main `package.json` [leading to unexpected behaviour](https://github.com/stenciljs/core/issues/5637) 
- removes developer wishes and agency - "*I* should control how & what is exported"
GitHub Issue Number: https://github.com/stenciljs/core/issues/5637 < the fix was merely a stop gap and is not a 'modern' solution (node now supports es modules natively) 
Stop stencil inserting the loader `package.json`

fix(loader): remove package.json as it interferes with main

---

src/compiler/bundle/bundle-output.ts
src/declarations/stencil-public-compiler.ts

Stencil's default `nodeResolve` config doesn't pay attention to the `exports` > `require` field (which is present in the axios lib - https://github.com/axios/axios/issues/5888)
GitHub Issue Number: https://github.com/stenciljs/core/issues/6202
Closes https://github.com/stenciljs/core/issues/6202
- Include `require` in nodeResolve `exportConditions` (Note - I'm not 100% sure if we should as I *think* axios is in the wrong here - https://github.com/axios/axios/issues/5888#issuecomment-2721184793)
- update `nodeResolve` types to match the plugin
- allow users' `nodeResolve` config to take precedence over default - giving users more control

build: improve `nodeResolve` config

---

src/declarations/stencil-public-runtime.ts

Add typings for ARIA attributes like `aria-labelledby`, `aria-hidden`, etc., to the DOMAttributes interface. This allows better accessibility support and developer experience via type safety and IntelliSense.
fixes: #6182
GitHub Issue Number: #6182 
Currently, JSX attributes with ARIA prefixes such as aria-label, aria-hidden, etc., are not typed, leading to missing IntelliSense and potential type errors in TypeScript.
JSX ARIA attributes are now explicitly typed in the DOMAttributes interface, enabling proper IntelliSense, autocomplete, and validation in IDEs and TypeScript-aware tooling.
This includes support for all standard ARIA attributes, and optionally, a generic index signature for custom aria-* values.

feat(jsx): add support for aria-* attributes in JSX typings

---

.github/workflows/main.yml
.github/workflows/test-types.yml
package.json
test/type-tests/README.md
test/type-tests/test.spec.tsx
test/type-tests/tsconfig.json
test/wdio/event-custom-type/cmp.tsx

After reviewing #6221 I looked into whether we have type tests for JSX files and it seems we don't.
This patch adds some basic type tests that help us verify that Stencil correctly generates and connects JSX namespaces.
n/a
This PR will fail as it requires #6221 to be merged first.
n/a

test(core): add type tests for JSX

---

src/runtime/styles.ts
src/runtime/test/shadow.spec.tsx
test/end-to-end/package.json
test/end-to-end/src/declarative-shadow-dom/__snapshots__/test.e2e.ts.snap
test/end-to-end/src/declarative-shadow-dom/test.e2e.ts
test/wdio/complex-properties/__snapshots__/cmp.test.tsx.snap

We have introduced a regression in https://github.com/stenciljs/core/pull/5892 which caused Stencil not setting scoped classes properly during runtime and therefor missing certain styles.
GitHub Issue Number: https://github.com/ionic-team/ionic-framework/issues/30323
Reverted particular change to enable this again.
n/a
Dev Build `4.29.0-dev.1743807712.6244a07`

fix(runtime): properly set scope classes

---

src/compiler/output-targets/dist-lazy/generate-lazy-module.ts
src/utils/sourcemaps.ts
src/utils/test/sourcemaps.spec.ts

Stencil creates empty sourcemap files with `{ "sourcesContent": [] }` content if `sourceMap` is disabled. This may be related to the Rollup upgrade which now emits these files.
GitHub Issue Number: ionic-team/ionic-framework#30323
Add an additional check to verify that there is a sourcemap file.
Added unit tests.
n/a

fix(utils): don't create sourcemap file if disabled

---

package.json
scripts/esbuild/dev-server.ts
scripts/esbuild/sys-node.ts
scripts/esbuild/utils/index.ts
scripts/test/validate-build.ts
src/dev-server/server-web-socket.ts
src/sys/node/bundles/open-in-editor-api.js
src/sys/node/bundles/ws.js
tsconfig.json

The build is failing due to a TypeScript issue in the component tests:
```
[ ERROR ]  TypeScript: node_modules/puppeteer/lib/types.d.ts:8:25
Cannot find module 'chromium-bidi/protocol/protocol.js' or its
corresponding type declarations.There are types at
'/home/runner/work/core/core/tmp-component-starter/node_modules/chromium-bidi/lib/esm/protocol/protocol.d.ts',
but this result could not be resolved under your current
'moduleResolution' setting. Consider updating to 'node[16](https://github.com/stenciljs/core/actions/runs/14845459798/job/41686072470?pr=6249#step:16:17)',
'nodenext', or 'bundler'.
L7:  import type { ProtocolMapping } from 'devtools-protocol/types/protocol-mapping.js';
L8:  import { Session } from 'chromium-bidi/protocol/protocol.js';
```
Update the module resolution to …

fix(build): fix build after dependency updates

---

src/declarations/stencil-public-compiler.ts
src/hydrate/runner/render.ts
test/end-to-end/src/declarative-shadow-dom/test.e2e.ts

GitHub Issue Number: #6240
`hydrateDocument` has been extended to provide the `serializeShadowRoot` opt to be inline with what is provided with `renderToString`
Test was added to `test.e2e.ts` to verify the new option

feat(hydrate): add `serializeShadowroot` to hydrateDocument

---

src/compiler/types/generate-prop-types.ts
src/compiler/types/tests/generate-prop-types.spec.ts
test/end-to-end/src/components.d.ts
test/wdio/src/components.d.ts
test/wdio/ts-target-props/components.d.ts

Currently, Stencil does not automatically add `@default` JSDoc to `@Prop()` declarations, even when a default value is present in the component's property definition. Developers have to manually add this JSDoc.
Stencil will now automatically add `@default 'value'` to the JSDoc of a `@Prop()` when a default value is detected for that property and no `@default` JSDoc is already present. This improves developer quality of life by reducing redundancy and making component APIs clearer.
No new documentation is required, as this is an automatic behavior change.
[ ] Yes
[x] No
Unit tests have been added to `src/compiler/types/tests/generate-prop-types.spec.ts` to verify the new behavior, including cases where a default value is present and where `@default` JSDoc is already manually set. All tests …

feat(compiler): Automatically add @default JSDoc to @Prop() declarations

---

RELEASE.md

This small PR fixes the `CHANGELOG.md` location in `RELEASE.md`.

fix: update `CHANGELOG.md` location

---

src/runtime/slot-polyfill-utils.ts
src/runtime/test/scoped.spec.tsx
src/runtime/vdom/vdom-render.ts

GitHub Issue Number: #6269
When using `onSlotchange` event listeners on `<slot>` elements in **scoped components**, the application crashes with:
```
TypeError: el.addEventListener is not a function
```
This occurs because in scoped components, Stencil uses a slot polyfill that replaces `<slot>` elements with text/comment nodes (since native shadow DOM is not used). These nodes don't have native `addEventListener` methods, causing runtime errors when the framework attempts to attach event listeners.
- `onSlotchange` event listeners now work correctly on `<slot>` elements in scoped components
- The slot polyfill now includes custom `addEventListener`, `removeEventListener`, and `dispatchEvent` methods for polyfilled slot nodes
- Event listeners are attached without errors and function as …

fix(runtime): add addEventListener support for slot elements in scope components

---

src/hydrate/platform/proxy-host-element.ts
src/runtime/client-hydrate.ts
src/runtime/parse-property-value.ts
src/runtime/proxy-component.ts
src/runtime/set-value.ts
test-form-associated.js
test/wdio/form-associated/cmp.test.tsx
test/wdio/form-associated/prop-check.test.tsx
test/wdio/form-associated/prop-check.tsx

GitHub Issue Number: #5461
Currently, form-associated Stencil components incorrectly handle boolean attributes like `disabled`. When `disabled="false"` is set on a form-associated component, Stencil parses the string `"false"` as boolean `false`, which then gets reflected back to the DOM as the `disabled` attribute. According to HTML specification, for form-associated elements, the mere presence of boolean attributes like `disabled` (regardless of their value) should disable the element.
This causes form-associated components to behave incorrectly when `disabled="false"` is explicitly set, as the component remains disabled when it should be enabled.
For form-associated components, boolean attribute parsing now follows HTML specification:
- Any string attribute value (including `"false"`) …

fix(runtime): correct boolean attribute handling for form-associated components

---

src/compiler/style/global-styles.ts
src/declarations/stencil-private.ts

Some Rollup types are incorrect after update.
GitHub Issue Number: #6231
Update the types.
n/a
n/a
n/a

fix(declarations): update PluginTransformResults after Rollup update

---

src/mock-doc/node.ts
src/runtime/slot-polyfill-utils.ts
src/runtime/vdom/vdom-render.ts

The slot event listener fix from PR #6281 was incorrectly implemented in the runtime layer (`src/runtime/slot-polyfill-utils.ts` and `src/runtime/vdom/vdom-render.ts`). However, as correctly pointed out by @johnjenkins in https://github.com/stenciljs/core/pull/6281#issuecomment-2963161151, this issue only manifests during unit testing with Stencil's MockDoc implementation, not in actual runtime scenarios.
The problem occurs because in scoped components, slot elements are polyfilled using text/comment nodes, and MockDoc's `MockTextNode` class (which inherits from `MockNode`) lacked the necessary event handling methods (`addEventListener`, `removeEventListener`, `dispatchEvent`), causing "addEventListener is not a function" errors during unit tests.
This PR moves the slot event listener …

fix(mock-doc): move slot event listener support from runtime to MockDoc

---

src/compiler/bundle/app-data-plugin.ts
src/compiler/config/test/validate-config.spec.ts
src/compiler/config/validate-config.ts
src/declarations/stencil-private.ts
src/declarations/stencil-public-compiler.ts

The new behaviour added via https://github.com/stenciljs/core/pull/6268 is probably desirable for a lot of users and use-cases; sharing globalStyle across all components. 
For some users however, this new behaviour might be undesirable if (for example): 
- They have designed their globalStyles around the lightDOM *alone*. For them, adding such a stylesheet to all components is completely unnecessary. An example might be globalStyles in a design-system that seek to control the marriage of potential components: doing something like `my-menu > my-link-item::part(icon)` [is not an option via traditional ::slotted(...) selectors atm](https://github.com/w3c/csswg-drafts/issues/3896)
- They are using their components during SSR. The nature of declarative-shadow-dom for SSR being declarative (😄) …

feat(global-styles): new `addGlobalStyleToComponents` extras option. Opt-out of new globalStyle behaviour

---

src/mock-doc/event.ts
src/mock-doc/test/shadow-dom-event-bubbling.spec.ts

MockDoc bubbles DOM events to `parentElement` every time during simulation, completely ignoring the special boundary rules of the Shadow DOM. For example, with the following DOM structure:
```bash
parent-host (Shadow Host)
└── #shadow-root (Shadow Root) 
└── child-host
```
When the event bubbles from the `child-host`, its `parentElement` is null, but its container is the shadow-root, and `shadow-root.host` points to the `parent-host`.
GitHub Issue Number: #5676
According to the W3C specification, when the event is set to `composed: true`, it can cross Shadow DOM boundaries.
Therefore, for the DOM structure example above, the correct bubbling path should be: `child → shadow-root → shadow-host → parent`.
**Test Coverage:**
Added consistency test: New test …

fix(mock-doc): ensure event bubbling follows shadow DOM boundaries

---

src/mock-doc/node.ts
src/runtime/test/event.spec.tsx

A regression was introduced in commit 1304ffc that causes infinite recursion when blur event handlers call `blur()` on input elements within the mock DOM environment. This results in "Maximum call stack size exceeded" errors during Stencil tests.
The issue manifests when:
1. `input.blur()` is called, which dispatches a blur event
2. A blur event handler processes the event and calls `querySelector` to find elements
3. The event handler then calls `blur()` on the same input element again
4. This creates an infinite loop between event dispatching and event handling
GitHub Issue Number: #6307
Added a recursion prevention mechanism that:
- Tracks elements currently processing specific event types using a WeakMap
- Prevents the same element from dispatching the same event type while already …

fix(mock-doc): prevent infinite recursion in blur event handlers

---

src/runtime/client-hydrate.ts
src/runtime/connected-callback.ts
src/runtime/test/hydrate-shadow-in-shadow.spec.tsx
src/runtime/update-component.ts
src/runtime/vdom/set-accessor.ts
test/wdio/ssr-hydration/cmp.test.tsx
test/wdio/ssr-hydration/scoped-child-cmp.tsx
test/wdio/ssr-hydration/scoped-parent-cmp.tsx
test/wdio/ssr-hydration/shadow-child-cmp.tsx
test/wdio/ssr-hydration/shadow-parent-cmp.tsx

GitHub Issue Number: https://github.com/stenciljs/core/issues/6313
Fixes https://github.com/stenciljs/core/issues/6313

fix(ssr): fixes for `scoped: true` components during SSR

---

src/runtime/styles.ts

When investigating #6320 I saw that there were places that the adoptedStyleSheets array was being recreated instead of mutated. MDN docs say you should only mutate this array: https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets
The array is mutated instead of recreated
I don't think this is a breaking change, since we already mutate adoptedStyleSheets [here (as an example)](https://github.com/stenciljs/core/pull/6268). However, I believe this was originally done because adoptedStyleSheets used to be frozen: https://github.com/GoogleChrome/web.dev/issues/10294
Because there's other places in the codebase that treat adoptedStyleSheets as mutable I don't think this is breaking but I do want to highlight that.

refactor(runtime): don't recreate adoptedStyleSheets

---

src/utils/shadow-root.ts
src/utils/style.ts

GitHub Issue Number: None
Since Ionic v8.6.0 I've been experiencing component instance creation performance issues, especially in virtual lists, where it can take items longer to appear. This was originally identified by end users: https://vger.social/post/20787019
I narrowed it down to the [stencil upgrade here](https://github.com/ionic-team/ionic-framework/pull/30450).
From there I found the regression occurring in [Stencil v4.33.0](https://github.com/stenciljs/core/releases/tag/v4.33.0) specifically. When I reverted [33363d4077728793e0c6f635a22dccbb5740be49](https://github.com/stenciljs/core/commit/33363d4077728793e0c6f635a22dccbb5740be49) the problem went away.
Once I identified the source of the issue, I found [some suspicious …

fix(utils): single global stylesheet instance for performance

---

src/client/client-window.ts
src/hydrate/platform/index.ts
src/runtime/styles.ts
src/testing/platform/index.ts
src/testing/platform/testing-platform.ts
src/utils/shadow-root.ts

Resolves #6326
GitHub Issue Number: #6326
Stencil constructable style sheets works with old spec where the array was immutable.
Note: I strongly recommend dropping support for < chrome 99 in stencil v5. Patches like this increase the bundle size for everyone in order to support *very* insecure/outdated browsers.
~~I would like help testing this before merge.~~ Tested loading stencil from Ionic list starter on chrome 98 and works OK.
https://github.com/salesforce/lwc/issues/2828

fix: contructable stylesheets with older immutable spec (chrome <99)

---

src/hydrate/platform/hydrate-app.ts
src/hydrate/platform/proxy-host-element.ts
src/runtime/bootstrap-custom-element.ts
src/runtime/bootstrap-lazy.ts
src/runtime/client-hydrate.ts
src/runtime/connected-callback.ts
src/runtime/disconnected-callback.ts
src/runtime/element.ts
src/runtime/hmr-component.ts
src/runtime/mode.ts
src/runtime/proxy-component.ts
src/runtime/set-value.ts
src/runtime/update-component.ts

Currently, the runtime code assumes that `getHostRef()` always returns a valid hostRef object without null checking. This can lead to runtime errors when `getHostRef()` returns `null` or `undefined` in certain edge cases, causing potential crashes or unexpected behavior in components.
This change adds defensive null checks for `hostRef` values throughout the Stencil runtime to prevent potential runtime errors. The changes include:
- Added null checks before accessing `hostRef` properties in hydration, connection callbacks, and component lifecycle methods
- Used optional chaining (`?.`) to safely access `hostRef` properties where appropriate
- Added early returns when `hostRef` is null to prevent further execution that would fail
- Enhanced robustness of the …

fix(runtime): double check hostRef value

---

src/runtime/connected-callback.ts

A regression was added in https://github.com/stenciljs/core/pull/6311. 
In an attempt to 'clean up' non-shadow dom trees and minimise 3rd-party-framework hydration mismatch errors, the first empty comment node of a component was removed *when* the component does not utilise `<slot />`s. 
This node removal had a side-effect as Angular uses empty comments as content placeholders (*only* in production builds) which caused the Angular app content to not render.
GitHub Issue Number: https://github.com/stenciljs/core/pull/6336)
The node removal was reverted. I *think* with https://github.com/stenciljs/core/pull/6314 now in-place all non-shadow components correctly shield their internals from the outside, so this behaviour is no longer required anyway

fix(runtime): do not remove first comment - can break frameworks

---

src/runtime/test/prop.spec.tsx
src/utils/constants.ts

The `HasAttribute` member flag only includes `String | Number | Boolean | Any` types, which means that props with `Unknown` types (complex objects) are not considered to have attributes. This creates an inconsistency with the `Prop` flag definition, which includes `Unknown` types.
The `HasAttribute` member flag now includes `Unknown` types (`String | Number | Boolean | Any | Unknown`), making it consistent with the `Prop` flag definition. This allows complex object props to properly support attribute-based initialization through JSON string parsing. The added test demonstrates that complex object props can now be correctly initialized via HTML attributes using JSON strings.
Added

fix(runtime): fixed parsing of complex attributes that contains JSON strings

---

package.json
test/wdio/render/render.test.tsx
test/wdio/text-content-patch/cmp.test.tsx

Uses document tree verification instead of snapshot tests to confirm rendering works for two failing tests. Tests were failing due to some limitations with the testing framework.  Specifically that numerous snapshots of the same segment of HTML were not allowed in certain use cases
Two WDIO tests were failing due to framework limitations on `toMatchInlineSnapshot`
The tests now verify attribute on the DOM tree for correctness.

chore(tests)

---

src/declarations/stencil-public-runtime.ts
src/internal/stencil-core/index.d.ts

Devs have no steer regarding the typing of mixin factory functions for use with the new `Mixin()` utility
The `MixinFactory` type has been exported for devs to use: 
```
import { Method, Prop, type MixinFactory } from '@stencil/core';
export const WithMixinThing: MixinFactory = (Base) => {
class MixinThing extends Base {
@Prop() mixinThing = 'mixing ???';
@Method()
async mixinMethod() {
console.log('Mixin method called');
return 'Mixin method result';
}
}
return MixinThing;
}
```

fix(Mixin): export `MixinFactory` type for ease of use

---

src/compiler/sys/typescript/typescript-resolve-module.ts
src/compiler/transformers/detect-modern-prop-decls.ts
src/compiler/transformers/static-to-meta/class-extension.ts

GitHub Issue Number: #6410
Fixes #6410
https://github.com/stenciljs/site/pull/1552

fix(build): add extended class source in collection dependencies

---

src/runtime/proxy-component.ts
src/runtime/test/attr.spec.tsx

GitHub Issue Number: #6411
Fixes #6411

fix(runtime): better boolean attribute handling
